import { MONTHS_OFFERED, PAGE, QUERY_DUE, QUERY_MIN, QUERY_REPLY_DAYS, STAGES, STATUS_FILTERS, csvCell } from '@/features/payout/history';
import type { Stage, StatusFilter } from '@/features/payout/history';

export { MONTHS_OFFERED, PAGE, QUERY_DUE, QUERY_MIN, QUERY_REPLY_DAYS, STAGES, STATUS_FILTERS, csvCell };
export type { Stage, StatusFilter };
export const PULL_DISTANCE = 70;
export const CATEGORIES = ['capture', 'conversion', 'installation', 'qc', 'other', 'supply'] as const;
export const payoutHistoryPath = (q: Record<string, string>) => { const p = new URLSearchParams(q).toString(); return p ? `/payout-history?${p}` : '/payout-history'; };

export const HISTORY_KEYS = {
  title: 'payoutHistory.title',
  subtitle: 'payoutHistory.subtitle',
  loading: 'payoutHistory.loading',
  error: {
    title: 'payoutHistory.error.title',
    body: 'payoutHistory.error.body',
  },
  refresh: {
    button: 'payoutHistory.refresh.button',
    pull: 'payoutHistory.refresh.pull',
    release: 'payoutHistory.refresh.release',
    busy: 'payoutHistory.refresh.busy',
  },
  close: 'payoutHistory.close',
  back: 'payoutHistory.back',
  link: {
    open: 'payoutHistory.link.open',
  },
  hero: {
    earned: 'payoutHistory.hero.earned',
    since: 'payoutHistory.hero.since',
    note: 'payoutHistory.hero.note',
    paid: 'payoutHistory.hero.paid',
    inProgress: 'payoutHistory.hero.inProgress',
    notFinal: 'payoutHistory.hero.notFinal',
    reversed: 'payoutHistory.hero.reversed',
    entries: 'payoutHistory.hero.entries',
    none: 'payoutHistory.hero.none',
  },
  stage: {
    projected: 'payoutHistory.stage.projected',
    approved: 'payoutHistory.stage.approved',
    held: 'payoutHistory.stage.held',
    cleared: 'payoutHistory.stage.cleared',
    sending: 'payoutHistory.stage.sending',
    failed: 'payoutHistory.stage.failed',
    paid: 'payoutHistory.stage.paid',
    forfeited: 'payoutHistory.stage.forfeited',
    reversed: 'payoutHistory.stage.reversed',
    hint: {
      projected: 'payoutHistory.stage.hint.projected',
      approved: 'payoutHistory.stage.hint.approved',
      held: 'payoutHistory.stage.hint.held',
      cleared: 'payoutHistory.stage.hint.cleared',
      sending: 'payoutHistory.stage.hint.sending',
      paid: 'payoutHistory.stage.hint.paid',
      forfeited: 'payoutHistory.stage.hint.forfeited',
      reversed: 'payoutHistory.stage.hint.reversed',
      failed: 'payoutHistory.stage.hint.failed',
    },
  },
  statements: {
    heading: 'payoutHistory.statements.heading',
    body: 'payoutHistory.statements.body',
    fy: 'payoutHistory.statements.fy',
    all: 'payoutHistory.statements.all',
    earned: 'payoutHistory.statements.earned',
    paid: 'payoutHistory.statements.paid',
    outstanding: 'payoutHistory.statements.outstanding',
    reversed: 'payoutHistory.statements.reversed',
    empty: 'payoutHistory.statements.empty',
    none: 'payoutHistory.statements.none',
    download: 'payoutHistory.statements.download',
    csv: 'payoutHistory.statements.csv',
    downloaded: 'payoutHistory.statements.downloaded',
    csvDone: 'payoutHistory.statements.csvDone',
    tds: 'payoutHistory.statements.tds',
  },
  statement: {
    heading: 'payoutHistory.statement.heading',
    number: 'payoutHistory.statement.number',
    holder: 'payoutHistory.statement.holder',
    period: 'payoutHistory.statement.period',
    generated: 'payoutHistory.statement.generated',
    footer: 'payoutHistory.statement.footer',
    col: {
      date: 'payoutHistory.statement.col.date',
      title: 'payoutHistory.statement.col.title',
      type: 'payoutHistory.statement.col.type',
      amount: 'payoutHistory.statement.col.amount',
      status: 'payoutHistory.statement.col.status',
    },
    type: {
      earned: 'payoutHistory.statement.type.earned',
      paid: 'payoutHistory.statement.type.paid',
      reversed: 'payoutHistory.statement.type.reversed',
    },
    totals: {
      earned: 'payoutHistory.statement.totals.earned',
      paid: 'payoutHistory.statement.totals.paid',
      reversed: 'payoutHistory.statement.totals.reversed',
      outstanding: 'payoutHistory.statement.totals.outstanding',
      tds: 'payoutHistory.statement.totals.tds',
    },
  },
  filter: {
    search: 'payoutHistory.filter.search',
    status: {
      all: 'payoutHistory.filter.status.all',
      paid: 'payoutHistory.filter.status.paid',
      inProgress: 'payoutHistory.filter.status.inProgress',
      projected: 'payoutHistory.filter.status.projected',
      reversed: 'payoutHistory.filter.status.reversed',
    },
    more: 'payoutHistory.filter.more',
    from: 'payoutHistory.filter.from',
    to: 'payoutHistory.filter.to',
    category: 'payoutHistory.filter.category',
    allCategories: 'payoutHistory.filter.allCategories',
    clear: 'payoutHistory.filter.clear',
  },
  category: {
    capture: 'payoutHistory.category.capture',
    conversion: 'payoutHistory.category.conversion',
    installation: 'payoutHistory.category.installation',
    qc: 'payoutHistory.category.qc',
    other: 'payoutHistory.category.other',
    supply: 'payoutHistory.category.supply',
  },
  list: {
    heading: 'payoutHistory.list.heading',
    count: 'payoutHistory.list.count',
    empty: {
      title: 'payoutHistory.list.empty.title',
      body: 'payoutHistory.list.empty.body',
    },
    noMatch: 'payoutHistory.list.noMatch',
    noMatchBody: 'payoutHistory.list.noMatchBody',
    showMore: 'payoutHistory.list.showMore',
  },
  row: {
    paidOn: 'payoutHistory.row.paidOn',
    via: 'payoutHistory.row.via',
    ref: 'payoutHistory.row.ref',
    adjusted: 'payoutHistory.row.adjusted',
    reversed: 'payoutHistory.row.reversed',
    question: 'payoutHistory.row.question',
    method: {
      bank_transfer: 'payoutHistory.row.method.bank_transfer',
      upi: 'payoutHistory.row.method.upi',
    },
    earned: 'payoutHistory.row.earned',
  },
  detail: {
    title: 'payoutHistory.detail.title',
    deal: 'payoutHistory.detail.deal',
    job: 'payoutHistory.detail.job',
    timeline: 'payoutHistory.detail.timeline',
    adjusted: 'payoutHistory.detail.adjusted',
    reversal: 'payoutHistory.detail.reversal',
    reversalNote: 'payoutHistory.detail.reversalNote',
    paidFacts: 'payoutHistory.detail.paidFacts',
    tds: 'payoutHistory.detail.tds',
    tdsLink: 'payoutHistory.detail.tdsLink',
    supplier: {
      note: 'payoutHistory.detail.supplier.note',
      open: 'payoutHistory.detail.supplier.open',
    },
    earnedOn: 'payoutHistory.detail.earnedOn',
  },
  event: {
    earned: 'payoutHistory.event.earned',
    cleared: 'payoutHistory.event.cleared',
    held: 'payoutHistory.event.held',
    heldReview: 'payoutHistory.event.heldReview',
    released: 'payoutHistory.event.released',
    adjusted: 'payoutHistory.event.adjusted',
    sent: 'payoutHistory.event.sent',
    failedDetails: 'payoutHistory.event.failedDetails',
    failed: 'payoutHistory.event.failed',
    paid: 'payoutHistory.event.paid',
    reversed: 'payoutHistory.event.reversed',
    forfeited: 'payoutHistory.event.forfeited',
    asked: 'payoutHistory.event.asked',
    answered: 'payoutHistory.event.answered',
  },
  ask: {
    heading: 'payoutHistory.ask.heading',
    body: 'payoutHistory.ask.body',
    label: 'payoutHistory.ask.label',
    hint: 'payoutHistory.ask.hint',
    send: 'payoutHistory.ask.send',
    sent: 'payoutHistory.ask.sent',
    thread: 'payoutHistory.ask.thread',
    status: {
      open: 'payoutHistory.ask.status.open',
      answered: 'payoutHistory.ask.status.answered',
      resolved: 'payoutHistory.ask.status.resolved',
    },
    from: {
      partner: 'payoutHistory.ask.from.partner',
      admin: 'payoutHistory.ask.from.admin',
    },
    resolve: 'payoutHistory.ask.resolve',
    resolved: 'payoutHistory.ask.resolved',
    followUp: 'payoutHistory.ask.followUp',
  },
  placeholder: 'payoutHistory.placeholder',
  alert: {
    query: 'payoutHistory.alert.query',
  },
  problem: {
    text_short: 'payoutHistory.problem.text_short',
    answer_short: 'payoutHistory.problem.answer_short',
    not_found: 'payoutHistory.problem.not_found',
    not_yours: 'payoutHistory.problem.not_yours',
    already_open: 'payoutHistory.problem.already_open',
    not_open: 'payoutHistory.problem.not_open',
    forbidden: 'payoutHistory.problem.forbidden',
    generic: 'payoutHistory.problem.generic',
  },
} as const;
