/** Screen 116 — Tax / GST Compliance. Types and translation keys only. */

import type { SupplierRiskKind } from '@/features/tax/gst';

export type GstComplianceStatus = 'loading' | 'ready' | 'error';

/** How often the figures re-read while open: a matched invoice or a new check moves them. */
export const POLL_MS = 30_000;

export type GstTab = 'reconcile' | 'suppliers' | 'documents';
export const GST_TABS: GstTab[] = ['reconcile', 'suppliers', 'documents'];
export type DocFilter = 'all' | 'output' | 'input' | 'at_risk' | 'pending_match';
export const DOC_FILTERS: DocFilter[] = ['all', 'output', 'input', 'at_risk', 'pending_match'];
export const RISK_KINDS: SupplierRiskKind[] = ['ok', 'restricted', 'filing_late', 'unverified', 'no_gstin', 'invalid_gstin'];
export const STANDINGS = ['active', 'suspended', 'cancelled'] as const;

const rec = <T extends string>(ns: string, keys: readonly T[]) => Object.fromEntries(keys.map((k) => [k, `${ns}.${k}`])) as Record<T, string>;

export const GST_KEYS = {
  title: 'gstCompliance.title',
  subtitle: 'gstCompliance.subtitle',
  loading: 'gstCompliance.loading',
  error: { title: 'gstCompliance.error.title', body: 'gstCompliance.error.body' },
  alert: { supplierRisk: 'gstCompliance.alert.supplierRisk' },
  period: { label: 'gstCompliance.period.label', open: 'gstCompliance.period.open', current: 'gstCompliance.period.current' },
  kpi: {
    net: 'gstCompliance.kpi.net',
    netCredit: 'gstCompliance.kpi.netCredit',
    output: 'gstCompliance.kpi.output',
    input: 'gstCompliance.kpi.input',
    atRisk: 'gstCompliance.kpi.atRisk',
    pending: 'gstCompliance.kpi.pending',
    toCheck: 'gstCompliance.kpi.toCheck',
    noTrend: 'gstCompliance.kpi.noTrend',
    vsLast: 'gstCompliance.kpi.vsLast',
    suppliersCount: 'gstCompliance.kpi.suppliersCount',
    allClear: 'gstCompliance.kpi.allClear',
  },
  empty: { title: 'gstCompliance.empty.title', body: 'gstCompliance.empty.body' },
  risk: {
    banner: 'gstCompliance.risk.banner',
    claimed: 'gstCompliance.risk.claimed',
    tell: 'gstCompliance.risk.tell',
    see: 'gstCompliance.risk.see',
  },
  handover: {
    heading: 'gstCompliance.handover.heading',
    done: 'gstCompliance.handover.done',
    open: 'gstCompliance.handover.open',
    changed: 'gstCompliance.handover.changed',
    changedBody: 'gstCompliance.handover.changedBody',
    action: 'gstCompliance.handover.action',
    sheetTitle: 'gstCompliance.handover.sheetTitle',
    intro: 'gstCompliance.handover.intro',
    note: 'gstCompliance.handover.note',
    noteHint: 'gstCompliance.handover.noteHint',
    confirm: 'gstCompliance.handover.confirm',
    notFiling: 'gstCompliance.handover.notFiling',
    openPeriod: 'gstCompliance.handover.openPeriod',
  },
  tabs: { label: 'gstCompliance.tabs.label', ...rec('gstCompliance.tabs', GST_TABS) },
  reconcile: {
    output: 'gstCompliance.reconcile.output',
    outputHint: 'gstCompliance.reconcile.outputHint',
    input: 'gstCompliance.reconcile.input',
    inputHint: 'gstCompliance.reconcile.inputHint',
    taxable: 'gstCompliance.reconcile.taxable',
    cgst: 'gstCompliance.reconcile.cgst',
    sgst: 'gstCompliance.reconcile.sgst',
    igst: 'gstCompliance.reconcile.igst',
    total: 'gstCompliance.reconcile.total',
    creditNotes: 'gstCompliance.reconcile.creditNotes',
    claimable: 'gstCompliance.reconcile.claimable',
    pending: 'gstCompliance.reconcile.pending',
    atRisk: 'gstCompliance.reconcile.atRisk',
    byRate: 'gstCompliance.reconcile.byRate',
    rate: 'gstCompliance.reconcile.rate',
    rateNote: 'gstCompliance.reconcile.rateNote',
    net: 'gstCompliance.reconcile.net',
    netHint: 'gstCompliance.reconcile.netHint',
    netCarry: 'gstCompliance.reconcile.netCarry',
    documents: 'gstCompliance.reconcile.documents',
    notFiled: 'gstCompliance.reconcile.notFiled',
  },
  suppliers: {
    empty: 'gstCompliance.suppliers.empty',
    gstin: 'gstCompliance.suppliers.gstin',
    noGstin: 'gstCompliance.suppliers.noGstin',
    lastReturn: 'gstCompliance.suppliers.lastReturn',
    neverFiled: 'gstCompliance.suppliers.neverFiled',
    checked: 'gstCompliance.suppliers.checked',
    neverChecked: 'gstCompliance.suppliers.neverChecked',
    checkDue: 'gstCompliance.suppliers.checkDue',
    inputPeriod: 'gstCompliance.suppliers.inputPeriod',
    atRisk: 'gstCompliance.suppliers.atRisk',
    claimedAlready: 'gstCompliance.suppliers.claimedAlready',
    since: 'gstCompliance.suppliers.since',
    record: 'gstCompliance.suppliers.record',
    history: 'gstCompliance.suppliers.history',
    standing: rec('gstCompliance.suppliers.standing', STANDINGS),
    risk: rec('gstCompliance.suppliers.riskLabel', RISK_KINDS),
    riskBody: rec('gstCompliance.suppliers.riskBody', RISK_KINDS),
    by: 'gstCompliance.suppliers.by',
    effective: 'gstCompliance.suppliers.effective',
  },
  check: {
    title: 'gstCompliance.check.title',
    intro: 'gstCompliance.check.intro',
    standing: 'gstCompliance.check.standing',
    lastReturn: 'gstCompliance.check.lastReturn',
    lastReturnHint: 'gstCompliance.check.lastReturnHint',
    never: 'gstCompliance.check.never',
    effectiveFrom: 'gstCompliance.check.effectiveFrom',
    effectiveHint: 'gstCompliance.check.effectiveHint',
    note: 'gstCompliance.check.note',
    confirm: 'gstCompliance.check.confirm',
  },
  docs: {
    empty: 'gstCompliance.docs.empty',
    emptyFilter: 'gstCompliance.docs.emptyFilter',
    filter: { label: 'gstCompliance.docs.filter.label', ...rec('gstCompliance.docs.filter', DOC_FILTERS) },
    creditNote: 'gstCompliance.docs.creditNote',
    intra: 'gstCompliance.docs.intra',
    inter: 'gstCompliance.docs.inter',
    rateOf: 'gstCompliance.docs.rateOf',
    credit: rec('gstCompliance.docs.credit', ['claimable', 'pending_match', 'at_risk'] as const),
    outputTag: 'gstCompliance.docs.outputTag',
    inputTag: 'gstCompliance.docs.inputTag',
  },
  exportAction: { label: 'gstCompliance.exportAction.label', done: 'gstCompliance.exportAction.done' },
  csv: {
    section: 'gstCompliance.csv.section',
    period: 'gstCompliance.csv.period',
    aiecGstin: 'gstCompliance.csv.aiecGstin',
    side: 'gstCompliance.csv.side',
    code: 'gstCompliance.csv.code',
    party: 'gstCompliance.csv.party',
    reference: 'gstCompliance.csv.reference',
    date: 'gstCompliance.csv.date',
    rate: 'gstCompliance.csv.rate',
    taxable: 'gstCompliance.csv.taxable',
    cgst: 'gstCompliance.csv.cgst',
    sgst: 'gstCompliance.csv.sgst',
    igst: 'gstCompliance.csv.igst',
    total: 'gstCompliance.csv.total',
    credit: 'gstCompliance.csv.credit',
    summary: 'gstCompliance.csv.summary',
  },
  action: { close: 'gstCompliance.action.close', open: 'gstCompliance.action.open' },
  toast: { checked: 'gstCompliance.toast.checked', handed: 'gstCompliance.toast.handed' },
  problem: {
    forbidden: 'gstCompliance.problem.forbidden',
    not_found: 'gstCompliance.problem.not_found',
    no_gstin: 'gstCompliance.problem.no_gstin',
    invalid_period: 'gstCompliance.problem.invalid_period',
    invalid_date: 'gstCompliance.problem.invalid_date',
    period_open: 'gstCompliance.problem.period_open',
    already_handed_over: 'gstCompliance.problem.already_handed_over',
    nothing_to_hand_over: 'gstCompliance.problem.nothing_to_hand_over',
    generic: 'gstCompliance.problem.generic',
  },
} as const;
