/** Screen 126 — Safety Compliance Checklist. Types and translation keys only. */

import type { SafetyFixKind } from '@/data/types';

export type SafetyStatus = 'loading' | 'ready' | 'error' | 'not_found';

export const POLL_MS = 20_000;
export const queueKey = (userId: string) => `aiec.safetyQueue.${userId}`;
export const viewKey = (userId: string, jobId: string) => `aiec.safetyView.${userId}.${jobId}`;

export const FIX_KINDS: SafetyFixKind[] = ['minor_adjustment', 'part_replaced', 'needs_rework'];
export const STATES = ['not_tested', 'passed', 'failed', 'retest_due', 'held', 'in_review', 'overridden'] as const;

/** Refusals that will not change on a retry: reported, not retried. */
export const FINAL_ERRORS = [
  'already_passed', 'overridden', 'held', 'in_review', 'fix_required', 'evidence_missing', 'depends_on', 'note_required', 'reading_required', 'not_failed', 'nothing_to_review',
  'engineer_required', 'reason_required', 'forbidden', 'not_found', 'not_yours', 'read_only', 'job_on_hold', 'not_started', 'invalid_input', 'captured_in_future', 'captured_invalid', 'captured_before_job',
] as const;

const rec = <T extends string>(ns: string, keys: readonly T[]) => Object.fromEntries(keys.map((k) => [k, `${ns}.${k}`])) as Record<T, string>;

export const jobPath = (id: string) => `/technician/jobs/${id}`;
export const sopPath = (id: string) => `/technician/jobs/${id}/sop`;
export const evidencePath = (id: string, stepId: string, slotId: string) => `/technician/jobs/${id}/evidence?step=${stepId}&slot=${encodeURIComponent(slotId)}`;
export const adminTrackPath = (userId: string) => `/admin/tracking/technician/${userId}`;
export const homePath = '/technician';

export const SAFETY_KEYS = {
  title: 'safetyChecklist.title',
  loading: 'safetyChecklist.loading',
  back: 'safetyChecklist.back',
  error: { title: 'safetyChecklist.error.title', body: 'safetyChecklist.error.body' },
  notFound: { title: 'safetyChecklist.notFound.title', body: 'safetyChecklist.notFound.body' },
  sync: { offline: 'safetyChecklist.sync.offline', queued: 'safetyChecklist.sync.queued', syncing: 'safetyChecklist.sync.syncing', notSent: 'safetyChecklist.sync.notSent', needsSignal: 'safetyChecklist.sync.needsSignal' },
  failed: { title: 'safetyChecklist.failed.title', item: 'safetyChecklist.failed.item', dismiss: 'safetyChecklist.failed.dismiss' },
  problem: rec('safetyChecklist.problem', [...FINAL_ERRORS, 'generic'] as const),
  hero: {
    intro: 'safetyChecklist.hero.intro',
    order: 'safetyChecklist.hero.order',
    progress: 'safetyChecklist.hero.progress',
    blocks: 'safetyChecklist.hero.blocks',
    clear: 'safetyChecklist.hero.clear',
    stateFallback: 'safetyChecklist.hero.stateFallback',
    stateConfigured: 'safetyChecklist.hero.stateConfigured',
    standard: 'safetyChecklist.hero.standard',
    clauses: 'safetyChecklist.hero.clauses',
  },
  readOnly: { notStarted: 'safetyChecklist.readOnly.notStarted', closed: 'safetyChecklist.readOnly.closed', hold: 'safetyChecklist.readOnly.hold', admin: 'safetyChecklist.readOnly.admin' },
  kind: { device: 'safetyChecklist.kind.device', trial: 'safetyChecklist.kind.trial', state: 'safetyChecklist.kind.state', critical: 'safetyChecklist.kind.critical' },
  state: rec('safetyChecklist.state', STATES),
  stateNote: {
    held_needs_rework: 'safetyChecklist.stateNote.held_needs_rework',
    held_too_many_fails: 'safetyChecklist.stateNote.held_too_many_fails',
    in_review: 'safetyChecklist.stateNote.in_review',
    overridden: 'safetyChecklist.stateNote.overridden',
    failed: 'safetyChecklist.stateNote.failed',
    retest_due: 'safetyChecklist.stateNote.retest_due',
  },
  item: {
    method: 'safetyChecklist.item.method',
    evidence: 'safetyChecklist.item.evidence',
    evidenceNeeded: 'safetyChecklist.item.evidenceNeeded',
    addPhoto: 'safetyChecklist.item.addPhoto',
    addVideo: 'safetyChecklist.item.addVideo',
    retake: 'safetyChecklist.item.retake',
    proof: 'safetyChecklist.item.proof',
    excepted: 'safetyChecklist.item.excepted',
    cannotCapture: 'safetyChecklist.item.cannotCapture',
    waitingFor: 'safetyChecklist.item.waitingFor',
    reading: 'safetyChecklist.item.reading',
    readingHint: 'safetyChecklist.item.readingHint',
    readingRequired: 'safetyChecklist.item.readingRequired',
    pass: 'safetyChecklist.item.pass',
    fail: 'safetyChecklist.item.fail',
    passDisabled: 'safetyChecklist.item.passDisabled',
    failNote: 'safetyChecklist.item.failNote',
    failNoteHint: 'safetyChecklist.item.failNoteHint',
    saveFail: 'safetyChecklist.item.saveFail',
    cancel: 'safetyChecklist.item.cancel',
    fixHeading: 'safetyChecklist.item.fixHeading',
    fixIntro: 'safetyChecklist.item.fixIntro',
    fixNote: 'safetyChecklist.item.fixNote',
    fixNoteHint: 'safetyChecklist.item.fixNoteHint',
    saveFix: 'safetyChecklist.item.saveFix',
    fixKind: rec('safetyChecklist.item.fixKind', FIX_KINDS),
    fixKindHint: rec('safetyChecklist.item.fixKindHint', FIX_KINDS),
    retestHeading: 'safetyChecklist.item.retestHeading',
    attempts: 'safetyChecklist.item.attempts',
    attemptLine: 'safetyChecklist.item.attemptLine',
    attemptPass: 'safetyChecklist.item.attemptPass',
    attemptFail: 'safetyChecklist.item.attemptFail',
    fixed: 'safetyChecklist.item.fixed',
    disagree: 'safetyChecklist.item.disagree',
    overrideDone: 'safetyChecklist.item.overrideDone',
    reviewDone: 'safetyChecklist.item.reviewDone',
    releasedNote: 'safetyChecklist.item.releasedNote',
  },
  disagree: { title: 'safetyChecklist.disagree.title', intro: 'safetyChecklist.disagree.intro', note: 'safetyChecklist.disagree.note', hint: 'safetyChecklist.disagree.hint', send: 'safetyChecklist.disagree.send' },
  admin: {
    heading: 'safetyChecklist.admin.heading',
    release: 'safetyChecklist.admin.release',
    releaseTitle: 'safetyChecklist.admin.releaseTitle',
    releaseIntro: 'safetyChecklist.admin.releaseIntro',
    releaseNote: 'safetyChecklist.admin.releaseNote',
    releaseConfirm: 'safetyChecklist.admin.releaseConfirm',
    override: 'safetyChecklist.admin.override',
    overrideTitle: 'safetyChecklist.admin.overrideTitle',
    overrideIntro: 'safetyChecklist.admin.overrideIntro',
    engineer: 'safetyChecklist.admin.engineer',
    engineerHint: 'safetyChecklist.admin.engineerHint',
    reason: 'safetyChecklist.admin.reason',
    reasonHint: 'safetyChecklist.admin.reasonHint',
    overrideConfirm: 'safetyChecklist.admin.overrideConfirm',
    resolve: 'safetyChecklist.admin.resolve',
    resolveTitle: 'safetyChecklist.admin.resolveTitle',
    theirWords: 'safetyChecklist.admin.theirWords',
    decisionStands: 'safetyChecklist.admin.decisionStands',
    decisionChanged: 'safetyChecklist.admin.decisionChanged',
    decisionNote: 'safetyChecklist.admin.decisionNote',
    decisionNoteHint: 'safetyChecklist.admin.decisionNoteHint',
    resolveConfirm: 'safetyChecklist.admin.resolveConfirm',
    decision: rec('safetyChecklist.admin.decision', ['method_stands', 'method_changed'] as const),
    noRole: 'safetyChecklist.admin.noRole',
  },
  states: {
    open: 'safetyChecklist.states.open',
    title: 'safetyChecklist.states.title',
    intro: 'safetyChecklist.states.intro',
    empty: 'safetyChecklist.states.empty',
    state: 'safetyChecklist.states.state',
    label: 'safetyChecklist.states.label',
    labelHint: 'safetyChecklist.states.labelHint',
    method: 'safetyChecklist.states.method',
    methodHint: 'safetyChecklist.states.methodHint',
    reading: 'safetyChecklist.states.reading',
    add: 'safetyChecklist.states.add',
    active: 'safetyChecklist.states.active',
    inactive: 'safetyChecklist.states.inactive',
    deactivate: 'safetyChecklist.states.deactivate',
    activate: 'safetyChecklist.states.activate',
    note: 'safetyChecklist.states.note',
    by: 'safetyChecklist.states.by',
  },
  summary: {
    open: 'safetyChecklist.summary.open',
    title: 'safetyChecklist.summary.title',
    intro: 'safetyChecklist.summary.intro',
    ready: 'safetyChecklist.summary.ready',
    notReady: 'safetyChecklist.summary.notReady',
    lineSummary: 'safetyChecklist.summary.lineSummary',
    generate: 'safetyChecklist.summary.generate',
    download: 'safetyChecklist.summary.download',
    versions: 'safetyChecklist.summary.versions',
    version: 'safetyChecklist.summary.version',
    liveNote: 'safetyChecklist.summary.liveNote',
    stateFallback: 'safetyChecklist.summary.stateFallback',
    stateLine: 'safetyChecklist.summary.stateLine',
    disclaimer: 'safetyChecklist.summary.disclaimer',
    fileTitle: 'safetyChecklist.summary.fileTitle',
  },
  toast: {
    passed: 'safetyChecklist.toast.passed',
    failed: 'safetyChecklist.toast.failed',
    fixed: 'safetyChecklist.toast.fixed',
    reworkHeld: 'safetyChecklist.toast.reworkHeld',
    queued: 'safetyChecklist.toast.queued',
    disagreed: 'safetyChecklist.toast.disagreed',
    released: 'safetyChecklist.toast.released',
    overridden: 'safetyChecklist.toast.overridden',
    resolved: 'safetyChecklist.toast.resolved',
    stateAdded: 'safetyChecklist.toast.stateAdded',
    summary: 'safetyChecklist.toast.summary',
  },
  capture: {
    preparing: 'safetyChecklist.capture.preparing',
    unreadable: 'safetyChecklist.capture.unreadable',
    keep: 'safetyChecklist.capture.keep',
    keepAnyway: 'safetyChecklist.capture.keepAnyway',
    retake: 'safetyChecklist.capture.retake',
    blurry: 'safetyChecklist.capture.blurry',
    dark: 'safetyChecklist.capture.dark',
    glare: 'safetyChecklist.capture.glare',
    unchecked: 'safetyChecklist.capture.unchecked',
    wrongKind: 'safetyChecklist.capture.wrongKind',
    tooLong: 'safetyChecklist.capture.tooLong',
    tooLarge: 'safetyChecklist.capture.tooLarge',
  },
  alert: { rework: 'safetyChecklist.alert.rework', repeatedFailure: 'safetyChecklist.alert.repeatedFailure', disagreement: 'safetyChecklist.alert.disagreement' },
} as const;
