/** Screen 144 — Interview Scheduling. Types and translation keys only. */

import { CONCERN_CATEGORIES, INTERVIEW_MODES, MAX_MISSES, NOTE_MIN, REASON_MIN, SLOT_LENGTHS } from '@/features/recruitment/interview';
import type { Phase } from '@/features/recruitment/interview';

export type InterviewStatus = 'loading' | 'ready' | 'error' | 'invalid' | 'not_found';
export const POLL_MS = 30_000;
export const PHASES: Phase[] = ['to_arrange', 'invited', 'scheduled', 'move_requested', 'needs_outcome', 'completed', 'missed', 'cancelled', 'skipped'];
export const RATING_OPTIONS = {
  communication: ['clear', 'ok', 'concern'],
  reliability: ['clear', 'ok', 'concern'],
  experience: ['confirmed', 'partly', 'not_confirmed'],
} as const;
export const OUTCOMES = ['recommend', 'hold', 'not_recommended'] as const;
export const WEEKDAYS = [1, 2, 3, 4, 5, 6, 0] as const;
export const BUFFERS = [0, 5, 10, 15, 30];
export const LEADS = [0, 2, 4, 8, 24];
export const HORIZONS = [7, 14, 21];
export const draftKey = (id: string) => `aiec.interviewDraft.${id}`;
export const keyKey = (id: string) => `aiec.application.${id}`;
export const boardPath = '/interviews';
export const detailPath = (id: string) => `/interviews/${id}`;
export const applicantPath = (id: string) => `/interview/${id}`;
export const applyPath = (id: string) => `/apply/${id}`;
export { CONCERN_CATEGORIES, INTERVIEW_MODES, MAX_MISSES, NOTE_MIN, REASON_MIN, SLOT_LENGTHS };

const rec = <T extends string | number>(ns: string, keys: readonly T[]) => Object.fromEntries(keys.map((k) => [k, `${ns}.${k}`])) as Record<T, string>;
const PROBLEMS = [
  'not_approved', 'already_active', 'modes_required', 'link_required', 'place_required', 'reason_required', 'slot_taken', 'slot_past', 'slot_too_soon', 'slot_closed', 'slot_outside', 'mode_not_offered', 'too_late', 'not_open', 'not_started',
  'ratings_required', 'note_required', 'concern_required', 'concern_text', 'outcome_required', 'outcome_reason_required', 'not_completed', 'window_order', 'slot_length', 'horizon', 'lead', 'nothing_open', 'closed_date',
  'invalid_link', 'forbidden', 'not_admin', 'not_found', 'offline', 'generic',
] as const;

export const INTERVIEW_KEYS = {
  title: 'interview.title',
  loading: 'interview.loading',
  brand: 'interview.brand',
  language: 'interview.language',
  error: { title: 'interview.error.title', body: 'interview.error.body' },
  invalid: { title: 'interview.invalid.title', body: 'interview.invalid.body', action: 'interview.invalid.action' },
  mode: rec('interview.mode', INTERVIEW_MODES),
  phase: rec('interview.phase', PHASES),
  concern: rec('interview.concern', CONCERN_CATEGORIES),
  signal: { positive: 'interview.signal.positive', neutral: 'interview.signal.neutral', caution: 'interview.signal.caution', block: 'interview.signal.block' },
  problem: rec('interview.problem', PROBLEMS),
  admin: {
    subtitle: 'interview.admin.subtitle',
    view: { label: 'interview.admin.view.label', week: 'interview.admin.view.week', month: 'interview.admin.view.month', agenda: 'interview.admin.view.agenda' },
    legend: { scheduled: 'interview.admin.legend.scheduled', attention: 'interview.admin.legend.attention', held: 'interview.admin.legend.held', missed: 'interview.admin.legend.missed' },
    day: { empty: 'interview.admin.day.empty', emptyBody: 'interview.admin.day.emptyBody' },
    availability: { open: 'interview.admin.availability.open', noSlots: 'interview.admin.availability.noSlots', openSlots: 'interview.admin.availability.openSlots' },
    queue: {
      heading: 'interview.admin.queue.heading',
      needsOutcome: 'interview.admin.queue.needsOutcome',
      toArrange: 'interview.admin.queue.toArrange',
      invited: 'interview.admin.queue.invited',
      conflicts: 'interview.admin.queue.conflicts',
      missed: 'interview.admin.queue.missed',
      emptyTitle: 'interview.admin.queue.emptyTitle',
      emptyBody: 'interview.admin.queue.emptyBody',
    },
    row: { score: 'interview.admin.row.score', waiting: 'interview.admin.row.waiting', today: 'interview.admin.row.today', misses: 'interview.admin.row.misses', moves: 'interview.admin.row.moves', noTime: 'interview.admin.row.noTime', conflict: 'interview.admin.row.conflict' },
  },
  detail: {
    summary: { phone: 'interview.detail.summary.phone', city: 'interview.detail.summary.city', languages: 'interview.detail.summary.languages', years: 'interview.detail.summary.years' },
    steps: { approved: 'interview.detail.steps.approved', invited: 'interview.detail.steps.invited', scheduled: 'interview.detail.steps.scheduled', held: 'interview.detail.steps.held', outcome: 'interview.detail.steps.outcome' },
    approvedOn: 'interview.detail.approvedOn',
    toArrangeBody: 'interview.detail.toArrangeBody',
    invitedBody: 'interview.detail.invitedBody',
    scheduledBody: 'interview.detail.scheduledBody',
    moveBody: 'interview.detail.moveBody',
    moveReasonAvailability: 'interview.detail.moveReasonAvailability',
    needsOutcomeBody: 'interview.detail.needsOutcomeBody',
    missedBody: 'interview.detail.missedBody',
    missedLimit: 'interview.detail.missedLimit',
    cancelledBody: 'interview.detail.cancelledBody',
    skippedBody: 'interview.detail.skippedBody',
    completedBody: 'interview.detail.completedBody',
    mode: 'interview.detail.mode',
    how: { phone: 'interview.detail.how.phone', video: 'interview.detail.how.video', in_person: 'interview.detail.how.in_person' },
    remindersSent: 'interview.detail.remindersSent',
    noReminders: 'interview.detail.noReminders',
    ratings: 'interview.detail.ratings',
    rating: { communication: 'interview.detail.rating.communication', reliability: 'interview.detail.rating.reliability', experience: 'interview.detail.rating.experience' },
    value: { clear: 'interview.detail.value.clear', ok: 'interview.detail.value.ok', concern: 'interview.detail.value.concern', confirmed: 'interview.detail.value.confirmed', partly: 'interview.detail.value.partly', not_confirmed: 'interview.detail.value.not_confirmed' },
    notes: 'interview.detail.notes',
    outcome: { label: 'interview.detail.outcome.label', recommend: 'interview.detail.outcome.recommend', hold: 'interview.detail.outcome.hold', not_recommended: 'interview.detail.outcome.not_recommended' },
    concernHeading: 'interview.detail.concernHeading',
    addenda: 'interview.detail.addenda',
    forOffer: 'interview.detail.forOffer',
    timeline: 'interview.detail.timeline',
    event: rec('interview.detail.event', ['invited', 'nudged', 'slot_chosen', 'rescheduled', 'move_requested', 'reminder', 'missed', 'completed', 'cancelled', 'skipped', 'addendum', 'availability'] as const),
    skippedBy: 'interview.detail.skippedBy',
    noSlots: 'interview.detail.noSlots',
    nearest: 'interview.detail.nearest',
  },
  action: {
    invite: 'interview.action.invite',
    book: 'interview.action.book',
    skip: 'interview.action.skip',
    reschedule: 'interview.action.reschedule',
    askMove: 'interview.action.askMove',
    cancel: 'interview.action.cancel',
    held: 'interview.action.held',
    notJoined: 'interview.action.notJoined',
    addNote: 'interview.action.addNote',
    back: 'interview.action.back',
    send: 'interview.action.send',
    confirm: 'interview.action.confirm',
    save: 'interview.action.save',
    keep: 'interview.action.keep',
    call: 'interview.action.call',
    verification: 'interview.action.verification',
  },
  invite: {
    heading: 'interview.invite.heading',
    body: 'interview.invite.body',
    modes: 'interview.invite.modes',
    link: 'interview.invite.link',
    linkHint: 'interview.invite.linkHint',
    place: 'interview.invite.place',
    placeHint: 'interview.invite.placeHint',
    note: 'interview.invite.note',
    done: 'interview.invite.done',
  },
  book: { heading: 'interview.book.heading', body: 'interview.book.body', when: 'interview.book.when', mode: 'interview.book.mode', reason: 'interview.book.reason', reasonHint: 'interview.book.reasonHint', done: 'interview.book.done', pick: 'interview.book.pick' },
  move: { heading: 'interview.move.heading', body: 'interview.move.body', reason: 'interview.move.reason', reasonHint: 'interview.move.reasonHint', done: 'interview.move.done' },
  cancelSheet: { heading: 'interview.cancelSheet.heading', body: 'interview.cancelSheet.body', reason: 'interview.cancelSheet.reason', done: 'interview.cancelSheet.done' },
  skipSheet: { heading: 'interview.skipSheet.heading', body: 'interview.skipSheet.body', reason: 'interview.skipSheet.reason', done: 'interview.skipSheet.done' },
  missed: { heading: 'interview.missed.heading', body: 'interview.missed.body', done: 'interview.missed.done' },
  complete: {
    heading: 'interview.complete.heading',
    body: 'interview.complete.body',
    ratings: 'interview.complete.ratings',
    note: 'interview.complete.note',
    noteHint: 'interview.complete.noteHint',
    concernCategory: 'interview.complete.concernCategory',
    concernText: 'interview.complete.concernText',
    concernHint: 'interview.complete.concernHint',
    concernAdd: 'interview.complete.concernAdd',
    outcome: 'interview.complete.outcome',
    reason: 'interview.complete.reason',
    reasonHint: 'interview.complete.reasonHint',
    draft: 'interview.complete.draft',
    done: 'interview.complete.done',
  },
  addendum: { heading: 'interview.addendum.heading', body: 'interview.addendum.body', text: 'interview.addendum.text', concern: 'interview.addendum.concern', done: 'interview.addendum.done' },
  avail: {
    heading: 'interview.avail.heading',
    body: 'interview.avail.body',
    day: rec('interview.avail.day', WEEKDAYS),
    from: 'interview.avail.from',
    to: 'interview.avail.to',
    off: 'interview.avail.off',
    slot: 'interview.avail.slot',
    slotUnit: 'interview.avail.slotUnit',
    buffer: 'interview.avail.buffer',
    lead: 'interview.avail.lead',
    leadUnit: 'interview.avail.leadUnit',
    horizon: 'interview.avail.horizon',
    horizonUnit: 'interview.avail.horizonUnit',
    closed: 'interview.avail.closed',
    closedAdd: 'interview.avail.closedAdd',
    closedHint: 'interview.avail.closedHint',
    closedNone: 'interview.avail.closedNone',
    save: 'interview.avail.save',
    saved: 'interview.avail.saved',
    updated: 'interview.avail.updated',
    neverChanged: 'interview.avail.neverChanged',
    conflictsHeading: 'interview.avail.conflictsHeading',
    conflictsBody: 'interview.avail.conflictsBody',
    askAll: 'interview.avail.askAll',
    keepAll: 'interview.avail.keepAll',
    askedAll: 'interview.avail.askedAll',
    keptAll: 'interview.avail.keptAll',
    placeholder: 'interview.avail.placeholder',
  },
  applicant: {
    heading: 'interview.applicant.heading',
    hello: 'interview.applicant.hello',
    chooseHeading: 'interview.applicant.chooseHeading',
    chooseBody: 'interview.applicant.chooseBody',
    changeHeading: 'interview.applicant.changeHeading',
    modeHeading: 'interview.applicant.modeHeading',
    dayHeading: 'interview.applicant.dayHeading',
    timeHeading: 'interview.applicant.timeHeading',
    slotsCount: 'interview.applicant.slotsCount',
    noSlotsTitle: 'interview.applicant.noSlotsTitle',
    noSlotsBody: 'interview.applicant.noSlotsBody',
    pickDay: 'interview.applicant.pickDay',
    confirm: 'interview.applicant.confirm',
    confirming: 'interview.applicant.confirming',
    moveBanner: 'interview.applicant.moveBanner',
    moveBannerAvailability: 'interview.applicant.moveBannerAvailability',
    moveReason: 'interview.applicant.moveReason',
    missedBanner: 'interview.applicant.missedBanner',
    missedLimit: 'interview.applicant.missedLimit',
    takenSlot: 'interview.applicant.takenSlot',
    confirmedHeading: 'interview.applicant.confirmedHeading',
    confirmedBody: 'interview.applicant.confirmedBody',
    howPhone: 'interview.applicant.howPhone',
    howVideo: 'interview.applicant.howVideo',
    howInPerson: 'interview.applicant.howInPerson',
    join: 'interview.applicant.join',
    addCalendar: 'interview.applicant.addCalendar',
    change: 'interview.applicant.change',
    tooLate: 'interview.applicant.tooLate',
    reminderNote: 'interview.applicant.reminderNote',
    thanksHeading: 'interview.applicant.thanksHeading',
    thanksBody: 'interview.applicant.thanksBody',
    skippedBody: 'interview.applicant.skippedBody',
    waitingBody: 'interview.applicant.waitingBody',
    backToApplication: 'interview.applicant.backToApplication',
    mode: { phone: 'interview.applicant.mode.phone', video: 'interview.applicant.mode.video', in_person: 'interview.applicant.mode.in_person' },
  },
  message: {
    invite: 'interview.message.invite',
    confirmed: 'interview.message.confirmed',
    adminMoved: 'interview.message.adminMoved',
    move: 'interview.message.move',
    moveAvailability: 'interview.message.moveAvailability',
    reminder: 'interview.message.reminder',
    missed: 'interview.message.missed',
    missedLast: 'interview.message.missedLast',
    nudge: 'interview.message.nudge',
    cancelled: 'interview.message.cancelled',
  },
} as const;
