/** Screen 197 — Subscription & Billing. Types and keys only. */
export const POLL_MS = 30_000;

export const SUBSCRIPTION_BILLING_KEYS = {
  title: 'billing.title',
  subtitle: 'billing.subtitle',
  loading: 'billing.loading',
  offline: 'billing.offline',
  refresh: 'billing.refresh',
  close: 'billing.close',
  cancel: 'billing.cancel',
  error: {
    title: 'billing.error.title',
    body: 'billing.error.body',
    retry: 'billing.error.retry',
    generic: 'billing.error.generic',
    forbidden: 'billing.error.forbidden',
    not_found: 'billing.error.not_found',
    tier_unknown: 'billing.error.tier_unknown',
    when_invalid: 'billing.error.when_invalid',
    same_tier: 'billing.error.same_tier',
    reason_short: 'billing.error.reason_short',
    tradeoffs_unconfirmed: 'billing.error.tradeoffs_unconfirmed',
    no_card_needed: 'billing.error.no_card_needed',
    last4_invalid: 'billing.error.last4_invalid',
    expiry_invalid: 'billing.error.expiry_invalid',
    expiry_past: 'billing.error.expiry_past',
    nothing_to_retry: 'billing.error.nothing_to_retry',
    no_change: 'billing.error.no_change',
    note_short: 'billing.error.note_short',
    card_declined: 'billing.error.card_declined',
    card_expired: 'billing.error.card_expired',
    no_card: 'billing.error.no_card',
  },
  note: {
    placeholders: 'billing.note.placeholders',
  },
  summary: {
    now: 'billing.summary.now',
    forecast: 'billing.summary.forecast',
    vsLast: 'billing.summary.vsLast',
    year: 'billing.summary.year',
    saving: 'billing.summary.saving',
  },
  attention: {
    title: 'billing.attention.title',
    hint: 'billing.attention.hint',
    clear: 'billing.attention.clear',
  },
  state: {
    ok: 'billing.state.ok',
    renewing_soon: 'billing.state.renewing_soon',
    card_expiring: 'billing.state.card_expiring',
    card_expired: 'billing.state.card_expired',
    payment_failed: 'billing.state.payment_failed',
    lapsed: 'billing.state.lapsed',
    no_card: 'billing.state.no_card',
  },
  stateHint: {
    renewing_soon: 'billing.stateHint.renewing_soon',
    card_expiring: 'billing.stateHint.card_expiring',
    card_expired: 'billing.stateHint.card_expired',
    payment_failed: 'billing.stateHint.payment_failed',
    lapsed: 'billing.stateHint.lapsed',
    no_card: 'billing.stateHint.no_card',
  },
  services: {
    title: 'billing.services.title',
    hint: 'billing.services.hint',
    critical: 'billing.services.critical',
    forecastWord: 'billing.services.forecastWord',
    usage: 'billing.services.usage',
    usedOf: 'billing.services.usedOf',
    usedPay: 'billing.services.usedPay',
    spike: 'billing.services.spike',
    couldSave: 'billing.services.couldSave',
    changePending: 'billing.services.changePending',
    renews: 'billing.services.renews',
  },
  renewals: {
    title: 'billing.renewals.title',
    hint: 'billing.renewals.hint',
    auto: 'billing.renewals.auto',
    manual: 'billing.renewals.manual',
  },
  metric: {
    operations: 'billing.metric.operations',
    messages: 'billing.metric.messages',
    requests: 'billing.metric.requests',
    transactions: 'billing.metric.transactions',
    checks: 'billing.metric.checks',
  },
  service: {
    hosting: 'billing.service.hosting',
    whatsapp: 'billing.service.whatsapp',
    sms: 'billing.service.sms',
    maps: 'billing.service.maps',
    payment_gateway: 'billing.service.payment_gateway',
    id_verification: 'billing.service.id_verification',
  },
  tier: {
    hosting: {
      spark: 'billing.tier.hosting.spark',
      standard: 'billing.tier.hosting.standard',
      scale: 'billing.tier.hosting.scale',
    },
    whatsapp: {
      starter: 'billing.tier.whatsapp.starter',
      growth: 'billing.tier.whatsapp.growth',
      scale: 'billing.tier.whatsapp.scale',
    },
    sms: {
      pay_go: 'billing.tier.sms.pay_go',
      pack: 'billing.tier.sms.pack',
      bulk: 'billing.tier.sms.bulk',
    },
    maps: {
      free_credit: 'billing.tier.maps.free_credit',
      standard: 'billing.tier.maps.standard',
    },
    payment_gateway: {
      standard: 'billing.tier.payment_gateway.standard',
      pro: 'billing.tier.payment_gateway.pro',
    },
    id_verification: {
      pay_go: 'billing.tier.id_verification.pay_go',
      bundle: 'billing.tier.id_verification.bundle',
    },
  },
  support: {
    community: 'billing.support.community',
    business: 'billing.support.business',
    always: 'billing.support.always',
  },
  feature: {
    backups_daily: 'billing.feature.backups_daily',
    uptime_sla: 'billing.feature.uptime_sla',
    templates: 'billing.feature.templates',
    analytics: 'billing.feature.analytics',
    priority_support: 'billing.feature.priority_support',
    delivery_reports: 'billing.feature.delivery_reports',
    sender_id: 'billing.feature.sender_id',
    route_optimisation: 'billing.feature.route_optimisation',
    settlement_t1: 'billing.feature.settlement_t1',
    bulk_checks: 'billing.feature.bulk_checks',
  },
  driver: {
    recruitment: 'billing.driver.recruitment',
    payment_reminder: 'billing.driver.payment_reminder',
    shipment: 'billing.driver.shipment',
    ticket: 'billing.driver.ticket',
    other: 'billing.driver.other',
  },
  invoiceStatus: {
    paid: 'billing.invoiceStatus.paid',
    failed: 'billing.invoiceStatus.failed',
    pending: 'billing.invoiceStatus.pending',
  },
  failure: {
    card_declined: 'billing.failure.card_declined',
    card_expired: 'billing.failure.card_expired',
    no_card: 'billing.failure.no_card',
    manual_due: 'billing.failure.manual_due',
  },
  sheet: {
    criticalNote: 'billing.sheet.criticalNote',
    planTitle: 'billing.sheet.planTitle',
    price: 'billing.sheet.price',
    perMonth: 'billing.sheet.perMonth',
    included: 'billing.sheet.included',
    none: 'billing.sheet.none',
    overage: 'billing.sheet.overage',
    perUnit: 'billing.sheet.perUnit',
    rate: 'billing.sheet.rate',
    perMin: 'billing.sheet.perMin',
    need: 'billing.sheet.need',
    support: 'billing.sheet.support',
    features: 'billing.sheet.features',
    pending: 'billing.sheet.pending',
  },
  usage: {
    title: 'billing.usage.title',
    hint: 'billing.usage.hint',
    chartLabel: 'billing.usage.chartLabel',
    chartNote: 'billing.usage.chartNote',
    appSends: 'billing.usage.appSends',
    spikeBadge: 'billing.usage.spikeBadge',
    drivers: 'billing.usage.drivers',
    unexplained: 'billing.usage.unexplained',
    addNote: 'billing.usage.addNote',
    noteLabel: 'billing.usage.noteLabel',
    noteSave: 'billing.usage.noteSave',
    noteSaved: 'billing.usage.noteSaved',
  },
  advice: {
    title: 'billing.advice.title',
    hint: 'billing.advice.hint',
    down: 'billing.advice.down',
    up: 'billing.advice.up',
    same: {
      fits: 'billing.advice.same.fits',
      blocked: 'billing.advice.same.blocked',
    },
    current: 'billing.advice.current',
    avgCost: 'billing.advice.avgCost',
    yourPlan: 'billing.advice.yourPlan',
    noTradeoffs: 'billing.advice.noTradeoffs',
    lost: 'billing.advice.lost',
    change: 'billing.advice.change',
    thisMonthFrom: 'billing.advice.thisMonthFrom',
    thisMonthTo: 'billing.advice.thisMonthTo',
    avgDelta: 'billing.advice.avgDelta',
    tradeoffsTitle: 'billing.advice.tradeoffsTitle',
    loseFeature: 'billing.advice.loseFeature',
    reason: 'billing.advice.reason',
    changeGo: 'billing.advice.changeGo',
    changed: 'billing.advice.changed',
  },
  tradeoff: {
    rate_limit_below_need: 'billing.tradeoff.rate_limit_below_need',
    lower_rate_limit: 'billing.tradeoff.lower_rate_limit',
    support_lower: 'billing.tradeoff.support_lower',
    features_lost: 'billing.tradeoff.features_lost',
    overage_exposure: 'billing.tradeoff.overage_exposure',
    free_allowance_small: 'billing.tradeoff.free_allowance_small',
  },
  when: {
    renewal: 'billing.when.renewal',
    now: 'billing.when.now',
  },
  billing: {
    title: 'billing.billing.title',
    card: 'billing.billing.card',
    cardLine: 'billing.billing.cardLine',
    noCard: 'billing.billing.noCard',
    expiring: 'billing.billing.expiring',
    updateCard: 'billing.billing.updateCard',
    last4: 'billing.billing.last4',
    cardSafe: 'billing.billing.cardSafe',
    expiry: 'billing.billing.expiry',
    cardSave: 'billing.billing.cardSave',
    cardSaved: 'billing.billing.cardSaved',
    settlement: 'billing.billing.settlement',
    renews: 'billing.billing.renews',
    auto: 'billing.billing.auto',
    autoOn: 'billing.billing.autoOn',
    autoOff: 'billing.billing.autoOff',
    autoReason: 'billing.billing.autoReason',
    autoSave: 'billing.billing.autoSave',
    autoSaved: 'billing.billing.autoSaved',
    retry: 'billing.billing.retry',
    retried: 'billing.billing.retried',
    markRenewed: 'billing.billing.markRenewed',
    renewNote: 'billing.billing.renewNote',
    renewedSave: 'billing.billing.renewedSave',
    renewedDone: 'billing.billing.renewedDone',
    invoices: 'billing.billing.invoices',
    noInvoices: 'billing.billing.noInvoices',
  },
  demo: {
    title: 'billing.demo.title',
    hint: 'billing.demo.hint',
    open: 'billing.demo.open',
    declined: 'billing.demo.declined',
    expired: 'billing.demo.expired',
    clear: 'billing.demo.clear',
  },
  alert: {
    paymentFailed: 'billing.alert.paymentFailed',
    cardExpiring: 'billing.alert.cardExpiring',
    renewalDue: 'billing.alert.renewalDue',
    spike: 'billing.alert.spike',
  },
  link: {
    open: 'billing.link.open',
  },
} as const;
