/** Screen 199 — Help, FAQ & Support. Types and keys only. */
export const POLL_MS = 60_000;
export const PAGE = 20;
export type HelpTab = 'help' | 'manage' | 'gaps';
export const TABS: HelpTab[] = ['help', 'manage', 'gaps'];

export const HELP_KEYS = {
  title: 'help.title',
  subtitle: 'help.subtitle',
  loading: 'help.loading',
  offline: 'help.offline',
  refresh: 'help.refresh',
  close: 'help.close',
  cancel: 'help.cancel',
  error: {
    title: 'help.error.title',
    body: 'help.error.body',
    retry: 'help.error.retry',
    generic: 'help.error.generic',
    forbidden: 'help.error.forbidden',
    not_found: 'help.error.not_found',
    reason_required: 'help.error.reason_required',
    reason_unknown: 'help.error.reason_unknown',
    comment_long: 'help.error.comment_long',
    text_short: 'help.error.text_short',
    text_long: 'help.error.text_long',
    too_many: 'help.error.too_many',
    kind_unknown: 'help.error.kind_unknown',
    category_unknown: 'help.error.category_unknown',
    roles_required: 'help.error.roles_required',
    role_unknown: 'help.error.role_unknown',
    title_short: 'help.error.title_short',
    body_short: 'help.error.body_short',
    body_long: 'help.error.body_long',
    translation_partial: 'help.error.translation_partial',
    routes_many: 'help.error.routes_many',
    route_invalid: 'help.error.route_invalid',
    note_short: 'help.error.note_short',
    status_unknown: 'help.error.status_unknown',
    no_change: 'help.error.no_change',
    article_required: 'help.error.article_required',
  },
  note: {
    placeholders: 'help.note.placeholders',
  },
  tab: {
    label: 'help.tab.label',
    help: 'help.tab.help',
    manage: 'help.tab.manage',
    gaps: 'help.tab.gaps',
  },
  reader: {
    viewing: 'help.reader.viewing',
    viewAs: 'help.reader.viewAs',
    viewAsHint: 'help.reader.viewAsHint',
    everyRole: 'help.reader.everyRole',
    search: 'help.reader.search',
    all: 'help.reader.all',
    count: 'help.reader.count',
    empty: 'help.reader.empty',
    emptyHint: 'help.reader.emptyHint',
    noMatch: 'help.reader.noMatch',
    noMatchHint: 'help.reader.noMatchHint',
    clear: 'help.reader.clear',
    more: 'help.reader.more',
    updated: 'help.reader.updated',
  },
  role: {
    admin: 'help.role.admin',
    surveyor: 'help.role.surveyor',
    technician: 'help.role.technician',
    customer: 'help.role.customer',
    supplier: 'help.role.supplier',
    all: 'help.role.all',
  },
  category: {
    getting_started: 'help.category.getting_started',
    account: 'help.category.account',
    leads_quotes: 'help.category.leads_quotes',
    earnings: 'help.category.earnings',
    payments: 'help.category.payments',
    projects: 'help.category.projects',
    service: 'help.category.service',
    documents: 'help.category.documents',
    orders: 'help.category.orders',
    training: 'help.category.training',
    admin: 'help.category.admin',
  },
  article: {
    lastChecked: 'help.article.lastChecked',
    version: 'help.article.version',
    screens: 'help.article.screens',
    open: 'help.article.open',
    noTranslation: 'help.article.noTranslation',
    helpfulQ: 'help.article.helpfulQ',
    yes: 'help.article.yes',
    no: 'help.article.no',
    reasonQ: 'help.article.reasonQ',
    reason: {
      wrong: 'help.article.reason.wrong',
      outdated: 'help.article.reason.outdated',
      unclear: 'help.article.reason.unclear',
      missing_steps: 'help.article.reason.missing_steps',
      other: 'help.article.reason.other',
    },
    comment: 'help.article.comment',
    send: 'help.article.send',
    thanks: 'help.article.thanks',
    thanksNo: 'help.article.thanksNo',
    change: 'help.article.change',
    yourAnswerYes: 'help.article.yourAnswerYes',
    yourAnswerNo: 'help.article.yourAnswerNo',
  },
  support: {
    title: 'help.support.title',
    hint: 'help.support.hint',
    urgent: 'help.support.urgent',
    chat: 'help.support.chat',
    ticket: 'help.support.ticket',
    call: 'help.support.call',
    messages: 'help.support.messages',
    safety: 'help.support.safety',
    noPhone: 'help.support.noPhone',
    adminNote: 'help.support.adminNote',
  },
  suggest: {
    button: 'help.suggest.button',
    title: 'help.suggest.title',
    hint: 'help.suggest.hint',
    label: 'help.suggest.label',
    send: 'help.suggest.send',
    sent: 'help.suggest.sent',
  },
  manage: {
    title: 'help.manage.title',
    hint: 'help.manage.hint',
    new: 'help.manage.new',
    search: 'help.manage.search',
    empty: 'help.manage.empty',
    emptyHint: 'help.manage.emptyHint',
    counts: {
      published: 'help.manage.counts.published',
      attention: 'help.manage.counts.attention',
      reviewDue: 'help.manage.counts.reviewDue',
      brokenLinks: 'help.manage.counts.brokenLinks',
      reported: 'help.manage.counts.reported',
      lowRate: 'help.manage.counts.lowRate',
    },
    flag: {
      attention: 'help.manage.flag.attention',
      review_due: 'help.manage.flag.review_due',
      broken_link: 'help.manage.flag.broken_link',
      reported: 'help.manage.flag.reported',
      low_rate: 'help.manage.flag.low_rate',
      draft: 'help.manage.flag.draft',
    },
    status: {
      all: 'help.manage.status.all',
      published: 'help.manage.status.published',
      draft: 'help.manage.status.draft',
      retired: 'help.manage.status.retired',
    },
    row: {
      reviewedOn: 'help.manage.row.reviewedOn',
      dueIn: 'help.manage.row.dueIn',
      overdue: 'help.manage.row.overdue',
      helpful: 'help.manage.row.helpful',
      few: 'help.manage.row.few',
      noAnswers: 'help.manage.row.noAnswers',
      reports: 'help.manage.row.reports',
      escalated: 'help.manage.row.escalated',
      broken: 'help.manage.row.broken',
    },
    catalogueUnknown: 'help.manage.catalogueUnknown',
  },
  detail: {
    stats: 'help.detail.stats',
    helpful: 'help.detail.helpful',
    notHelpful: 'help.detail.notHelpful',
    reports: 'help.detail.reports',
    escalations: 'help.detail.escalations',
    few: 'help.detail.few',
    comments: 'help.detail.comments',
    versions: 'help.detail.versions',
    edit: 'help.detail.edit',
    reviewTitle: 'help.detail.reviewTitle',
    reviewHint: 'help.detail.reviewHint',
    reviewNote: 'help.detail.reviewNote',
    reviewSave: 'help.detail.reviewSave',
    reviewed: 'help.detail.reviewed',
    retire: 'help.detail.retire',
    publish: 'help.detail.publish',
    statusNote: 'help.detail.statusNote',
    statusSaved: 'help.detail.statusSaved',
    retiredNote: 'help.detail.retiredNote',
    roles: 'help.detail.roles',
    checkedBy: 'help.detail.checkedBy',
  },
  editor: {
    titleNew: 'help.editor.titleNew',
    titleEdit: 'help.editor.titleEdit',
    category: 'help.editor.category',
    roles: 'help.editor.roles',
    rolesHint: 'help.editor.rolesHint',
    routes: 'help.editor.routes',
    routesHint: 'help.editor.routesHint',
    titleEn: 'help.editor.titleEn',
    bodyEn: 'help.editor.bodyEn',
    titleHi: 'help.editor.titleHi',
    bodyHi: 'help.editor.bodyHi',
    titleMr: 'help.editor.titleMr',
    bodyMr: 'help.editor.bodyMr',
    translationHint: 'help.editor.translationHint',
    note: 'help.editor.note',
    publish: 'help.editor.publish',
    save: 'help.editor.save',
    saved: 'help.editor.saved',
    newVersion: 'help.editor.newVersion',
  },
  gaps: {
    title: 'help.gaps.title',
    hint: 'help.gaps.hint',
    suggestions: 'help.gaps.suggestions',
    suggestionsEmpty: 'help.gaps.suggestionsEmpty',
    status: {
      new: 'help.gaps.status.new',
      planned: 'help.gaps.status.planned',
      done: 'help.gaps.status.done',
      declined: 'help.gaps.status.declined',
    },
    from: 'help.gaps.from',
    searched: 'help.gaps.searched',
    handle: 'help.gaps.handle',
    handleStatus: 'help.gaps.handleStatus',
    note: 'help.gaps.note',
    article: 'help.gaps.article',
    save: 'help.gaps.save',
    saved: 'help.gaps.saved',
    misses: 'help.gaps.misses',
    missesHint: 'help.gaps.missesHint',
    missesEmpty: 'help.gaps.missesEmpty',
    missCount: 'help.gaps.missCount',
    missDone: 'help.gaps.missDone',
    coverage: 'help.gaps.coverage',
    coverageHint: 'help.gaps.coverageHint',
    coverageLine: 'help.gaps.coverageLine',
    coverageNone: 'help.gaps.coverageNone',
  },
  alert: {
    reported: 'help.alert.reported',
    brokenLink: 'help.alert.brokenLink',
    suggestions: 'help.alert.suggestions',
  },
  link: {
    open: 'help.link.open',
  },
} as const;
