/** Screen 193 — Single-Person Monitor Control Panel. Types and keys only. */
export const POLL_MS = 30_000;

export const SINGLE_PERSON_MONITOR_KEYS = {
  title: 'monitor.title',
  subtitle: 'monitor.subtitle',
  loading: 'monitor.loading',
  offline: 'monitor.offline',
  refresh: 'monitor.refresh',
  close: 'monitor.close',
  error: {
    title: 'monitor.error.title',
    body: 'monitor.error.body',
    retry: 'monitor.error.retry',
    generic: 'monitor.error.generic',
    forbidden: 'monitor.error.forbidden',
    not_found: 'monitor.error.not_found',
    not_allowed: 'monitor.error.not_allowed',
    panel_changed: 'monitor.error.panel_changed',
    signals_need_you: 'monitor.error.signals_need_you',
    note_short: 'monitor.error.note_short',
    review_invalid: 'monitor.error.review_invalid',
    too_many: 'monitor.error.too_many',
    unknown_signal: 'monitor.error.unknown_signal',
    time_invalid: 'monitor.error.time_invalid',
    days_invalid: 'monitor.error.days_invalid',
    already_away: 'monitor.error.already_away',
    until_invalid: 'monitor.error.until_invalid',
    backup_invalid: 'monitor.error.backup_invalid',
    reason_short: 'monitor.error.reason_short',
    access_unavailable: 'monitor.error.access_unavailable',
  },
  status: {
    ok: 'monitor.status.ok',
    watch: 'monitor.status.watch',
    act: 'monitor.status.act',
  },
  hero: {
    allClear: 'monitor.hero.allClear',
    act: 'monitor.hero.act',
    critical: 'monitor.hero.critical',
    watch: 'monitor.hero.watch',
    never: 'monitor.hero.never',
    last: 'monitor.hero.last',
    checkedToday: 'monitor.hero.checkedToday',
    notChecked: 'monitor.hero.notChecked',
  },
  judgement: {
    title: 'monitor.judgement.title',
    body: 'monitor.judgement.body',
  },
  group: {
    safety: 'monitor.group.safety',
    systems: 'monitor.group.systems',
    automation: 'monitor.group.automation',
    business: 'monitor.group.business',
    financial: 'monitor.group.financial',
    workforce: 'monitor.group.workforce',
  },
  signal: {
    critical_alerts: {
      label: 'monitor.signal.critical_alerts.label',
      ok: 'monitor.signal.critical_alerts.ok',
      watch: 'monitor.signal.critical_alerts.watch',
      act: 'monitor.signal.critical_alerts.act',
    },
    safety: {
      label: 'monitor.signal.safety.label',
      ok: 'monitor.signal.safety.ok',
      watch: 'monitor.signal.safety.watch',
      act: 'monitor.signal.safety.act',
    },
    emergency_chain: {
      label: 'monitor.signal.emergency_chain.label',
      ok: 'monitor.signal.emergency_chain.ok',
      watch: 'monitor.signal.emergency_chain.watch',
      act: 'monitor.signal.emergency_chain.act',
    },
    audit_chain: {
      label: 'monitor.signal.audit_chain.label',
      ok: 'monitor.signal.audit_chain.ok',
      watch: 'monitor.signal.audit_chain.watch',
      act: 'monitor.signal.audit_chain.act',
    },
    integrations: {
      label: 'monitor.signal.integrations.label',
      ok: 'monitor.signal.integrations.ok',
      watch: 'monitor.signal.integrations.watch',
      act: 'monitor.signal.integrations.act',
    },
    sandbox_prod: {
      label: 'monitor.signal.sandbox_prod.label',
      ok: 'monitor.signal.sandbox_prod.ok',
      watch: 'monitor.signal.sandbox_prod.watch',
      act: 'monitor.signal.sandbox_prod.act',
    },
    automation: {
      label: 'monitor.signal.automation.label',
      ok: 'monitor.signal.automation.ok',
      watch: 'monitor.signal.automation.watch',
      act: 'monitor.signal.automation.act',
    },
    sla: {
      label: 'monitor.signal.sla.label',
      ok: 'monitor.signal.sla.ok',
      watch: 'monitor.signal.sla.watch',
      act: 'monitor.signal.sla.act',
    },
    commitments: {
      label: 'monitor.signal.commitments.label',
      ok: 'monitor.signal.commitments.ok',
      watch: 'monitor.signal.commitments.watch',
      act: 'monitor.signal.commitments.act',
    },
    leads_new: {
      label: 'monitor.signal.leads_new.label',
      ok: 'monitor.signal.leads_new.ok',
      watch: 'monitor.signal.leads_new.watch',
      act: 'monitor.signal.leads_new.act',
    },
    conversion: {
      label: 'monitor.signal.conversion.label',
      ok: 'monitor.signal.conversion.ok',
      watch: 'monitor.signal.conversion.watch',
      act: 'monitor.signal.conversion.act',
    },
    quotes_expiring: {
      label: 'monitor.signal.quotes_expiring.label',
      ok: 'monitor.signal.quotes_expiring.ok',
      watch: 'monitor.signal.quotes_expiring.watch',
      act: 'monitor.signal.quotes_expiring.act',
    },
    revenue_month: {
      label: 'monitor.signal.revenue_month.label',
      ok: 'monitor.signal.revenue_month.ok',
      watch: 'monitor.signal.revenue_month.watch',
      act: 'monitor.signal.revenue_month.act',
    },
    payments_overdue: {
      label: 'monitor.signal.payments_overdue.label',
      ok: 'monitor.signal.payments_overdue.ok',
      watch: 'monitor.signal.payments_overdue.watch',
      act: 'monitor.signal.payments_overdue.act',
    },
    supplier_pay: {
      label: 'monitor.signal.supplier_pay.label',
      ok: 'monitor.signal.supplier_pay.ok',
      watch: 'monitor.signal.supplier_pay.watch',
      act: 'monitor.signal.supplier_pay.act',
    },
    payouts: {
      label: 'monitor.signal.payouts.label',
      ok: 'monitor.signal.payouts.ok',
      watch: 'monitor.signal.payouts.watch',
      act: 'monitor.signal.payouts.act',
    },
    workforce: {
      label: 'monitor.signal.workforce.label',
      ok: 'monitor.signal.workforce.ok',
      watch: 'monitor.signal.workforce.watch',
      act: 'monitor.signal.workforce.act',
    },
    quality: {
      label: 'monitor.signal.quality.label',
      ok: 'monitor.signal.quality.ok',
      watch: 'monitor.signal.quality.watch',
      act: 'monitor.signal.quality.act',
    },
  },
  card: {
    open: 'monitor.card.open',
    none: 'monitor.card.none',
  },
  trend: {
    up: 'monitor.trend.up',
    upNoPct: 'monitor.trend.upNoPct',
    down: 'monitor.trend.down',
    downNoPct: 'monitor.trend.downNoPct',
    flat: 'monitor.trend.flat',
    first: 'monitor.trend.first',
  },
  outside: {
    title: 'monitor.outside.title',
    hint: 'monitor.outside.hint',
  },
  check: {
    title: 'monitor.check.title',
    hint: 'monitor.check.hint',
    allFine: 'monitor.check.allFine',
    withConcerns: 'monitor.check.withConcerns',
    needYou: 'monitor.check.needYou',
    note: 'monitor.check.note',
    doneFine: 'monitor.check.doneFine',
    doneConcerns: 'monitor.check.doneConcerns',
    streak: 'monitor.check.streak',
    history: 'monitor.check.history',
    empty: 'monitor.check.empty',
    line: 'monitor.check.line',
    kind: {
      all_fine: 'monitor.check.kind.all_fine',
      with_concerns: 'monitor.check.kind.with_concerns',
    },
    team: 'monitor.check.team',
    saw: 'monitor.check.saw',
  },
  config: {
    title: 'monitor.config.title',
    hint: 'monitor.config.hint',
    preset: 'monitor.config.preset',
    pinned: 'monitor.config.pinned',
    pick: 'monitor.config.pick',
    rhythm: 'monitor.config.rhythm',
    time: 'monitor.config.time',
    days: 'monitor.config.days',
    save: 'monitor.config.save',
    saved: 'monitor.config.saved',
  },
  preset: {
    early: 'monitor.preset.early',
    growing: 'monitor.preset.growing',
    mature: 'monitor.preset.mature',
    custom: 'monitor.preset.custom',
  },
  day: {
    '0': 'monitor.day.0',
    '1': 'monitor.day.1',
    '2': 'monitor.day.2',
    '3': 'monitor.day.3',
    '4': 'monitor.day.4',
    '5': 'monitor.day.5',
    '6': 'monitor.day.6',
  },
  concern: {
    title: 'monitor.concern.title',
    hint: 'monitor.concern.hint',
    note: 'monitor.concern.note',
    review: 'monitor.concern.review',
    add: 'monitor.concern.add',
    added: 'monitor.concern.added',
    list: 'monitor.concern.list',
    none: 'monitor.concern.none',
    due: 'monitor.concern.due',
    resolve: 'monitor.concern.resolve',
    resolveNote: 'monitor.concern.resolveNote',
    resolveDo: 'monitor.concern.resolveDo',
    resolved: 'monitor.concern.resolved',
  },
  absence: {
    title: 'monitor.absence.title',
    hint: 'monitor.absence.hint',
    limit: 'monitor.absence.limit',
    until: 'monitor.absence.until',
    backup: 'monitor.absence.backup',
    matrix: 'monitor.absence.matrix',
    other: 'monitor.absence.other',
    pick: 'monitor.absence.pick',
    reason: 'monitor.absence.reason',
    set: 'monitor.absence.set',
    setDone: 'monitor.absence.setDone',
    active: 'monitor.absence.active',
    end: 'monitor.absence.end',
    endReason: 'monitor.absence.endReason',
    endDo: 'monitor.absence.endDo',
    ended: 'monitor.absence.ended',
    noCandidates: 'monitor.absence.noCandidates',
    covering: 'monitor.absence.covering',
    matrixLink: 'monitor.absence.matrixLink',
  },
  note: {
    team: 'monitor.note.team',
    placeholders: 'monitor.note.placeholders',
  },
  link: {
    open: 'monitor.link.open',
  },
} as const;
