import { APPROVED_WAIT, CATEGORIES, OUTLIER_TIMES, PAGE, PERIODS, SINGLE_SHARE, SPIKE_MIN_RISE, SPIKE_RATIO, STATUSES } from '@/features/commission/payoutTracker';
import type { PayoutCategory, PayoutStatus, PeriodId } from '@/features/commission/payoutTracker';

export { APPROVED_WAIT, CATEGORIES, OUTLIER_TIMES, PAGE, PERIODS, SINGLE_SHARE, SPIKE_MIN_RISE, SPIKE_RATIO, STATUSES };
export type { PayoutCategory, PayoutStatus, PeriodId };
export const PULL_DISTANCE = 70;
export const SORTS = ['recent', 'amount'] as const;
export type Sort = (typeof SORTS)[number];
export const payoutTrackerPath = (q: Record<string, string>) => { const p = new URLSearchParams(q).toString(); return p ? `/payout-tracker?${p}` : '/payout-tracker'; };

export const PAYOUT_KEYS = {
  title: 'payoutTracker.title',
  subtitle: 'payoutTracker.subtitle',
  loading: 'payoutTracker.loading',
  error: {
    title: 'payoutTracker.error.title',
    body: 'payoutTracker.error.body',
  },
  refresh: {
    button: 'payoutTracker.refresh.button',
    pull: 'payoutTracker.refresh.pull',
    release: 'payoutTracker.refresh.release',
    busy: 'payoutTracker.refresh.busy',
  },
  close: 'payoutTracker.close',
  kpi: {
    approved: {
      label: 'payoutTracker.kpi.approved.label',
      caption: 'payoutTracker.kpi.approved.caption',
      none: 'payoutTracker.kpi.approved.none',
      note: 'payoutTracker.kpi.approved.note',
    },
    pending: {
      label: 'payoutTracker.kpi.pending.label',
      caption: 'payoutTracker.kpi.pending.caption',
      held: 'payoutTracker.kpi.pending.held',
    },
    earned: {
      label: 'payoutTracker.kpi.earned.label',
      caption: 'payoutTracker.kpi.earned.caption',
    },
    paid: {
      label: 'payoutTracker.kpi.paid.label',
      caption: 'payoutTracker.kpi.paid.caption',
    },
    trendUp: 'payoutTracker.kpi.trendUp',
    trendDown: 'payoutTracker.kpi.trendDown',
    trendFlat: 'payoutTracker.kpi.trendFlat',
    noTrend: 'payoutTracker.kpi.noTrend',
    noWindow: 'payoutTracker.kpi.noWindow',
  },
  period: {
    '7': 'payoutTracker.period.7',
    '30': 'payoutTracker.period.30',
    '90': 'payoutTracker.period.90',
    all: 'payoutTracker.period.all',
    custom: 'payoutTracker.period.custom',
    showing: 'payoutTracker.period.showing',
    showingAll: 'payoutTracker.period.showingAll',
  },
  attention: {
    heading: 'payoutTracker.attention.heading',
    body: 'payoutTracker.attention.body',
    none: 'payoutTracker.attention.none',
    spike: 'payoutTracker.attention.spike',
    spikeSingle: 'payoutTracker.attention.spikeSingle',
    spikeActivity: 'payoutTracker.attention.spikeActivity',
    spikeRule: 'payoutTracker.attention.spikeRule',
    outlier: 'payoutTracker.attention.outlier',
    stale: 'payoutTracker.attention.stale',
    held: 'payoutTracker.attention.held',
    open: 'payoutTracker.attention.open',
    openRule: 'payoutTracker.attention.openRule',
  },
  category: {
    heading: 'payoutTracker.category.heading',
    capture: 'payoutTracker.category.capture',
    conversion: 'payoutTracker.category.conversion',
    installation: 'payoutTracker.category.installation',
    qc: 'payoutTracker.category.qc',
    other: 'payoutTracker.category.other',
    share: 'payoutTracker.category.share',
    count: 'payoutTracker.category.count',
    spikeBadge: 'payoutTracker.category.spikeBadge',
    empty: 'payoutTracker.category.empty',
    open: 'payoutTracker.category.open',
  },
  currency: {
    inr: 'payoutTracker.currency.inr',
    others: 'payoutTracker.currency.others',
    line: 'payoutTracker.currency.line',
  },
  filter: {
    heading: 'payoutTracker.filter.heading',
    search: 'payoutTracker.filter.search',
    partner: 'payoutTracker.filter.partner',
    allPartners: 'payoutTracker.filter.allPartners',
    category: 'payoutTracker.filter.category',
    allCategories: 'payoutTracker.filter.allCategories',
    from: 'payoutTracker.filter.from',
    to: 'payoutTracker.filter.to',
    status: 'payoutTracker.filter.status',
    statusAll: 'payoutTracker.filter.statusAll',
    sort: 'payoutTracker.filter.sort',
    sortRecent: 'payoutTracker.filter.sortRecent',
    sortAmount: 'payoutTracker.filter.sortAmount',
    clear: 'payoutTracker.filter.clear',
    more: 'payoutTracker.filter.more',
  },
  status: {
    projected: 'payoutTracker.status.projected',
    approved: 'payoutTracker.status.approved',
    paid: 'payoutTracker.status.paid',
    forfeited: 'payoutTracker.status.forfeited',
    explain: {
      projected: 'payoutTracker.status.explain.projected',
      approved: 'payoutTracker.status.explain.approved',
      paid: 'payoutTracker.status.explain.paid',
      forfeited: 'payoutTracker.status.explain.forfeited',
    },
  },
  list: {
    summary: 'payoutTracker.list.summary',
    empty: 'payoutTracker.list.empty',
    emptyBody: 'payoutTracker.list.emptyBody',
    noMatch: 'payoutTracker.list.noMatch',
    noMatchBody: 'payoutTracker.list.noMatchBody',
    showMore: 'payoutTracker.list.showMore',
    earned: 'payoutTracker.list.earned',
    paid: 'payoutTracker.list.paid',
    held: 'payoutTracker.list.held',
    outlier: 'payoutTracker.list.outlier',
    stale: 'payoutTracker.list.stale',
    role: {
      surveyor: 'payoutTracker.list.role.surveyor',
      technician: 'payoutTracker.list.role.technician',
      supplier: 'payoutTracker.list.role.supplier',
      other: 'payoutTracker.list.role.other',
    },
  },
  export: {
    button: 'payoutTracker.export.button',
    done: 'payoutTracker.export.done',
  },
  detail: {
    title: 'payoutTracker.detail.title',
    partner: 'payoutTracker.detail.partner',
    reason: 'payoutTracker.detail.reason',
    amount: 'payoutTracker.detail.amount',
    status: 'payoutTracker.detail.status',
    deal: 'payoutTracker.detail.deal',
    job: 'payoutTracker.detail.job',
    earned: 'payoutTracker.detail.earned',
    paid: 'payoutTracker.detail.paid',
    id: 'payoutTracker.detail.id',
    rule: 'payoutTracker.detail.rule',
    ruleInferred: 'payoutTracker.detail.ruleInferred',
    noRule: 'payoutTracker.detail.noRule',
    heldBody: 'payoutTracker.detail.heldBody',
    openRule: 'payoutTracker.detail.openRule',
    openCertificate: 'payoutTracker.detail.openCertificate',
    query: {
      heading: 'payoutTracker.detail.query.heading',
      from: {
        partner: 'payoutTracker.detail.query.from.partner',
        admin: 'payoutTracker.detail.query.from.admin',
      },
      status: {
        open: 'payoutTracker.detail.query.status.open',
        answered: 'payoutTracker.detail.query.status.answered',
        resolved: 'payoutTracker.detail.query.status.resolved',
      },
      answer: 'payoutTracker.detail.query.answer',
      hint: 'payoutTracker.detail.query.hint',
      send: 'payoutTracker.detail.query.send',
      sent: 'payoutTracker.detail.query.sent',
      problem: 'payoutTracker.detail.query.problem',
    },
    openPartner: 'payoutTracker.detail.openPartner',
  },
  placeholder: 'payoutTracker.placeholder',
  problem: {
    generic: 'payoutTracker.problem.generic',
  },
  alert: {
    spike: 'payoutTracker.alert.spike',
  },
} as const;
