/** Screen 103 — Site Delivery Checklist. Types and translation keys only. */

import type { DeliveryReceiverRole, DiscrepancyKind } from '@/data/types';

export type DeliveryChecklistStatus = 'loading' | 'ready' | 'error';

/** The most photographs one part can carry. */
export const MAX_PHOTOS = 3;

export const RECEIVER_ROLES: DeliveryReceiverRole[] = ['technician', 'site_contact'];
export const DISCREPANCY_KINDS: DiscrepancyKind[] = ['damaged', 'count', 'wrong_spec'];

export const DELIVERY_CHECKLIST_KEYS = {
  title: 'deliveryChecklist.title',
  subtitleAdmin: 'deliveryChecklist.subtitleAdmin',
  subtitleTechnician: 'deliveryChecklist.subtitleTechnician',
  loading: 'deliveryChecklist.loading',
  error: { title: 'deliveryChecklist.error.title', body: 'deliveryChecklist.error.body' },
  alert: { discrepancy: 'deliveryChecklist.alert.discrepancy' },
  board: {
    arrivalsHeading: 'deliveryChecklist.board.arrivalsHeading',
    arrivalsHint: 'deliveryChecklist.board.arrivalsHint',
    recentHeading: 'deliveryChecklist.board.recentHeading',
    emptyTitle: 'deliveryChecklist.board.emptyTitle',
    emptyBody: 'deliveryChecklist.board.emptyBody',
    emptyPoBody: 'deliveryChecklist.board.emptyPoBody',
    showAll: 'deliveryChecklist.board.showAll',
    start: 'deliveryChecklist.board.start',
    continue: 'deliveryChecklist.board.continue',
    view: 'deliveryChecklist.board.view',
    checkedOf: 'deliveryChecklist.board.checkedOf',
    untracked: 'deliveryChecklist.board.untracked',
    stillOnWay: 'deliveryChecklist.board.stillOnWay',
    eta: 'deliveryChecklist.board.eta',
    summary: 'deliveryChecklist.board.summary',
    reportRaised: 'deliveryChecklist.board.reportRaised',
    tracking: {
      dispatched: 'deliveryChecklist.board.tracking.dispatched',
      in_transit: 'deliveryChecklist.board.tracking.in_transit',
      nearby: 'deliveryChecklist.board.tracking.nearby',
      arrived: 'deliveryChecklist.board.tracking.arrived',
    },
  },
  work: {
    progress: 'deliveryChecklist.work.progress',
    progressOf: 'deliveryChecklist.work.progressOf',
    discard: 'deliveryChecklist.work.discard',
    discardBody: 'deliveryChecklist.work.discardBody',
    discardConfirm: 'deliveryChecklist.work.discardConfirm',
    complete: 'deliveryChecklist.work.complete',
    remaining: 'deliveryChecklist.work.remaining',
    nothingTitle: 'deliveryChecklist.work.nothingTitle',
    nothingBody: 'deliveryChecklist.work.nothingBody',
    notFound: 'deliveryChecklist.work.notFound',
    notFoundBody: 'deliveryChecklist.work.notFoundBody',
    photoRule: 'deliveryChecklist.work.photoRule',
  },
  item: {
    expected: 'deliveryChecklist.item.expected',
    state: {
      pending: 'deliveryChecklist.item.state.pending',
      ok: 'deliveryChecklist.item.state.ok',
      discrepancy: 'deliveryChecklist.item.state.discrepancy',
      not_arrived: 'deliveryChecklist.item.state.not_arrived',
    },
    onDelivery: 'deliveryChecklist.item.onDelivery',
    yes: 'deliveryChecklist.item.yes',
    no: 'deliveryChecklist.item.no',
    notOnBody: 'deliveryChecklist.item.notOnBody',
    count: 'deliveryChecklist.item.count',
    countHint: 'deliveryChecklist.item.countHint',
    condition: 'deliveryChecklist.item.condition',
    conditionOk: 'deliveryChecklist.item.conditionOk',
    conditionBad: 'deliveryChecklist.item.conditionBad',
    spec: 'deliveryChecklist.item.spec',
    specOk: 'deliveryChecklist.item.specOk',
    specBad: 'deliveryChecklist.item.specBad',
    photos: 'deliveryChecklist.item.photos',
    photoSlot: 'deliveryChecklist.item.photoSlot',
    photoMore: 'deliveryChecklist.item.photoMore',
    photoHint: 'deliveryChecklist.item.photoHint',
    photoNone: 'deliveryChecklist.item.photoNone',
    note: 'deliveryChecklist.item.note',
    noteHint: 'deliveryChecklist.item.noteHint',
    noteHintRequired: 'deliveryChecklist.item.noteHintRequired',
    noteMissing: 'deliveryChecklist.item.noteMissing',
    confirm: 'deliveryChecklist.item.confirm',
    reconfirm: 'deliveryChecklist.item.reconfirm',
    willRaise: 'deliveryChecklist.item.willRaise',
    received: 'deliveryChecklist.item.received',
    checkedBy: 'deliveryChecklist.item.checkedBy',
    kind: {
      damaged: 'deliveryChecklist.item.kind.damaged',
      count: 'deliveryChecklist.item.kind.count',
      wrong_spec: 'deliveryChecklist.item.kind.wrong_spec',
    },
    blocked: {
      quantity: 'deliveryChecklist.item.blocked.quantity',
      photo: 'deliveryChecklist.item.blocked.photo',
      note: 'deliveryChecklist.item.blocked.note',
    },
  },
  sign: {
    title: 'deliveryChecklist.sign.title',
    intro: 'deliveryChecklist.sign.intro',
    summary: 'deliveryChecklist.sign.summary',
    summaryRest: 'deliveryChecklist.sign.summaryRest',
    summaryReport: 'deliveryChecklist.sign.summaryReport',
    role: 'deliveryChecklist.sign.role',
    role_technician: 'deliveryChecklist.sign.role_technician',
    role_site_contact: 'deliveryChecklist.sign.role_site_contact',
    roleHint_site_contact: 'deliveryChecklist.sign.roleHint_site_contact',
    name: 'deliveryChecklist.sign.name',
    nameHint: 'deliveryChecklist.sign.nameHint',
    phone: 'deliveryChecklist.sign.phone',
    ack: 'deliveryChecklist.sign.ack',
    ackHint: 'deliveryChecklist.sign.ackHint',
    note: 'deliveryChecklist.sign.note',
    submit: 'deliveryChecklist.sign.submit',
  },
  done: {
    title: 'deliveryChecklist.done.title',
    fully: 'deliveryChecklist.done.fully',
    partial: 'deliveryChecklist.done.partial',
    report: 'deliveryChecklist.done.report',
    jobReady: 'deliveryChecklist.done.jobReady',
    back: 'deliveryChecklist.done.back',
  },
  record: {
    completedAt: 'deliveryChecklist.record.completedAt',
    receivedBy: 'deliveryChecklist.record.receivedBy',
    recordedBy: 'deliveryChecklist.record.recordedBy',
    ack: 'deliveryChecklist.record.ack',
    note: 'deliveryChecklist.record.note',
    laterDefects: 'deliveryChecklist.record.laterDefects',
    reportHeading: 'deliveryChecklist.record.reportHeading',
    reportBody: 'deliveryChecklist.record.reportBody',
    reportWithdrawn: 'deliveryChecklist.record.reportWithdrawn',
    fromVehicle: 'deliveryChecklist.record.fromVehicle',
  },
  toast: {
    itemSaved: 'deliveryChecklist.toast.itemSaved',
    discarded: 'deliveryChecklist.toast.discarded',
  },
  problem: {
    forbidden: 'deliveryChecklist.problem.forbidden',
    not_found: 'deliveryChecklist.problem.not_found',
    invalid_state: 'deliveryChecklist.problem.invalid_state',
    invalid_quantity: 'deliveryChecklist.problem.invalid_quantity',
    photo_required: 'deliveryChecklist.problem.photo_required',
    note_required: 'deliveryChecklist.problem.note_required',
    nothing_arrived: 'deliveryChecklist.problem.nothing_arrived',
    incomplete: 'deliveryChecklist.problem.incomplete',
    receiver_required: 'deliveryChecklist.problem.receiver_required',
    generic: 'deliveryChecklist.problem.generic',
  },
} as const;
