import { DEFAULT_RATES, NO_PAN_RATE, REASON_MIN, SECTIONS, csvCell, fyLabel } from '@/features/tax/tds';
import type { TdsSection } from '@/features/tax/tds';

export { DEFAULT_RATES, NO_PAN_RATE, REASON_MIN, SECTIONS, csvCell, fyLabel };
export type { TdsSection };
export const PULL_DISTANCE = 70;
export const tdsStatementPath = (fy?: string) => (fy ? `/tds-statement?fy=${fy}` : '/tds-statement');

export const TDS_KEYS = {
  title: 'tdsStatement.title',
  subtitle: 'tdsStatement.subtitle',
  subtitleAdmin: 'tdsStatement.subtitleAdmin',
  loading: 'tdsStatement.loading',
  error: {
    title: 'tdsStatement.error.title',
    body: 'tdsStatement.error.body',
  },
  refresh: {
    button: 'tdsStatement.refresh.button',
    pull: 'tdsStatement.refresh.pull',
    release: 'tdsStatement.refresh.release',
    busy: 'tdsStatement.refresh.busy',
  },
  close: 'tdsStatement.close',
  cancel: 'tdsStatement.cancel',
  link: {
    open: 'tdsStatement.link.open',
  },
  fy: {
    chip: 'tdsStatement.fy.chip',
  },
  summary: {
    gross: 'tdsStatement.summary.gross',
    deducted: 'tdsStatement.summary.deducted',
    limit: 'tdsStatement.summary.limit',
    status: {
      zero: {
        title: 'tdsStatement.summary.status.zero.title',
        body: 'tdsStatement.summary.status.zero.body',
      },
      deducting: {
        title: 'tdsStatement.summary.status.deducting.title',
        body: 'tdsStatement.summary.status.deducting.body',
      },
      watching: {
        title: 'tdsStatement.summary.status.watching.title',
        body: 'tdsStatement.summary.status.watching.body',
      },
    },
    toDeduct: 'tdsStatement.summary.toDeduct',
    earlier: 'tdsStatement.summary.earlier',
  },
  pan: {
    onFile: 'tdsStatement.pan.onFile',
    missing: {
      title: 'tdsStatement.pan.missing.title',
      body: 'tdsStatement.pan.missing.body',
    },
  },
  rule: {
    heading: 'tdsStatement.rule.heading',
    line: 'tdsStatement.rule.line',
    section: {
      '194H': 'tdsStatement.rule.section.194H',
      '194C': 'tdsStatement.rule.section.194C',
      '194Q': 'tdsStatement.rule.section.194Q',
    },
    next: 'tdsStatement.rule.next',
    note: 'tdsStatement.rule.note',
  },
  quarters: {
    heading: 'tdsStatement.quarters.heading',
    body: 'tdsStatement.quarters.body',
  },
  quarter: {
    label: 'tdsStatement.quarter.label',
    gross: 'tdsStatement.quarter.gross',
    tds: 'tdsStatement.quarter.tds',
    cert: {
      final: 'tdsStatement.quarter.cert.final',
      provisional: 'tdsStatement.quarter.cert.provisional',
      none: 'tdsStatement.quarter.cert.none',
    },
    download: 'tdsStatement.quarter.download',
    downloadProvisional: 'tdsStatement.quarter.downloadProvisional',
    downloaded: 'tdsStatement.quarter.downloaded',
  },
  annual: {
    heading: 'tdsStatement.annual.heading',
    download: 'tdsStatement.annual.download',
  },
  deductions: {
    heading: 'tdsStatement.deductions.heading',
    empty: 'tdsStatement.deductions.empty',
    line: 'tdsStatement.deductions.line',
    detail: 'tdsStatement.deductions.detail',
    higher: 'tdsStatement.deductions.higher',
    catchUp: 'tdsStatement.deductions.catchUp',
    pending: 'tdsStatement.deductions.pending',
    openHistory: 'tdsStatement.deductions.openHistory',
  },
  cert: {
    heading: 'tdsStatement.cert.heading',
    headingProvisional: 'tdsStatement.cert.headingProvisional',
    deductor: 'tdsStatement.cert.deductor',
    holder: 'tdsStatement.cert.holder',
    pan: 'tdsStatement.cert.pan',
    number: 'tdsStatement.cert.number',
    line: {
      period: 'tdsStatement.cert.line.period',
      section: 'tdsStatement.cert.line.section',
      gross: 'tdsStatement.cert.line.gross',
      tds: 'tdsStatement.cert.line.tds',
      ack: 'tdsStatement.cert.line.ack',
      filed: 'tdsStatement.cert.line.filed',
    },
    col: {
      date: 'tdsStatement.cert.col.date',
      payout: 'tdsStatement.cert.col.payout',
      gross: 'tdsStatement.cert.col.gross',
      rate: 'tdsStatement.cert.col.rate',
      tax: 'tdsStatement.cert.col.tax',
    },
    period: {
      year: 'tdsStatement.cert.period.year',
      quarter: 'tdsStatement.cert.period.quarter',
    },
    status: {
      final: 'tdsStatement.cert.status.final',
      provisional: 'tdsStatement.cert.status.provisional',
    },
    footer: 'tdsStatement.cert.footer',
  },
  admin: {
    kpi: {
      tds: 'tdsStatement.admin.kpi.tds',
      gross: 'tdsStatement.admin.kpi.gross',
      partners: 'tdsStatement.admin.kpi.partners',
      below: 'tdsStatement.admin.kpi.below',
      noPan: 'tdsStatement.admin.kpi.noPan',
      deposited: 'tdsStatement.admin.kpi.deposited',
    },
    quarters: {
      heading: 'tdsStatement.admin.quarters.heading',
    },
    quarter: {
      line: 'tdsStatement.admin.quarter.line',
      totals: 'tdsStatement.admin.quarter.totals',
      empty: 'tdsStatement.admin.quarter.empty',
    },
    month: {
      line: 'tdsStatement.admin.month.line',
      deposited: 'tdsStatement.admin.month.deposited',
      open: 'tdsStatement.admin.month.open',
    },
    deposit: {
      button: 'tdsStatement.admin.deposit.button',
      title: 'tdsStatement.admin.deposit.title',
      note: 'tdsStatement.admin.deposit.note',
      bsr: 'tdsStatement.admin.deposit.bsr',
      serial: 'tdsStatement.admin.deposit.serial',
      date: 'tdsStatement.admin.deposit.date',
      amount: 'tdsStatement.admin.deposit.amount',
      save: 'tdsStatement.admin.deposit.save',
      saved: 'tdsStatement.admin.deposit.saved',
    },
    return: {
      due: 'tdsStatement.admin.return.due',
      filed: 'tdsStatement.admin.return.filed',
      button: 'tdsStatement.admin.return.button',
      title: 'tdsStatement.admin.return.title',
      note: 'tdsStatement.admin.return.note',
      ack: 'tdsStatement.admin.return.ack',
      date: 'tdsStatement.admin.return.date',
      save: 'tdsStatement.admin.return.save',
      saved: 'tdsStatement.admin.return.saved',
    },
    export: {
      button: 'tdsStatement.admin.export.button',
      done: 'tdsStatement.admin.export.done',
      all: 'tdsStatement.admin.export.all',
    },
    rates: {
      heading: 'tdsStatement.admin.rates.heading',
      body: 'tdsStatement.admin.rates.body',
      line: 'tdsStatement.admin.rates.line',
      role: 'tdsStatement.admin.rates.role',
      upcoming: 'tdsStatement.admin.rates.upcoming',
      schedule: 'tdsStatement.admin.rates.schedule',
      title: 'tdsStatement.admin.rates.title',
      rate: 'tdsStatement.admin.rates.rate',
      threshold: 'tdsStatement.admin.rates.threshold',
      effective: 'tdsStatement.admin.rates.effective',
      reason: 'tdsStatement.admin.rates.reason',
      reasonHint: 'tdsStatement.admin.rates.reasonHint',
      save: 'tdsStatement.admin.rates.save',
      saved: 'tdsStatement.admin.rates.saved',
      history: 'tdsStatement.admin.rates.history',
      version: 'tdsStatement.admin.rates.version',
    },
    profiles: {
      heading: 'tdsStatement.admin.profiles.heading',
      body: 'tdsStatement.admin.profiles.body',
      row: 'tdsStatement.admin.profiles.row',
      noPan: 'tdsStatement.admin.profiles.noPan',
      add: 'tdsStatement.admin.profiles.add',
      title: 'tdsStatement.admin.profiles.title',
      pan: 'tdsStatement.admin.profiles.pan',
      panHint: 'tdsStatement.admin.profiles.panHint',
      save: 'tdsStatement.admin.profiles.save',
      saved: 'tdsStatement.admin.profiles.saved',
    },
    role: {
      surveyor: 'tdsStatement.admin.role.surveyor',
      technician: 'tdsStatement.admin.role.technician',
      supplier: 'tdsStatement.admin.role.supplier',
    },
    note: {
      how: 'tdsStatement.admin.note.how',
      supplier: 'tdsStatement.admin.note.supplier',
    },
  },
  placeholder: 'tdsStatement.placeholder',
  alert: {
    untaxed: 'tdsStatement.alert.untaxed',
    supplier: 'tdsStatement.alert.supplier',
  },
  problem: {
    rate_invalid: 'tdsStatement.problem.rate_invalid',
    threshold_invalid: 'tdsStatement.problem.threshold_invalid',
    date_invalid: 'tdsStatement.problem.date_invalid',
    date_past: 'tdsStatement.problem.date_past',
    date_far: 'tdsStatement.problem.date_far',
    before_current: 'tdsStatement.problem.before_current',
    reason_short: 'tdsStatement.problem.reason_short',
    bsr_invalid: 'tdsStatement.problem.bsr_invalid',
    serial_invalid: 'tdsStatement.problem.serial_invalid',
    amount_invalid: 'tdsStatement.problem.amount_invalid',
    ack_invalid: 'tdsStatement.problem.ack_invalid',
    pan_invalid: 'tdsStatement.problem.pan_invalid',
    nothing_to_file: 'tdsStatement.problem.nothing_to_file',
    not_found: 'tdsStatement.problem.not_found',
    forbidden: 'tdsStatement.problem.forbidden',
    generic: 'tdsStatement.problem.generic',
  },
} as const;
