/** Screen 146 — Offer & Onboarding Agreement. Types and translation keys only. */

import { MAX_ADDENDUM_ITEMS, REASON_MIN, REQUEST_MIN, TERM_DEFS } from '@/features/recruitment/agreement';

export const POLL_MS = 30_000;
export const DEMO_OTP = '123456';
export const OTP_LENGTH = 6;
export const WRONG_BEFORE_FALLBACK = 3;
export const TABS = ['offers', 'terms'] as const;
export type AgreementTab = (typeof TABS)[number];
export const STAGE_FILTERS = ['all', 'to_prepare', 'sent', 'signed', 'waiting'] as const;
export type StageFilter = (typeof STAGE_FILTERS)[number];
export const STAGES = ['interview_open', 'verifying', 'waitlisted', 'to_prepare', 'draft', 'sent', 'signed', 'withdrawn'] as const;
export const ROLES = ['surveyor', 'technician', 'supplier'] as const;
export const boardPath = '/offers';
export const detailPath = (id: string) => `/offers/${id}`;
export const applyPath = (id: string) => `/apply/${id}`;
export const keyKey = (id: string) => `aiec.application.${id}`;
export const draftKey = (id: string) => `aiec.agreementDraft.${id}`;
export { MAX_ADDENDUM_ITEMS, REASON_MIN, REQUEST_MIN, TERM_DEFS };

const rec = <T extends string | number>(ns: string, keys: readonly T[]) => Object.fromEntries(keys.map((k) => [k, `${ns}.${k}`])) as Record<T, string>;
const TERM_KEYS = ['conversionPct', 'closePct', 'installPoolPct', 'leadBonusPct', 'qcFee', 'deliverySlaDays', 'paymentTermsDays', 'minQualityScore', 'qualityStandards', 'warrantyMonths', 'territoryZoneIds'] as const;
const PROBLEMS = [
  'not_approved', 'interview_open', 'waitlisted', 'verification_open', 'concern_override_required', 'territory_required', 'phone_taken', 'already_signed', 'already_sent', 'not_open',
  'addendum_empty', 'addendum_too_many', 'addendum_term', 'addendum_range', 'addendum_same', 'addendum_reason', 'request_open', 'request_short', 'reason_required',
  'consent_required', 'identity_required', 'signature_required', 'name_required', 'invalid_terms', 'effective_past', 'invalid_link', 'forbidden', 'not_admin', 'not_found', 'offline', 'generic',
] as const;

export const AGREEMENT_KEYS = {
  title: 'agreement.title',
  loading: 'agreement.loading',
  brand: 'agreement.brand',
  language: 'agreement.language',
  error: { title: 'agreement.error.title', body: 'agreement.error.body' },
  invalid: { title: 'agreement.invalid.title', body: 'agreement.invalid.body', action: 'agreement.invalid.action' },
  tabs: { label: 'agreement.tabs.label', offers: 'agreement.tabs.offers', terms: 'agreement.tabs.terms' },
  stage: rec('agreement.stage', STAGES),
  stageFilter: { label: 'agreement.stageFilter.label', ...rec('agreement.stageFilter', ['all', 'to_prepare', 'sent', 'signed', 'waiting'] as const) },
  term: rec('agreement.term', TERM_KEYS),
  unit: { pct: 'agreement.unit.pct', inr: 'agreement.unit.inr', days: 'agreement.unit.days', score: 'agreement.unit.score', months: 'agreement.unit.months' },
  admin: {
    subtitle: 'agreement.admin.subtitle',
    search: 'agreement.admin.search',
    heading: 'agreement.admin.heading',
    hint: 'agreement.admin.hint',
    emptyTitle: 'agreement.admin.emptyTitle',
    emptyBody: 'agreement.admin.emptyBody',
    filteredTitle: 'agreement.admin.filteredTitle',
    filteredBody: 'agreement.admin.filteredBody',
    clear: 'agreement.admin.clear',
    row: { version: 'agreement.admin.row.version', sentAgo: 'agreement.admin.row.sentAgo', question: 'agreement.admin.row.question', basic: 'agreement.admin.row.basic', full: 'agreement.admin.row.full', concern: 'agreement.admin.row.concern' },
    stageBody: rec('agreement.admin.stageBody', STAGES),
  },
  detail: {
    gate: 'agreement.detail.gate',
    gateClear: 'agreement.detail.gateClear',
    gateConditional: 'agreement.detail.gateConditional',
    gateBlocked: 'agreement.detail.gateBlocked',
    openVerification: 'agreement.detail.openVerification',
    openInterview: 'agreement.detail.openInterview',
    interview: 'agreement.detail.interview',
    interviewNone: 'agreement.detail.interviewNone',
    skipped: 'agreement.detail.skipped',
    overrideHeading: 'agreement.detail.overrideHeading',
    overrideBody: 'agreement.detail.overrideBody',
    overrideReason: 'agreement.detail.overrideReason',
    overrideKept: 'agreement.detail.overrideKept',
    template: 'agreement.detail.template',
    newer: 'agreement.detail.newer',
    termsHeading: 'agreement.detail.termsHeading',
    standard: 'agreement.detail.standard',
    custom: 'agreement.detail.custom',
    territory: 'agreement.detail.territory',
    territoryHint: 'agreement.detail.territoryHint',
    phoneTaken: 'agreement.detail.phoneTaken',
    document: 'agreement.detail.document',
    prepare: 'agreement.detail.prepare',
    reprepare: 'agreement.detail.reprepare',
    send: 'agreement.detail.send',
    sendBody: 'agreement.detail.sendBody',
    withdraw: 'agreement.detail.withdraw',
    withdrawBody: 'agreement.detail.withdrawBody',
    withdrawReason: 'agreement.detail.withdrawReason',
    addendumHeading: 'agreement.detail.addendumHeading',
    addendumBody: 'agreement.detail.addendumBody',
    addendumOpen: 'agreement.detail.addendumOpen',
    addendumValue: 'agreement.detail.addendumValue',
    addendumRange: 'agreement.detail.addendumRange',
    addendumReason: 'agreement.detail.addendumReason',
    addendumSave: 'agreement.detail.addendumSave',
    addendumBy: 'agreement.detail.addendumBy',
    requestsHeading: 'agreement.detail.requestsHeading',
    requestFrom: 'agreement.detail.requestFrom',
    respondApprove: 'agreement.detail.respondApprove',
    respondDecline: 'agreement.detail.respondDecline',
    respondNote: 'agreement.detail.respondNote',
    respondNoteHint: 'agreement.detail.respondNoteHint',
    answered: 'agreement.detail.answered',
    signedBody: 'agreement.detail.signedBody',
    signedVia: 'agreement.detail.signedVia',
    otp: 'agreement.detail.otp',
    fallback: 'agreement.detail.fallback',
    activationHeading: 'agreement.detail.activationHeading',
    activationBody: 'agreement.detail.activationBody',
    capability: { basic: 'agreement.detail.capability.basic', full: 'agreement.detail.capability.full' },
    step: { bank: 'agreement.detail.step.bank', photo: 'agreement.detail.step.photo' },
    stepDone: 'agreement.detail.stepDone',
    stepMark: 'agreement.detail.stepMark',
    stepUndo: 'agreement.detail.stepUndo',
    timeline: 'agreement.detail.timeline',
    event: rec('agreement.detail.event', ['prepared', 'addendum', 'sent', 'nudged', 'request', 'response', 'withdrawn', 'signed', 'activated', 'step'] as const),
    back: 'agreement.detail.back',
    confirm: 'agreement.detail.confirm',
  },
  templates: {
    heading: 'agreement.templates.heading',
    body: 'agreement.templates.body',
    legal: 'agreement.templates.legal',
    current: 'agreement.templates.current',
    versions: 'agreement.templates.versions',
    publishHeading: 'agreement.templates.publishHeading',
    effective: 'agreement.templates.effective',
    effectiveHint: 'agreement.templates.effectiveHint',
    note: 'agreement.templates.note',
    noteHint: 'agreement.templates.noteHint',
    publish: 'agreement.templates.publish',
    published: 'agreement.templates.published',
    standards: 'agreement.templates.standards',
    forward: 'agreement.templates.forward',
    version: 'agreement.templates.version',
  },
  doc: {
    heading: 'agreement.doc.heading',
    between: 'agreement.doc.between',
    number: 'agreement.doc.number',
    version: 'agreement.doc.version',
    terms: 'agreement.doc.terms',
    custom: 'agreement.doc.custom',
    customBody: 'agreement.doc.customBody',
    territory: 'agreement.doc.territory',
    download: 'agreement.doc.download',
    signedHeading: 'agreement.doc.signedHeading',
    signedBy: 'agreement.doc.signedBy',
    role: rec('agreement.doc.role', ROLES),
  },
  applicant: {
    heading: 'agreement.applicant.heading',
    hello: 'agreement.applicant.hello',
    noneTitle: 'agreement.applicant.noneTitle',
    noneBody: 'agreement.applicant.noneBody',
    withdrawnTitle: 'agreement.applicant.withdrawnTitle',
    withdrawnBody: 'agreement.applicant.withdrawnBody',
    readFirst: 'agreement.applicant.readFirst',
    askHeading: 'agreement.applicant.askHeading',
    askBody: 'agreement.applicant.askBody',
    askLabel: 'agreement.applicant.askLabel',
    askHint: 'agreement.applicant.askHint',
    askSend: 'agreement.applicant.askSend',
    askSent: 'agreement.applicant.askSent',
    askWaiting: 'agreement.applicant.askWaiting',
    askAnswered: 'agreement.applicant.askAnswered',
    signHeading: 'agreement.applicant.signHeading',
    signBody: 'agreement.applicant.signBody',
    consent: 'agreement.applicant.consent',
    otpHeading: 'agreement.applicant.otpHeading',
    otpBody: 'agreement.applicant.otpBody',
    otpLabel: 'agreement.applicant.otpLabel',
    otpVerify: 'agreement.applicant.otpVerify',
    otpWrong: 'agreement.applicant.otpWrong',
    otpVerified: 'agreement.applicant.otpVerified',
    otpFallback: 'agreement.applicant.otpFallback',
    otpFallbackNote: 'agreement.applicant.otpFallbackNote',
    methodDrawn: 'agreement.applicant.methodDrawn',
    methodTyped: 'agreement.applicant.methodTyped',
    nameLabel: 'agreement.applicant.nameLabel',
    nameHint: 'agreement.applicant.nameHint',
    drawLabel: 'agreement.applicant.drawLabel',
    clear: 'agreement.applicant.clear',
    typedLabel: 'agreement.applicant.typedLabel',
    sign: 'agreement.applicant.sign',
    signing: 'agreement.applicant.signing',
    waitingToSign: 'agreement.applicant.waitingToSign',
    doneHeading: 'agreement.applicant.doneHeading',
    doneBody: 'agreement.applicant.doneBody',
    capabilityBasic: 'agreement.applicant.capabilityBasic',
    capabilityFull: 'agreement.applicant.capabilityFull',
    stepsHeading: 'agreement.applicant.stepsHeading',
    stepsBody: 'agreement.applicant.stepsBody',
    signIn: 'agreement.applicant.signIn',
    backToApplication: 'agreement.applicant.backToApplication',
    draftKept: 'agreement.applicant.draftKept',
  },
  message: { sent: 'agreement.message.sent', nudge: 'agreement.message.nudge', approved: 'agreement.message.approved', declined: 'agreement.message.declined', withdrawn: 'agreement.message.withdrawn', signed: 'agreement.message.signed' },
  alert: { request: 'agreement.alert.request' },
  problem: rec('agreement.problem', PROBLEMS),
} as const;
