/** Screen 200 — App Version, Changelog & Feedback. Types and keys only. */
export type AppInfoTab = 'whatsnew' | 'ideas' | 'about' | 'inbox' | 'release';
export const TABS: AppInfoTab[] = ['whatsnew', 'ideas', 'about'];
export const ADMIN_TABS: AppInfoTab[] = ['whatsnew', 'ideas', 'about', 'inbox', 'release'];
export const VERSION_KEY = 'aiec.appVersion';
export const CHECKED_KEY = 'aiec.updateCheckedAt';

export const APP_INFO_KEYS = {
  title: 'appInfo.title',
  subtitle: 'appInfo.subtitle',
  loading: 'appInfo.loading',
  offline: 'appInfo.offline',
  refresh: 'appInfo.refresh',
  close: 'appInfo.close',
  cancel: 'appInfo.cancel',
  error: {
    title: 'appInfo.error.title',
    body: 'appInfo.error.body',
    retry: 'appInfo.error.retry',
    generic: 'appInfo.error.generic',
    forbidden: 'appInfo.error.forbidden',
    not_found: 'appInfo.error.not_found',
    version_invalid: 'appInfo.error.version_invalid',
    version_not_newer: 'appInfo.error.version_not_newer',
    items_required: 'appInfo.error.items_required',
    items_many: 'appInfo.error.items_many',
    kind_unknown: 'appInfo.error.kind_unknown',
    text_short: 'appInfo.error.text_short',
    roles_required: 'appInfo.error.roles_required',
    role_unknown: 'appInfo.error.role_unknown',
    route_invalid: 'appInfo.error.route_invalid',
    browser_invalid: 'appInfo.error.browser_invalid',
    area_unknown: 'appInfo.error.area_unknown',
    text_long: 'appInfo.error.text_long',
    too_many: 'appInfo.error.too_many',
    own_feedback: 'appInfo.error.own_feedback',
    status_unknown: 'appInfo.error.status_unknown',
    note_short: 'appInfo.error.note_short',
    duplicate_invalid: 'appInfo.error.duplicate_invalid',
    publish_invalid: 'appInfo.error.publish_invalid',
    title_short: 'appInfo.error.title_short',
  },
  note: {
    placeholders: 'appInfo.note.placeholders',
  },
  tab: {
    label: 'appInfo.tab.label',
    whatsnew: 'appInfo.tab.whatsnew',
    ideas: 'appInfo.tab.ideas',
    about: 'appInfo.tab.about',
    inbox: 'appInfo.tab.inbox',
    release: 'appInfo.tab.release',
  },
  update: {
    title: 'appInfo.update.title',
    running: 'appInfo.update.running',
    forYou: 'appInfo.update.forYou',
    workflow: 'appInfo.update.workflow',
    none: 'appInfo.update.none',
    now: 'appInfo.update.now',
    see: 'appInfo.update.see',
    later: 'appInfo.update.later',
    done: 'appInfo.update.done',
    upToDate: 'appInfo.update.upToDate',
    checked: 'appInfo.update.checked',
    compatTooOld: 'appInfo.update.compatTooOld',
    compatUnknown: 'appInfo.update.compatUnknown',
    stub: 'appInfo.update.stub',
  },
  whatsnew: {
    title: 'appInfo.whatsnew.title',
    mine: 'appInfo.whatsnew.mine',
    all: 'appInfo.whatsnew.all',
    empty: 'appInfo.whatsnew.empty',
    emptyHint: 'appInfo.whatsnew.emptyHint',
    noneForRole: 'appInfo.whatsnew.noneForRole',
    version: 'appInfo.whatsnew.version',
    youAreHere: 'appInfo.whatsnew.youAreHere',
    newer: 'appInfo.whatsnew.newer',
    open: 'appInfo.whatsnew.open',
    workflowNote: 'appInfo.whatsnew.workflowNote',
    forEveryone: 'appInfo.whatsnew.forEveryone',
  },
  kind: {
    workflow: 'appInfo.kind.workflow',
    new: 'appInfo.kind.new',
    improved: 'appInfo.kind.improved',
    fixed: 'appInfo.kind.fixed',
  },
  role: {
    admin: 'appInfo.role.admin',
    surveyor: 'appInfo.role.surveyor',
    technician: 'appInfo.role.technician',
    customer: 'appInfo.role.customer',
    supplier: 'appInfo.role.supplier',
    all: 'appInfo.role.all',
  },
  untranslated: 'appInfo.untranslated',
  ideas: {
    title: 'appInfo.ideas.title',
    hint: 'appInfo.ideas.hint',
    helpLink: 'appInfo.ideas.helpLink',
    kind: {
      idea: 'appInfo.ideas.kind.idea',
      problem: 'appInfo.ideas.kind.problem',
      praise: 'appInfo.ideas.kind.praise',
    },
    areaLabel: 'appInfo.ideas.areaLabel',
    area: {
      overall: 'appInfo.ideas.area.overall',
      speed: 'appInfo.ideas.area.speed',
      design: 'appInfo.ideas.area.design',
      language: 'appInfo.ideas.area.language',
      offline: 'appInfo.ideas.area.offline',
      notifications: 'appInfo.ideas.area.notifications',
      reports: 'appInfo.ideas.area.reports',
      other: 'appInfo.ideas.area.other',
    },
    text: 'appInfo.ideas.text',
    send: 'appInfo.ideas.send',
    sent: 'appInfo.ideas.sent',
    sentGrouped: 'appInfo.ideas.sentGrouped',
    similarTitle: 'appInfo.ideas.similarTitle',
    similarOthers: 'appInfo.ideas.similarOthers',
    meToo: 'appInfo.ideas.meToo',
    meTooDone: 'appInfo.ideas.meTooDone',
    votes: 'appInfo.ideas.votes',
    mine: 'appInfo.ideas.mine',
    mineEmpty: 'appInfo.ideas.mineEmpty',
    roadmap: 'appInfo.ideas.roadmap',
    roadmapHint: 'appInfo.ideas.roadmapHint',
    roadmapEmpty: 'appInfo.ideas.roadmapEmpty',
    status: {
      new: 'appInfo.ideas.status.new',
      planned: 'appInfo.ideas.status.planned',
      done: 'appInfo.ideas.status.done',
      declined: 'appInfo.ideas.status.declined',
      duplicate: 'appInfo.ideas.status.duplicate',
    },
    draftKept: 'appInfo.ideas.draftKept',
  },
  about: {
    title: 'appInfo.about.title',
    version: 'appInfo.about.version',
    latest: 'appInfo.about.latest',
    checked: 'appInfo.about.checked',
    deviceLabel: 'appInfo.about.deviceLabel',
    deviceLine: 'appInfo.about.deviceLine',
    device: {
      phone: 'appInfo.about.device.phone',
      tablet: 'appInfo.about.device.tablet',
      desktop: 'appInfo.about.device.desktop',
    },
    compatLabel: 'appInfo.about.compatLabel',
    compat: {
      ok: 'appInfo.about.compat.ok',
      too_old: 'appInfo.about.compat.too_old',
      unknown: 'appInfo.about.compat.unknown',
    },
    compatNeeds: 'appInfo.about.compatNeeds',
    compatNone: 'appInfo.about.compatNone',
    credits: 'appInfo.about.credits',
    creditsHint: 'appInfo.about.creditsHint',
    credit: {
      icons: 'appInfo.about.credit.icons',
      language: 'appInfo.about.credit.language',
      maps: 'appInfo.about.credit.maps',
      framework: 'appInfo.about.credit.framework',
      routing: 'appInfo.about.credit.routing',
      charts: 'appInfo.about.credit.charts',
      reading: 'appInfo.about.credit.reading',
      tooling: 'appInfo.about.credit.tooling',
      other: 'appInfo.about.credit.other',
      google_fonts: 'appInfo.about.credit.google_fonts',
      osm: 'appInfo.about.credit.osm',
    },
    creditServices: 'appInfo.about.creditServices',
    runtime: 'appInfo.about.runtime',
    tooling: 'appInfo.about.tooling',
  },
  inbox: {
    title: 'appInfo.inbox.title',
    hint: 'appInfo.inbox.hint',
    empty: 'appInfo.inbox.empty',
    emptyHint: 'appInfo.inbox.emptyHint',
    filter: {
      open: 'appInfo.inbox.filter.open',
      all: 'appInfo.inbox.filter.all',
    },
    from: 'appInfo.inbox.from',
    similar: 'appInfo.inbox.similar',
    votes: 'appInfo.inbox.votes',
    answer: 'appInfo.inbox.answer',
    status: 'appInfo.inbox.status',
    note: 'appInfo.inbox.note',
    publish: 'appInfo.inbox.publish',
    publicTitle: 'appInfo.inbox.publicTitle',
    publicNote: 'appInfo.inbox.publicNote',
    duplicateOf: 'appInfo.inbox.duplicateOf',
    applyCluster: 'appInfo.inbox.applyCluster',
    save: 'appInfo.inbox.save',
    saved: 'appInfo.inbox.saved',
  },
  release: {
    title: 'appInfo.release.title',
    hint: 'appInfo.release.hint',
    version: 'appInfo.release.version',
    versionHint: 'appInfo.release.versionHint',
    items: 'appInfo.release.items',
    addItem: 'appInfo.release.addItem',
    removeItem: 'appInfo.release.removeItem',
    itemKind: 'appInfo.release.itemKind',
    itemRoles: 'appInfo.release.itemRoles',
    itemEn: 'appInfo.release.itemEn',
    itemHi: 'appInfo.release.itemHi',
    itemMr: 'appInfo.release.itemMr',
    itemRoute: 'appInfo.release.itemRoute',
    requires: 'appInfo.release.requires',
    requiresHint: 'appInfo.release.requiresHint',
    publish: 'appInfo.release.publish',
    published: 'appInfo.release.published',
  },
  adoption: {
    title: 'appInfo.adoption.title',
    hint: 'appInfo.adoption.hint',
    reported: 'appInfo.adoption.reported',
    onLatest: 'appInfo.adoption.onLatest',
    behind: 'appInfo.adoption.behind',
    unsupported: 'appInfo.adoption.unsupported',
    none: 'appInfo.adoption.none',
  },
  alert: {
    feedback: 'appInfo.alert.feedback',
  },
  link: {
    open: 'appInfo.link.open',
  },
} as const;
