import { CORRECTION_MAX, EXPLAIN_MIN, FIRST_RESPONSE, PAGE, PATTERN_DAYS, PATTERN_MIN, PROGRESS_EVERY, REASON_MIN, RESOLVE_TARGET, ESCALATED_TARGET, REVIEW_DUE, STATES, SYSTEMIC_MIN, TEXT_MIN, TOPICS, UPDATE_MIN } from '@/features/payout/dispute';
import type { Topic } from '@/features/payout/dispute';

export { CORRECTION_MAX, EXPLAIN_MIN, FIRST_RESPONSE, PAGE, PATTERN_DAYS, PATTERN_MIN, PROGRESS_EVERY, REASON_MIN, RESOLVE_TARGET, ESCALATED_TARGET, REVIEW_DUE, STATES, SYSTEMIC_MIN, TEXT_MIN, TOPICS, UPDATE_MIN };
export type { Topic };
export type Flag = 'all' | 'late' | 'repeat' | 'systemic';
export type FormKind = 'question' | 'dispute';
export const FLAGS: readonly Flag[] = ['all', 'late', 'repeat', 'systemic'];
export const ADMIN_STATES = ['active', 'open', 'in_review', 'escalated', 'resolved', 'all'] as const;
export const disputePath = (q: Record<string, string>) => { const p = new URLSearchParams(q).toString(); return p ? `/payout-dispute?${p}` : '/payout-dispute'; };

export const DISPUTE_KEYS = {
  title: 'payoutDispute.title',
  subtitle: 'payoutDispute.subtitle',
  subtitleAdmin: 'payoutDispute.subtitleAdmin',
  subtitleSupplier: 'payoutDispute.subtitleSupplier',
  loading: 'payoutDispute.loading',
  error: {
    title: 'payoutDispute.error.title',
    body: 'payoutDispute.error.body',
  },
  refresh: {
    button: 'payoutDispute.refresh.button',
  },
  close: 'payoutDispute.close',
  cancel: 'payoutDispute.cancel',
  back: 'payoutDispute.back',
  link: {
    open: 'payoutDispute.link.open',
  },
  state: {
    open: 'payoutDispute.state.open',
    in_review: 'payoutDispute.state.in_review',
    escalated: 'payoutDispute.state.escalated',
    answered: 'payoutDispute.state.answered',
    resolved: 'payoutDispute.state.resolved',
  },
  kind: {
    question: 'payoutDispute.kind.question',
    dispute: 'payoutDispute.kind.dispute',
  },
  topic: {
    amount_low: 'payoutDispute.topic.amount_low',
    missing: 'payoutDispute.topic.missing',
    wrong_rule: 'payoutDispute.topic.wrong_rule',
    held_long: 'payoutDispute.topic.held_long',
    deduction: 'payoutDispute.topic.deduction',
    other: 'payoutDispute.topic.other',
  },
  resolution: {
    adjustment: 'payoutDispute.resolution.adjustment',
    explanation: 'payoutDispute.resolution.explanation',
    withdrawn: 'payoutDispute.resolution.withdrawn',
  },
  sla: {
    on_track: 'payoutDispute.sla.on_track',
    due_soon: 'payoutDispute.sla.due_soon',
    overdue: 'payoutDispute.sla.overdue',
    done: 'payoutDispute.sla.done',
    answerBy: 'payoutDispute.sla.answerBy',
    wasDue: 'payoutDispute.sla.wasDue',
  },
  list: {
    heading: 'payoutDispute.list.heading',
    empty: {
      title: 'payoutDispute.list.empty.title',
      body: 'payoutDispute.list.empty.body',
    },
    none: {
      title: 'payoutDispute.list.none.title',
      body: 'payoutDispute.list.none.body',
    },
    clear: 'payoutDispute.list.clear',
    more: 'payoutDispute.list.more',
    new: 'payoutDispute.list.new',
  },
  row: {
    about: 'payoutDispute.row.about',
    round: 'payoutDispute.row.round',
    systemic: 'payoutDispute.row.systemic',
    late: 'payoutDispute.row.late',
    claimed: 'payoutDispute.row.claimed',
  },
  pick: {
    heading: 'payoutDispute.pick.heading',
    body: 'payoutDispute.pick.body',
    empty: 'payoutDispute.pick.empty',
    open: 'payoutDispute.pick.open',
  },
  form: {
    heading: 'payoutDispute.form.heading',
    entry: 'payoutDispute.form.entry',
    choice: {
      heading: 'payoutDispute.form.choice.heading',
      question: {
        label: 'payoutDispute.form.choice.question.label',
        hint: 'payoutDispute.form.choice.question.hint',
      },
      dispute: {
        label: 'payoutDispute.form.choice.dispute.label',
        hint: 'payoutDispute.form.choice.dispute.hint',
      },
    },
    topic: 'payoutDispute.form.topic',
    claimed: 'payoutDispute.form.claimed',
    claimedHint: 'payoutDispute.form.claimedHint',
    text: 'payoutDispute.form.text',
    textHint: 'payoutDispute.form.textHint',
    valid: 'payoutDispute.form.valid',
    send: 'payoutDispute.form.send',
    sendQuestion: 'payoutDispute.form.sendQuestion',
    sendDispute: 'payoutDispute.form.sendDispute',
    sentToast: 'payoutDispute.form.sentToast',
    draft: 'payoutDispute.form.draft',
    disabledHint: 'payoutDispute.form.disabledHint',
    repeatNote: 'payoutDispute.form.repeatNote',
    same: {
      title: 'payoutDispute.form.same.title',
      body: 'payoutDispute.form.same.body',
      none: 'payoutDispute.form.same.none',
      add: 'payoutDispute.form.same.add',
    },
    missing: {
      title: 'payoutDispute.form.missing.title',
      body: 'payoutDispute.form.missing.body',
    },
  },
  detail: {
    heading: 'payoutDispute.detail.heading',
    entry: 'payoutDispute.detail.entry',
    earned: 'payoutDispute.detail.earned',
    claimed: 'payoutDispute.detail.claimed',
    thread: 'payoutDispute.detail.thread',
    earlier: 'payoutDispute.detail.earlier',
    earlierItem: 'payoutDispute.detail.earlierItem',
    nextUpdate: 'payoutDispute.detail.nextUpdate',
    escalated: 'payoutDispute.detail.escalated',
    result: 'payoutDispute.detail.result',
    resultAdjust: 'payoutDispute.detail.resultAdjust',
    resultStage: 'payoutDispute.detail.resultStage',
    resultExplain: 'payoutDispute.detail.resultExplain',
    resultWithdrawn: 'payoutDispute.detail.resultWithdrawn',
    askAgain: 'payoutDispute.detail.askAgain',
    askAgainButton: 'payoutDispute.detail.askAgainButton',
    withdraw: 'payoutDispute.detail.withdraw',
    withdrawn: 'payoutDispute.detail.withdrawn',
    openEntry: 'payoutDispute.detail.openEntry',
    missing: {
      title: 'payoutDispute.detail.missing.title',
      body: 'payoutDispute.detail.missing.body',
    },
  },
  from: {
    partner: 'payoutDispute.from.partner',
    admin: 'payoutDispute.from.admin',
    system: 'payoutDispute.from.system',
  },
  progress: 'payoutDispute.progress',
  msg: {
    received: 'payoutDispute.msg.received',
    adjusted: 'payoutDispute.msg.adjusted',
    escalated: 'payoutDispute.msg.escalated',
    stillWorking: 'payoutDispute.msg.stillWorking',
    stillEscalated: 'payoutDispute.msg.stillEscalated',
  },
  kpi: {
    active: 'payoutDispute.kpi.active',
    late: 'payoutDispute.kpi.late',
    escalated: 'payoutDispute.kpi.escalated',
    systemic: 'payoutDispute.kpi.systemic',
    median: 'payoutDispute.kpi.median',
    medianNone: 'payoutDispute.kpi.medianNone',
    supplier: 'payoutDispute.kpi.supplier',
  },
  filter: {
    state: {
      active: 'payoutDispute.filter.state.active',
      open: 'payoutDispute.filter.state.open',
      in_review: 'payoutDispute.filter.state.in_review',
      escalated: 'payoutDispute.filter.state.escalated',
      answered: 'payoutDispute.filter.state.answered',
      resolved: 'payoutDispute.filter.state.resolved',
      all: 'payoutDispute.filter.state.all',
    },
    flag: {
      all: 'payoutDispute.filter.flag.all',
      late: 'payoutDispute.filter.flag.late',
      repeat: 'payoutDispute.filter.flag.repeat',
      systemic: 'payoutDispute.filter.flag.systemic',
    },
  },
  search: {
    placeholder: 'payoutDispute.search.placeholder',
  },
  pattern: {
    heading: 'payoutDispute.pattern.heading',
    body: 'payoutDispute.pattern.body',
    open: 'payoutDispute.pattern.open',
  },
  supplier: {
    note: 'payoutDispute.supplier.note',
    openThem: 'payoutDispute.supplier.openThem',
    heading: 'payoutDispute.supplier.heading',
    body: 'payoutDispute.supplier.body',
    payment: 'payoutDispute.supplier.payment',
    paymentItem: 'payoutDispute.supplier.paymentItem',
    none: 'payoutDispute.supplier.none',
    position: 'payoutDispute.supplier.position',
    positionHint: 'payoutDispute.supplier.positionHint',
    claimed: 'payoutDispute.supplier.claimed',
    send: 'payoutDispute.supplier.send',
    sent: 'payoutDispute.supplier.sent',
    list: 'payoutDispute.supplier.list',
    empty: 'payoutDispute.supplier.empty',
    row: 'payoutDispute.supplier.row',
    status: {
      open: 'payoutDispute.supplier.status.open',
      resolved: 'payoutDispute.supplier.status.resolved',
    },
    decision: {
      uphold: 'payoutDispute.supplier.decision.uphold',
      supplier_favor: 'payoutDispute.supplier.decision.supplier_favor',
      partial: 'payoutDispute.supplier.decision.partial',
    },
    dueBy: 'payoutDispute.supplier.dueBy',
    kind: {
      amount: 'payoutDispute.supplier.kind.amount',
      retention_timing: 'payoutDispute.supplier.kind.retention_timing',
      invoice: 'payoutDispute.supplier.kind.invoice',
    },
  },
  rule: {
    site_visit: 'payoutDispute.rule.site_visit',
    lead_qualified: 'payoutDispute.rule.lead_qualified',
    conversion: 'payoutDispute.rule.conversion',
    referral_bonus: 'payoutDispute.rule.referral_bonus',
    sales_close: 'payoutDispute.rule.sales_close',
    install_pool: 'payoutDispute.rule.install_pool',
    qc_fee: 'payoutDispute.rule.qc_fee',
  },
  admin: {
    context: 'payoutDispute.admin.context',
    trace: 'payoutDispute.admin.trace',
    traceInferred: 'payoutDispute.admin.traceInferred',
    noRule: 'payoutDispute.admin.noRule',
    repeat: 'payoutDispute.admin.repeat',
    history: 'payoutDispute.admin.history',
    target: 'payoutDispute.admin.target',
    firstBy: 'payoutDispute.admin.firstBy',
    escalation: 'payoutDispute.admin.escalation',
  },
  decide: {
    heading: 'payoutDispute.decide.heading',
    explain: 'payoutDispute.decide.explain',
    adjust: 'payoutDispute.decide.adjust',
    escalate: 'payoutDispute.decide.escalate',
    update: 'payoutDispute.decide.update',
  },
  explain: {
    label: 'payoutDispute.explain.label',
    hint: 'payoutDispute.explain.hint',
    send: 'payoutDispute.explain.send',
  },
  adjust: {
    to: 'payoutDispute.adjust.to',
    hint: 'payoutDispute.adjust.hint',
    diff: 'payoutDispute.adjust.diff',
    reason: 'payoutDispute.adjust.reason',
    reasonHint: 'payoutDispute.adjust.reasonHint',
    systemic: 'payoutDispute.adjust.systemic',
    systemicNote: 'payoutDispute.adjust.systemicNote',
    systemicHint: 'payoutDispute.adjust.systemicHint',
    send: 'payoutDispute.adjust.send',
    notPayable: 'payoutDispute.adjust.notPayable',
  },
  escalate: {
    reason: 'payoutDispute.escalate.reason',
    hint: 'payoutDispute.escalate.hint',
    send: 'payoutDispute.escalate.send',
  },
  update: {
    label: 'payoutDispute.update.label',
    hint: 'payoutDispute.update.hint',
    send: 'payoutDispute.update.send',
  },
  systemic: {
    heading: 'payoutDispute.systemic.heading',
    body: 'payoutDispute.systemic.body',
    others: 'payoutDispute.systemic.others',
    othersNone: 'payoutDispute.systemic.othersNone',
    noRule: 'payoutDispute.systemic.noRule',
    openRules: 'payoutDispute.systemic.openRules',
    flag: 'payoutDispute.systemic.flag',
    flagSend: 'payoutDispute.systemic.flagSend',
    outcome: 'payoutDispute.systemic.outcome',
    rule_changed: 'payoutDispute.systemic.rule_changed',
    no_change: 'payoutDispute.systemic.no_change',
    reviewNote: 'payoutDispute.systemic.reviewNote',
    reviewHint: 'payoutDispute.systemic.reviewHint',
    reviewSend: 'payoutDispute.systemic.reviewSend',
    reviewed: 'payoutDispute.systemic.reviewed',
  },
  placeholder: {
    note: 'payoutDispute.placeholder.note',
  },
  done: {
    explained: 'payoutDispute.done.explained',
    adjusted: 'payoutDispute.done.adjusted',
    escalated: 'payoutDispute.done.escalated',
    update: 'payoutDispute.done.update',
    flagged: 'payoutDispute.done.flagged',
    reviewed: 'payoutDispute.done.reviewed',
  },
  problem: {
    generic: 'payoutDispute.problem.generic',
    text_short: 'payoutDispute.problem.text_short',
    topic_missing: 'payoutDispute.problem.topic_missing',
    claim_invalid: 'payoutDispute.problem.claim_invalid',
    amount_required: 'payoutDispute.problem.amount_required',
    same_words: 'payoutDispute.problem.same_words',
    already_open: 'payoutDispute.problem.already_open',
    not_found: 'payoutDispute.problem.not_found',
    not_yours: 'payoutDispute.problem.not_yours',
    not_admin: 'payoutDispute.problem.not_admin',
    forbidden: 'payoutDispute.problem.forbidden',
    not_open: 'payoutDispute.problem.not_open',
    answer_short: 'payoutDispute.problem.answer_short',
    explain_short: 'payoutDispute.problem.explain_short',
    reason_short: 'payoutDispute.problem.reason_short',
    update_short: 'payoutDispute.problem.update_short',
    correction_invalid: 'payoutDispute.problem.correction_invalid',
    correction_too_large: 'payoutDispute.problem.correction_too_large',
    entry_not_payable: 'payoutDispute.problem.entry_not_payable',
    already_resolved: 'payoutDispute.problem.already_resolved',
    already_flagged: 'payoutDispute.problem.already_flagged',
    systemic_short: 'payoutDispute.problem.systemic_short',
    no_review_needed: 'payoutDispute.problem.no_review_needed',
    outcome_missing: 'payoutDispute.problem.outcome_missing',
    rule_unknown: 'payoutDispute.problem.rule_unknown',
  },
  alert: {
    raised: 'payoutDispute.alert.raised',
    escalated: 'payoutDispute.alert.escalated',
    systemic: 'payoutDispute.alert.systemic',
    pattern: 'payoutDispute.alert.pattern',
  },
} as const;
