import { APPROVE_DUE, EXPEDITE_REASON_MIN, FLAGS, HOLD_KINDS, HOLD_REASON_MIN, HOLD_REVIEW, RELATED_FLAGS, ROUTINE_LIMIT } from '@/features/commission/payoutApproval';
import type { HoldKind, PayoutFlag, QueueState } from '@/features/commission/payoutApproval';

export { APPROVE_DUE, EXPEDITE_REASON_MIN, FLAGS, HOLD_KINDS, HOLD_REASON_MIN, HOLD_REVIEW, RELATED_FLAGS, ROUTINE_LIMIT };
export type { HoldKind, PayoutFlag, QueueState };
export const PAGE = 20;
export const PULL_DISTANCE = 70;
export const STATES = ['pending', 'held', 'cleared'] as const;
export const FLAG_FILTERS = ['all', 'flagged', 'routine'] as const;
export type FlagFilter = (typeof FLAG_FILTERS)[number];
export const payoutApprovalPath = (q: Record<string, string>) => { const p = new URLSearchParams(q).toString(); return p ? `/payout-approval?${p}` : '/payout-approval'; };

export const APPROVAL_KEYS = {
  title: 'payoutApproval.title',
  subtitle: 'payoutApproval.subtitle',
  loading: 'payoutApproval.loading',
  error: {
    title: 'payoutApproval.error.title',
    body: 'payoutApproval.error.body',
  },
  refresh: {
    button: 'payoutApproval.refresh.button',
    pull: 'payoutApproval.refresh.pull',
    release: 'payoutApproval.refresh.release',
    busy: 'payoutApproval.refresh.busy',
  },
  close: 'payoutApproval.close',
  cancel: 'payoutApproval.cancel',
  back: 'payoutApproval.back',
  summary: {
    pending: 'payoutApproval.summary.pending',
    pendingCaption: 'payoutApproval.summary.pendingCaption',
    routine: 'payoutApproval.summary.routine',
    routineCaption: 'payoutApproval.summary.routineCaption',
    held: 'payoutApproval.summary.held',
    heldCaption: 'payoutApproval.summary.heldCaption',
    cleared: 'payoutApproval.summary.cleared',
    clearedCaption: 'payoutApproval.summary.clearedCaption',
    none: 'payoutApproval.summary.none',
  },
  state: {
    pending: 'payoutApproval.state.pending',
    held: 'payoutApproval.state.held',
    cleared: 'payoutApproval.state.cleared',
    all: 'payoutApproval.state.all',
  },
  flagFilter: {
    all: 'payoutApproval.flagFilter.all',
    flagged: 'payoutApproval.flagFilter.flagged',
    routine: 'payoutApproval.flagFilter.routine',
  },
  search: 'payoutApproval.search',
  flag: {
    open_snag: 'payoutApproval.flag.open_snag',
    open_issue: 'payoutApproval.flag.open_issue',
    open_dispute: 'payoutApproval.flag.open_dispute',
    damaged_parts: 'payoutApproval.flag.damaged_parts',
    amount_high: 'payoutApproval.flag.amount_high',
    amount_low: 'payoutApproval.flag.amount_low',
    not_payable: 'payoutApproval.flag.not_payable',
    short: {
      open_snag: 'payoutApproval.flag.short.open_snag',
      open_issue: 'payoutApproval.flag.short.open_issue',
      open_dispute: 'payoutApproval.flag.short.open_dispute',
      damaged_parts: 'payoutApproval.flag.short.damaged_parts',
      amount_high: 'payoutApproval.flag.short.amount_high',
      amount_low: 'payoutApproval.flag.short.amount_low',
      not_payable: 'payoutApproval.flag.short.not_payable',
    },
    hint: {
      amount_high_rule: 'payoutApproval.flag.hint.amount_high_rule',
      amount_low_rule: 'payoutApproval.flag.hint.amount_low_rule',
      amount_high_typical: 'payoutApproval.flag.hint.amount_high_typical',
      not_payable: 'payoutApproval.flag.hint.not_payable',
    },
    seen: 'payoutApproval.flag.seen',
    openRelated: 'payoutApproval.flag.openRelated',
  },
  row: {
    earned: 'payoutApproval.row.earned',
    earnedToday: 'payoutApproval.row.earnedToday',
    approve: 'payoutApproval.row.approve',
    review: 'payoutApproval.row.review',
    hold: 'payoutApproval.row.hold',
    heldFor: 'payoutApproval.row.heldFor',
    heldToday: 'payoutApproval.row.heldToday',
    clearedBy: 'payoutApproval.row.clearedBy',
    urgent: 'payoutApproval.row.urgent',
    routine: 'payoutApproval.row.routine',
    role: {
      surveyor: 'payoutApproval.row.role.surveyor',
      technician: 'payoutApproval.row.role.technician',
      supplier: 'payoutApproval.row.role.supplier',
      other: 'payoutApproval.row.role.other',
    },
  },
  batch: {
    select: 'payoutApproval.batch.select',
    done: 'payoutApproval.batch.done',
    selectAll: 'payoutApproval.batch.selectAll',
    clear: 'payoutApproval.batch.clear',
    hint: 'payoutApproval.batch.hint',
    notRoutine: 'payoutApproval.batch.notRoutine',
    review: 'payoutApproval.batch.review',
    title: 'payoutApproval.batch.title',
    intro: 'payoutApproval.batch.intro',
    total: 'payoutApproval.batch.total',
    confirm: 'payoutApproval.batch.confirm',
    done_toast: 'payoutApproval.batch.done_toast',
    skipped: 'payoutApproval.batch.skipped',
  },
  empty: {
    title: 'payoutApproval.empty.title',
    body: 'payoutApproval.empty.body',
    noMatch: 'payoutApproval.empty.noMatch',
    noMatchBody: 'payoutApproval.empty.noMatchBody',
    clear: 'payoutApproval.empty.clear',
  },
  list: {
    showMore: 'payoutApproval.list.showMore',
    count: 'payoutApproval.list.count',
  },
  detail: {
    title: 'payoutApproval.detail.title',
    what: 'payoutApproval.detail.what',
    deal: 'payoutApproval.detail.deal',
    job: 'payoutApproval.detail.job',
    noRecord: 'payoutApproval.detail.noRecord',
    how: 'payoutApproval.detail.how',
    rule: 'payoutApproval.detail.rule',
    ruleInferred: 'payoutApproval.detail.ruleInferred',
    noRule: 'payoutApproval.detail.noRule',
    dealValue: 'payoutApproval.detail.dealValue',
    tier: 'payoutApproval.detail.tier',
    expected: 'payoutApproval.detail.expected',
    expectedExact: 'payoutApproval.detail.expectedExact',
    openRule: 'payoutApproval.detail.openRule',
    openCertificate: 'payoutApproval.detail.openCertificate',
    flags: 'payoutApproval.detail.flags',
    noFlags: 'payoutApproval.detail.noFlags',
    history: {
      heading: 'payoutApproval.detail.history.heading',
      approved: 'payoutApproval.detail.history.approved',
      approvedBatch: 'payoutApproval.detail.history.approvedBatch',
      approvedUrgent: 'payoutApproval.detail.history.approvedUrgent',
      held: 'payoutApproval.detail.history.held',
      released: 'payoutApproval.detail.history.released',
    },
    noHistory: 'payoutApproval.detail.noHistory',
    partnerSees: 'payoutApproval.detail.partnerSees',
    approve: 'payoutApproval.detail.approve',
    approveUrgent: 'payoutApproval.detail.approveUrgent',
    hold: 'payoutApproval.detail.hold',
    releaseHold: 'payoutApproval.detail.releaseHold',
    releaseHoldBody: 'payoutApproval.detail.releaseHoldBody',
    heldBody: 'payoutApproval.detail.heldBody',
    heldBodyToday: 'payoutApproval.detail.heldBodyToday',
    heldReasonLabel: 'payoutApproval.detail.heldReasonLabel',
  },
  urgent: {
    toggle: 'payoutApproval.urgent.toggle',
    body: 'payoutApproval.urgent.body',
    reason: 'payoutApproval.urgent.reason',
    reasonHint: 'payoutApproval.urgent.reasonHint',
  },
  hold: {
    title: 'payoutApproval.hold.title',
    kind: {
      quality: 'payoutApproval.hold.kind.quality',
      dispute: 'payoutApproval.hold.kind.dispute',
      information: 'payoutApproval.hold.kind.information',
      rule_check: 'payoutApproval.hold.kind.rule_check',
      other: 'payoutApproval.hold.kind.other',
    },
    reason: 'payoutApproval.hold.reason',
    reasonHint: 'payoutApproval.hold.reasonHint',
    kindLabel: 'payoutApproval.hold.kindLabel',
    confirm: 'payoutApproval.hold.confirm',
    done: 'payoutApproval.hold.done',
  },
  approve: {
    done: 'payoutApproval.approve.done',
    doneUrgent: 'payoutApproval.approve.doneUrgent',
    released: 'payoutApproval.approve.released',
  },
  partner: {
    onHold: 'payoutApproval.partner.onHold',
    cleared: 'payoutApproval.partner.cleared',
    hold: {
      quality: 'payoutApproval.partner.hold.quality',
      dispute: 'payoutApproval.partner.hold.dispute',
      information: 'payoutApproval.partner.hold.information',
      rule_check: 'payoutApproval.partner.hold.rule_check',
      other: 'payoutApproval.partner.hold.other',
    },
  },
  placeholder: 'payoutApproval.placeholder',
  note: {
    disbursement: 'payoutApproval.note.disbursement',
  },
  problem: {
    not_found: 'payoutApproval.problem.not_found',
    not_pending: 'payoutApproval.problem.not_pending',
    not_holdable: 'payoutApproval.problem.not_holdable',
    not_held: 'payoutApproval.problem.not_held',
    flags_unacknowledged: 'payoutApproval.problem.flags_unacknowledged',
    reason_required: 'payoutApproval.problem.reason_required',
    kind_invalid: 'payoutApproval.problem.kind_invalid',
    not_admin: 'payoutApproval.problem.not_admin',
    generic: 'payoutApproval.problem.generic',
  },
} as const;
