/** Screen 115 — Supplier Payment History. Types and translation keys only. */

import type { SupplierPaymentPart } from '@/data/types';

export type PaymentHistoryStatus = 'loading' | 'ready' | 'error';

/** Rows fetched per page. A long relationship is read a page at a time, never all at once. */
export const PAGE_SIZE = 20;

export type PartFilter = 'all' | SupplierPaymentPart;
export const PART_FILTERS: PartFilter[] = ['all', 'upfront', 'balance', 'retention'];
export const ADJUSTMENT_DIRECTIONS = ['credit', 'top_up'] as const;
export const REASON_MIN = 8;

const rec = <T extends string>(ns: string, keys: readonly T[]) => Object.fromEntries(keys.map((k) => [k, `${ns}.${k}`])) as Record<T, string>;

export const HISTORY_KEYS = {
  title: 'supplierPaymentHistory.title',
  subtitle: 'supplierPaymentHistory.subtitle',
  subtitleSupplier: 'supplierPaymentHistory.subtitleSupplier',
  loading: 'supplierPaymentHistory.loading',
  error: { title: 'supplierPaymentHistory.error.title', body: 'supplierPaymentHistory.error.body' },
  totals: {
    paid: 'supplierPaymentHistory.totals.paid',
    adjustments: 'supplierPaymentHistory.totals.adjustments',
    net: 'supplierPaymentHistory.totals.net',
    count: 'supplierPaymentHistory.totals.count',
    filtered: 'supplierPaymentHistory.totals.filtered',
  },
  filter: {
    label: 'supplierPaymentHistory.filter.label',
    search: 'supplierPaymentHistory.filter.search',
    supplier: 'supplierPaymentHistory.filter.supplier',
    allSuppliers: 'supplierPaymentHistory.filter.allSuppliers',
    type: 'supplierPaymentHistory.filter.type',
    from: 'supplierPaymentHistory.filter.from',
    to: 'supplierPaymentHistory.filter.to',
    badRange: 'supplierPaymentHistory.filter.badRange',
    clear: 'supplierPaymentHistory.filter.clear',
    ...rec('supplierPaymentHistory.filter', ['all', 'upfront', 'balance', 'retention'] as const),
  },
  part: rec('supplierPayment.part', ['upfront', 'balance', 'retention'] as const),
  list: {
    emptyTitle: 'supplierPaymentHistory.list.emptyTitle',
    emptyBody: 'supplierPaymentHistory.list.emptyBody',
    emptyFilterTitle: 'supplierPaymentHistory.list.emptyFilterTitle',
    emptyFilterBody: 'supplierPaymentHistory.list.emptyFilterBody',
    paidOn: 'supplierPaymentHistory.list.paidOn',
    adjusted: 'supplierPaymentHistory.list.adjusted',
    queried: 'supplierPaymentHistory.list.queried',
    paid: 'supplierPaymentHistory.list.paid',
    monthTotal: 'supplierPaymentHistory.list.monthTotal',
    showing: 'supplierPaymentHistory.list.showing',
    more: 'supplierPaymentHistory.list.more',
    unknownInvoice: 'supplierPaymentHistory.list.unknownInvoice',
  },
  exportAction: { label: 'supplierPaymentHistory.exportAction.label', done: 'supplierPaymentHistory.exportAction.done', none: 'supplierPaymentHistory.exportAction.none' },
  csv: {
    code: 'supplierPaymentHistory.csv.code',
    date: 'supplierPaymentHistory.csv.date',
    supplier: 'supplierPaymentHistory.csv.supplier',
    order: 'supplierPaymentHistory.csv.order',
    site: 'supplierPaymentHistory.csv.site',
    type: 'supplierPaymentHistory.csv.type',
    invoices: 'supplierPaymentHistory.csv.invoices',
    paid: 'supplierPaymentHistory.csv.paid',
    adjustments: 'supplierPaymentHistory.csv.adjustments',
    net: 'supplierPaymentHistory.csv.net',
    reference: 'supplierPaymentHistory.csv.reference',
  },
  detail: {
    title: 'supplierPaymentHistory.detail.title',
    paidAmount: 'supplierPaymentHistory.detail.paidAmount',
    nowStands: 'supplierPaymentHistory.detail.nowStands',
    supplier: 'supplierPaymentHistory.detail.supplier',
    order: 'supplierPaymentHistory.detail.order',
    site: 'supplierPaymentHistory.detail.site',
    paidOn: 'supplierPaymentHistory.detail.paidOn',
    reference: 'supplierPaymentHistory.detail.reference',
    approvedBy: 'supplierPaymentHistory.detail.approvedBy',
    basisHeading: 'supplierPaymentHistory.detail.basisHeading',
    basisHint: 'supplierPaymentHistory.detail.basisHint',
    basisOrder: 'supplierPaymentHistory.detail.basisOrder',
    basisTerms: 'supplierPaymentHistory.detail.basisTerms',
    basisTermsCustom: 'supplierPaymentHistory.detail.basisTermsCustom',
    basisShare: 'supplierPaymentHistory.detail.basisShare',
    basisNet: 'supplierPaymentHistory.detail.basisNet',
    basisPaid: 'supplierPaymentHistory.detail.basisPaid',
    agrees: 'supplierPaymentHistory.detail.agrees',
    differs: 'supplierPaymentHistory.detail.differs',
    noTerms: 'supplierPaymentHistory.detail.noTerms',
    termType: rec('supplierPaymentHistory.detail.termType', ['net', 'milestone', 'advance'] as const),
    invoicesHeading: 'supplierPaymentHistory.detail.invoicesHeading',
    noInvoice: 'supplierPaymentHistory.detail.noInvoice',
    invoiceOpen: 'supplierPaymentHistory.detail.invoiceOpen',
    invoiceStatus: rec('supplierPaymentHistory.detail.invoiceStatus', ['matched', 'awaiting_delivery', 'mismatch', 'rejected'] as const),
    adjustmentsHeading: 'supplierPaymentHistory.detail.adjustmentsHeading',
    adjustmentsHint: 'supplierPaymentHistory.detail.adjustmentsHint',
    noAdjustments: 'supplierPaymentHistory.detail.noAdjustments',
    credit: 'supplierPaymentHistory.detail.credit',
    topUp: 'supplierPaymentHistory.detail.topUp',
    original: 'supplierPaymentHistory.detail.original',
    queriesHeading: 'supplierPaymentHistory.detail.queriesHeading',
    queryBy: 'supplierPaymentHistory.detail.queryBy',
    evidenceHeading: 'supplierPaymentHistory.detail.evidenceHeading',
    historyHeading: 'supplierPaymentHistory.detail.historyHeading',
    disputesHeading: 'supplierPaymentHistory.detail.disputesHeading',
    disputeOpen: 'supplierPaymentHistory.detail.disputeOpen',
    disputeDecided: 'supplierPaymentHistory.detail.disputeDecided',
    disputeRound: 'supplierPaymentHistory.detail.disputeRound',
    disputeDecision: rec('supplierPaymentHistory.detail.disputeDecision', ['uphold', 'supplier_favor', 'partial'] as const),
    by: 'supplierPaymentHistory.detail.by',
    release: 'supplierPaymentHistory.detail.release',
    notFound: 'supplierPaymentHistory.detail.notFound',
    notFoundBody: 'supplierPaymentHistory.detail.notFoundBody',
  },
  evidence: rec('supplierPaymentHistory.evidence', ['invoice_matched', 'manual_override', 'po_sent', 'acknowledged', 'delivery_received', 'delivery_signed', 'net_elapsed', 'retention_released', 'installation_handover'] as const),
  event: rec('supplierPaymentHistory.event', ['triggered', 'held', 'hold_released', 'approved', 'reversed', 'executed', 'amount_changed'] as const),
  action: { dispute: 'supplierPaymentHistory.action.dispute', contest: 'supplierPaymentHistory.action.contest', adjust: 'supplierPaymentHistory.action.adjust', query: 'supplierPaymentHistory.action.query', close: 'supplierPaymentHistory.action.close', back: 'supplierPaymentHistory.action.back' },
  adjust: {
    title: 'supplierPaymentHistory.adjust.title',
    intro: 'supplierPaymentHistory.adjust.intro',
    direction: 'supplierPaymentHistory.adjust.direction',
    credit: 'supplierPaymentHistory.adjust.credit',
    topUp: 'supplierPaymentHistory.adjust.topUp',
    amount: 'supplierPaymentHistory.adjust.amount',
    amountHint: 'supplierPaymentHistory.adjust.amountHint',
    reason: 'supplierPaymentHistory.adjust.reason',
    reasonHint: 'supplierPaymentHistory.adjust.reasonHint',
    result: 'supplierPaymentHistory.adjust.result',
    confirm: 'supplierPaymentHistory.adjust.confirm',
  },
  querySheet: {
    title: 'supplierPaymentHistory.querySheet.title',
    intro: 'supplierPaymentHistory.querySheet.intro',
    note: 'supplierPaymentHistory.querySheet.note',
    noteHint: 'supplierPaymentHistory.querySheet.noteHint',
    confirm: 'supplierPaymentHistory.querySheet.confirm',
  },
  disputeSheet: {
    title: 'supplierPaymentHistory.disputeSheet.title',
    intro: 'supplierPaymentHistory.disputeSheet.intro',
    position: 'supplierPaymentHistory.disputeSheet.position',
    positionHint: 'supplierPaymentHistory.disputeSheet.positionHint',
    claimed: 'supplierPaymentHistory.disputeSheet.claimed',
    claimedHint: 'supplierPaymentHistory.disputeSheet.claimedHint',
    halt: 'supplierPaymentHistory.disputeSheet.halt',
    haltHint: 'supplierPaymentHistory.disputeSheet.haltHint',
    confirm: 'supplierPaymentHistory.disputeSheet.confirm',
  },
  contestSheet: { title: 'supplierPaymentHistory.contestSheet.title', intro: 'supplierPaymentHistory.contestSheet.intro', reason: 'supplierPaymentHistory.contestSheet.reason', confirm: 'supplierPaymentHistory.contestSheet.confirm' },
  toast: { adjusted: 'supplierPaymentHistory.toast.adjusted', queried: 'supplierPaymentHistory.toast.queried', disputed: 'supplierPaymentHistory.toast.disputed', contested: 'supplierPaymentHistory.toast.contested' },
  problem: {
    forbidden: 'supplierPaymentHistory.problem.forbidden',
    not_found: 'supplierPaymentHistory.problem.not_found',
    invalid_amount: 'supplierPaymentHistory.problem.invalid_amount',
    exceeds_payment: 'supplierPaymentHistory.problem.exceeds_payment',
    note_required: 'supplierPaymentHistory.problem.note_required',
    position_required: 'supplierPaymentHistory.problem.position_required',
    already_open: 'supplierPaymentHistory.problem.already_open',
    reopen_window_closed: 'supplierPaymentHistory.problem.reopen_window_closed',
    invalid_state: 'supplierPaymentHistory.problem.invalid_state',
    amount_required: 'supplierPaymentHistory.problem.amount_required',
    generic: 'supplierPaymentHistory.problem.generic',
  },
} as const;
