import { useCallback, useEffect, useMemo, useState } from 'react';
import { useData } from '@/data/DataProvider';
import { useSession } from '@/session/SessionProvider';
import type { CommissionEntry } from '@/data/types';
import type { PeriodId, PeriodTotals, TrackerStatus } from './commission-tracker.types';

export type RaiseQueryResult = 'blocked' | 'raised';

interface CommissionTrackerState {
  status: TrackerStatus;
  period: PeriodId;
  setPeriod: (period: PeriodId) => void;
  entries: CommissionEntry[];
  totals: PeriodTotals;
  paidToDate: number;
  pendingTotal: number;
  nextPayoutDate: string;
  /** Returns which happened, so the view can show the right translated toast
   *  — this hook never touches copy itself. */
  raiseQuery: (entry: CommissionEntry) => RaiseQueryResult;
  reload: () => Promise<void>;
}

const weekStart = (d: Date) => {
  const day = new Date(d);
  day.setHours(0, 0, 0, 0);
  day.setDate(day.getDate() - day.getDay());
  return day;
};

/**
 * Owns the surveyor's own commission ledger.
 *
 * Every entry here is generated by an upstream event — nothing on this screen
 * is ever created directly. Status is read straight off the same
 * `CommissionEntry` records the admin-side payout queue reads, so this is a
 * live mirror, never a second ledger that could quietly drift.
 */
export function useCommissionTracker(): CommissionTrackerState {
  const repository = useData();
  const { user, isDemo } = useSession();

  const [status, setStatus] = useState<TrackerStatus>('loading');
  const [period, setPeriod] = useState<PeriodId>('thisMonth');
  const [entries, setEntries] = useState<CommissionEntry[]>([]);

  const load = useCallback(async () => {
    if (!user) return;
    try {
      const list = await repository.listCommissions(user.id);
      setEntries(list);
      setStatus(list.length === 0 ? 'empty' : 'ready');
    } catch {
      setStatus((current) => (current === 'ready' ? current : 'error'));
    }
  }, [repository, user]);

  useEffect(() => {
    void load();
  }, [load]);

  const totals = useMemo<PeriodTotals>(() => {
    const now = new Date();
    const sumEarned = (from: number, to: number) =>
      entries
        .filter((e) => e.status !== 'forfeited')
        .filter((e) => {
          const t = new Date(e.earnedAt).getTime();
          return t >= from && t < to;
        })
        .reduce((sum, e) => sum + e.amount, 0);

    if (period === 'allTime') {
      return {
        current: entries.filter((e) => e.status !== 'forfeited').reduce((s, e) => s + e.amount, 0),
        previous: 0,
        changePct: null,
      };
    }

    const thisWeekStart = weekStart(now).getTime();
    const lastWeekStart = thisWeekStart - 7 * 86_400_000;
    const thisMonthStart = new Date(now.getFullYear(), now.getMonth(), 1).getTime();
    const lastMonthStart = new Date(now.getFullYear(), now.getMonth() - 1, 1).getTime();

    let current = 0;
    let previous = 0;
    if (period === 'thisWeek') {
      current = sumEarned(thisWeekStart, Date.now());
      previous = sumEarned(lastWeekStart, thisWeekStart);
    } else if (period === 'lastWeek') {
      current = sumEarned(lastWeekStart, thisWeekStart);
      previous = sumEarned(lastWeekStart - 7 * 86_400_000, lastWeekStart);
    } else {
      current = sumEarned(thisMonthStart, Date.now());
      previous = sumEarned(lastMonthStart, thisMonthStart);
    }

    return { current, previous, changePct: previous > 0 ? (current - previous) / previous : null };
  }, [entries, period]);

  const paidToDate = useMemo(
    () => entries.filter((e) => e.status === 'paid').reduce((sum, e) => sum + e.amount, 0),
    [entries],
  );
  const pendingTotal = useMemo(
    () =>
      entries
        .filter((e) => e.status === 'projected' || e.status === 'approved')
        .reduce((sum, e) => sum + e.amount, 0),
    [entries],
  );

  // Payouts run on the 1st of the month, matching the nightly-accrual
  // automation rule that finalises the ledger.
  const nextPayoutDate = useMemo(() => {
    const now = new Date();
    return new Date(now.getFullYear(), now.getMonth() + 1, 1).toISOString();
  }, []);

  const raiseQuery = useCallback(
    (_entry: CommissionEntry): RaiseQueryResult => {
      if (isDemo) return 'blocked';
      // SIMULATED: there is no Payout Dispute screen built yet to route to —
      // it belongs to a later, not-yet-built module. The acknowledgement is
      // real regardless, so the surveyor is not left wondering if it registered.
      return 'raised';
    },
    [isDemo],
  );

  return {
    status,
    period,
    setPeriod,
    entries,
    totals,
    paidToDate,
    pendingTotal,
    nextPayoutDate,
    raiseQuery,
    reload: load,
  };
}
