/** Screen 190 — Automation Testing & Sandbox. Types and keys only. */
export const POLL_MS = 20_000;
export const TABS = ['test', 'library', 'promote'] as const;
export type SandboxTab = (typeof TABS)[number];

export const AUTOMATION_SANDBOX_KEYS = {
  title: 'automationSandbox.title',
  subtitle: 'automationSandbox.subtitle',
  loading: 'automationSandbox.loading',
  offline: 'automationSandbox.offline',
  refresh: 'automationSandbox.refresh',
  close: 'automationSandbox.close',
  error: {
    title: 'automationSandbox.error.title',
    body: 'automationSandbox.error.body',
    retry: 'automationSandbox.error.retry',
    generic: 'automationSandbox.error.generic',
    forbidden: 'automationSandbox.error.forbidden',
    not_found: 'automationSandbox.error.not_found',
    nothing_to_run: 'automationSandbox.error.nothing_to_run',
    expected_needs: 'automationSandbox.error.expected_needs',
    expected_invalid: 'automationSandbox.error.expected_invalid',
    scenario_not_applicable: 'automationSandbox.error.scenario_not_applicable',
    built_in_locked: 'automationSandbox.error.built_in_locked',
    note_short: 'automationSandbox.error.note_short',
    name_short: 'automationSandbox.error.name_short',
    facts_missing: 'automationSandbox.error.facts_missing',
    too_many: 'automationSandbox.error.too_many',
    engine_unknown: 'automationSandbox.error.engine_unknown',
    rule_retired: 'automationSandbox.error.rule_retired',
    already_active: 'automationSandbox.error.already_active',
    not_tested: 'automationSandbox.error.not_tested',
    many_unconfirmed: 'automationSandbox.error.many_unconfirmed',
    conflicts_unacknowledged: 'automationSandbox.error.conflicts_unacknowledged',
    not_simulated: 'automationSandbox.error.not_simulated',
  },
  safe: {
    title: 'automationSandbox.safe.title',
    body: 'automationSandbox.safe.body',
    proof: 'automationSandbox.safe.proof',
  },
  tab: {
    label: 'automationSandbox.tab.label',
    test: 'automationSandbox.tab.test',
    library: 'automationSandbox.tab.library',
    promote: 'automationSandbox.tab.promote',
  },
  engine: {
    custom_rule: 'automationSandbox.engine.custom_rule',
    escalation: 'automationSandbox.engine.escalation',
    commission: 'automationSandbox.engine.commission',
  },
  test: {
    title: 'automationSandbox.test.title',
    rule: 'automationSandbox.test.rule',
    noRules: 'automationSandbox.test.noRules',
    scenarios: 'automationSandbox.test.scenarios',
    all: 'automationSandbox.test.all',
    none: 'automationSandbox.test.none',
    noScenarios: 'automationSandbox.test.noScenarios',
    expectTitle: 'automationSandbox.test.expectTitle',
    expectHint: 'automationSandbox.test.expectHint',
    expectOne: 'automationSandbox.test.expectOne',
    expectAny: 'automationSandbox.test.expectAny',
    run: 'automationSandbox.test.run',
    done: 'automationSandbox.test.done',
    skipped: 'automationSandbox.test.skipped',
  },
  run: {
    title: 'automationSandbox.run.title',
    empty: 'automationSandbox.run.empty',
    status: {
      matched: 'automationSandbox.run.status.matched',
      differs: 'automationSandbox.run.status.differs',
      new: 'automationSandbox.run.status.new',
    },
    expected: 'automationSandbox.run.expected',
    actual: 'automationSandbox.run.actual',
    from: {
      declared: 'automationSandbox.run.from.declared',
      baseline: 'automationSandbox.run.from.baseline',
      none: 'automationSandbox.run.from.none',
    },
    accept: 'automationSandbox.run.accept',
    accepted: 'automationSandbox.run.accepted',
    acceptedToast: 'automationSandbox.run.acceptedToast',
    differsNote: 'automationSandbox.run.differsNote',
    differsDeclared: 'automationSandbox.run.differsDeclared',
    facts: 'automationSandbox.run.facts',
    recent: 'automationSandbox.run.recent',
    line: 'automationSandbox.run.line',
  },
  outcome: {
    fires: 'automationSandbox.outcome.fires',
    action: 'automationSandbox.outcome.action',
    failedConditions: 'automationSandbox.outcome.failedConditions',
    tiersFired: 'automationSandbox.outcome.tiersFired',
    reachesBackup: 'automationSandbox.outcome.reachesBackup',
    skippedUnfilled: 'automationSandbox.outcome.skippedUnfilled',
    exhausted: 'automationSandbox.outcome.exhausted',
    total: 'automationSandbox.outcome.total',
    surveyor: 'automationSandbox.outcome.surveyor',
    technicians: 'automationSandbox.outcome.technicians',
    burdenPct: 'automationSandbox.outcome.burdenPct',
  },
  action: {
    none: 'automationSandbox.action.none',
    alert: 'automationSandbox.action.alert',
    task: 'automationSandbox.action.task',
    message: 'automationSandbox.action.message',
  },
  yes: 'automationSandbox.yes',
  no: 'automationSandbox.no',
  fact: {
    subject: 'automationSandbox.fact.subject',
    kind: 'automationSandbox.fact.kind',
    ageMinutes: 'automationSandbox.fact.ageMinutes',
    dealValue: 'automationSandbox.fact.dealValue',
    source: 'automationSandbox.fact.source',
    surveyorTier: 'automationSandbox.fact.surveyorTier',
    closer: 'automationSandbox.fact.closer',
    leadMinutes: 'automationSandbox.fact.leadMinutes',
    assistantMinutes: 'automationSandbox.fact.assistantMinutes',
    inspectors: 'automationSandbox.fact.inspectors',
  },
  source: {
    field: 'automationSandbox.source.field',
    referral: 'automationSandbox.source.referral',
  },
  tier: {
    new: 'automationSandbox.tier.new',
    established: 'automationSandbox.tier.established',
    senior: 'automationSandbox.tier.senior',
  },
  subject: {
    lead: 'automationSandbox.subject.lead',
    payment: 'automationSandbox.subject.payment',
    job: 'automationSandbox.subject.job',
    ticket: 'automationSandbox.subject.ticket',
  },
  commissionRule: 'automationSandbox.commissionRule',
  scenario: {
    lead_typical: 'automationSandbox.scenario.lead_typical',
    lead_stuck: 'automationSandbox.scenario.lead_stuck',
    lead_unassigned: 'automationSandbox.scenario.lead_unassigned',
    payment_overdue: 'automationSandbox.scenario.payment_overdue',
    payment_overdue_large: 'automationSandbox.scenario.payment_overdue_large',
    delivery_delay: 'automationSandbox.scenario.delivery_delay',
    ticket_waiting: 'automationSandbox.scenario.ticket_waiting',
    esc_sos: 'automationSandbox.scenario.esc_sos',
    esc_critical: 'automationSandbox.scenario.esc_critical',
    esc_payout: 'automationSandbox.scenario.esc_payout',
    esc_high: 'automationSandbox.scenario.esc_high',
    com_residential: 'automationSandbox.scenario.com_residential',
    com_commercial: 'automationSandbox.scenario.com_commercial',
    com_referral: 'automationSandbox.scenario.com_referral',
  },
  library: {
    title: 'automationSandbox.library.title',
    hint: 'automationSandbox.library.hint',
    due: 'automationSandbox.library.due',
    stale: 'automationSandbox.library.stale',
    reviewed: 'automationSandbox.library.reviewed',
    builtIn: 'automationSandbox.library.builtIn',
    custom: 'automationSandbox.library.custom',
    empty: 'automationSandbox.library.empty',
    pick: 'automationSandbox.library.pick',
    review: 'automationSandbox.library.review',
    reviewTitle: 'automationSandbox.library.reviewTitle',
    reviewNote: 'automationSandbox.library.reviewNote',
    reviewDo: 'automationSandbox.library.reviewDo',
    reviewDone: 'automationSandbox.library.reviewDone',
    add: 'automationSandbox.library.add',
    addTitle: 'automationSandbox.library.addTitle',
    name: 'automationSandbox.library.name',
    kind: 'automationSandbox.library.kind',
    save: 'automationSandbox.library.save',
    saved: 'automationSandbox.library.saved',
    edit: 'automationSandbox.library.edit',
    delete: 'automationSandbox.library.delete',
    deleted: 'automationSandbox.library.deleted',
    draftNote: 'automationSandbox.library.draftNote',
  },
  promote: {
    title: 'automationSandbox.promote.title',
    hint: 'automationSandbox.promote.hint',
    empty: 'automationSandbox.promote.empty',
    status: {
      untested: 'automationSandbox.promote.status.untested',
      tested_passed: 'automationSandbox.promote.status.tested_passed',
      tested_failed: 'automationSandbox.promote.status.tested_failed',
      stale: 'automationSandbox.promote.status.stale',
      promoted: 'automationSandbox.promote.status.promoted',
    },
    progress: 'automationSandbox.promote.progress',
    tested: 'automationSandbox.promote.tested',
    neverTested: 'automationSandbox.promote.neverTested',
    staleNote: 'automationSandbox.promote.staleNote',
    nudge: 'automationSandbox.promote.nudge',
    suite: 'automationSandbox.promote.suite',
    suiteDone: 'automationSandbox.promote.suiteDone',
    acceptAll: 'automationSandbox.promote.acceptAll',
    acceptedAll: 'automationSandbox.promote.acceptedAll',
    go: 'automationSandbox.promote.go',
    sheetTitle: 'automationSandbox.promote.sheetTitle',
    matching: 'automationSandbox.promote.matching',
    many: 'automationSandbox.promote.many',
    conflicts: 'automationSandbox.promote.conflicts',
    fromNow: 'automationSandbox.promote.fromNow',
    confirmMany: 'automationSandbox.promote.confirmMany',
    ack: 'automationSandbox.promote.ack',
    live: 'automationSandbox.promote.live',
    done: 'automationSandbox.promote.done',
    build: 'automationSandbox.promote.build',
    edit: 'automationSandbox.promote.edit',
  },
  note: {
    placeholders: 'automationSandbox.note.placeholders',
  },
  link: {
    open: 'automationSandbox.link.open',
  },
} as const;
