/** Screen 195 — Security & Session Management. Types and keys only. */
export const POLL_MS = 30_000;

export const SECURITY_SESSION_KEYS = {
  title: 'security.title',
  subtitle: 'security.subtitle',
  loading: 'security.loading',
  offline: 'security.offline',
  refresh: 'security.refresh',
  close: 'security.close',
  cancel: 'security.cancel',
  error: {
    title: 'security.error.title',
    body: 'security.error.body',
    retry: 'security.error.retry',
    generic: 'security.error.generic',
    forbidden: 'security.error.forbidden',
    not_found: 'security.error.not_found',
    already_ended: 'security.error.already_ended',
    reason_short: 'security.error.reason_short',
    note_short: 'security.error.note_short',
    nothing_to_revoke: 'security.error.nothing_to_revoke',
    cannot_lock_self: 'security.error.cannot_lock_self',
    already_locked: 'security.error.already_locked',
    not_locked: 'security.error.not_locked',
    method_invalid: 'security.error.method_invalid',
    phone_invalid: 'security.error.phone_invalid',
    phone_taken: 'security.error.phone_taken',
    nothing_to_confirm: 'security.error.nothing_to_confirm',
    already_decided: 'security.error.already_decided',
    already_enrolled: 'security.error.already_enrolled',
    not_required: 'security.error.not_required',
    already_excepted: 'security.error.already_excepted',
    until_invalid: 'security.error.until_invalid',
    until_too_far: 'security.error.until_too_far',
    no_change: 'security.error.no_change',
    preview_stale: 'security.error.preview_stale',
    weaken_unconfirmed: 'security.error.weaken_unconfirmed',
    admin_2fa_locked: 'security.error.admin_2fa_locked',
    grace_range: 'security.error.grace_range',
    min_length_range: 'security.error.min_length_range',
    rotate_range: 'security.error.rotate_range',
    reuse_range: 'security.error.reuse_range',
    failed_range: 'security.error.failed_range',
    window_range: 'security.error.window_range',
    lockout_range: 'security.error.lockout_range',
    idle_range: 'security.error.idle_range',
    hours_range: 'security.error.hours_range',
    cannot_simulate_self: 'security.error.cannot_simulate_self',
  },
  summary: {
    sessions: 'security.summary.sessions',
    failures: 'security.summary.failures',
    attention: 'security.summary.attention',
    locked: 'security.summary.locked',
  },
  tab: {
    label: 'security.tab.label',
    overview: 'security.tab.overview',
    accounts: 'security.tab.accounts',
    events: 'security.tab.events',
    exceptions: 'security.tab.exceptions',
    policy: 'security.tab.policy',
  },
  role: {
    admin: 'security.role.admin',
    surveyor: 'security.role.surveyor',
    technician: 'security.role.technician',
    supplier: 'security.role.supplier',
    customer: 'security.role.customer',
  },
  note: {
    placeholders: 'security.note.placeholders',
  },
  overview: {
    attention: 'security.overview.attention',
    attentionHint: 'security.overview.attentionHint',
    clear: 'security.overview.clear',
    second: 'security.overview.second',
    secondHint: 'security.overview.secondHint',
    required: 'security.overview.required',
    optional: 'security.overview.optional',
    setUp: 'security.overview.setUp',
    xOfY: 'security.overview.xOfY',
    inGrace: 'security.overview.inGrace',
    excepted: 'security.overview.excepted',
    blocked: 'security.overview.blocked',
    people: 'security.overview.people',
    since: 'security.overview.since',
    rules: 'security.overview.rules',
    rulesHint: 'security.overview.rulesHint',
    change: 'security.overview.change',
  },
  attention: {
    place: 'security.attention.place',
    locked: 'security.attention.locked',
    request: 'security.attention.request',
    exception_ending: 'security.attention.exception_ending',
    failures: 'security.attention.failures',
    placeHint: 'security.attention.placeHint',
    lockedHint: 'security.attention.lockedHint',
    requestHint: 'security.attention.requestHint',
    exception_endingHint: 'security.attention.exception_endingHint',
    failuresHint: 'security.attention.failuresHint',
  },
  accounts: {
    search: 'security.accounts.search',
    allRoles: 'security.accounts.allRoles',
    state: {
      all: 'security.accounts.state.all',
      attention: 'security.accounts.state.attention',
      no2fa: 'security.accounts.state.no2fa',
      locked: 'security.accounts.state.locked',
      flagged: 'security.accounts.state.flagged',
    },
    count: 'security.accounts.count',
    empty: 'security.accounts.empty',
    emptyHint: 'security.accounts.emptyHint',
    clear: 'security.accounts.clear',
    locked: 'security.accounts.locked',
    flagged: 'security.accounts.flagged',
    sessions: 'security.accounts.sessions',
    lastSeen: 'security.accounts.lastSeen',
    more: 'security.accounts.more',
  },
  tf: {
    enrolled: 'security.tf.enrolled',
    grace: 'security.tf.grace',
    excepted: 'security.tf.excepted',
    blocked: 'security.tf.blocked',
    not_required: 'security.tf.not_required',
  },
  tfMethod: {
    authenticator: 'security.tfMethod.authenticator',
    second_phone: 'security.tfMethod.second_phone',
  },
  session: {
    thisDevice: 'security.session.thisDevice',
    simulated: 'security.session.simulated',
    status: {
      active: 'security.session.status.active',
      revoked: 'security.session.status.revoked',
      expired: 'security.session.status.expired',
      signed_out: 'security.session.status.signed_out',
    },
    noPlace: 'security.session.noPlace',
    opened: 'security.session.opened',
    active: 'security.session.active',
    ended: 'security.session.ended',
    newPlace: 'security.session.newPlace',
    confirmed: 'security.session.confirmed',
    denied: 'security.session.denied',
    itsThem: 'security.session.itsThem',
    notThem: 'security.session.notThem',
    revoke: 'security.session.revoke',
    reason: {
      'device lost': 'security.session.reason.device lost',
      signed_out: 'security.session.reason.signed_out',
      idle: 'security.session.reason.idle',
      too_long: 'security.session.reason.too_long',
      'password changed': 'security.session.reason.password changed',
      account_suspended: 'security.session.reason.account_suspended',
      'not the account holder': 'security.session.reason.not the account holder',
    },
  },
  account: {
    you: 'security.account.you',
    lockTitle: 'security.account.lockTitle',
    lockLine: 'security.account.lockLine',
    recoveryTitle: 'security.account.recoveryTitle',
    recoveryHint: 'security.account.recoveryHint',
    method: 'security.account.method',
    recoveryNote: 'security.account.recoveryNote',
    newPhone: 'security.account.newPhone',
    newPhoneHint: 'security.account.newPhoneHint',
    recoveryStart: 'security.account.recoveryStart',
    recoveryIssued: 'security.account.recoveryIssued',
    newNumber: 'security.account.newNumber',
    cancelRecovery: 'security.account.cancelRecovery',
    codeTitle: 'security.account.codeTitle',
    codeOnce: 'security.account.codeOnce',
    codePhone: 'security.account.codePhone',
    codeDone: 'security.account.codeDone',
    sessionsTitle: 'security.account.sessionsTitle',
    sessionsHint: 'security.account.sessionsHint',
    noSessions: 'security.account.noSessions',
    signOutAll: 'security.account.signOutAll',
    signOutOthers: 'security.account.signOutOthers',
    secondTitle: 'security.account.secondTitle',
    secondState: 'security.account.secondState',
    secondMethod: 'security.account.secondMethod',
    graceEnds: 'security.account.graceEnds',
    grant: 'security.account.grant',
    deviceTitle: 'security.account.deviceTitle',
    deviceHint: 'security.account.deviceHint',
    lost: 'security.account.lost',
    deviceSelf: 'security.account.deviceSelf',
    alreadyLocked: 'security.account.alreadyLocked',
    eventsTitle: 'security.account.eventsTitle',
    allEvents: 'security.account.allEvents',
  },
  lock: {
    reason: {
      device_lost: 'security.lock.reason.device_lost',
      not_me: 'security.lock.reason.not_me',
      admin: 'security.lock.reason.admin',
    },
  },
  method: {
    call_back_known: 'security.method.call_back_known',
    in_person: 'security.method.in_person',
    video_call: 'security.method.video_call',
    reference: 'security.method.reference',
  },
  confirm: {
    revoke: {
      title: 'security.confirm.revoke.title',
      body: 'security.confirm.revoke.body',
      why: 'security.confirm.revoke.why',
      go: 'security.confirm.revoke.go',
    },
    others: {
      title: 'security.confirm.others.title',
      body: 'security.confirm.others.body',
      why: 'security.confirm.others.why',
      go: 'security.confirm.others.go',
    },
    lost: {
      title: 'security.confirm.lost.title',
      body: 'security.confirm.lost.body',
      why: 'security.confirm.lost.why',
      go: 'security.confirm.lost.go',
    },
    place_me: {
      title: 'security.confirm.place_me.title',
      body: 'security.confirm.place_me.body',
      why: 'security.confirm.place_me.why',
      go: 'security.confirm.place_me.go',
    },
    place_not: {
      title: 'security.confirm.place_not.title',
      body: 'security.confirm.place_not.body',
      why: 'security.confirm.place_not.why',
      go: 'security.confirm.place_not.go',
    },
    cancel_recovery: {
      title: 'security.confirm.cancel_recovery.title',
      body: 'security.confirm.cancel_recovery.body',
      why: 'security.confirm.cancel_recovery.why',
      go: 'security.confirm.cancel_recovery.go',
    },
    grant: {
      title: 'security.confirm.grant.title',
      body: 'security.confirm.grant.body',
      why: 'security.confirm.grant.why',
      go: 'security.confirm.grant.go',
    },
  },
  done: {
    revoke: 'security.done.revoke',
    others: 'security.done.others',
    lost: 'security.done.lost',
    place_me: 'security.done.place_me',
    place_not: 'security.done.place_not',
    cancel_recovery: 'security.done.cancel_recovery',
    grant: 'security.done.grant',
    ex_grant: 'security.done.ex_grant',
    ex_decline: 'security.done.ex_decline',
    ex_end: 'security.done.ex_end',
  },
  demo: {
    title: 'security.demo.title',
    hint: 'security.demo.hint',
    open: 'security.demo.open',
    city: 'security.demo.city',
    device: 'security.demo.device',
    signIn: 'security.demo.signIn',
    fail: 'security.demo.fail',
    paused: 'security.demo.paused',
  },
  events: {
    search: 'security.events.search',
    group: {
      all: 'security.events.group.all',
      signins: 'security.events.group.signins',
      places: 'security.events.group.places',
      devices: 'security.events.group.devices',
      factors: 'security.events.group.factors',
      rules: 'security.events.group.rules',
    },
    severity: 'security.events.severity',
    anySeverity: 'security.events.anySeverity',
    sev: {
      info: 'security.events.sev.info',
      notice: 'security.events.sev.notice',
      warning: 'security.events.sev.warning',
      critical: 'security.events.sev.critical',
    },
    flaggedOnly: 'security.events.flaggedOnly',
    oneAccount: 'security.events.oneAccount',
    count: 'security.events.count',
    empty: 'security.events.empty',
    emptyHint: 'security.events.emptyHint',
    more: 'security.events.more',
    open: 'security.events.open',
    resolved: 'security.events.resolved',
  },
  eventKind: {
    login_success: 'security.eventKind.login_success',
    login_failed: 'security.eventKind.login_failed',
    login_paused: 'security.eventKind.login_paused',
    new_location: 'security.eventKind.new_location',
    location_confirmed: 'security.eventKind.location_confirmed',
    location_denied: 'security.eventKind.location_denied',
    session_revoked: 'security.eventKind.session_revoked',
    sessions_revoked_all: 'security.eventKind.sessions_revoked_all',
    session_expired: 'security.eventKind.session_expired',
    device_lost: 'security.eventKind.device_lost',
    account_locked: 'security.eventKind.account_locked',
    recovery_started: 'security.eventKind.recovery_started',
    recovery_completed: 'security.eventKind.recovery_completed',
    recovery_failed: 'security.eventKind.recovery_failed',
    recovery_cancelled: 'security.eventKind.recovery_cancelled',
    twofa_enrolled: 'security.eventKind.twofa_enrolled',
    twofa_passed: 'security.eventKind.twofa_passed',
    twofa_failed: 'security.eventKind.twofa_failed',
    twofa_requested: 'security.eventKind.twofa_requested',
    twofa_exception_granted: 'security.eventKind.twofa_exception_granted',
    twofa_exception_declined: 'security.eventKind.twofa_exception_declined',
    twofa_exception_ended: 'security.eventKind.twofa_exception_ended',
    policy_changed: 'security.eventKind.policy_changed',
    password_reset: 'security.eventKind.password_reset',
  },
  exceptions: {
    title: 'security.exceptions.title',
    hint: 'security.exceptions.hint',
    open: 'security.exceptions.open',
    all: 'security.exceptions.all',
    empty: 'security.exceptions.empty',
    emptyHint: 'security.exceptions.emptyHint',
    asked: 'security.exceptions.asked',
    byPerson: 'security.exceptions.byPerson',
    decided: 'security.exceptions.decided',
    untilLine: 'security.exceptions.untilLine',
    controls: 'security.exceptions.controls',
    grant: 'security.exceptions.grant',
    decline: 'security.exceptions.decline',
    end: 'security.exceptions.end',
    until: 'security.exceptions.until',
    untilHint: 'security.exceptions.untilHint',
    why: {
      grant: 'security.exceptions.why.grant',
      decline: 'security.exceptions.why.decline',
      end: 'security.exceptions.why.end',
    },
    go: {
      grant: 'security.exceptions.go.grant',
      decline: 'security.exceptions.go.decline',
      end: 'security.exceptions.go.end',
    },
  },
  exStatus: {
    requested: 'security.exStatus.requested',
    active: 'security.exStatus.active',
    declined: 'security.exStatus.declined',
    ended: 'security.exStatus.ended',
    expired: 'security.exStatus.expired',
  },
  policy: {
    inForce: 'security.policy.inForce',
    second: {
      title: 'security.policy.second.title',
      hint: 'security.policy.second.hint',
      required: 'security.policy.second.required',
      adminLocked: 'security.policy.second.adminLocked',
      on: 'security.policy.second.on',
      off: 'security.policy.second.off',
      grace: 'security.policy.second.grace',
      graceHint: 'security.policy.second.graceHint',
    },
    password: {
      title: 'security.policy.password.title',
      hint: 'security.policy.password.hint',
      summary: 'security.policy.password.summary',
      now: 'security.policy.password.now',
      min: 'security.policy.password.min',
      upper: 'security.policy.password.upper',
      digit: 'security.policy.password.digit',
      symbol: 'security.policy.password.symbol',
      rotate: 'security.policy.password.rotate',
      rotateHint: 'security.policy.password.rotateHint',
      reuse: 'security.policy.password.reuse',
      scope: 'security.policy.password.scope',
    },
    yes: 'security.policy.yes',
    no: 'security.policy.no',
    signIn: {
      title: 'security.policy.signIn.title',
      hint: 'security.policy.signIn.hint',
      summary: 'security.policy.signIn.summary',
      max: 'security.policy.signIn.max',
      window: 'security.policy.signIn.window',
      pause: 'security.policy.signIn.pause',
    },
    minutes: 'security.policy.minutes',
    hours: 'security.policy.hours',
    sessions: {
      title: 'security.policy.sessions.title',
      hint: 'security.policy.sessions.hint',
      admin: 'security.policy.sessions.admin',
      summary: 'security.policy.sessions.summary',
      idle: 'security.policy.sessions.idle',
      max: 'security.policy.sessions.max',
    },
    review: {
      title: 'security.policy.review.title',
      newlyRequired: 'security.policy.review.newlyRequired',
      sessionsEnding: 'security.policy.review.sessionsEnding',
      weaker: 'security.policy.review.weaker',
      weakerLine: 'security.policy.review.weakerLine',
      reason: 'security.policy.review.reason',
      confirm: 'security.policy.review.confirm',
      discard: 'security.policy.review.discard',
      publish: 'security.policy.review.publish',
    },
    saved: 'security.policy.saved',
    history: 'security.policy.history',
    version: 'security.policy.version',
  },
  weak: {
    twofa_off: 'security.weak.twofa_off',
    grace_longer: 'security.weak.grace_longer',
    session_longer: 'security.weak.session_longer',
    idle_longer: 'security.weak.idle_longer',
    password_shorter: 'security.weak.password_shorter',
    password_classes: 'security.weak.password_classes',
    rotation_longer: 'security.weak.rotation_longer',
    reuse_less: 'security.weak.reuse_less',
    more_failures: 'security.weak.more_failures',
    shorter_pause: 'security.weak.shorter_pause',
  },
  alert: {
    newPlace: 'security.alert.newPlace',
    accountLocked: 'security.alert.accountLocked',
    failedLogins: 'security.alert.failedLogins',
  },
  link: {
    open: 'security.link.open',
  },
} as const;
