/** Screen 136 — Rework Assignment. Types and translation keys only. */

import type { SnagSeverity } from '@/features/qc/snags';
import { SEVERITIES } from '@/features/qc/snags';

export type ReworkStatus = 'loading' | 'ready' | 'error' | 'not_found';
export const POLL_MS = 15_000;
export const draftKey = (userId: string, snagId: string) => `aiec.reworkDraft.${userId}.${snagId}`;
export const SEVERITY_LIST: SnagSeverity[] = SEVERITIES;

export const FINAL_ERRORS = [
  'notes_required', 'evidence_required', 'reason_required', 'scope_note_required', 'cannot_lower', 'part_required', 'quantity_required', 'invalid_state', 'not_owner', 'no_owner',
  'not_found', 'forbidden', 'not_technician', 'supplier_unavailable', 'already_ordered', 'too_many_attachments', 'video_too_large', 'video_too_long', 'wrong_kind', 'not_a_video', 'not_a_photo',
] as const;

const rec = <T extends string>(ns: string, keys: readonly T[]) => Object.fromEntries(keys.map((k) => [k, `${ns}.${k}`])) as Record<T, string>;
export const listPath = '/rework';
export const snagListPath = (jobId: string, snagId?: string) => `/snags/${jobId}${snagId ? `?snag=${snagId}` : ''}`;
export const reworkPath = (id: string) => `/rework/${id}`;

export const REWORK_KEYS = {
  title: 'rework.title',
  loading: 'rework.loading',
  back: 'rework.back',
  toSnag: 'rework.toSnag',
  error: { title: 'rework.error.title', body: 'rework.error.body' },
  notFound: { title: 'rework.notFound.title', body: 'rework.notFound.body', action: 'rework.notFound.action' },
  problem: rec('rework.problem', [...FINAL_ERRORS, 'offline', 'generic'] as const),
  severity: rec('rework.severity', SEVERITIES),
  urgency: rec('rework.urgency', ['immediate', 'standard', 'relaxed'] as const),
  urgencyHint: rec('rework.urgencyHint', ['immediate', 'standard', 'relaxed'] as const),
  status: rec('rework.status', ['open', 'assigned', 'in_progress', 'ready_for_retest', 'disputed', 'verified', 'waived', 'withdrawn'] as const),
  list: {
    heading: 'rework.list.heading',
    mine: 'rework.list.mine',
    unassigned: 'rework.list.unassigned',
    inHand: 'rework.list.inHand',
    waiting: 'rework.list.waiting',
    emptyTitle: 'rework.list.emptyTitle',
    emptyBody: 'rework.list.emptyBody',
    due: 'rework.list.due',
    owner: 'rework.list.owner',
    overdue: 'rework.list.overdue',
    source: rec('rework.list.source', ['qc_mechanical', 'qc_electrical', 'snag'] as const),
    all: 'rework.list.all',
  },
  finding: {
    heading: 'rework.finding.heading',
    site: 'rework.finding.site',
    map: 'rework.finding.map',
    evidence: 'rework.finding.evidence',
    noEvidence: 'rework.finding.noEvidence',
    group: 'rework.finding.group',
    groupRule: 'rework.finding.groupRule',
    disputed: 'rework.finding.disputed',
    pending: 'rework.finding.pending',
    closed: 'rework.finding.closed',
    due: 'rework.finding.due',
    previous: 'rework.finding.previous',
    previousBy: 'rework.finding.previousBy',
    scope: 'rework.finding.scope',
  },
  assign: {
    heading: 'rework.assign.heading',
    body: 'rework.assign.body',
    bodyGroup: 'rework.assign.bodyGroup',
    who: 'rework.assign.who',
    choose: 'rework.assign.choose',
    open: 'rework.assign.open',
    reason: 'rework.assign.reason',
    reasonHint: 'rework.assign.reasonHint',
    reasonNew: 'rework.assign.reasonNew',
    due: rec('rework.assign.due', SEVERITIES),
    go: 'rework.assign.go',
    goReassign: 'rework.assign.goReassign',
    toast: 'rework.assign.toast',
    current: 'rework.assign.current',
  },
  work: {
    heading: 'rework.work.heading',
    startHint: 'rework.work.startHint',
    start: 'rework.work.start',
    startToast: 'rework.work.startToast',
    notes: 'rework.work.notes',
    notesHint: 'rework.work.notesHint',
    notesOk: 'rework.work.notesOk',
    evidence: 'rework.work.evidence',
    evidenceHint: 'rework.work.evidenceHint',
    addPhoto: 'rework.work.addPhoto',
    addVideo: 'rework.work.addVideo',
    remove: 'rework.work.remove',
    complete: 'rework.work.complete',
    completeToast: 'rework.work.completeToast',
    doneTitle: 'rework.work.doneTitle',
    doneBody: 'rework.work.doneBody',
    draftRestored: 'rework.work.draftRestored',
    waitingStart: 'rework.work.waitingStart',
    checklistHint: 'rework.work.checklistHint',
  },
  parts: {
    heading: 'rework.parts.heading',
    intro: 'rework.parts.intro',
    none: 'rework.parts.none',
    request: 'rework.parts.request',
    description: 'rework.parts.description',
    descriptionHint: 'rework.parts.descriptionHint',
    quantity: 'rework.parts.quantity',
    note: 'rework.parts.note',
    send: 'rework.parts.send',
    toast: 'rework.parts.toast',
    line: 'rework.parts.line',
    status: rec('rework.parts.status', ['requested', 'drafted', 'ordered', 'in_transit', 'received'] as const),
    order: 'rework.parts.order',
    orderTitle: 'rework.parts.orderTitle',
    orderBody: 'rework.parts.orderBody',
    supplier: 'rework.parts.supplier',
    chooseOption: 'rework.parts.chooseOption',
    optionLine: 'rework.parts.optionLine',
    none2: 'rework.parts.none2',
    go: 'rework.parts.go',
    orderToast: 'rework.parts.orderToast',
    po: 'rework.parts.po',
  },
  escalate: {
    heading: 'rework.escalate.heading',
    intro: 'rework.escalate.intro',
    open: 'rework.escalate.open',
    severity: 'rework.escalate.severity',
    note: 'rework.escalate.note',
    noteHint: 'rework.escalate.noteHint',
    go: 'rework.escalate.go',
    toast: 'rework.escalate.toast',
    raisesBlock: 'rework.escalate.raisesBlock',
  },
  handBack: { heading: 'rework.handBack.heading', intro: 'rework.handBack.intro', open: 'rework.handBack.open', reason: 'rework.handBack.reason', hint: 'rework.handBack.hint', go: 'rework.handBack.go', toast: 'rework.handBack.toast' },
  history: { heading: 'rework.history.heading' },
  event: rec('rework.event', ['raised', 'failed_again', 'assigned', 'reassigned', 'handed_back', 'rework_started', 'escalated', 'part_requested', 'part_ordered', 'regraded', 'linked', 'disputed', 'dispute_decided', 'ready_for_retest', 'verified', 'waived', 'withdrawn'] as const),
  alert: { escalated: 'rework.alert.escalated' },
  cancel: 'rework.cancel',
} as const;
