/** Screen 189 — Integration Management. Types and keys only. */
export const POLL_MS = 15_000;

export const INTEGRATION_MANAGEMENT_KEYS = {
  title: 'integrationManagement.title',
  subtitle: 'integrationManagement.subtitle',
  loading: 'integrationManagement.loading',
  offline: 'integrationManagement.offline',
  refresh: 'integrationManagement.refresh',
  close: 'integrationManagement.close',
  error: {
    title: 'integrationManagement.error.title',
    body: 'integrationManagement.error.body',
    retry: 'integrationManagement.error.retry',
    generic: 'integrationManagement.error.generic',
    forbidden: 'integrationManagement.error.forbidden',
    not_found: 'integrationManagement.error.not_found',
    secret_short: 'integrationManagement.error.secret_short',
    secret_long: 'integrationManagement.error.secret_long',
    secret_spaces: 'integrationManagement.error.secret_spaces',
    secret_weak: 'integrationManagement.error.secret_weak',
    secret_same: 'integrationManagement.error.secret_same',
    key_id_long: 'integrationManagement.error.key_id_long',
    reason_short: 'integrationManagement.error.reason_short',
    rotating: 'integrationManagement.error.rotating',
    not_rotating: 'integrationManagement.error.not_rotating',
    live_not_configured: 'integrationManagement.error.live_not_configured',
    live_not_tested: 'integrationManagement.error.live_not_tested',
    confirm_required: 'integrationManagement.error.confirm_required',
    same_mode: 'integrationManagement.error.same_mode',
  },
  banner: {
    title: 'integrationManagement.banner.title',
    body: 'integrationManagement.banner.body',
    open: 'integrationManagement.banner.open',
  },
  env: {
    title: 'integrationManagement.env.title',
    demo: 'integrationManagement.env.demo',
    production: 'integrationManagement.env.production',
    testCount: 'integrationManagement.env.testCount',
    switch: 'integrationManagement.env.switch',
    toProduction: 'integrationManagement.env.toProduction',
    toDemo: 'integrationManagement.env.toDemo',
    warnProduction: 'integrationManagement.env.warnProduction',
    warnDemo: 'integrationManagement.env.warnDemo',
  },
  integrations: {
    title: 'integrationManagement.integrations.title',
  },
  integration: {
    payment_gateway: 'integrationManagement.integration.payment_gateway',
    whatsapp: 'integrationManagement.integration.whatsapp',
    sms: 'integrationManagement.integration.sms',
    maps: 'integrationManagement.integration.maps',
    financing_partner: 'integrationManagement.integration.financing_partner',
    bank_feed: 'integrationManagement.integration.bank_feed',
    payout_rail: 'integrationManagement.integration.payout_rail',
    id_verification: 'integrationManagement.integration.id_verification',
  },
  status: {
    operational: 'integrationManagement.status.operational',
    degraded: 'integrationManagement.status.degraded',
    down: 'integrationManagement.status.down',
    rotating: 'integrationManagement.status.rotating',
    not_configured: 'integrationManagement.status.not_configured',
  },
  mode: {
    sandbox: 'integrationManagement.mode.sandbox',
    live: 'integrationManagement.mode.live',
    sandboxName: 'integrationManagement.mode.sandboxName',
    liveName: 'integrationManagement.mode.liveName',
    title: 'integrationManagement.mode.title',
    toLive: 'integrationManagement.mode.toLive',
    toSandbox: 'integrationManagement.mode.toSandbox',
    warnLive: 'integrationManagement.mode.warnLive',
    warnSandbox: 'integrationManagement.mode.warnSandbox',
    reason: 'integrationManagement.mode.reason',
    understand: 'integrationManagement.mode.understand',
    apply: 'integrationManagement.mode.apply',
    done: 'integrationManagement.mode.done',
  },
  card: {
    lastSuccess: 'integrationManagement.card.lastSuccess',
    noSuccess: 'integrationManagement.card.noSuccess',
    health: 'integrationManagement.card.health',
    degradedNote: 'integrationManagement.card.degradedNote',
    credential: 'integrationManagement.card.credential',
    rotated: 'integrationManagement.card.rotated',
    due: 'integrationManagement.card.due',
    noCredential: 'integrationManagement.card.noCredential',
    rotatingNote: 'integrationManagement.card.rotatingNote',
    webhook: 'integrationManagement.card.webhook',
    copy: 'integrationManagement.card.copy',
    copied: 'integrationManagement.card.copied',
    test: 'integrationManagement.card.test',
    tested: 'integrationManagement.card.tested',
    derived: 'integrationManagement.card.derived',
    rotate: 'integrationManagement.card.rotate',
    switchMode: 'integrationManagement.card.switchMode',
    healthLink: 'integrationManagement.card.healthLink',
    cancelRotation: 'integrationManagement.card.cancelRotation',
    slots: 'integrationManagement.card.slots',
  },
  slot: {
    sandbox: 'integrationManagement.slot.sandbox',
    live: 'integrationManagement.slot.live',
    none: 'integrationManagement.slot.none',
    inUse: 'integrationManagement.slot.inUse',
    add: 'integrationManagement.slot.add',
    demoNote: 'integrationManagement.slot.demoNote',
  },
  rotate: {
    title: 'integrationManagement.rotate.title',
    slot: 'integrationManagement.rotate.slot',
    keyId: 'integrationManagement.rotate.keyId',
    secret: 'integrationManagement.rotate.secret',
    secretHint: 'integrationManagement.rotate.secretHint',
    valid: 'integrationManagement.rotate.valid',
    reason: 'integrationManagement.rotate.reason',
    window: 'integrationManagement.rotate.window',
    first: 'integrationManagement.rotate.first',
    save: 'integrationManagement.rotate.save',
    done: 'integrationManagement.rotate.done',
    cancelTitle: 'integrationManagement.rotate.cancelTitle',
    cancelBody: 'integrationManagement.rotate.cancelBody',
    cancelReason: 'integrationManagement.rotate.cancelReason',
    cancelDo: 'integrationManagement.rotate.cancelDo',
  },
  isolation: {
    title: 'integrationManagement.isolation.title',
    body: 'integrationManagement.isolation.body',
    verify: 'integrationManagement.isolation.verify',
    ok: 'integrationManagement.isolation.ok',
    fail: 'integrationManagement.isolation.fail',
    row: 'integrationManagement.isolation.row',
    checked: 'integrationManagement.isolation.checked',
  },
  history: {
    title: 'integrationManagement.history.title',
    empty: 'integrationManagement.history.empty',
    line: 'integrationManagement.history.line',
  },
  note: {
    placeholders: 'integrationManagement.note.placeholders',
  },
  alert: {
    sandboxInProduction: 'integrationManagement.alert.sandboxInProduction',
  },
  link: {
    open: 'integrationManagement.link.open',
  },
} as const;
