/** Screen 143 — Applicant Screening & Scoring. Types and translation keys only. */

import { DECLINE_REASONS, FACTORS, WEIGHT_MAX } from '@/features/recruitment/screening';
import { SECTIONS } from '@/features/recruitment/application';

export const TABS = ['queue', 'waiting', 'decided', 'scoring'] as const;
export type ScreeningTab = (typeof TABS)[number];
export const ROLE_FILTERS = ['all', 'surveyor', 'technician', 'supplier'] as const;
export type RoleFilter = (typeof ROLE_FILTERS)[number];
export const RATINGS = ['strong', 'steady', 'weak'] as const;
export const POLL_MS = 30_000;
export const WEIGHT_STEP = 5;
export { DECLINE_REASONS, FACTORS, SECTIONS, WEIGHT_MAX };
export const screeningPath = (tab?: ScreeningTab, app?: string) => `/screening${tab || app ? '?' : ''}${[tab ? `tab=${tab}` : '', app ? `app=${app}` : ''].filter(Boolean).join('&')}`;
export const applicationPath = (id: string) => `/applications/${id}`;

const rec = <T extends string | number>(ns: string, keys: readonly T[]) => Object.fromEntries(keys.map((k) => [k, `${ns}.${k}`])) as Record<T, string>;
const PROBLEMS = ['not_open', 'reason_required', 'adjust_range', 'nothing_selected', 'sum_not_100', 'out_of_range', 'forbidden', 'not_admin', 'not_found', 'not_approved', 'offline', 'generic'] as const;

export const SCREENING_KEYS = {
  title: 'screening.title',
  subtitle: 'screening.subtitle',
  loading: 'screening.loading',
  error: { title: 'screening.error.title', body: 'screening.error.body' },
  tabs: { label: 'screening.tabs.label', ...rec('screening.tabs', TABS) },
  demand: { busy: 'screening.demand.busy', surge: 'screening.demand.surge' },
  overdueNote: 'screening.overdueNote',
  filter: { search: 'screening.filter.search', role: 'screening.filter.role', all: 'screening.filter.all', select: 'screening.filter.select', done: 'screening.filter.done', selectAll: 'screening.filter.selectAll', declineSelected: 'screening.filter.declineSelected' },
  list: {
    queueHeading: 'screening.list.queueHeading',
    queueHint: 'screening.list.queueHint',
    waitingHeading: 'screening.list.waitingHeading',
    waitingHint: 'screening.list.waitingHint',
    decidedHeading: 'screening.list.decidedHeading',
    decidedHint: 'screening.list.decidedHint',
    emptyQueueTitle: 'screening.list.emptyQueueTitle',
    emptyQueueBody: 'screening.list.emptyQueueBody',
    emptyWaitingTitle: 'screening.list.emptyWaitingTitle',
    emptyWaitingBody: 'screening.list.emptyWaitingBody',
    emptyDecidedTitle: 'screening.list.emptyDecidedTitle',
    emptyDecidedBody: 'screening.list.emptyDecidedBody',
    emptyFilteredTitle: 'screening.list.emptyFilteredTitle',
    emptyFilteredBody: 'screening.list.emptyFilteredBody',
    clearFilter: 'screening.list.clearFilter',
  },
  row: {
    waiting: 'screening.row.waiting',
    today: 'screening.row.today',
    overdue: 'screening.row.overdue',
    why: 'screening.row.why',
    adjusted: 'screening.row.adjusted',
    toCheck: 'screening.row.toCheck',
    select: 'screening.row.select',
    askedAgo: 'screening.row.askedAgo',
    askedToday: 'screening.row.askedToday',
    approved: 'screening.row.approved',
    rejected: 'screening.row.rejected',
    score: 'screening.row.score',
  },
  factor: { name: rec('screening.factor.name', FACTORS), hint: rec('screening.factor.hint', FACTORS) },
  detail: {
    place: 'screening.detail.place',
    outOf: 'screening.detail.outOf',
    breakdown: 'screening.detail.breakdown',
    weight: 'screening.detail.weight',
    points: 'screening.detail.points',
    frozen: 'screening.detail.frozen',
    live: 'screening.detail.live',
    noDetail: 'screening.detail.noDetail',
    open: 'screening.detail.open',
    interview: 'screening.detail.interview',
    outstanding: 'screening.detail.outstanding',
    outstandingNone: 'screening.detail.outstandingNone',
    next: 'screening.detail.next',
    close: 'screening.detail.close',
    notOpen: 'screening.detail.notOpen',
    waitingNote: 'screening.detail.waitingNote',
    asked: 'screening.detail.asked',
    answered: 'screening.detail.answered',
    decisionApproved: 'screening.detail.decisionApproved',
    decisionRejected: 'screening.detail.decisionRejected',
    reason: 'screening.detail.reason',
    note: 'screening.detail.note',
    languageNote: 'screening.detail.languageNote',
  },
  d: {
    completeness: 'screening.d.completeness',
    experience: 'screening.d.experience',
    experienceWords: 'screening.d.experienceWords',
    experienceNoWords: 'screening.d.experienceNoWords',
    zone: 'screening.d.zone',
    supplier: 'screening.d.supplier',
    noTerritory: 'screening.d.noTerritory',
    availability: 'screening.d.availability',
    startSoon: 'screening.d.startSoon',
    startNone: 'screening.d.startNone',
    references: 'screening.d.references',
    noReferences: 'screening.d.noReferences',
  },
  adjust: {
    heading: 'screening.adjust.heading',
    body: 'screening.adjust.body',
    points: 'screening.adjust.points',
    pointsHint: 'screening.adjust.pointsHint',
    reason: 'screening.adjust.reason',
    reasonHint: 'screening.adjust.reasonHint',
    save: 'screening.adjust.save',
    remove: 'screening.adjust.remove',
    open: 'screening.adjust.open',
    by: 'screening.adjust.by',
    saved: 'screening.adjust.saved',
    removed: 'screening.adjust.removed',
  },
  action: { approve: 'screening.action.approve', ask: 'screening.action.ask', decline: 'screening.action.decline', send: 'screening.action.send', back: 'screening.action.back', confirm: 'screening.action.confirm' },
  approve: { heading: 'screening.approve.heading', body: 'screening.approve.body', note: 'screening.approve.note', done: 'screening.approve.done' },
  ask: { heading: 'screening.ask.heading', body: 'screening.ask.body', sections: 'screening.ask.sections', note: 'screening.ask.note', noteHint: 'screening.ask.noteHint', done: 'screening.ask.done' },
  declineSheet: { heading: 'screening.declineSheet.heading', body: 'screening.declineSheet.body', reason: 'screening.declineSheet.reason', note: 'screening.declineSheet.note', preview: 'screening.declineSheet.preview', done: 'screening.declineSheet.done' },
  bulk: { heading: 'screening.bulk.heading', body: 'screening.bulk.body', confirm: 'screening.bulk.confirm', done: 'screening.bulk.done', skipped: 'screening.bulk.skipped' },
  decline: rec('screening.decline', DECLINE_REASONS),
  message: {
    approved: 'screening.message.approved',
    infoRequest: 'screening.message.infoRequest',
    decline: rec('screening.message.decline', DECLINE_REASONS),
  },
  scoring: {
    heading: 'screening.scoring.heading',
    body: 'screening.scoring.body',
    placeholder: 'screening.scoring.placeholder',
    total: 'screening.scoring.total',
    max: 'screening.scoring.max',
    less: 'screening.scoring.less',
    more: 'screening.scoring.more',
    save: 'screening.scoring.save',
    reset: 'screening.scoring.reset',
    changed: 'screening.scoring.changed',
    neverChanged: 'screening.scoring.neverChanged',
    saved: 'screening.scoring.saved',
    reshuffleHeading: 'screening.scoring.reshuffleHeading',
    reshuffleBody: 'screening.scoring.reshuffleBody',
    apply: 'screening.scoring.apply',
    keep: 'screening.scoring.keep',
    noChange: 'screening.scoring.noChange',
  },
  feedback: {
    heading: 'screening.feedback.heading',
    body: 'screening.feedback.body',
    notEnough: 'screening.feedback.notEnough',
    suggest: 'screening.feedback.suggest',
    noSuggest: 'screening.feedback.noSuggest',
    row: 'screening.feedback.row',
    na: 'screening.feedback.na',
    toRate: 'screening.feedback.toRate',
    toRateNone: 'screening.feedback.toRateNone',
    rate: { label: 'screening.feedback.rate.label', ...rec('screening.feedback.rate', RATINGS) },
    note: 'screening.feedback.note',
    saved: 'screening.feedback.saved',
    outcomeHeading: 'screening.feedback.outcomeHeading',
  },
  problem: rec('screening.problem', PROBLEMS),
} as const;
