/** Screen 192 — User & Role Permissions. Types and keys only. */
export const POLL_MS = 20_000;

export const USER_ROLE_PERMISSIONS_KEYS = {
  title: 'accessControl.title',
  subtitle: 'accessControl.subtitle',
  loading: 'accessControl.loading',
  offline: 'accessControl.offline',
  refresh: 'accessControl.refresh',
  close: 'accessControl.close',
  error: {
    title: 'accessControl.error.title',
    body: 'accessControl.error.body',
    retry: 'accessControl.error.retry',
    generic: 'accessControl.error.generic',
    forbidden: 'accessControl.error.forbidden',
    not_found: 'accessControl.error.not_found',
    reason_short: 'accessControl.error.reason_short',
    no_screens: 'accessControl.error.no_screens',
    too_many: 'accessControl.error.too_many',
    locked: 'accessControl.error.locked',
    public_screen: 'accessControl.error.public_screen',
    high_risk_unconfirmed: 'accessControl.error.high_risk_unconfirmed',
    nothing_to_revoke: 'accessControl.error.nothing_to_revoke',
    nothing_to_change: 'accessControl.error.nothing_to_change',
    last_admin: 'accessControl.error.last_admin',
    until_invalid: 'accessControl.error.until_invalid',
    name_short: 'accessControl.error.name_short',
    name_taken: 'accessControl.error.name_taken',
    base_invalid: 'accessControl.error.base_invalid',
    role_in_use: 'accessControl.error.role_in_use',
  },
  summary: {
    admins: 'accessControl.summary.admins',
    overrides: 'accessControl.summary.overrides',
    due: 'accessControl.summary.due',
    screens: 'accessControl.summary.screens',
    safeguard: 'accessControl.summary.safeguard',
  },
  creep: {
    title: 'accessControl.creep.title',
    role_diverges: 'accessControl.creep.role_diverges',
    person_many: 'accessControl.creep.person_many',
    outside_high: 'accessControl.creep.outside_high',
  },
  tab: {
    label: 'accessControl.tab.label',
    matrix: 'accessControl.tab.matrix',
    roles: 'accessControl.tab.roles',
    users: 'accessControl.tab.users',
    audit: 'accessControl.tab.audit',
  },
  matrix: {
    title: 'accessControl.matrix.title',
    hint: 'accessControl.matrix.hint',
    search: 'accessControl.matrix.search',
    allModules: 'accessControl.matrix.allModules',
    module: 'accessControl.matrix.module',
    foundation: 'accessControl.matrix.foundation',
    changed: 'accessControl.matrix.changed',
    adminOnly: 'accessControl.matrix.adminOnly',
    count: 'accessControl.matrix.count',
    empty: 'accessControl.matrix.empty',
    noMatch: 'accessControl.matrix.noMatch',
    more: 'accessControl.matrix.more',
    legend: 'accessControl.matrix.legend',
    cell: 'accessControl.matrix.cell',
  },
  state: {
    allowed: 'accessControl.state.allowed',
    denied: 'accessControl.state.denied',
  },
  source: {
    public: 'accessControl.source.public',
    locked: 'accessControl.source.locked',
    role_default: 'accessControl.source.role_default',
    role_grant: 'accessControl.source.role_grant',
    role_revoke: 'accessControl.source.role_revoke',
    custom_role: 'accessControl.source.custom_role',
    override_allow: 'accessControl.source.override_allow',
    override_deny: 'accessControl.source.override_deny',
    none: 'accessControl.source.none',
  },
  risk: {
    low: 'accessControl.risk.low',
    medium: 'accessControl.risk.medium',
    high: 'accessControl.risk.high',
  },
  change: {
    title: 'accessControl.change.title',
    standard: 'accessControl.change.standard',
    grant: 'accessControl.change.grant',
    revoke: 'accessControl.change.revoke',
    reset: 'accessControl.change.reset',
    reason: 'accessControl.change.reason',
    preview: 'accessControl.change.preview',
    users: 'accessControl.change.users',
    willBe: 'accessControl.change.willBe',
    highRisk: 'accessControl.change.highRisk',
    confirmHigh: 'accessControl.change.confirmHigh',
    apply: 'accessControl.change.apply',
    done: 'accessControl.change.done',
    locked: 'accessControl.change.locked',
  },
  roles: {
    title: 'accessControl.roles.title',
    hint: 'accessControl.roles.hint',
    users: 'accessControl.roles.users',
    grants: 'accessControl.roles.grants',
    revokes: 'accessControl.roles.revokes',
    builtIn: 'accessControl.roles.builtIn',
    custom: 'accessControl.roles.custom',
    behaves: 'accessControl.roles.behaves',
    new: 'accessControl.roles.new',
    newTitle: 'accessControl.roles.newTitle',
    name: 'accessControl.roles.name',
    nameHi: 'accessControl.roles.nameHi',
    nameMr: 'accessControl.roles.nameMr',
    base: 'accessControl.roles.base',
    baseHint: 'accessControl.roles.baseHint',
    description: 'accessControl.roles.description',
    copy: 'accessControl.roles.copy',
    copyNone: 'accessControl.roles.copyNone',
    reason: 'accessControl.roles.reason',
    create: 'accessControl.roles.create',
    created: 'accessControl.roles.created',
    retire: 'accessControl.roles.retire',
    retireReason: 'accessControl.roles.retireReason',
    retireDo: 'accessControl.roles.retireDo',
    retired: 'accessControl.roles.retired',
    see: 'accessControl.roles.see',
  },
  users: {
    title: 'accessControl.users.title',
    hint: 'accessControl.users.hint',
    search: 'accessControl.users.search',
    open: 'accessControl.users.open',
    empty: 'accessControl.users.empty',
    overrides: 'accessControl.users.overrides',
    lastAdmin: 'accessControl.users.lastAdmin',
  },
  detail: {
    allowed: 'accessControl.detail.allowed',
    beyond: 'accessControl.detail.beyond',
    none: 'accessControl.detail.none',
    roles: 'accessControl.detail.roles',
    assign: 'accessControl.detail.assign',
    unassign: 'accessControl.detail.unassign',
    noRoles: 'accessControl.detail.noRoles',
    noFitting: 'accessControl.detail.noFitting',
    reason: 'accessControl.detail.reason',
    roleDone: 'accessControl.detail.roleDone',
  },
  override: {
    title: 'accessControl.override.title',
    hint: 'accessControl.override.hint',
    screen: 'accessControl.override.screen',
    pick: 'accessControl.override.pick',
    find: 'accessControl.override.find',
    effect: 'accessControl.override.effect',
    allow: 'accessControl.override.allow',
    deny: 'accessControl.override.deny',
    reason: 'accessControl.override.reason',
    until: 'accessControl.override.until',
    noEnd: 'accessControl.override.noEnd',
    add: 'accessControl.override.add',
    added: 'accessControl.override.added',
    list: 'accessControl.override.list',
    none: 'accessControl.override.none',
    line: 'accessControl.override.line',
    by: 'accessControl.override.by',
    until_on: 'accessControl.override.until_on',
    dueOn: 'accessControl.override.dueOn',
    reviewed: 'accessControl.override.reviewed',
    ended: {
      expired: 'accessControl.override.ended.expired',
      removed: 'accessControl.override.ended.removed',
    },
    review: 'accessControl.override.review',
    reviewNote: 'accessControl.override.reviewNote',
    reviewDo: 'accessControl.override.reviewDo',
    remove: 'accessControl.override.remove',
    removeReason: 'accessControl.override.removeReason',
    removeDo: 'accessControl.override.removeDo',
    removed: 'accessControl.override.removed',
    highRisk: 'accessControl.override.highRisk',
  },
  audit: {
    title: 'accessControl.audit.title',
    hint: 'accessControl.audit.hint',
    search: 'accessControl.audit.search',
    all: 'accessControl.audit.all',
    empty: 'accessControl.audit.empty',
    more: 'accessControl.audit.more',
    line: 'accessControl.audit.line',
    for: 'accessControl.audit.for',
    screens: 'accessControl.audit.screens',
    refused: 'accessControl.audit.refused',
  },
  kind: {
    role_grant: 'accessControl.kind.role_grant',
    role_revoke: 'accessControl.kind.role_revoke',
    role_reset: 'accessControl.kind.role_reset',
    role_created: 'accessControl.kind.role_created',
    role_retired: 'accessControl.kind.role_retired',
    role_assigned: 'accessControl.kind.role_assigned',
    role_unassigned: 'accessControl.kind.role_unassigned',
    override_set: 'accessControl.kind.override_set',
    override_removed: 'accessControl.kind.override_removed',
    override_expired: 'accessControl.kind.override_expired',
    override_reviewed: 'accessControl.kind.override_reviewed',
    refused: 'accessControl.kind.refused',
  },
  note: {
    enforcement: 'accessControl.note.enforcement',
    placeholders: 'accessControl.note.placeholders',
  },
  alert: {
    sensitive: 'accessControl.alert.sensitive',
  },
  link: {
    open: 'accessControl.link.open',
  },
} as const;
