/** Screen 153 — SOP Document Repository. Constants and translation keys only. */

import type { SopError, SopSource } from '@/data/repository';
import { PAGE } from '@/features/sop/library';

export { PAGE };
export const FILTERS = ['all', 'bookmarked', 'saved'] as const;
export type Filter = (typeof FILTERS)[number];
export const SOURCES: SopSource[] = ['installation', 'delivery', 'safety', 'quality', 'reference'];
export const offlineKey = (userId: string) => `aiec.sopOffline.${userId}`;
export const libraryKey = (userId: string) => `aiec.sopLib.${userId}`;
export const bookmarkQueueKey = (userId: string) => `aiec.sopBookmarkQueue.${userId}`;
export const docPath = (id: string, version?: number) => `/sops/${id}${version ? `?v=${version}` : ''}`;
export const listPath = '/sops';
export const POLL_MS = 60_000;

const rec = <T extends string>(ns: string, keys: readonly T[]) => Object.fromEntries(keys.map((k) => [k, `${ns}.${k}`])) as Record<T, string>;
const PROBLEMS: (SopError | 'offline' | 'generic')[] = ['not_admin', 'forbidden', 'not_found', 'name_required', 'name_taken', 'category_unknown', 'title_required', 'steps_required', 'translation_mismatch', 'date_invalid', 'date_in_past', 'note_required', 'not_editable', 'offline', 'generic'];

export const SOP_KEYS = {
  title: 'sopRepo.title',
  subtitle: 'sopRepo.subtitle',
  loading: 'sopRepo.loading',
  error: { title: 'sopRepo.error.title', body: 'sopRepo.error.body' },
  notFound: { title: 'sopRepo.notFound.title', body: 'sopRepo.notFound.body', action: 'sopRepo.notFound.action' },
  search: { label: 'sopRepo.search.label', placeholder: 'sopRepo.search.placeholder' },
  filter: { label: 'sopRepo.filter.label', ...rec('sopRepo.filter', FILTERS) },
  category: { all: 'sopRepo.category.all', installation: 'sopRepo.category.installation', delivery: 'sopRepo.category.delivery', safety: 'sopRepo.category.safety', quality: 'sopRepo.category.quality' },
  source: rec('sopRepo.source', SOURCES),
  summary: { count: 'sopRepo.summary.count' },
  empty: { title: 'sopRepo.empty.title', body: 'sopRepo.empty.body' },
  noMatch: { title: 'sopRepo.noMatch.title', body: 'sopRepo.noMatch.body', action: 'sopRepo.noMatch.action' },
  more: { shown: 'sopRepo.more.shown', button: 'sopRepo.more.button' },
  row: {
    version: 'sopRepo.row.version',
    inForce: 'sopRepo.row.inForce',
    upcoming: 'sopRepo.row.upcoming',
    saved: 'sopRepo.row.saved',
    stale: 'sopRepo.row.stale',
    referenceOnly: 'sopRepo.row.referenceOnly',
    bookmark: 'sopRepo.row.bookmark',
    unbookmark: 'sopRepo.row.unbookmark',
    steps: 'sopRepo.row.steps',
  },
  offline: {
    banner: 'sopRepo.offline.banner',
    cached: 'sopRepo.offline.cached',
    onlySaved: 'sopRepo.offline.onlySaved',
    staleBanner: 'sopRepo.offline.staleBanner',
    updateAll: 'sopRepo.offline.updateAll',
    updated: 'sopRepo.offline.updated',
  },
  reader: {
    back: 'sopRepo.reader.back',
    version: 'sopRepo.reader.version',
    versionOption: 'sopRepo.reader.versionOption',
    stateCurrent: 'sopRepo.reader.stateCurrent',
    stateUpcoming: 'sopRepo.reader.stateUpcoming',
    statePast: 'sopRepo.reader.statePast',
    effective: 'sopRepo.reader.effective',
    publishedBy: 'sopRepo.reader.publishedBy',
    changeNote: 'sopRepo.reader.changeNote',
    changes: 'sopRepo.reader.changes',
    changesNone: 'sopRepo.reader.changesNone',
    first: 'sopRepo.reader.first',
    newItem: 'sopRepo.reader.newItem',
    changedItem: 'sopRepo.reader.changedItem',
    removedNote: 'sopRepo.reader.removedNote',
    pastWarning: 'sopRepo.reader.pastWarning',
    pastShowCurrent: 'sopRepo.reader.pastShowCurrent',
    upcomingNote: 'sopRepo.reader.upcomingNote',
    required: 'sopRepo.reader.required',
    optional: 'sopRepo.reader.optional',
    photo: 'sopRepo.reader.photo',
    video: 'sopRepo.reader.video',
    critical: 'sopRepo.reader.critical',
    evidence: 'sopRepo.reader.evidence',
    appliesWhen: 'sopRepo.reader.appliesWhen',
    standard: 'sopRepo.reader.standard',
    english: 'sopRepo.reader.english',
    governedBy: 'sopRepo.reader.governedBy',
    openGoverning: 'sopRepo.reader.openGoverning',
    referenceNote: 'sopRepo.reader.referenceNote',
    builtIn: 'sopRepo.reader.builtIn',
    steps: 'sopRepo.reader.steps',
  },
  copy: {
    save: 'sopRepo.copy.save',
    saved: 'sopRepo.copy.saved',
    remove: 'sopRepo.copy.remove',
    update: 'sopRepo.copy.update',
    stale: 'sopRepo.copy.stale',
    staleOffline: 'sopRepo.copy.staleOffline',
    current: 'sopRepo.copy.current',
    unknown: 'sopRepo.copy.unknown',
    savedOn: 'sopRepo.copy.savedOn',
    savedToast: 'sopRepo.copy.savedToast',
    removedToast: 'sopRepo.copy.removedToast',
    needsSignal: 'sopRepo.copy.needsSignal',
    fromCopy: 'sopRepo.copy.fromCopy',
  },
  admin: {
    newCategory: 'sopRepo.admin.newCategory',
    newReference: 'sopRepo.admin.newReference',
    categoryTitle: 'sopRepo.admin.categoryTitle',
    categoryBody: 'sopRepo.admin.categoryBody',
    categoryName: 'sopRepo.admin.categoryName',
    categoryNameHi: 'sopRepo.admin.categoryNameHi',
    categoryNameMr: 'sopRepo.admin.categoryNameMr',
    categoryOptional: 'sopRepo.admin.categoryOptional',
    categoryAdd: 'sopRepo.admin.categoryAdd',
    categoryAdded: 'sopRepo.admin.categoryAdded',
    noCustomCategory: 'sopRepo.admin.noCustomCategory',
    refTitle: 'sopRepo.admin.refTitle',
    refTitleNew: 'sopRepo.admin.refTitleNew',
    refTitleVersion: 'sopRepo.admin.refTitleVersion',
    refBody: 'sopRepo.admin.refBody',
    refCategory: 'sopRepo.admin.refCategory',
    docTitle: 'sopRepo.admin.docTitle',
    docTitleHi: 'sopRepo.admin.docTitleHi',
    docTitleMr: 'sopRepo.admin.docTitleMr',
    steps: 'sopRepo.admin.steps',
    stepsHint: 'sopRepo.admin.stepsHint',
    stepsHi: 'sopRepo.admin.stepsHi',
    stepsMr: 'sopRepo.admin.stepsMr',
    stepsOtherHint: 'sopRepo.admin.stepsOtherHint',
    effective: 'sopRepo.admin.effective',
    effectiveHint: 'sopRepo.admin.effectiveHint',
    note: 'sopRepo.admin.note',
    noteHint: 'sopRepo.admin.noteHint',
    publish: 'sopRepo.admin.publish',
    published: 'sopRepo.admin.published',
    newVersion: 'sopRepo.admin.newVersion',
    cancel: 'sopRepo.admin.cancel',
    enforcedNote: 'sopRepo.admin.enforcedNote',
  },
  close: 'sopRepo.close',
  problem: rec('sopRepo.problem', PROBLEMS),
} as const;
