/** Screen 101 — Delivery Scheduling. Types and translation keys only. */

import type { DeliveryRescheduleCause, DeliveryWindow } from '@/data/types';

export type DeliverySchedulingStatus = 'loading' | 'ready' | 'error';

export type DeliveryFilter = 'all' | 'to_book' | 'attention';
export const DELIVERY_FILTERS: DeliveryFilter[] = ['all', 'to_book', 'attention'];

/** Who a moved date is down to, in the order Admin is offered them. */
export const RESCHEDULE_CAUSES: DeliveryRescheduleCause[] = ['site', 'supplier', 'aiec', 'other'];

export const WINDOW_LABEL_KEYS: Record<DeliveryWindow, string> = {
  morning: 'deliveryScheduling.window.morning',
  afternoon: 'deliveryScheduling.window.afternoon',
};

/** How many "next available" slots are offered as one-tap choices. */
export const NEXT_SLOT_CHOICES = 6;

export const DELIVERY_SCHEDULING_KEYS = {
  title: 'deliveryScheduling.title',
  subtitleAdmin: 'deliveryScheduling.subtitleAdmin',
  subtitleSupplier: 'deliveryScheduling.subtitleSupplier',
  loading: 'deliveryScheduling.loading',
  error: { title: 'deliveryScheduling.error.title', body: 'deliveryScheduling.error.body' },
  view: {
    label: 'deliveryScheduling.view.label',
    week: 'deliveryScheduling.view.week',
    month: 'deliveryScheduling.view.month',
    agenda: 'deliveryScheduling.view.agenda',
  },
  filter: {
    all: 'deliveryScheduling.filter.all',
    to_book: 'deliveryScheduling.filter.to_book',
    attention: 'deliveryScheduling.filter.attention',
    allSuppliers: 'deliveryScheduling.filter.allSuppliers',
    label: 'deliveryScheduling.filter.label',
  },
  legend: {
    heading: 'deliveryScheduling.legend.heading',
    onTrack: 'deliveryScheduling.legend.onTrack',
    later: 'deliveryScheduling.legend.later',
    problem: 'deliveryScheduling.legend.problem',
    delivered: 'deliveryScheduling.legend.delivered',
  },
  window: {
    morning: 'deliveryScheduling.window.morning',
    afternoon: 'deliveryScheduling.window.afternoon',
  },
  day: {
    empty: 'deliveryScheduling.day.empty',
    emptyBody: 'deliveryScheduling.day.emptyBody',
  },
  queue: {
    heading: 'deliveryScheduling.queue.heading',
    hintAdmin: 'deliveryScheduling.queue.hintAdmin',
    hintSupplier: 'deliveryScheduling.queue.hintSupplier',
    empty: 'deliveryScheduling.queue.empty',
    emptyBody: 'deliveryScheduling.queue.emptyBody',
    promised: 'deliveryScheduling.queue.promised',
    siteReady: 'deliveryScheduling.queue.siteReady',
    siteNotReady: 'deliveryScheduling.queue.siteNotReady',
    book: 'deliveryScheduling.queue.book',
    rebook: 'deliveryScheduling.queue.rebook',
    waiting: 'deliveryScheduling.queue.waiting',
    failedBefore: 'deliveryScheduling.queue.failedBefore',
  },
  card: {
    siteUnknown: 'deliveryScheduling.card.siteUnknown',
    status: {
      unscheduled: 'deliveryScheduling.card.status.unscheduled',
      scheduled: 'deliveryScheduling.card.status.scheduled',
      attempt_failed: 'deliveryScheduling.card.status.attempt_failed',
      delivered: 'deliveryScheduling.card.status.delivered',
    },
    later: 'deliveryScheduling.card.later',
    conflict: 'deliveryScheduling.card.conflict',
    readinessLost: 'deliveryScheduling.card.readinessLost',
    outsideWindows: 'deliveryScheduling.card.outsideWindows',
    followsPo: 'deliveryScheduling.card.followsPo',
  },
  sheet: {
    title: 'deliveryScheduling.sheet.title',
    supplier: 'deliveryScheduling.sheet.supplier',
    promised: 'deliveryScheduling.sheet.promised',
    booked: 'deliveryScheduling.sheet.booked',
    notBooked: 'deliveryScheduling.sheet.notBooked',
    value: 'deliveryScheduling.sheet.value',
    openOrder: 'deliveryScheduling.sheet.openOrder',
    messages: 'deliveryScheduling.sheet.messages',
    technician: 'deliveryScheduling.sheet.technician',
    noTechnician: 'deliveryScheduling.sheet.noTechnician',
    job: 'deliveryScheduling.sheet.job',
    dependsOn: 'deliveryScheduling.sheet.dependsOn',
    dependsOnBooked: 'deliveryScheduling.sheet.dependsOnBooked',
    dependsOnDelivered: 'deliveryScheduling.sheet.dependsOnDelivered',
    dependsOnUnbooked: 'deliveryScheduling.sheet.dependsOnUnbooked',
    dependents: 'deliveryScheduling.sheet.dependents',
    conflictBanner: 'deliveryScheduling.sheet.conflictBanner',
    lostBanner: 'deliveryScheduling.sheet.lostBanner',
    outsideBanner: 'deliveryScheduling.sheet.outsideBanner',
    outsideBannerSupplier: 'deliveryScheduling.sheet.outsideBannerSupplier',
    laterBanner: 'deliveryScheduling.sheet.laterBanner',
  },
  readiness: {
    heading: 'deliveryScheduling.readiness.heading',
    hint: 'deliveryScheduling.readiness.hint',
    locked: 'deliveryScheduling.readiness.locked',
    confirmed: 'deliveryScheduling.readiness.confirmed',
    reset: 'deliveryScheduling.readiness.reset',
    contact: 'deliveryScheduling.readiness.contact',
    contactHint: 'deliveryScheduling.readiness.contactHint',
    save: 'deliveryScheduling.readiness.save',
    confirm: 'deliveryScheduling.readiness.confirm',
    supplierNote: 'deliveryScheduling.readiness.supplierNote',
    item: {
      shaft_civil: 'deliveryScheduling.readiness.item.shaft_civil',
      pit_depth: 'deliveryScheduling.readiness.item.pit_depth',
      machine_room: 'deliveryScheduling.readiness.item.machine_room',
      power_supply: 'deliveryScheduling.readiness.item.power_supply',
      access_route: 'deliveryScheduling.readiness.item.access_route',
      storage_space: 'deliveryScheduling.readiness.item.storage_space',
    },
  },
  book: {
    heading: 'deliveryScheduling.book.heading',
    rebookHeading: 'deliveryScheduling.book.rebookHeading',
    nextAvailable: 'deliveryScheduling.book.nextAvailable',
    otherDate: 'deliveryScheduling.book.otherDate',
    date: 'deliveryScheduling.book.date',
    window: 'deliveryScheduling.book.window',
    noneFree: 'deliveryScheduling.book.noneFree',
    supplierWindows: 'deliveryScheduling.book.supplierWindows',
    dependsOn: 'deliveryScheduling.book.dependsOn',
    dependsNone: 'deliveryScheduling.book.dependsNone',
    dependsHint: 'deliveryScheduling.book.dependsHint',
    lateCause: 'deliveryScheduling.book.lateCause',
    lateHint: 'deliveryScheduling.book.lateHint',
    promiseMoves: 'deliveryScheduling.book.promiseMoves',
    promiseStays: 'deliveryScheduling.book.promiseStays',
    submit: 'deliveryScheduling.book.submit',
    noWindowsTitle: 'deliveryScheduling.book.noWindowsTitle',
    noWindowsAdmin: 'deliveryScheduling.book.noWindowsAdmin',
    noWindowsSupplier: 'deliveryScheduling.book.noWindowsSupplier',
    enterWindows: 'deliveryScheduling.book.enterWindows',
    needsReadiness: 'deliveryScheduling.book.needsReadiness',
  },
  resched: {
    heading: 'deliveryScheduling.resched.heading',
    current: 'deliveryScheduling.resched.current',
    cause: 'deliveryScheduling.resched.cause',
    reason: 'deliveryScheduling.resched.reason',
    reasonHint: 'deliveryScheduling.resched.reasonHint',
    supplierNote: 'deliveryScheduling.resched.supplierNote',
    submit: 'deliveryScheduling.resched.submit',
    open: 'deliveryScheduling.resched.open',
  },
  cause: {
    supplier: 'deliveryScheduling.cause.supplier',
    site: 'deliveryScheduling.cause.site',
    aiec: 'deliveryScheduling.cause.aiec',
    other: 'deliveryScheduling.cause.other',
  },
  slotState: {
    past: 'deliveryScheduling.slotState.past',
    too_soon: 'deliveryScheduling.slotState.too_soon',
    off_day: 'deliveryScheduling.slotState.off_day',
    window_not_offered: 'deliveryScheduling.slotState.window_not_offered',
    blackout: 'deliveryScheduling.slotState.blackout',
    full: 'deliveryScheduling.slotState.full',
    no_availability: 'deliveryScheduling.slotState.no_availability',
  },
  attempt: {
    heading: 'deliveryScheduling.attempt.heading',
    body: 'deliveryScheduling.attempt.body',
    open: 'deliveryScheduling.attempt.open',
    note: 'deliveryScheduling.attempt.note',
    warning: 'deliveryScheduling.attempt.warning',
    submit: 'deliveryScheduling.attempt.submit',
    failedCount: 'deliveryScheduling.attempt.failedCount',
  },
  timeline: {
    heading: 'deliveryScheduling.timeline.heading',
    empty: 'deliveryScheduling.timeline.empty',
    scheduled: 'deliveryScheduling.timeline.scheduled',
    rescheduled: 'deliveryScheduling.timeline.rescheduled',
    attempt_failed: 'deliveryScheduling.timeline.attempt_failed',
    by: 'deliveryScheduling.timeline.by',
    cause: 'deliveryScheduling.timeline.cause',
    promiseMoved: 'deliveryScheduling.timeline.promiseMoved',
  },
  availability: {
    open: 'deliveryScheduling.availability.open',
    title: 'deliveryScheduling.availability.title',
    titleFor: 'deliveryScheduling.availability.titleFor',
    intro: 'deliveryScheduling.availability.intro',
    weekdays: 'deliveryScheduling.availability.weekdays',
    windows: 'deliveryScheduling.availability.windows',
    maxPerDay: 'deliveryScheduling.availability.maxPerDay',
    maxHint: 'deliveryScheduling.availability.maxHint',
    leadDays: 'deliveryScheduling.availability.leadDays',
    leadHint: 'deliveryScheduling.availability.leadHint',
    blackouts: 'deliveryScheduling.availability.blackouts',
    blackoutDate: 'deliveryScheduling.availability.blackoutDate',
    blackoutReason: 'deliveryScheduling.availability.blackoutReason',
    addBlackout: 'deliveryScheduling.availability.addBlackout',
    remove: 'deliveryScheduling.availability.remove',
    none: 'deliveryScheduling.availability.none',
    summary: 'deliveryScheduling.availability.summary',
    updated: 'deliveryScheduling.availability.updated',
    save: 'deliveryScheduling.availability.save',
    onBehalf: 'deliveryScheduling.availability.onBehalf',
    invalid: 'deliveryScheduling.availability.invalid',
  },
  alert: {
    attemptFailed: 'deliveryScheduling.alert.attemptFailed',
  },
  problem: {
    readiness_required: 'deliveryScheduling.problem.readiness_required',
    contact_required: 'deliveryScheduling.problem.contact_required',
    slot_unavailable: 'deliveryScheduling.problem.slot_unavailable',
    sequence_conflict: 'deliveryScheduling.problem.sequence_conflict',
    prerequisite_not_scheduled: 'deliveryScheduling.problem.prerequisite_not_scheduled',
    dependency_cycle: 'deliveryScheduling.problem.dependency_cycle',
    late_cause_required: 'deliveryScheduling.problem.late_cause_required',
    reason_required: 'deliveryScheduling.problem.reason_required',
    no_availability: 'deliveryScheduling.problem.no_availability',
    invalid_state: 'deliveryScheduling.problem.invalid_state',
    forbidden: 'deliveryScheduling.problem.forbidden',
    invalid_input: 'deliveryScheduling.problem.invalid_input',
    generic: 'deliveryScheduling.problem.generic',
  },
  toast: {
    booked: 'deliveryScheduling.toast.booked',
    rescheduled: 'deliveryScheduling.toast.rescheduled',
    technician: 'deliveryScheduling.toast.technician',
    conflicts: 'deliveryScheduling.toast.conflicts',
    attempt: 'deliveryScheduling.toast.attempt',
    readinessSaved: 'deliveryScheduling.toast.readinessSaved',
    readinessConfirmed: 'deliveryScheduling.toast.readinessConfirmed',
    availabilitySaved: 'deliveryScheduling.toast.availabilitySaved',
  },
} as const;
