/** Screen 138 — Customer Handover Walkthrough. Types and translation keys only. */

import { DOCS, MODES, SCRIPT } from '@/features/qc/walkthrough';

export type WalkthroughStatus = 'loading' | 'ready' | 'error' | 'not_found';
export const POLL_MS = 15_000;
export const STEPS = ['arrange', 'demonstrate', 'documents', 'signoff', 'amc', 'feedback', 'review'] as const;
export type StepId = (typeof STEPS)[number];
export const draftKey = (userId: string, jobId: string) => `aiec.walkthroughDraft.${userId}.${jobId}`;
export const SCORES = [1, 2, 3, 4, 5] as const;
export const GROUPS = ['operation', 'emergency', 'care'] as const;
export { DOCS, MODES };

export const FINAL_ERRORS = [
  'mode_required', 'conductor_required', 'representative_required', 'script_open', 'documents_open', 'not_unlocked', 'invalid_state', 'not_conducted', 'understood_required',
  'signature_required', 'signer_required', 'already_signed', 'score_invalid', 'tier_required', 'question_required', 'answer_required', 'not_found', 'forbidden', 'date_required',
] as const;

const rec = <T extends string>(ns: string, keys: readonly T[]) => Object.fromEntries(keys.map((k) => [k, `${ns}.${k}`])) as Record<T, string>;
export const boardPath = '/handover-walkthrough';
export const warrantyPath = (id: string) => `/warranty/${id}`;
export const checklistPath = (id: string) => `/handover-checklist/${id}`;
const SCRIPT_IDS = SCRIPT.map((i) => i.id);

export const WALK_KEYS = {
  title: 'walkthrough.title',
  loading: 'walkthrough.loading',
  back: 'walkthrough.back',
  next: 'walkthrough.next',
  error: { title: 'walkthrough.error.title', body: 'walkthrough.error.body' },
  notFound: { title: 'walkthrough.notFound.title', body: 'walkthrough.notFound.body', action: 'walkthrough.notFound.action' },
  locked: { title: 'walkthrough.locked.title', body: 'walkthrough.locked.body', customerBody: 'walkthrough.locked.customerBody', action: 'walkthrough.locked.action' },
  board: { heading: 'walkthrough.board.heading', emptyTitle: 'walkthrough.board.emptyTitle', emptyBody: 'walkthrough.board.emptyBody', open: 'walkthrough.board.open' },
  problem: rec('walkthrough.problem', [...FINAL_ERRORS, 'offline', 'generic'] as const),
  status: rec('walkthrough.status', ['locked', 'not_started', 'arranged', 'conducted', 'signed_off'] as const),
  step: rec('walkthrough.step', STEPS),
  mode: rec('walkthrough.mode', MODES),
  modeHint: rec('walkthrough.modeHint', MODES),
  arrange: {
    heading: 'walkthrough.arrange.heading',
    intro: 'walkthrough.arrange.intro',
    mode: 'walkthrough.arrange.mode',
    date: 'walkthrough.arrange.date',
    dateHint: 'walkthrough.arrange.dateHint',
    window: 'walkthrough.arrange.window',
    morning: 'walkthrough.arrange.morning',
    afternoon: 'walkthrough.arrange.afternoon',
    conductor: 'walkthrough.arrange.conductor',
    choose: 'walkthrough.arrange.choose',
    repHeading: 'walkthrough.arrange.repHeading',
    repHint: 'walkthrough.arrange.repHint',
    repName: 'walkthrough.arrange.repName',
    repPhone: 'walkthrough.arrange.repPhone',
    repRelation: 'walkthrough.arrange.repRelation',
    save: 'walkthrough.arrange.save',
    saved: 'walkthrough.arrange.saved',
    summary: 'walkthrough.arrange.summary',
    with: 'walkthrough.arrange.with',
    when: 'walkthrough.arrange.when',
    notArranged: 'walkthrough.arrange.notArranged',
    draftRestored: 'walkthrough.arrange.draftRestored',
    remoteNote: 'walkthrough.arrange.remoteNote',
  },
  demo: {
    heading: 'walkthrough.demo.heading',
    intro: 'walkthrough.demo.intro',
    customerIntro: 'walkthrough.demo.customerIntro',
    group: rec('walkthrough.demo.group', GROUPS),
    item: rec('walkthrough.demo.item', SCRIPT_IDS),
    hint: rec('walkthrough.demo.hint', SCRIPT_IDS),
    required: 'walkthrough.demo.required',
    optional: 'walkthrough.demo.optional',
    progress: 'walkthrough.demo.progress',
    shown: 'walkthrough.demo.shown',
    arrangeFirst: 'walkthrough.demo.arrangeFirst',
  },
  docs: {
    heading: 'walkthrough.docs.heading',
    intro: 'walkthrough.docs.intro',
    name: rec('walkthrough.docs.name', DOCS),
    notReady: 'walkthrough.docs.notReady',
    fix: 'walkthrough.docs.fix',
    printed: 'walkthrough.docs.printed',
    digital: 'walkthrough.docs.digital',
    given: 'walkthrough.docs.given',
    givenPrinted: 'walkthrough.docs.givenPrinted',
    givenDigital: 'walkthrough.docs.givenDigital',
    emergencyAbout: 'walkthrough.docs.emergencyAbout',
    arrangeFirst: 'walkthrough.docs.arrangeFirst',
  },
  sign: {
    heading: 'walkthrough.sign.heading',
    intro: 'walkthrough.sign.intro',
    conduct: 'walkthrough.sign.conduct',
    conductHint: 'walkthrough.sign.conductHint',
    conductToast: 'walkthrough.sign.conductToast',
    blocked: rec('walkthrough.sign.blocked', ['mode_required', 'script_open', 'documents_open'] as const),
    waiting: 'walkthrough.sign.waiting',
    conducted: 'walkthrough.sign.conducted',
    due: 'walkthrough.sign.due',
    understood: 'walkthrough.sign.understood',
    note: 'walkthrough.sign.note',
    confirm: 'walkthrough.sign.confirm',
    toast: 'walkthrough.sign.toast',
    signed: 'walkthrough.sign.signed',
    signedDevice: 'walkthrough.sign.signedDevice',
    deviceHeading: 'walkthrough.sign.deviceHeading',
    deviceHint: 'walkthrough.sign.deviceHint',
    signer: 'walkthrough.sign.signer',
    signature: 'walkthrough.sign.signature',
    clear: 'walkthrough.sign.clear',
    record: 'walkthrough.sign.record',
    remote: 'walkthrough.sign.remote',
    distinct: 'walkthrough.sign.distinct',
  },
  amc: {
    heading: 'walkthrough.amc.heading',
    intro: 'walkthrough.amc.intro',
    tier: rec('walkthrough.amc.tier', ['basic', 'standard', 'comprehensive'] as const),
    tierLine: 'walkthrough.amc.tierLine',
    choice: rec('walkthrough.amc.choice', ['enrol', 'later', 'declined'] as const),
    choiceHint: rec('walkthrough.amc.choiceHint', ['enrol', 'later', 'declined'] as const),
    note: 'walkthrough.amc.note',
    save: 'walkthrough.amc.save',
    toast: 'walkthrough.amc.toast',
    saved: 'walkthrough.amc.saved',
    savedTier: 'walkthrough.amc.savedTier',
    after: 'walkthrough.amc.after',
    waiting: 'walkthrough.amc.waiting',
  },
  feedback: {
    heading: 'walkthrough.feedback.heading',
    intro: 'walkthrough.feedback.intro',
    score: rec('walkthrough.feedback.score', ['1', '2', '3', '4', '5'] as const),
    comment: 'walkthrough.feedback.comment',
    send: 'walkthrough.feedback.send',
    toast: 'walkthrough.feedback.toast',
    thanks: 'walkthrough.feedback.thanks',
    waiting: 'walkthrough.feedback.waiting',
    signal: 'walkthrough.feedback.signal',
    given: 'walkthrough.feedback.given',
  },
  review: {
    heading: 'walkthrough.review.heading',
    intro: 'walkthrough.review.intro',
    arranged: 'walkthrough.review.arranged',
    shown: 'walkthrough.review.shown',
    docs: 'walkthrough.review.docs',
    conducted: 'walkthrough.review.conducted',
    signed: 'walkthrough.review.signed',
    amc: 'walkthrough.review.amc',
    feedback: 'walkthrough.review.feedback',
    none: 'walkthrough.review.none',
    notYet: 'walkthrough.review.notYet',
    questions: 'walkthrough.review.questions',
    warranty: 'walkthrough.review.warranty',
  },
  ask: {
    heading: 'walkthrough.ask.heading',
    intro: 'walkthrough.ask.intro',
    label: 'walkthrough.ask.label',
    hint: 'walkthrough.ask.hint',
    send: 'walkthrough.ask.send',
    toast: 'walkthrough.ask.toast',
    waiting: 'walkthrough.ask.waiting',
    answer: 'walkthrough.ask.answer',
    answerGo: 'walkthrough.ask.answerGo',
    answerToast: 'walkthrough.ask.answerToast',
    answered: 'walkthrough.ask.answered',
    none: 'walkthrough.ask.none',
  },
  alert: { negative: 'walkthrough.alert.negative' },
  cancel: 'walkthrough.cancel',
} as const;
