import { BURDEN_WARN_PCT, NOTICE_DAYS, NOTICE_MAX, REASON_MIN, SIGNIFICANT_CHANGE, TOP_PARTY_WARN_SHARE } from '@/features/commission/rules';

export { BURDEN_WARN_PCT, NOTICE_DAYS, NOTICE_MAX, REASON_MIN, SIGNIFICANT_CHANGE, TOP_PARTY_WARN_SHARE };
export const VIEWS = ['rules', 'simulate', 'history'] as const;
export type View = (typeof VIEWS)[number];
export const PULL_DISTANCE = 70;
/** The simulator's crew is kept small enough to read at a glance. */
export const MAX_CREW = 6;
export const MAX_INSPECTORS = 3;
export const commissionRulesPath = (view?: View) => (view && view !== 'rules' ? `/commission-rules?view=${view}` : '/commission-rules');
export const TIERS_PATH = '/partner-tiers';

export const COMMISSION_KEYS = {
  title: 'commissionRules.title',
  subtitle: 'commissionRules.subtitle',
  placeholder: 'commissionRules.placeholder',
  loading: 'commissionRules.loading',
  error: {
    title: 'commissionRules.error.title',
    body: 'commissionRules.error.body',
  },
  refresh: {
    button: 'commissionRules.refresh.button',
    pull: 'commissionRules.refresh.pull',
    release: 'commissionRules.refresh.release',
    busy: 'commissionRules.refresh.busy',
  },
  tab: {
    rules: 'commissionRules.tab.rules',
    simulate: 'commissionRules.tab.simulate',
    history: 'commissionRules.tab.history',
  },
  close: 'commissionRules.close',
  cancel: 'commissionRules.cancel',
  back: 'commissionRules.back',
  rules: {
    intro: 'commissionRules.rules.intro',
    tierHeading: 'commissionRules.rules.tierHeading',
    tierBody: 'commissionRules.rules.tierBody',
    tierConversion: 'commissionRules.rules.tierConversion',
    tierLead: 'commissionRules.rules.tierLead',
    tierNoLead: 'commissionRules.rules.tierNoLead',
    tierLink: 'commissionRules.rules.tierLink',
    stackHeading: 'commissionRules.rules.stackHeading',
    stackBody: 'commissionRules.rules.stackBody',
    traceHeading: 'commissionRules.rules.traceHeading',
    traceBody: 'commissionRules.rules.traceBody',
    notFromRule: 'commissionRules.rules.notFromRule',
  },
  group: {
    surveyor: 'commissionRules.group.surveyor',
    technician: 'commissionRules.group.technician',
    inspector: 'commissionRules.group.inspector',
  },
  rule: {
    site_visit: {
      name: 'commissionRules.rule.site_visit.name',
      what: 'commissionRules.rule.site_visit.what',
    },
    lead_qualified: {
      name: 'commissionRules.rule.lead_qualified.name',
      what: 'commissionRules.rule.lead_qualified.what',
    },
    conversion: {
      name: 'commissionRules.rule.conversion.name',
      what: 'commissionRules.rule.conversion.what',
    },
    referral_bonus: {
      name: 'commissionRules.rule.referral_bonus.name',
      what: 'commissionRules.rule.referral_bonus.what',
    },
    sales_close: {
      name: 'commissionRules.rule.sales_close.name',
      what: 'commissionRules.rule.sales_close.what',
    },
    install_pool: {
      name: 'commissionRules.rule.install_pool.name',
      what: 'commissionRules.rule.install_pool.what',
    },
    qc_fee: {
      name: 'commissionRules.rule.qc_fee.name',
      what: 'commissionRules.rule.qc_fee.what',
    },
  },
  trigger: {
    site_visit_verified: 'commissionRules.trigger.site_visit_verified',
    lead_qualified: 'commissionRules.trigger.lead_qualified',
    deal_closed: 'commissionRules.trigger.deal_closed',
    referral_won: 'commissionRules.trigger.referral_won',
    handover_issued: 'commissionRules.trigger.handover_issued',
    label: 'commissionRules.trigger.label',
  },
  ledger: {
    ledger: 'commissionRules.ledger.ledger',
    cost_report: 'commissionRules.ledger.cost_report',
    pending: 'commissionRules.ledger.pending',
    pendingBody: 'commissionRules.ledger.pendingBody',
  },
  summary: {
    fixed: 'commissionRules.summary.fixed',
    conversion: 'commissionRules.summary.conversion',
    share: 'commissionRules.summary.share',
    pool: 'commissionRules.summary.pool',
    fee: 'commissionRules.summary.fee',
  },
  card: {
    version: 'commissionRules.card.version',
    change: 'commissionRules.card.change',
    upcomingTitle: 'commissionRules.card.upcomingTitle',
    noticeSent: 'commissionRules.card.noticeSent',
    noticeNone: 'commissionRules.card.noticeNone',
    tierAware: 'commissionRules.card.tierAware',
    negotiable: 'commissionRules.card.negotiable',
    entries: 'commissionRules.card.entries',
  },
  stack: {
    closing_credit: 'commissionRules.stack.closing_credit',
    lead_source: 'commissionRules.stack.lead_source',
    job_role: 'commissionRules.stack.job_role',
    rest: 'commissionRules.stack.rest',
  },
  param: {
    amount: 'commissionRules.param.amount',
    pct: 'commissionRules.param.pct',
    floor: 'commissionRules.param.floor',
    leadBonusPct: 'commissionRules.param.leadBonusPct',
    minCrewPct: 'commissionRules.param.minCrewPct',
    range: 'commissionRules.param.range',
  },
  change: {
    title: 'commissionRules.change.title',
    now: 'commissionRules.change.now',
    effective: 'commissionRules.change.effective',
    effectiveHint: 'commissionRules.change.effectiveHint',
    reason: 'commissionRules.change.reason',
    reasonHint: 'commissionRules.change.reasonHint',
    notify: 'commissionRules.change.notify',
    notifyBody: 'commissionRules.change.notifyBody',
    message: 'commissionRules.change.message',
    messageHint: 'commissionRules.change.messageHint',
    previewHeading: 'commissionRules.change.previewHeading',
    previewBusy: 'commissionRules.change.previewBusy',
    significant: 'commissionRules.change.significant',
    small: 'commissionRules.change.small',
    checksHeading: 'commissionRules.change.checksHeading',
    noChecks: 'commissionRules.change.noChecks',
    checkIn: 'commissionRules.change.checkIn',
    ack: 'commissionRules.change.ack',
    scenarios: 'commissionRules.change.scenarios',
    colNow: 'commissionRules.change.colNow',
    colNew: 'commissionRules.change.colNew',
    colChange: 'commissionRules.change.colChange',
    review: 'commissionRules.change.review',
    confirmHeading: 'commissionRules.change.confirmHeading',
    confirmBody: 'commissionRules.change.confirmBody',
    publish: 'commissionRules.change.publish',
    published: 'commissionRules.change.published',
  },
  scenario: {
    typical: 'commissionRules.scenario.typical',
    small: 'commissionRules.scenario.small',
    large: 'commissionRules.scenario.large',
    reassigned: 'commissionRules.scenario.reassigned',
    referral: 'commissionRules.scenario.referral',
    one_person: 'commissionRules.scenario.one_person',
  },
  check: {
    burden_high: 'commissionRules.check.burden_high',
    floor_pays_more: 'commissionRules.check.floor_pays_more',
    one_party_dominates: 'commissionRules.check.one_party_dominates',
    stack_collision: 'commissionRules.check.stack_collision',
    notice_short: 'commissionRules.check.notice_short',
  },
  sim: {
    heading: 'commissionRules.sim.heading',
    body: 'commissionRules.sim.body',
    value: 'commissionRules.sim.value',
    source: 'commissionRules.sim.source',
    sourceField: 'commissionRules.sim.sourceField',
    sourceReferral: 'commissionRules.sim.sourceReferral',
    tier: 'commissionRules.sim.tier',
    closedBy: 'commissionRules.sim.closedBy',
    closedNone: 'commissionRules.sim.closedNone',
    closedSame: 'commissionRules.sim.closedSame',
    closedOther: 'commissionRules.sim.closedOther',
    crew: 'commissionRules.sim.crew',
    crewName: 'commissionRules.sim.crewName',
    crewLead: 'commissionRules.sim.crewLead',
    crewMinutes: 'commissionRules.sim.crewMinutes',
    crewAdd: 'commissionRules.sim.crewAdd',
    crewRemove: 'commissionRules.sim.crewRemove',
    inspectors: 'commissionRules.sim.inspectors',
    compare: 'commissionRules.sim.compare',
    compareNone: 'commissionRules.sim.compareNone',
    compareHint: 'commissionRules.sim.compareHint',
    results: 'commissionRules.sim.results',
    stage: {
      capture: 'commissionRules.sim.stage.capture',
      deal_won: 'commissionRules.sim.stage.deal_won',
      handover: 'commissionRules.sim.stage.handover',
    },
    party: {
      surveyor: 'commissionRules.sim.party.surveyor',
      closer: 'commissionRules.sim.party.closer',
      referrer: 'commissionRules.sim.party.referrer',
      technician_lead: 'commissionRules.sim.party.technician_lead',
      technician: 'commissionRules.sim.party.technician',
      inspector: 'commissionRules.sim.party.inspector',
    },
    line: 'commissionRules.sim.line',
    colNow: 'commissionRules.sim.colNow',
    colProposed: 'commissionRules.sim.colProposed',
    total: 'commissionRules.sim.total',
    burden: 'commissionRules.sim.burden',
    top: 'commissionRules.sim.top',
    floorNote: 'commissionRules.sim.floorNote',
    dropped: 'commissionRules.sim.dropped',
    droppedRow: 'commissionRules.sim.droppedRow',
    noLines: 'commissionRules.sim.noLines',
    busy: 'commissionRules.sim.busy',
    proposedChecks: 'commissionRules.sim.proposedChecks',
  },
  history: {
    intro: 'commissionRules.history.intro',
    state: {
      current: 'commissionRules.history.state.current',
      past: 'commissionRules.history.state.past',
      upcoming: 'commissionRules.history.state.upcoming',
    },
    by: 'commissionRules.history.by',
    notice: 'commissionRules.history.notice',
    noticeBare: 'commissionRules.history.noticeBare',
    noticeNone: 'commissionRules.history.noticeNone',
    seen: 'commissionRules.history.seen',
    start: 'commissionRules.history.start',
    entries: 'commissionRules.history.entries',
    versions: 'commissionRules.history.versions',
  },
  checkName: {
    burden_high: 'commissionRules.checkName.burden_high',
    floor_pays_more: 'commissionRules.checkName.floor_pays_more',
    one_party_dominates: 'commissionRules.checkName.one_party_dominates',
    stack_collision: 'commissionRules.checkName.stack_collision',
    notice_short: 'commissionRules.checkName.notice_short',
  },
  link: {
    open: 'commissionRules.link.open',
    fromRules: 'commissionRules.link.fromRules',
    rates: 'commissionRules.link.rates',
    upcoming: 'commissionRules.link.upcoming',
  },
  problem: {
    unknown_rule: 'commissionRules.problem.unknown_rule',
    param_missing: 'commissionRules.problem.param_missing',
    param_range: 'commissionRules.problem.param_range',
    param_unknown: 'commissionRules.problem.param_unknown',
    no_change: 'commissionRules.problem.no_change',
    effective_past: 'commissionRules.problem.effective_past',
    effective_before_current: 'commissionRules.problem.effective_before_current',
    reason_required: 'commissionRules.problem.reason_required',
    notice_too_long: 'commissionRules.problem.notice_too_long',
    checks_unacknowledged: 'commissionRules.problem.checks_unacknowledged',
    generic: 'commissionRules.problem.generic',
  },
} as const;
