/** Screen 148 — Partner Tier & Category Assignment. Types and translation keys only. */

import { DEFER_MAX_DAYS, EFFECTIVE_MAX_DAYS, METRICS, REASON_MIN, TIER_IDS } from '@/features/partners/tiers';
import type { Metric, TierRole } from '@/features/partners/tiers';

export const POLL_MS = 60_000;
export const TABS = ['partners', 'criteria'] as const;
export type Tab = (typeof TABS)[number];
export const FILTERS = ['all', 'promotion', 'incident', 'review', 'dispute'] as const;
export type Filter = (typeof FILTERS)[number];
export const ROLE_FILTERS = ['all', 'surveyor', 'technician', 'supplier'] as const;
export type RoleFilter = (typeof ROLE_FILTERS)[number];
export const OUTCOMES = ['tier_stands', 'tier_changed', 'criteria_unclear'] as const;
export const FIELD_ROLES = ['surveyor', 'technician'] as const;
export const draftKey = (userId: string, partnerId: string) => `aiec.tierDraft.${userId}.${partnerId}`;
export const criteriaDraftKey = (userId: string, role: string) => `aiec.tierCriteriaDraft.${userId}.${role}`;
export const partnerPath = (id: string) => `/partner-tiers/${id}`;
export const PAYMENT_TERMS_PATH = '/admin/suppliers/payment-terms';
export { DEFER_MAX_DAYS, EFFECTIVE_MAX_DAYS, METRICS, REASON_MIN, TIER_IDS };
export type { Metric, TierRole };

const rec = <T extends string>(ns: string, keys: readonly T[]) => Object.fromEntries(keys.map((k) => [k, `${ns}.${k}`])) as Record<T, string>;
const PROBLEMS = [
  'reason_required', 'same_tier', 'criteria_not_met', 'incident_ack_required', 'effective_invalid', 'defer_invalid', 'grounds_required', 'dispute_open', 'not_open',
  'tier_required', 'tiers_shape', 'not_rising', 'unknown_metric', 'effective_past', 'not_admin', 'not_found', 'forbidden', 'offline', 'generic',
] as const;

export const TIER_KEYS = {
  title: 'partnerTiers.title',
  subtitle: 'partnerTiers.subtitle',
  loading: 'partnerTiers.loading',
  error: { title: 'partnerTiers.error.title', body: 'partnerTiers.error.body' },
  notFound: { title: 'partnerTiers.notFound.title', body: 'partnerTiers.notFound.body' },
  back: 'partnerTiers.back',
  tabs: { label: 'partnerTiers.tabs.label', ...rec('partnerTiers.tabs', TABS) },
  role: rec('partnerTiers.role', ['surveyor', 'technician', 'supplier'] as const),
  tier: {
    surveyor: rec('partnerTiers.tier.surveyor', TIER_IDS.surveyor as readonly string[]),
    technician: rec('partnerTiers.tier.technician', TIER_IDS.technician as readonly string[]),
    supplier: rec('partnerTiers.tier.supplier', TIER_IDS.supplier as readonly string[]),
  } as Record<TierRole, Record<string, string>>,
  metric: rec('partnerTiers.metric', METRICS),
  value: { percent: 'partnerTiers.value.percent', number: 'partnerTiers.value.number' },
  criterion: { min: 'partnerTiers.criterion.min', max: 'partnerTiers.criterion.max', none: 'partnerTiers.criterion.none', met: 'partnerTiers.criterion.met', notMet: 'partnerTiers.criterion.notMet' },
  effect: {
    commission: 'partnerTiers.effect.commission',
    commissionNone: 'partnerTiers.effect.commissionNone',
    canLead: 'partnerTiers.effect.canLead',
    cannotLead: 'partnerTiers.effect.cannotLead',
    supplier: 'partnerTiers.effect.supplier',
  },
  board: {
    stats: { total: 'partnerTiers.board.stats.total', promotion: 'partnerTiers.board.stats.promotion', incident: 'partnerTiers.board.stats.incident', review: 'partnerTiers.board.stats.review', dispute: 'partnerTiers.board.stats.dispute' },
    filter: { label: 'partnerTiers.board.filter.label', ...rec('partnerTiers.board.filter', FILTERS) },
    roleFilter: { label: 'partnerTiers.board.roleFilter.label', ...rec('partnerTiers.board.roleFilter', ROLE_FILTERS) },
    search: 'partnerTiers.board.search',
    searchPlaceholder: 'partnerTiers.board.searchPlaceholder',
    empty: { title: 'partnerTiers.board.empty.title', body: 'partnerTiers.board.empty.body' },
    noMatch: { title: 'partnerTiers.board.noMatch.title', body: 'partnerTiers.board.noMatch.body', clear: 'partnerTiers.board.noMatch.clear' },
    since: 'partnerTiers.board.since',
    eligible: 'partnerTiers.board.eligible',
    pending: 'partnerTiers.board.pending',
    flag: { promotion: 'partnerTiers.board.flag.promotion', incident: 'partnerTiers.board.flag.incident', deferred: 'partnerTiers.board.flag.deferred', review: 'partnerTiers.board.flag.review', dispute: 'partnerTiers.board.flag.dispute' },
    open: 'partnerTiers.board.open',
  },
  detail: {
    since: 'partnerTiers.detail.since',
    joined: 'partnerTiers.detail.joined',
    ladder: 'partnerTiers.detail.ladder',
    ladderHint: 'partnerTiers.detail.ladderHint',
    current: 'partnerTiers.detail.current',
    eligible: 'partnerTiers.detail.eligible',
    criteriaVersion: 'partnerTiers.detail.criteriaVersion',
    supplierNote: 'partnerTiers.detail.supplierNote',
    supplierDefaults: 'partnerTiers.detail.supplierDefaults',
    openTerms: 'partnerTiers.detail.openTerms',
    termType: { net: 'partnerTiers.detail.termType.net', milestone: 'partnerTiers.detail.termType.milestone', advance: 'partnerTiers.detail.termType.advance' },
    upfront: 'partnerTiers.detail.upfront',
    retention: 'partnerTiers.detail.retention',
    pendingChange: 'partnerTiers.detail.pendingChange',
    incidentTitle: 'partnerTiers.detail.incidentTitle',
    incidentBody: 'partnerTiers.detail.incidentBody',
    incidentRow: 'partnerTiers.detail.incidentRow',
    deferredTitle: 'partnerTiers.detail.deferredTitle',
    deferredBody: 'partnerTiers.detail.deferredBody',
    reviewTitle: 'partnerTiers.detail.reviewTitle',
    reviewBody: 'partnerTiers.detail.reviewBody',
    promotionTitle: 'partnerTiers.detail.promotionTitle',
    promotionBody: 'partnerTiers.detail.promotionBody',
    actions: 'partnerTiers.detail.actions',
    history: 'partnerTiers.detail.history',
    historyEmpty: 'partnerTiers.detail.historyEmpty',
    historyRow: 'partnerTiers.detail.historyRow',
    historyInitial: 'partnerTiers.detail.historyInitial',
    kind: rec('partnerTiers.detail.kind', ['initial', 'promotion', 'demotion', 'exception', 'review', 'dispute', 'supplier_terms'] as const),
    criteriaAtTime: 'partnerTiers.detail.criteriaAtTime',
    ackShown: 'partnerTiers.detail.ackShown',
    by: 'partnerTiers.detail.by',
    effectiveOn: 'partnerTiers.detail.effectiveOn',
    disputes: 'partnerTiers.detail.disputes',
    noDisputes: 'partnerTiers.detail.noDisputes',
    disputeRaised: 'partnerTiers.detail.disputeRaised',
    disputeSnapshot: 'partnerTiers.detail.disputeSnapshot',
    disputeOpen: 'partnerTiers.detail.disputeOpen',
    disputeDecided: 'partnerTiers.detail.disputeDecided',
    outcome: rec('partnerTiers.detail.outcome', ['tier_stands', 'tier_changed', 'criteria_unclear'] as const),
  },
  change: {
    button: 'partnerTiers.change.button',
    heading: 'partnerTiers.change.heading',
    body: 'partnerTiers.change.body',
    bodySupplier: 'partnerTiers.change.bodySupplier',
    tier: 'partnerTiers.change.tier',
    tierPlaceholder: 'partnerTiers.change.tierPlaceholder',
    date: 'partnerTiers.change.date',
    dateHint: 'partnerTiers.change.dateHint',
    dateSupplier: 'partnerTiers.change.dateSupplier',
    reason: 'partnerTiers.change.reason',
    reasonHint: 'partnerTiers.change.reasonHint',
    exception: 'partnerTiers.change.exception',
    exceptionHint: 'partnerTiers.change.exceptionHint',
    incident: 'partnerTiers.change.incident',
    incidentHint: 'partnerTiers.change.incidentHint',
    unmet: 'partnerTiers.change.unmet',
    allMet: 'partnerTiers.change.allMet',
    down: 'partnerTiers.change.down',
    preview: 'partnerTiers.change.preview',
    confirm: 'partnerTiers.change.confirm',
    saved: 'partnerTiers.change.saved',
    scheduled: 'partnerTiers.change.scheduled',
    draftKept: 'partnerTiers.change.draftKept',
  },
  defer: {
    button: 'partnerTiers.defer.button',
    heading: 'partnerTiers.defer.heading',
    body: 'partnerTiers.defer.body',
    until: 'partnerTiers.defer.until',
    untilHint: 'partnerTiers.defer.untilHint',
    reason: 'partnerTiers.defer.reason',
    reasonHint: 'partnerTiers.defer.reasonHint',
    confirm: 'partnerTiers.defer.confirm',
    saved: 'partnerTiers.defer.saved',
  },
  dispute: {
    button: 'partnerTiers.dispute.button',
    heading: 'partnerTiers.dispute.heading',
    body: 'partnerTiers.dispute.body',
    grounds: 'partnerTiers.dispute.grounds',
    groundsHint: 'partnerTiers.dispute.groundsHint',
    confirm: 'partnerTiers.dispute.confirm',
    saved: 'partnerTiers.dispute.saved',
    decide: 'partnerTiers.dispute.decide',
    decideHeading: 'partnerTiers.dispute.decideHeading',
    decideBody: 'partnerTiers.dispute.decideBody',
    outcome: 'partnerTiers.dispute.outcome',
    outcomeHint: rec('partnerTiers.dispute.outcomeHint', ['tier_stands', 'tier_changed', 'criteria_unclear'] as const),
    note: 'partnerTiers.dispute.note',
    noteHint: 'partnerTiers.dispute.noteHint',
    newTier: 'partnerTiers.dispute.newTier',
    decided: 'partnerTiers.dispute.decided',
    confirmDecide: 'partnerTiers.dispute.confirmDecide',
  },
  review: {
    keep: 'partnerTiers.review.keep',
    keepHeading: 'partnerTiers.review.keepHeading',
    keepBody: 'partnerTiers.review.keepBody',
    reason: 'partnerTiers.review.reason',
    reasonHint: 'partnerTiers.review.reasonHint',
    confirm: 'partnerTiers.review.confirm',
    saved: 'partnerTiers.review.saved',
    due: 'partnerTiers.review.due',
    kept: 'partnerTiers.review.kept',
  },
  criteria: {
    heading: 'partnerTiers.criteria.heading',
    hint: 'partnerTiers.criteria.hint',
    version: 'partnerTiers.criteria.version',
    inForce: 'partnerTiers.criteria.inForce',
    from: 'partnerTiers.criteria.from',
    supplierHeading: 'partnerTiers.criteria.supplierHeading',
    supplierBody: 'partnerTiers.criteria.supplierBody',
    openTerms: 'partnerTiers.criteria.openTerms',
    tierLabel: 'partnerTiers.criteria.tierLabel',
    firstTier: 'partnerTiers.criteria.firstTier',
    atLeast: 'partnerTiers.criteria.atLeast',
    atMost: 'partnerTiers.criteria.atMost',
    commissionPlus: 'partnerTiers.criteria.commissionPlus',
    canLead: 'partnerTiers.criteria.canLead',
    edited: 'partnerTiers.criteria.edited',
    reset: 'partnerTiers.criteria.reset',
    publish: 'partnerTiers.criteria.publish',
    publishHeading: 'partnerTiers.criteria.publishHeading',
    publishBody: 'partnerTiers.criteria.publishBody',
    effective: 'partnerTiers.criteria.effective',
    effectiveHint: 'partnerTiers.criteria.effectiveHint',
    note: 'partnerTiers.criteria.note',
    noteHint: 'partnerTiers.criteria.noteHint',
    confirm: 'partnerTiers.criteria.confirm',
    saved: 'partnerTiers.criteria.saved',
    history: 'partnerTiers.criteria.history',
    changeNote: 'partnerTiers.criteria.changeNote',
    placeholder: 'partnerTiers.criteria.placeholder',
    reviewNote: 'partnerTiers.criteria.reviewNote',
  },
  action: { cancel: 'partnerTiers.action.cancel' },
  problem: rec('partnerTiers.problem', PROBLEMS),
} as const;
