/** Screen 187 — Audit Log of Automated Actions. Types and keys only. */
export const POLL_MS = 20_000;
export const PAGE = 25;

export const AUDIT_LOG_KEYS = {
  title: 'auditLog.title',
  subtitle: 'auditLog.subtitle',
  loading: 'auditLog.loading',
  offline: 'auditLog.offline',
  refresh: 'auditLog.refresh',
  close: 'auditLog.close',
  error: {
    title: 'auditLog.error.title',
    body: 'auditLog.error.body',
    retry: 'auditLog.error.retry',
    generic: 'auditLog.error.generic',
  },
  integrity: {
    ok: 'auditLog.integrity.ok',
    okBody: 'auditLog.integrity.okBody',
    broken: 'auditLog.integrity.broken',
    brokenBody: 'auditLog.integrity.brokenBody',
    head: 'auditLog.integrity.head',
    note: 'auditLog.integrity.note',
  },
  stats: {
    all: 'auditLog.stats.all',
    shown: 'auditLog.stats.shown',
    today: 'auditLog.stats.today',
  },
  volume: {
    title: 'auditLog.volume.title',
  },
  filters: {
    search: 'auditLog.filters.search',
    searchHint: 'auditLog.filters.searchHint',
    category: 'auditLog.filters.category',
    allCategories: 'auditLog.filters.allCategories',
    source: 'auditLog.filters.source',
    allSources: 'auditLog.filters.allSources',
    record: 'auditLog.filters.record',
    recordHint: 'auditLog.filters.recordHint',
    from: 'auditLog.filters.from',
    to: 'auditLog.filters.to',
    clear: 'auditLog.filters.clear',
  },
  list: {
    showing: 'auditLog.list.showing',
    more: 'auditLog.list.more',
    empty: 'auditLog.list.empty',
    emptyBody: 'auditLog.list.emptyBody',
    noMatch: 'auditLog.list.noMatch',
    noMatchBody: 'auditLog.list.noMatchBody',
  },
  detail: {
    title: 'auditLog.detail.title',
    did: 'auditLog.detail.did',
    why: 'auditLog.detail.why',
    which: 'auditLog.detail.which',
    source: 'auditLog.detail.source',
    step: 'auditLog.detail.step',
    rule: 'auditLog.detail.rule',
    ruleChanged: 'auditLog.detail.ruleChanged',
    acted: 'auditLog.detail.acted',
    recordType: 'auditLog.detail.recordType',
    recordId: 'auditLog.detail.recordId',
    openRecord: 'auditLog.detail.openRecord',
    keeping: 'auditLog.detail.keeping',
    code: 'auditLog.detail.code',
    at: 'auditLog.detail.at',
    hash: 'auditLog.detail.hash',
    prev: 'auditLog.detail.prev',
    asRecorded: 'auditLog.detail.asRecorded',
    copy: 'auditLog.detail.copy',
    copied: 'auditLog.detail.copied',
    same: 'auditLog.detail.same',
    sameNone: 'auditLog.detail.sameNone',
    exportTrail: 'auditLog.detail.exportTrail',
    noRoute: 'auditLog.detail.noRoute',
  },
  export: {
    button: 'auditLog.export.button',
    title: 'auditLog.export.title',
    body: 'auditLog.export.body',
    everything: 'auditLog.export.everything',
    csv: 'auditLog.export.csv',
    empty: 'auditLog.export.empty',
    done: 'auditLog.export.done',
  },
  exports: {
    title: 'auditLog.exports.title',
    line: 'auditLog.exports.line',
  },
  alert: {
    chainBroken: 'auditLog.alert.chainBroken',
  },
  category: {
    overrides: 'auditLog.category.overrides',
  },
  manual: {
    badge: 'auditLog.manual.badge',
    by: 'auditLog.manual.by',
    open: 'auditLog.manual.open',
  },
  link: {
    open: 'auditLog.link.open',
  },
} as const;
