/** Screen 150 — Partner Deactivation & Exit. Types and translation keys only. */

import { INTERVIEW_REASONS, INVOLUNTARY_REASONS, LAST_DAY_MAX_DAYS, REASON_MIN, STAGES, VOLUNTARY_REASONS } from '@/features/partners/exit';

export const POLL_MS = 30_000;
export const KINDS = ['voluntary', 'involuntary'] as const;
export const HOWS = ['call', 'message', 'in_person'] as const;
export const INTERVIEW_HOWS = ['call', 'in_person', 'form', 'declined'] as const;
export const OUTCOMES = ['uphold', 'partner_favor', 'partial'] as const;
export const RETURNS = ['yes', 'maybe', 'no'] as const;
export const draftKey = (userId: string, partnerId: string) => `aiec.exitDraft.${userId}.${partnerId}`;
export const exitPath = (partnerId: string) => `/partner-exit/${partnerId}`;
export const directoryPath = '/partner-directory';
export const supplierPaymentsPath = '/supplier-payments';
export { INTERVIEW_REASONS, INVOLUNTARY_REASONS, LAST_DAY_MAX_DAYS, REASON_MIN, STAGES, VOLUNTARY_REASONS };

const rec = <T extends string>(ns: string, keys: readonly T[]) => Object.fromEntries(keys.map((k) => [k, `${ns}.${k}`])) as Record<T, string>;
const PROBLEMS = [
  'not_admin', 'not_found', 'reason_invalid', 'note_required', 'last_day_invalid', 'exit_open', 'not_active', 'not_open', 'target_required', 'target_invalid', 'action_invalid',
  'item_not_open', 'finish_not_allowed', 'gate_blocked', 'settlement_exists', 'settlement_missing', 'settlement_locked', 'no_dispute', 'dispute_open', 'nothing_to_pay',
  'reference_required', 'amount_invalid', 'reason_required', 'access_ended', 'access_not_ended', 'withheld', 'offline', 'generic',
] as const;

export const EXIT_KEYS = {
  title: 'partnerExit.title',
  subtitle: 'partnerExit.subtitle',
  loading: 'partnerExit.loading',
  error: { title: 'partnerExit.error.title', body: 'partnerExit.error.body' },
  notFound: { title: 'partnerExit.notFound.title', body: 'partnerExit.notFound.body' },
  back: 'partnerExit.back',
  type: rec('partnerExit.type', ['surveyor', 'technician', 'supplier'] as const),
  kind: rec('partnerExit.kind', KINDS),
  stage: rec('partnerExit.stage', ['plan', 'work', 'settlement', 'access', 'interview', 'done'] as const),
  status: rec('partnerExit.status', ['in_progress', 'completed', 'cancelled'] as const),
  blocker: rec('partnerExit.blocker', ['work_open', 'work_finishing', 'settlement_missing', 'settlement_disputed'] as const),
  reason: { ...rec('partnerExit.reason', VOLUNTARY_REASONS), ...rec('partnerExit.reason', INVOLUNTARY_REASONS), ...rec('partnerExit.reason', INTERVIEW_REASONS) } as Record<string, string>,
  board: {
    open: 'partnerExit.board.open',
    openEmpty: 'partnerExit.board.openEmpty',
    done: 'partnerExit.board.done',
    doneEmpty: 'partnerExit.board.doneEmpty',
    startHint: 'partnerExit.board.startHint',
    toDirectory: 'partnerExit.board.toDirectory',
    lastDay: 'partnerExit.board.lastDay',
    workLeft: 'partnerExit.board.workLeft',
    owed: 'partnerExit.board.owed',
    closed: 'partnerExit.board.closed',
    attrition: 'partnerExit.board.attrition',
    attritionHint: 'partnerExit.board.attritionHint',
    attritionEmpty: 'partnerExit.board.attritionEmpty',
    attritionTotal: 'partnerExit.board.attritionTotal',
    attritionInvoluntary: 'partnerExit.board.attritionInvoluntary',
    tenure: 'partnerExit.board.tenure',
    byReason: 'partnerExit.board.byReason',
  },
  start: {
    heading: 'partnerExit.start.heading',
    body: 'partnerExit.start.body',
    kind: 'partnerExit.start.kind',
    kindHint: rec('partnerExit.start.kindHint', KINDS),
    reason: 'partnerExit.start.reason',
    reasonPlaceholder: 'partnerExit.start.reasonPlaceholder',
    note: 'partnerExit.start.note',
    noteHint: 'partnerExit.start.noteHint',
    lastDay: 'partnerExit.start.lastDay',
    lastDayHint: 'partnerExit.start.lastDayHint',
    inHand: 'partnerExit.start.inHand',
    inHandNone: 'partnerExit.start.inHandNone',
    owed: 'partnerExit.start.owed',
    violationWarn: 'partnerExit.start.violationWarn',
    notActive: 'partnerExit.start.notActive',
    confirm: 'partnerExit.start.confirm',
    confirmViolation: 'partnerExit.start.confirmViolation',
    draftKept: 'partnerExit.start.draftKept',
    started: 'partnerExit.start.started',
  },
  summary: { code: 'partnerExit.summary.code', started: 'partnerExit.summary.started', lastDay: 'partnerExit.summary.lastDay', by: 'partnerExit.summary.by', cancel: 'partnerExit.summary.cancel', cancelled: 'partnerExit.summary.cancelled', completed: 'partnerExit.summary.completed' },
  steps: { plan: 'partnerExit.steps.plan', work: 'partnerExit.steps.work', settlement: 'partnerExit.steps.settlement', access: 'partnerExit.steps.access', interview: 'partnerExit.steps.interview' },
  work: {
    heading: 'partnerExit.work.heading',
    body: 'partnerExit.work.body',
    bodyViolation: 'partnerExit.work.bodyViolation',
    none: 'partnerExit.work.none',
    itemType: rec('partnerExit.work.itemType', ['lead', 'job', 'order'] as const),
    selectAll: 'partnerExit.work.selectAll',
    selected: 'partnerExit.work.selected',
    action: 'partnerExit.work.action',
    actionOption: rec('partnerExit.work.actionOption', ['reassigned', 'returned_to_pool', 'finish_first', 'alternate_sourcing', 'cancelled'] as const),
    actionHint: rec('partnerExit.work.actionHint', ['reassigned', 'returned_to_pool', 'finish_first', 'alternate_sourcing', 'cancelled'] as const),
    to: 'partnerExit.work.to',
    toPlaceholder: 'partnerExit.work.toPlaceholder',
    note: 'partnerExit.work.note',
    noteHint: 'partnerExit.work.noteHint',
    apply: 'partnerExit.work.apply',
    applied: 'partnerExit.work.applied',
    finishing: 'partnerExit.work.finishing',
    decided: 'partnerExit.work.decided',
    history: 'partnerExit.work.history',
    historyRow: 'partnerExit.work.historyRow',
    canLead: 'partnerExit.work.canLead',
    cannotLead: 'partnerExit.work.cannotLead',
    holds: 'partnerExit.work.holds',
    open: 'partnerExit.work.open',
    jobNote: 'partnerExit.work.jobNote',
    orderNote: 'partnerExit.work.orderNote',
  },
  settle: {
    heading: 'partnerExit.settle.heading',
    body: 'partnerExit.settle.body',
    bodyViolation: 'partnerExit.settle.bodyViolation',
    line: rec('partnerExit.settle.line', ['commission_payable', 'payment_owed', 'advance_recoverable', 'adjustment'] as const),
    held: rec('partnerExit.settle.held', ['commission_pending', 'retention_held'] as const),
    heldHint: 'partnerExit.settle.heldHint',
    noLines: 'partnerExit.settle.noLines',
    total: 'partnerExit.settle.total',
    totalNegative: 'partnerExit.settle.totalNegative',
    asOf: 'partnerExit.settle.asOf',
    live: 'partnerExit.settle.live',
    confirm: 'partnerExit.settle.confirm',
    recalc: 'partnerExit.settle.recalc',
    confirmed: 'partnerExit.settle.confirmed',
    withhold: 'partnerExit.settle.withhold',
    withholdHint: 'partnerExit.settle.withholdHint',
    withholdReason: 'partnerExit.settle.withholdReason',
    withheldTitle: 'partnerExit.settle.withheldTitle',
    withheldBody: 'partnerExit.settle.withheldBody',
    release: 'partnerExit.settle.release',
    releaseNote: 'partnerExit.settle.releaseNote',
    agree: 'partnerExit.settle.agree',
    agreeHow: 'partnerExit.settle.agreeHow',
    agreeNote: 'partnerExit.settle.agreeNote',
    how: rec('partnerExit.settle.how', [...HOWS, 'decision'] as const),
    agreed: 'partnerExit.settle.agreed',
    dispute: 'partnerExit.settle.dispute',
    disputeHeading: 'partnerExit.settle.disputeHeading',
    disputeBody: 'partnerExit.settle.disputeBody',
    claimed: 'partnerExit.settle.claimed',
    claimedHint: 'partnerExit.settle.claimedHint',
    grounds: 'partnerExit.settle.grounds',
    groundsHint: 'partnerExit.settle.groundsHint',
    raise: 'partnerExit.settle.raise',
    disputeOpen: 'partnerExit.settle.disputeOpen',
    disputeBy: 'partnerExit.settle.disputeBy',
    decide: 'partnerExit.settle.decide',
    outcome: 'partnerExit.settle.outcome',
    outcomeOption: rec('partnerExit.settle.outcomeOption', OUTCOMES),
    outcomeHint: rec('partnerExit.settle.outcomeHint', OUTCOMES),
    amount: 'partnerExit.settle.amount',
    amountHint: 'partnerExit.settle.amountHint',
    decisionNote: 'partnerExit.settle.decisionNote',
    decisionNoteHint: 'partnerExit.settle.decisionNoteHint',
    decisionRecorded: 'partnerExit.settle.decisionRecorded',
    decidedBy: 'partnerExit.settle.decidedBy',
    adjustment: 'partnerExit.settle.adjustment',
    pay: 'partnerExit.settle.pay',
    payHint: 'partnerExit.settle.payHint',
    reference: 'partnerExit.settle.reference',
    paid: 'partnerExit.settle.paid',
    paidBy: 'partnerExit.settle.paidBy',
    supplierPay: 'partnerExit.settle.supplierPay',
    supplierPayLink: 'partnerExit.settle.supplierPayLink',
    nothing: 'partnerExit.settle.nothing',
    recorded: 'partnerExit.settle.recorded',
  },
  access: {
    heading: 'partnerExit.access.heading',
    body: 'partnerExit.access.body',
    bodyViolation: 'partnerExit.access.bodyViolation',
    ready: 'partnerExit.access.ready',
    waiting: 'partnerExit.access.waiting',
    end: 'partnerExit.access.end',
    endHeading: 'partnerExit.access.endHeading',
    endBody: 'partnerExit.access.endBody',
    endConfirm: 'partnerExit.access.endConfirm',
    ended: 'partnerExit.access.ended',
    endedFirst: 'partnerExit.access.endedFirst',
    effects: { surveyor: 'partnerExit.access.effects.surveyor', technician: 'partnerExit.access.effects.technician', supplier: 'partnerExit.access.effects.supplier' },
    lastDayAuto: 'partnerExit.access.lastDayAuto',
    done: 'partnerExit.access.done',
  },
  interview: {
    heading: 'partnerExit.interview.heading',
    body: 'partnerExit.interview.body',
    how: 'partnerExit.interview.how',
    howOption: rec('partnerExit.interview.howOption', INTERVIEW_HOWS),
    reasons: 'partnerExit.interview.reasons',
    wouldReturn: 'partnerExit.interview.wouldReturn',
    returnOption: rec('partnerExit.interview.returnOption', RETURNS),
    notes: 'partnerExit.interview.notes',
    save: 'partnerExit.interview.save',
    saved: 'partnerExit.interview.saved',
    recorded: 'partnerExit.interview.recorded',
    declined: 'partnerExit.interview.declined',
  },
  cancel: { heading: 'partnerExit.cancel.heading', body: 'partnerExit.cancel.body', reason: 'partnerExit.cancel.reason', reasonHint: 'partnerExit.cancel.reasonHint', confirm: 'partnerExit.cancel.confirm', keep: 'partnerExit.cancel.keep', done: 'partnerExit.cancel.done', afterAccess: 'partnerExit.cancel.afterAccess' },
  alert: { stuck: 'partnerExit.alert.stuck', violation: 'partnerExit.alert.violation' },
  action: { cancel: 'partnerExit.action.cancel' },
  problem: rec('partnerExit.problem', PROBLEMS),
} as const;
