/** Screen 131 — QC Inspector Assignment. Types and translation keys only. */

import type { QcWindow } from '@/data/types';

export type QcStatus = 'loading' | 'ready' | 'error' | 'not_found';

export const POLL_MS = 20_000;
export const draftKey = (userId: string, jobId: string) => `aiec.qcDraft.${userId}.${jobId}`;
export const viewKey = (userId: string, jobId: string) => `aiec.qcView.${userId}.${jobId}`;
export const EXCEPTION_MIN = 20;
export const REASON_MIN = 8;
export const WINDOW_IDS: QcWindow[] = ['morning', 'afternoon'];

export const FINAL_ERRORS = [
  'not_ready', 'already_checked', 'already_assigned', 'unknown_inspector', 'not_active', 'not_independent', 'exception_note_required', 'invalid_state', 'reason_required', 'same_inspector',
  'dates_invalid', 'date_invalid', 'in_past', 'too_far', 'not_working_day', 'inspector_busy', 'customer_unconfirmed', 'already_flagged', 'already_set', 'forbidden', 'not_found',
] as const;

const rec = <T extends string>(ns: string, keys: readonly T[]) => Object.fromEntries(keys.map((k) => [k, `${ns}.${k}`])) as Record<T, string>;

export const boardPath = '/qc-assignments';
export const detailPath = (id: string) => `/qc-assignments/${id}`;
export const jobPath = (id: string) => `/technician/jobs/${id}`;
export const homePath = '/technician';

export const QC_KEYS = {
  title: 'qcAssignment.title',
  boardTitle: 'qcAssignment.boardTitle',
  loading: 'qcAssignment.loading',
  back: 'qcAssignment.back',
  error: { title: 'qcAssignment.error.title', body: 'qcAssignment.error.body' },
  notFound: { title: 'qcAssignment.notFound.title', body: 'qcAssignment.notFound.body', action: 'qcAssignment.notFound.action' },
  empty: { title: 'qcAssignment.empty.title', body: 'qcAssignment.empty.body' },
  emptyMine: { title: 'qcAssignment.emptyMine.title', body: 'qcAssignment.emptyMine.body' },
  problem: rec('qcAssignment.problem', [...FINAL_ERRORS, 'offline', 'generic'] as const),
  jobStatus: rec('qcAssignment.jobStatus', ['scheduled', 'materials_pending', 'in_progress', 'qc_pending', 'handover_pending', 'completed', 'on_hold'] as const),
  status: rec('qcAssignment.status', ['assigned', 'scheduled', 'in_progress', 'completed', 'cancelled'] as const),
  window: rec('qcAssignment.window', ['morning', 'afternoon', 'any'] as const),
  busy: rec('qcAssignment.busy', ['booked', 'unavailable', 'installing'] as const),
  board: {
    subtitle: 'qcAssignment.board.subtitle',
    ready: 'qcAssignment.board.ready',
    unassigned: 'qcAssignment.board.unassigned',
    scheduled: 'qcAssignment.board.scheduled',
    conflicts: 'qcAssignment.board.conflicts',
    heading: 'qcAssignment.board.heading',
    waiting: 'qcAssignment.board.waiting',
    problems: rec('qcAssignment.board.problems', ['installation_open', 'safety_open', 'awaiting_lead', 'on_hold', 'not_finished'] as const),
    noInspector: 'qcAssignment.board.noInspector',
    exceptionTag: 'qcAssignment.board.exceptionTag',
    conflictTag: 'qcAssignment.board.conflictTag',
    prefTag: 'qcAssignment.board.prefTag',
    inspectors: 'qcAssignment.board.inspectors',
    inspectorsNote: 'qcAssignment.board.inspectorsNote',
    week: 'qcAssignment.board.week',
    off: 'qcAssignment.board.off',
    addOff: 'qcAssignment.board.addOff',
    open: 'qcAssignment.board.open',
    mine: 'qcAssignment.board.mine',
    mineBody: 'qcAssignment.board.mineBody',
    notReady: 'qcAssignment.board.notReady',
  },
  readiness: {
    heading: 'qcAssignment.readiness.heading',
    intro: 'qcAssignment.readiness.intro',
    installation: 'qcAssignment.readiness.installation',
    safety: 'qcAssignment.readiness.safety',
    lead: 'qcAssignment.readiness.lead',
    done: 'qcAssignment.readiness.done',
    open: 'qcAssignment.readiness.open',
    ready: 'qcAssignment.readiness.ready',
    blocked: 'qcAssignment.readiness.blocked',
    beyond: 'qcAssignment.readiness.beyond',
  },
  pref: {
    heading: 'qcAssignment.pref.heading',
    intro: 'qcAssignment.pref.intro',
    none: 'qcAssignment.pref.none',
    recorded: 'qcAssignment.pref.recorded',
    dates: 'qcAssignment.pref.dates',
    date: 'qcAssignment.pref.date',
    addDate: 'qcAssignment.pref.addDate',
    removeDate: 'qcAssignment.pref.removeDate',
    window: 'qcAssignment.pref.window',
    note: 'qcAssignment.pref.note',
    save: 'qcAssignment.pref.save',
    toast: 'qcAssignment.pref.toast',
  },
  inspector: {
    heading: 'qcAssignment.inspector.heading',
    intro: 'qcAssignment.inspector.intro',
    eligible: 'qcAssignment.inspector.eligible',
    gap: 'qcAssignment.inspector.gap',
    blocked: 'qcAssignment.inspector.blocked',
    missing: 'qcAssignment.inspector.missing',
    skill: rec('qcAssignment.inspector.skill', ['mechanical', 'electrical', 'safety_rescue', 'mrl_gearless', 'hydraulic'] as const),
    problem: rec('qcAssignment.inspector.problemTag', ['not_active', 'missing_skill', 'not_independent'] as const),
    involvement: rec('qcAssignment.inspector.involvement', ['lead', 'crew', 'checked_in', 'finished_steps', 'left_the_job'] as const),
    load: 'qcAssignment.inspector.load',
    away: 'qcAssignment.inspector.away',
    onPref: 'qcAssignment.inspector.onPref',
    free: 'qcAssignment.inspector.free',
    exceptionLabel: 'qcAssignment.inspector.exceptionLabel',
    exceptionHint: 'qcAssignment.inspector.exceptionHint',
    noneEligible: 'qcAssignment.inspector.noneEligible',
    adminHeading: 'qcAssignment.inspector.adminHeading',
    adminBody: 'qcAssignment.inspector.adminBody',
    adminReason: 'qcAssignment.inspector.adminReason',
    adminGo: 'qcAssignment.inspector.adminGo',
    adminAdvised: 'qcAssignment.inspector.adminAdvised',
    assign: 'qcAssignment.inspector.assign',
    assignException: 'qcAssignment.inspector.assignException',
    pick: 'qcAssignment.inspector.pick',
    toast: 'qcAssignment.inspector.toast',
    toastAdmin: 'qcAssignment.inspector.toastAdmin',
  },
  assigned: {
    heading: 'qcAssignment.assigned.heading',
    exception: 'qcAssignment.assigned.exception',
    exceptionAdmin: 'qcAssignment.assigned.exceptionAdmin',
    exceptionNote: 'qcAssignment.assigned.exceptionNote',
    assignedBy: 'qcAssignment.assigned.assignedBy',
    notified: 'qcAssignment.assigned.notified',
    previous: 'qcAssignment.assigned.previous',
    reassign: 'qcAssignment.assigned.reassign',
    reassignTitle: 'qcAssignment.assigned.reassignTitle',
    reassignBody: 'qcAssignment.assigned.reassignBody',
    reassignReason: 'qcAssignment.assigned.reassignReason',
    reassignPick: 'qcAssignment.assigned.reassignPick',
    reassignSelf: 'qcAssignment.assigned.reassignSelf',
    reassignGo: 'qcAssignment.assigned.reassignGo',
    toastReassigned: 'qcAssignment.assigned.toastReassigned',
    history: 'qcAssignment.assigned.history',
    event: rec('qcAssignment.assigned.event', ['assigned', 'exception_assigned', 'reassigned', 'preference_recorded', 'scheduled', 'rescheduled', 'conflict_flagged', 'conflict_cleared', 'cancelled'] as const),
    by: 'qcAssignment.assigned.by',
  },
  conflict: {
    heading: 'qcAssignment.conflict.heading',
    installation: 'qcAssignment.conflict.installation',
    self: 'qcAssignment.conflict.self',
    body: 'qcAssignment.conflict.body',
    clear: 'qcAssignment.conflict.clear',
    clearTitle: 'qcAssignment.conflict.clearTitle',
    clearBody: 'qcAssignment.conflict.clearBody',
    clearNote: 'qcAssignment.conflict.clearNote',
    clearGo: 'qcAssignment.conflict.clearGo',
    toastCleared: 'qcAssignment.conflict.toastCleared',
    report: 'qcAssignment.conflict.report',
    reportTitle: 'qcAssignment.conflict.reportTitle',
    reportBody: 'qcAssignment.conflict.reportBody',
    reportNote: 'qcAssignment.conflict.reportNote',
    reportGo: 'qcAssignment.conflict.reportGo',
    toastReported: 'qcAssignment.conflict.toastReported',
    told: 'qcAssignment.conflict.told',
  },
  visit: {
    heading: 'qcAssignment.visit.heading',
    intro: 'qcAssignment.visit.intro',
    scheduled: 'qcAssignment.visit.scheduled',
    notScheduled: 'qcAssignment.visit.notScheduled',
    suggestions: 'qcAssignment.visit.suggestions',
    none: 'qcAssignment.visit.none',
    preferred: 'qcAssignment.visit.preferred',
    unmet: 'qcAssignment.visit.unmet',
    date: 'qcAssignment.visit.date',
    window: 'qcAssignment.visit.window',
    agreed: 'qcAssignment.visit.agreed',
    agreedHint: 'qcAssignment.visit.agreedHint',
    matches: 'qcAssignment.visit.matches',
    book: 'qcAssignment.visit.book',
    move: 'qcAssignment.visit.move',
    toast: 'qcAssignment.visit.toast',
  },
  briefing: {
    heading: 'qcAssignment.briefing.heading',
    intro: 'qcAssignment.briefing.intro',
    steps: 'qcAssignment.briefing.steps',
    photos: 'qcAssignment.briefing.photos',
    noPhotos: 'qcAssignment.briefing.noPhotos',
    doneBy: 'qcAssignment.briefing.doneBy',
    notApplicable: 'qcAssignment.briefing.notApplicable',
    safetyCritical: 'qcAssignment.briefing.safetyCritical',
    safety: 'qcAssignment.briefing.safety',
    issues: 'qcAssignment.briefing.issues',
    noIssues: 'qcAssignment.briefing.noIssues',
    open: 'qcAssignment.briefing.open',
    resolved: 'qcAssignment.briefing.resolved',
    parts: 'qcAssignment.briefing.parts',
    noParts: 'qcAssignment.briefing.noParts',
    substituted: 'qcAssignment.briefing.substituted',
    unreadable: 'qcAssignment.briefing.unreadable',
    team: 'qcAssignment.briefing.team',
    site: 'qcAssignment.briefing.site',
    lead: 'qcAssignment.briefing.lead',
    assistant: 'qcAssignment.briefing.assistant',
  },
  mine: {
    heading: 'qcAssignment.mine.heading',
    off: 'qcAssignment.mine.off',
    offBody: 'qcAssignment.mine.offBody',
    offDate: 'qcAssignment.mine.offDate',
    offWindow: 'qcAssignment.mine.offWindow',
    offReason: 'qcAssignment.mine.offReason',
    offAdd: 'qcAssignment.mine.offAdd',
    offRemove: 'qcAssignment.mine.offRemove',
    offAll: 'qcAssignment.mine.offAll',
    offNone: 'qcAssignment.mine.offNone',
    toastOff: 'qcAssignment.mine.toastOff',
  },
  sync: { local: 'qcAssignment.sync.local', saved: 'qcAssignment.sync.saved', draftRestored: 'qcAssignment.sync.draftRestored' },
  cancel: 'qcAssignment.cancel',
  missing: 'qcAssignment.missing',
  alert: { conflict: 'qcAssignment.alert.conflict' },
} as const;
