/** Screen 104 — Material Received Confirmation. Types and translation keys only. */

import type { ConfirmationPartyRole } from '@/data/types';

export type DeliveryConfirmationStatus = 'loading' | 'ready' | 'error';

/** Who else may co-sign, beside the one who received it. */
export const SECOND_PARTY_ROLES: Extract<ConfirmationPartyRole, 'customer' | 'site_contact'>[] = ['customer', 'site_contact'];

/** Where signatures wait on the device when the network is down on site. */
export const QUEUE_STORAGE_KEY = 'aiec.deliveryConfirmQueue';

export const DELIVERY_CONFIRMATION_KEYS = {
  title: 'deliveryConfirmation.title',
  subtitleAdmin: 'deliveryConfirmation.subtitleAdmin',
  subtitleTechnician: 'deliveryConfirmation.subtitleTechnician',
  subtitleCustomer: 'deliveryConfirmation.subtitleCustomer',
  loading: 'deliveryConfirmation.loading',
  error: { title: 'deliveryConfirmation.error.title', body: 'deliveryConfirmation.error.body' },
  board: {
    awaitingHeading: 'deliveryConfirmation.board.awaitingHeading',
    awaitingHint: 'deliveryConfirmation.board.awaitingHint',
    signedHeading: 'deliveryConfirmation.board.signedHeading',
    customerHeading: 'deliveryConfirmation.board.customerHeading',
    emptyTitle: 'deliveryConfirmation.board.emptyTitle',
    emptyBody: 'deliveryConfirmation.board.emptyBody',
    emptyCustomerBody: 'deliveryConfirmation.board.emptyCustomerBody',
    sign: 'deliveryConfirmation.board.sign',
    open: 'deliveryConfirmation.board.open',
    summary: 'deliveryConfirmation.board.summary',
    queued: 'deliveryConfirmation.board.queued',
    signedOn: 'deliveryConfirmation.board.signedOn',
    pendingReports: 'deliveryConfirmation.board.pendingReports',
    showAll: 'deliveryConfirmation.board.showAll',
  },
  doc: {
    notFound: 'deliveryConfirmation.doc.notFound',
    notFoundBody: 'deliveryConfirmation.doc.notFoundBody',
    statusAwaiting: 'deliveryConfirmation.doc.statusAwaiting',
    statusSigned: 'deliveryConfirmation.doc.statusSigned',
    site: 'deliveryConfirmation.doc.site',
    order: 'deliveryConfirmation.doc.order',
    supplier: 'deliveryConfirmation.doc.supplier',
    vehicle: 'deliveryConfirmation.doc.vehicle',
    partsHeading: 'deliveryConfirmation.doc.partsHeading',
    received: 'deliveryConfirmation.doc.received',
    photos: 'deliveryConfirmation.doc.photos',
    verdict: {
      ok: 'deliveryConfirmation.doc.verdict.ok',
      discrepancy: 'deliveryConfirmation.doc.verdict.discrepancy',
      not_arrived: 'deliveryConfirmation.doc.verdict.not_arrived',
    },
    kind: {
      damaged: 'deliveryConfirmation.doc.kind.damaged',
      count: 'deliveryConfirmation.doc.kind.count',
      wrong_spec: 'deliveryConfirmation.doc.kind.wrong_spec',
    },
    stillToCome: 'deliveryConfirmation.doc.stillToCome',
    fullyDelivered: 'deliveryConfirmation.doc.fullyDelivered',
    partDelivered: 'deliveryConfirmation.doc.partDelivered',
    pendingHeading: 'deliveryConfirmation.doc.pendingHeading',
    pendingBody: 'deliveryConfirmation.doc.pendingBody',
    pendingBodyCustomer: 'deliveryConfirmation.doc.pendingBodyCustomer',
    reportOpen: 'deliveryConfirmation.doc.reportOpen',
    reportWithdrawn: 'deliveryConfirmation.doc.reportWithdrawn',
    reportResolved: 'deliveryConfirmation.doc.reportResolved',
    receivedBy: 'deliveryConfirmation.doc.receivedBy',
    signedHeading: 'deliveryConfirmation.doc.signedHeading',
    role: {
      technician: 'deliveryConfirmation.doc.role.technician',
      site_contact: 'deliveryConfirmation.doc.role.site_contact',
      customer: 'deliveryConfirmation.doc.role.customer',
    },
    signatureOf: 'deliveryConfirmation.doc.signatureOf',
    signedAt: 'deliveryConfirmation.doc.signedAt',
    locked: 'deliveryConfirmation.doc.locked',
    lockedBody: 'deliveryConfirmation.doc.lockedBody',
    delayed: 'deliveryConfirmation.doc.delayed',
    aloneNote: 'deliveryConfirmation.doc.aloneNote',
    recordedBy: 'deliveryConfirmation.doc.recordedBy',
    materialsFired: 'deliveryConfirmation.doc.materialsFired',
    customerCopy: 'deliveryConfirmation.doc.customerCopy',
  },
  sign: {
    heading: 'deliveryConfirmation.sign.heading',
    intro: 'deliveryConfirmation.sign.intro',
    primary: 'deliveryConfirmation.sign.primary',
    primaryHint: 'deliveryConfirmation.sign.primaryHint',
    clear: 'deliveryConfirmation.sign.clear',
    pad: 'deliveryConfirmation.sign.pad',
    second: 'deliveryConfirmation.sign.second',
    secondHint: 'deliveryConfirmation.sign.secondHint',
    secondRole: 'deliveryConfirmation.sign.secondRole',
    secondName: 'deliveryConfirmation.sign.secondName',
    noSecondNote: 'deliveryConfirmation.sign.noSecondNote',
    noSecondHint: 'deliveryConfirmation.sign.noSecondHint',
    submit: 'deliveryConfirmation.sign.submit',
    submitOffline: 'deliveryConfirmation.sign.submitOffline',
    offlineTitle: 'deliveryConfirmation.sign.offlineTitle',
    offlineBody: 'deliveryConfirmation.sign.offlineBody',
    queuedTitle: 'deliveryConfirmation.sign.queuedTitle',
    queuedBody: 'deliveryConfirmation.sign.queuedBody',
    lockWarning: 'deliveryConfirmation.sign.lockWarning',
    pendingWarning: 'deliveryConfirmation.sign.pendingWarning',
  },
  toast: {
    signed: 'deliveryConfirmation.toast.signed',
    queued: 'deliveryConfirmation.toast.queued',
    sent: 'deliveryConfirmation.toast.sent',
  },
  problem: {
    forbidden: 'deliveryConfirmation.problem.forbidden',
    not_found: 'deliveryConfirmation.problem.not_found',
    invalid_state: 'deliveryConfirmation.problem.invalid_state',
    invalid_input: 'deliveryConfirmation.problem.invalid_input',
    signature_required: 'deliveryConfirmation.problem.signature_required',
    note_required: 'deliveryConfirmation.problem.note_required',
    generic: 'deliveryConfirmation.problem.generic',
  },
} as const;
