/** Screen 184 — Escalation Matrix Configuration. Types and keys only. */
export const POLL_MS = 20_000;
export const POLL_BUSY_MS = 4_000;
export const ALERTS_ROUTE = '/admin/alerts';

export const ESCALATION_MATRIX_KEYS = {
  title: 'escalationMatrix.title',
  subtitle: 'escalationMatrix.subtitle',
  refresh: 'escalationMatrix.refresh',
  loading: 'escalationMatrix.loading',
  offline: 'escalationMatrix.offline',
  error: {
    title: 'escalationMatrix.error.title',
    body: 'escalationMatrix.error.body',
    retry: 'escalationMatrix.error.retry',
    generic: 'escalationMatrix.error.generic',
    forbidden: 'escalationMatrix.error.forbidden',
    not_found: 'escalationMatrix.error.not_found',
    invalid_phone: 'escalationMatrix.error.invalid_phone',
    same_as_admin: 'escalationMatrix.error.same_as_admin',
    duplicate_contact: 'escalationMatrix.error.duplicate_contact',
    name_required: 'escalationMatrix.error.name_required',
    unknown_user: 'escalationMatrix.error.unknown_user',
    invalid_slot: 'escalationMatrix.error.invalid_slot',
    drill_running: 'escalationMatrix.error.drill_running',
    reason_required: 'escalationMatrix.error.reason_required',
    invalid_state: 'escalationMatrix.error.invalid_state',
    vital_cannot_be_off: 'escalationMatrix.error.vital_cannot_be_off',
    chain_no_tiers: 'escalationMatrix.error.chain_no_tiers',
    chain_too_many_tiers: 'escalationMatrix.error.chain_too_many_tiers',
    chain_tier_no_target: 'escalationMatrix.error.chain_tier_no_target',
    chain_tier_no_channel: 'escalationMatrix.error.chain_tier_no_channel',
    chain_bad_delay: 'escalationMatrix.error.chain_bad_delay',
    chain_first_delay: 'escalationMatrix.error.chain_first_delay',
    chain_unknown_target: 'escalationMatrix.error.chain_unknown_target',
    chain_bad_repeat: 'escalationMatrix.error.chain_bad_repeat',
    chain_single_person: 'escalationMatrix.error.chain_single_person',
  },
  summary: {
    vital: 'escalationMatrix.summary.vital',
    vitalValue: 'escalationMatrix.summary.vitalValue',
    drills: 'escalationMatrix.summary.drills',
    gaps: 'escalationMatrix.summary.gaps',
    running: 'escalationMatrix.summary.running',
  },
  noBackup: {
    title: 'escalationMatrix.noBackup.title',
    body: 'escalationMatrix.noBackup.body',
  },
  backups: {
    title: 'escalationMatrix.backups.title',
    hint: 'escalationMatrix.backups.hint',
    primary: 'escalationMatrix.backups.primary',
    primaryHint: 'escalationMatrix.backups.primaryHint',
    slot: 'escalationMatrix.backups.slot',
    notSet: 'escalationMatrix.backups.notSet',
    set: 'escalationMatrix.backups.set',
    edit: 'escalationMatrix.backups.edit',
    hasAccount: 'escalationMatrix.backups.hasAccount',
    phoneOnly: 'escalationMatrix.backups.phoneOnly',
    demoTitle: 'escalationMatrix.backups.demoTitle',
    demoHint: 'escalationMatrix.backups.demoHint',
    sms: 'escalationMatrix.backups.sms',
    call: 'escalationMatrix.backups.call',
  },
  rail: {
    working: 'escalationMatrix.rail.working',
    failing: 'escalationMatrix.rail.failing',
    silent: 'escalationMatrix.rail.silent',
  },
  contact: {
    title: 'escalationMatrix.contact.title',
    name: 'escalationMatrix.contact.name',
    phone: 'escalationMatrix.contact.phone',
    phoneHint: 'escalationMatrix.contact.phoneHint',
    account: 'escalationMatrix.contact.account',
    accountNone: 'escalationMatrix.contact.accountNone',
    accountHint: 'escalationMatrix.contact.accountHint',
    note: 'escalationMatrix.contact.note',
    noteHint: 'escalationMatrix.contact.noteHint',
    save: 'escalationMatrix.contact.save',
    cancel: 'escalationMatrix.contact.cancel',
    remove: 'escalationMatrix.contact.remove',
    removeAsk: 'escalationMatrix.contact.removeAsk',
    removeYes: 'escalationMatrix.contact.removeYes',
    removeNo: 'escalationMatrix.contact.removeNo',
  },
  scenarios: {
    title: 'escalationMatrix.scenarios.title',
    hint: 'escalationMatrix.scenarios.hint',
  },
  scenario: {
    sos: {
      name: 'escalationMatrix.scenario.sos.name',
      covers: 'escalationMatrix.scenario.sos.covers',
    },
    safety: {
      name: 'escalationMatrix.scenario.safety.name',
      covers: 'escalationMatrix.scenario.safety.covers',
    },
    payout_failure: {
      name: 'escalationMatrix.scenario.payout_failure.name',
      covers: 'escalationMatrix.scenario.payout_failure.covers',
    },
    critical_exception: {
      name: 'escalationMatrix.scenario.critical_exception.name',
      covers: 'escalationMatrix.scenario.critical_exception.covers',
    },
    high_exception: {
      name: 'escalationMatrix.scenario.high_exception.name',
      covers: 'escalationMatrix.scenario.high_exception.covers',
    },
  },
  vital: 'escalationMatrix.vital',
  off: 'escalationMatrix.off',
  trigger: {
    unacknowledged: 'escalationMatrix.trigger.unacknowledged',
    unresolved: 'escalationMatrix.trigger.unresolved',
  },
  chain: {
    step: 'escalationMatrix.chain.step',
    now: 'escalationMatrix.chain.now',
    after: 'escalationMatrix.chain.after',
    total: 'escalationMatrix.chain.total',
    unfilled: 'escalationMatrix.chain.unfilled',
    unfilledNote: 'escalationMatrix.chain.unfilledNote',
  },
  unit: {
    min: 'escalationMatrix.unit.min',
    h: 'escalationMatrix.unit.h',
    d: 'escalationMatrix.unit.d',
  },
  target: {
    primary: 'escalationMatrix.target.primary',
    backup: 'escalationMatrix.target.backup',
  },
  channel: {
    inApp: 'escalationMatrix.channel.inApp',
    sms: 'escalationMatrix.channel.sms',
    call: 'escalationMatrix.channel.call',
  },
  lastResort: {
    title: 'escalationMatrix.lastResort.title',
    repeat: 'escalationMatrix.lastResort.repeat',
    none: 'escalationMatrix.lastResort.none',
    limit: 'escalationMatrix.lastResort.limit',
  },
  unfilledWarn: 'escalationMatrix.unfilledWarn',
  drillStatus: {
    never: 'escalationMatrix.drillStatus.never',
    passed: 'escalationMatrix.drillStatus.passed',
    gaps: 'escalationMatrix.drillStatus.gaps',
    due: 'escalationMatrix.drillStatus.due',
    overdue: 'escalationMatrix.drillStatus.overdue',
    running: 'escalationMatrix.drillStatus.running',
  },
  openGap: 'escalationMatrix.openGap',
  actions: {
    test: 'escalationMatrix.actions.test',
    edit: 'escalationMatrix.actions.edit',
    seeDrill: 'escalationMatrix.actions.seeDrill',
  },
  edit: {
    title: 'escalationMatrix.edit.title',
    enabled: 'escalationMatrix.edit.enabled',
    enabledHint: 'escalationMatrix.edit.enabledHint',
    vitalOn: 'escalationMatrix.edit.vitalOn',
    stops: 'escalationMatrix.edit.stops',
    steps: 'escalationMatrix.edit.steps',
    who: 'escalationMatrix.edit.who',
    how: 'escalationMatrix.edit.how',
    delay: 'escalationMatrix.edit.delay',
    delayFirst: 'escalationMatrix.edit.delayFirst',
    addStep: 'escalationMatrix.edit.addStep',
    removeStep: 'escalationMatrix.edit.removeStep',
    repeatTitle: 'escalationMatrix.edit.repeatTitle',
    repeatEvery: 'escalationMatrix.edit.repeatEvery',
    repeatTimes: 'escalationMatrix.edit.repeatTimes',
    save: 'escalationMatrix.edit.save',
    revert: 'escalationMatrix.edit.revert',
    saved: 'escalationMatrix.edit.saved',
    singleTitle: 'escalationMatrix.edit.singleTitle',
    singleBody: 'escalationMatrix.edit.singleBody',
    singleNote: 'escalationMatrix.edit.singleNote',
    singleHint: 'escalationMatrix.edit.singleHint',
    sheetHint: 'escalationMatrix.edit.sheetHint',
  },
  drill: {
    title: 'escalationMatrix.drill.title',
    hint: 'escalationMatrix.drill.hint',
    running: 'escalationMatrix.drill.running',
    passed: 'escalationMatrix.drill.passed',
    gaps: 'escalationMatrix.drill.gaps',
    waiting: 'escalationMatrix.drill.waiting',
    stepLine: 'escalationMatrix.drill.stepLine',
    confirm: 'escalationMatrix.drill.confirm',
    passedBody: 'escalationMatrix.drill.passedBody',
    gapsTitle: 'escalationMatrix.drill.gapsTitle',
    gapsBody: 'escalationMatrix.drill.gapsBody',
    again: 'escalationMatrix.drill.again',
    accept: 'escalationMatrix.drill.accept',
    acceptHint: 'escalationMatrix.drill.acceptHint',
    acceptNote: 'escalationMatrix.drill.acceptNote',
    acceptSave: 'escalationMatrix.drill.acceptSave',
    accepted: 'escalationMatrix.drill.accepted',
    by: 'escalationMatrix.drill.by',
  },
  step: {
    pending: 'escalationMatrix.step.pending',
    confirmed: 'escalationMatrix.step.confirmed',
    failed: 'escalationMatrix.step.failed',
    no_response: 'escalationMatrix.step.no_response',
    unfilled: 'escalationMatrix.step.unfilled',
    no_phone: 'escalationMatrix.step.no_phone',
    no_account: 'escalationMatrix.step.no_account',
  },
  fix: {
    unfilled: 'escalationMatrix.fix.unfilled',
    no_phone: 'escalationMatrix.fix.no_phone',
    no_account: 'escalationMatrix.fix.no_account',
    failed: 'escalationMatrix.fix.failed',
    no_response: 'escalationMatrix.fix.no_response',
  },
  runs: {
    title: 'escalationMatrix.runs.title',
    empty: 'escalationMatrix.runs.empty',
    emptyHint: 'escalationMatrix.runs.emptyHint',
    running: 'escalationMatrix.runs.running',
    stopped: 'escalationMatrix.runs.stopped',
    exhausted: 'escalationMatrix.runs.exhausted',
    progress: 'escalationMatrix.runs.progress',
    next: 'escalationMatrix.runs.next',
    stoppedBy: {
      acknowledged: 'escalationMatrix.runs.stoppedBy.acknowledged',
      resolved: 'escalationMatrix.runs.stoppedBy.resolved',
    },
    exhaustedNote: 'escalationMatrix.runs.exhaustedNote',
    sent: 'escalationMatrix.runs.sent',
    failed: 'escalationMatrix.runs.failed',
    skipped: 'escalationMatrix.runs.skipped',
    skipReason: {
      unfilled: 'escalationMatrix.runs.skipReason.unfilled',
      no_phone: 'escalationMatrix.runs.skipReason.no_phone',
      no_account: 'escalationMatrix.runs.skipReason.no_account',
      gateway_refused: 'escalationMatrix.runs.skipReason.gateway_refused',
    },
    repeat: 'escalationMatrix.runs.repeat',
    alert: 'escalationMatrix.runs.alert',
  },
  drills: {
    title: 'escalationMatrix.drills.title',
    empty: 'escalationMatrix.drills.empty',
    emptyBody: 'escalationMatrix.drills.emptyBody',
    open: 'escalationMatrix.drills.open',
  },
  history: {
    title: 'escalationMatrix.history.title',
    line: 'escalationMatrix.history.line',
  },
  placeholders: {
    title: 'escalationMatrix.placeholders.title',
    body: 'escalationMatrix.placeholders.body',
  },
  close: 'escalationMatrix.close',
  alert: {
    exhausted: 'escalationMatrix.alert.exhausted',
    drillGap: 'escalationMatrix.alert.drillGap',
  },
  link: {
    open: 'escalationMatrix.link.open',
  },
} as const;
