/** Screen 117 — Supplier Dispute Resolution. Types and translation keys only. */

import type { DisputeCorrection, DisputeProcessArea, SupplierDisputeDecision, SupplierDisputeEventKind, SupplierDisputeKind } from '@/data/types';
import type { DisputeEffect, DisputeSlaState } from '@/data/repository';

export type DisputeStatus = 'loading' | 'ready' | 'error';

/** How often the queue re-reads while open: the resolution clocks keep running. */
export const POLL_MS = 30_000;

export type QueueFilter = 'open' | 'resolved' | 'all';
export const QUEUE_FILTERS: QueueFilter[] = ['open', 'resolved', 'all'];
export const KINDS: SupplierDisputeKind[] = ['amount', 'retention_timing', 'invoice'];
export const DECISIONS: SupplierDisputeDecision[] = ['uphold', 'supplier_favor', 'partial'];
export const SLA_STATES: DisputeSlaState[] = ['on_track', 'due_soon', 'overdue', 'resolved'];
export const EFFECTS: DisputeEffect[] = ['payment_adjustment', 'payment_amount', 'retention_release', 'invoice_accept', 'none'];
export const CORRECTIONS: DisputeCorrection[] = ['none', 'payment_adjustment', 'payment_amount', 'retention_released', 'invoice_accepted'];
export const AREAS: DisputeProcessArea[] = ['invoice_matching', 'payment_terms', 'delivery_sop', 'other'];
export const EVENT_KINDS: SupplierDisputeEventKind[] = ['raised', 'decided', 'reopened', 'process_flagged', 'process_addressed'];
export const AGREEMENT_STATES = ['none', 'active', 'expiring', 'lapsed'] as const;
export const RETENTION_STATUSES = ['held', 'paused', 'released', 'withheld'] as const;
export const PAYMENT_STATUSES = ['pending_approval', 'held', 'approved', 'executed'] as const;

const rec = <T extends string>(ns: string, keys: readonly T[]) => Object.fromEntries(keys.map((k) => [k, `${ns}.${k}`])) as Record<T, string>;

export const DISPUTE_KEYS = {
  title: 'supplierDispute.title',
  subtitle: 'supplierDispute.subtitle',
  loading: 'supplierDispute.loading',
  error: { title: 'supplierDispute.error.title', body: 'supplierDispute.error.body' },
  alert: { haltThreat: 'supplierDispute.alert.haltThreat' },
  totals: { open: 'supplierDispute.totals.open', overdue: 'supplierDispute.totals.overdue', halt: 'supplierDispute.totals.halt', claimed: 'supplierDispute.totals.claimed', count: 'supplierDispute.totals.count' },
  filter: { label: 'supplierDispute.filter.label', search: 'supplierDispute.filter.search', ...rec('supplierDispute.filter', QUEUE_FILTERS) },
  list: {
    emptyOpenTitle: 'supplierDispute.list.emptyOpenTitle',
    emptyOpenBody: 'supplierDispute.list.emptyOpenBody',
    emptyResolvedTitle: 'supplierDispute.list.emptyResolvedTitle',
    emptyResolvedBody: 'supplierDispute.list.emptyResolvedBody',
    emptySearchTitle: 'supplierDispute.list.emptySearchTitle',
    emptySearchBody: 'supplierDispute.list.emptySearchBody',
    clear: 'supplierDispute.list.clear',
    due: 'supplierDispute.list.due',
    overdue: 'supplierDispute.list.overdue',
    resolvedOn: 'supplierDispute.list.resolvedOn',
    round: 'supplierDispute.list.round',
    halt: 'supplierDispute.list.halt',
    process: 'supplierDispute.list.process',
    claims: 'supplierDispute.list.claims',
    noAmount: 'supplierDispute.list.noAmount',
  },
  kind: rec('supplierDispute.kind', KINDS),
  sla: rec('supplierDispute.sla', SLA_STATES),
  decision: rec('supplierDispute.decision', DECISIONS),
  effect: rec('supplierDispute.effect', EFFECTS),
  correction: rec('supplierDispute.correction', CORRECTIONS),
  area: rec('supplierDispute.area', AREAS),
  detail: {
    back: 'supplierDispute.detail.back',
    notFound: 'supplierDispute.detail.notFound',
    notFoundBody: 'supplierDispute.detail.notFoundBody',
    supplier: 'supplierDispute.detail.supplier',
    order: 'supplierDispute.detail.order',
    about: 'supplierDispute.detail.about',
    raised: 'supplierDispute.detail.raised',
    raisedFor: 'supplierDispute.detail.raisedFor',
    claimed: 'supplierDispute.detail.claimed',
    dueBy: 'supplierDispute.detail.dueBy',
    haltHeading: 'supplierDispute.detail.haltHeading',
    haltBody: 'supplierDispute.detail.haltBody',
    sidesHeading: 'supplierDispute.detail.sidesHeading',
    positionHeading: 'supplierDispute.detail.positionHeading',
    evidenceHeading: 'supplierDispute.detail.evidenceHeading',
    evidenceHint: 'supplierDispute.detail.evidenceHint',
    orderTotal: 'supplierDispute.detail.orderTotal',
    terms: 'supplierDispute.detail.terms',
    termsShare: 'supplierDispute.detail.termsShare',
    reconciles: 'supplierDispute.detail.reconciles',
    differs: 'supplierDispute.detail.differs',
    payment: 'supplierDispute.detail.payment',
    paymentLine: 'supplierDispute.detail.paymentLine',
    adjustment: 'supplierDispute.detail.adjustment',
    retention: 'supplierDispute.detail.retention',
    retentionPaused: 'supplierDispute.detail.retentionPaused',
    invoices: 'supplierDispute.detail.invoices',
    noInvoices: 'supplierDispute.detail.noInvoices',
    rejectedInvoice: 'supplierDispute.detail.rejectedInvoice',
    reports: 'supplierDispute.detail.reports',
    noReports: 'supplierDispute.detail.noReports',
    defects: 'supplierDispute.detail.defects',
    delivered: 'supplierDispute.detail.delivered',
    openEvidence: 'supplierDispute.detail.openEvidence',
    relationshipHeading: 'supplierDispute.detail.relationshipHeading',
    relationshipHint: 'supplierDispute.detail.relationshipHint',
    onTime: 'supplierDispute.detail.onTime',
    quality: 'supplierDispute.detail.quality',
    rated: 'supplierDispute.detail.rated',
    notRated: 'supplierDispute.detail.notRated',
    agreement: 'supplierDispute.detail.agreement',
    tier: 'supplierDispute.detail.tier',
    openOrders: 'supplierDispute.detail.openOrders',
    orderValue: 'supplierDispute.detail.orderValue',
    alternatives: 'supplierDispute.detail.alternatives',
    priorDisputes: 'supplierDispute.detail.priorDisputes',
    priorBody: 'supplierDispute.detail.priorBody',
    otherOpen: 'supplierDispute.detail.otherOpen',
    agreementState: rec('supplierDispute.detail.agreementState', AGREEMENT_STATES),
    retentionStatus: rec('supplierDispute.detail.retentionStatus', RETENTION_STATUSES),
    tierName: rec('supplierDispute.detail.tierName', ['new', 'standard', 'trusted'] as const),
    termType: rec('supplierDispute.detail.termType', ['net', 'milestone', 'advance'] as const),
    invoiceStatus: rec('supplierDispute.detail.invoiceStatus', ['matched', 'awaiting_delivery', 'mismatch', 'rejected'] as const),
    paymentStatus: rec('supplierDispute.detail.paymentStatus', PAYMENT_STATUSES),
    decisionsHeading: 'supplierDispute.detail.decisionsHeading',
    noDecision: 'supplierDispute.detail.noDecision',
    decidedBy: 'supplierDispute.detail.decidedBy',
    correctionLine: 'supplierDispute.detail.correctionLine',
    seeCorrection: 'supplierDispute.detail.seeCorrection',
    reopenNote: 'supplierDispute.detail.reopenNote',
    processHeading: 'supplierDispute.detail.processHeading',
    processHint: 'supplierDispute.detail.processHint',
    processOpen: 'supplierDispute.detail.processOpen',
    processAddressed: 'supplierDispute.detail.processAddressed',
    processBy: 'supplierDispute.detail.processBy',
    processGo: 'supplierDispute.detail.processGo',
    historyHeading: 'supplierDispute.detail.historyHeading',
    by: 'supplierDispute.detail.by',
    messages: 'supplierDispute.detail.messages',
  },
  event: rec('supplierDispute.event', EVENT_KINDS),
  action: {
    decide: 'supplierDispute.action.decide',
    reopen: 'supplierDispute.action.reopen',
    log: 'supplierDispute.action.log',
    flag: 'supplierDispute.action.flag',
    address: 'supplierDispute.action.address',
    close: 'supplierDispute.action.close',
  },
  decide: {
    title: 'supplierDispute.decide.title',
    intro: 'supplierDispute.decide.intro',
    choose: 'supplierDispute.decide.choose',
    amount: 'supplierDispute.decide.amount',
    amountFixed: 'supplierDispute.decide.amountFixed',
    amountHint: 'supplierDispute.decide.amountHint',
    remaining: 'supplierDispute.decide.remaining',
    note: 'supplierDispute.decide.note',
    noteHint: 'supplierDispute.decide.noteHint',
    willDo: 'supplierDispute.decide.willDo',
    upholdWill: 'supplierDispute.decide.upholdWill',
    contextWarn: 'supplierDispute.decide.contextWarn',
    confirm: 'supplierDispute.decide.confirm',
  },
  reopenSheet: { title: 'supplierDispute.reopenSheet.title', intro: 'supplierDispute.reopenSheet.intro', reason: 'supplierDispute.reopenSheet.reason', confirm: 'supplierDispute.reopenSheet.confirm' },
  processSheet: {
    title: 'supplierDispute.processSheet.title',
    intro: 'supplierDispute.processSheet.intro',
    area: 'supplierDispute.processSheet.area',
    note: 'supplierDispute.processSheet.note',
    confirm: 'supplierDispute.processSheet.confirm',
    addressTitle: 'supplierDispute.processSheet.addressTitle',
    addressIntro: 'supplierDispute.processSheet.addressIntro',
    addressNote: 'supplierDispute.processSheet.addressNote',
    addressConfirm: 'supplierDispute.processSheet.addressConfirm',
  },
  raise: {
    title: 'supplierDispute.raise.title',
    intro: 'supplierDispute.raise.intro',
    kind: 'supplierDispute.raise.kind',
    target: 'supplierDispute.raise.target',
    pick: 'supplierDispute.raise.pick',
    none: 'supplierDispute.raise.none',
    position: 'supplierDispute.raise.position',
    positionHint: 'supplierDispute.raise.positionHint',
    claimed: 'supplierDispute.raise.claimed',
    claimedHint: 'supplierDispute.raise.claimedHint',
    halt: 'supplierDispute.raise.halt',
    haltHint: 'supplierDispute.raise.haltHint',
    confirm: 'supplierDispute.raise.confirm',
    payment: 'supplierDispute.raise.payment',
    retention: 'supplierDispute.raise.retention',
    invoice: 'supplierDispute.raise.invoice',
  },
  toast: { decided: 'supplierDispute.toast.decided', reopened: 'supplierDispute.toast.reopened', raised: 'supplierDispute.toast.raised', flagged: 'supplierDispute.toast.flagged', addressed: 'supplierDispute.toast.addressed' },
  problem: {
    forbidden: 'supplierDispute.problem.forbidden',
    not_found: 'supplierDispute.problem.not_found',
    invalid_state: 'supplierDispute.problem.invalid_state',
    note_required: 'supplierDispute.problem.note_required',
    amount_required: 'supplierDispute.problem.amount_required',
    amount_exceeds: 'supplierDispute.problem.amount_exceeds',
    partial_not_allowed: 'supplierDispute.problem.partial_not_allowed',
    partial_needs_less: 'supplierDispute.problem.partial_needs_less',
    nothing_left: 'supplierDispute.problem.nothing_left',
    payment_locked: 'supplierDispute.problem.payment_locked',
    not_actionable: 'supplierDispute.problem.not_actionable',
    position_required: 'supplierDispute.problem.position_required',
    invalid_amount: 'supplierDispute.problem.invalid_amount',
    target_required: 'supplierDispute.problem.target_required',
    already_open: 'supplierDispute.problem.already_open',
    reopen_window_closed: 'supplierDispute.problem.reopen_window_closed',
    generic: 'supplierDispute.problem.generic',
  },
} as const;
