export const POLL_MS = 20_000;
export const LIST_ROUTE = '/workflow-rules';
export const ruleRoute = (id: string): string => `/workflow-rules/${id}`;
export const draftKey = (userId: string, id: string): string => `aiec.workflowDraft.${userId}.${id}`;

export const WORKFLOW_RULES_KEYS = {
  title: 'workflowRules.title',
  subtitle: 'workflowRules.subtitle',
  loading: 'workflowRules.loading',
  error: {
    title: 'workflowRules.error.title',
    body: 'workflowRules.error.body',
  },
  refresh: 'workflowRules.refresh',
  close: 'workflowRules.close',
  back: 'workflowRules.back',
  notFound: 'workflowRules.notFound',
  link: {
    open: 'workflowRules.link.open',
  },
  new: 'workflowRules.new',
  why: {
    title: 'workflowRules.why.title',
    body: 'workflowRules.why.body',
  },
  filter: {
    active: 'workflowRules.filter.active',
    draft: 'workflowRules.filter.draft',
    paused: 'workflowRules.filter.paused',
    retired: 'workflowRules.filter.retired',
    all: 'workflowRules.filter.all',
  },
  empty: {
    title: 'workflowRules.empty.title',
    body: 'workflowRules.empty.body',
    filtered: 'workflowRules.empty.filtered',
  },
  library: {
    title: 'workflowRules.library.title',
  },
  starters: {
    title: 'workflowRules.starters.title',
    use: 'workflowRules.starters.use',
  },
  starter: {
    untouchedHighValue: {
      name: 'workflowRules.starter.untouchedHighValue.name',
      hint: 'workflowRules.starter.untouchedHighValue.hint',
    },
    unassignedLead: {
      name: 'workflowRules.starter.unassignedLead.name',
      hint: 'workflowRules.starter.unassignedLead.hint',
    },
    bigOverdue: {
      name: 'workflowRules.starter.bigOverdue.name',
      hint: 'workflowRules.starter.bigOverdue.hint',
    },
    ticketWaiting: {
      name: 'workflowRules.starter.ticketWaiting.name',
      hint: 'workflowRules.starter.ticketWaiting.hint',
    },
    jobStuck: {
      name: 'workflowRules.starter.jobStuck.name',
      hint: 'workflowRules.starter.jobStuck.hint',
    },
  },
  card: {
    fired: 'workflowRules.card.fired',
    matching: 'workflowRules.card.matching',
    lastActed: 'workflowRules.card.lastActed',
    neverActed: 'workflowRules.card.neverActed',
    open: 'workflowRules.card.open',
    copy: 'workflowRules.card.copy',
    pause: 'workflowRules.card.pause',
    retire: 'workflowRules.card.retire',
    conflict: 'workflowRules.card.conflict',
  },
  status: {
    draft: 'workflowRules.status.draft',
    active: 'workflowRules.status.active',
    paused: 'workflowRules.status.paused',
    retired: 'workflowRules.status.retired',
  },
  builder: {
    new: 'workflowRules.builder.new',
    edit: 'workflowRules.builder.edit',
    about: 'workflowRules.builder.about',
    name: 'workflowRules.builder.name',
    nameHint: 'workflowRules.builder.nameHint',
    watch: 'workflowRules.builder.watch',
    when: 'workflowRules.builder.when',
    whenHint: 'workflowRules.builder.whenHint',
    all: 'workflowRules.builder.all',
    any: 'workflowRules.builder.any',
    addCondition: 'workflowRules.builder.addCondition',
    removeCondition: 'workflowRules.builder.removeCondition',
    field: 'workflowRules.builder.field',
    op: 'workflowRules.builder.op',
    value: 'workflowRules.builder.value',
    then: 'workflowRules.builder.then',
    thenHint: 'workflowRules.builder.thenHint',
    severity: 'workflowRules.builder.severity',
    dueIn: 'workflowRules.builder.dueIn',
    template: 'workflowRules.builder.template',
    templatePick: 'workflowRules.builder.templatePick',
    note: 'workflowRules.builder.note',
    noteHint: 'workflowRules.builder.noteHint',
    summary: 'workflowRules.builder.summary',
    checks: 'workflowRules.builder.checks',
    checksOk: 'workflowRules.builder.checksOk',
    saveDraft: 'workflowRules.builder.saveDraft',
    saved: 'workflowRules.builder.saved',
    activate: 'workflowRules.builder.activate',
    testFirst: 'workflowRules.builder.testFirst',
    saveFirst: 'workflowRules.builder.saveFirst',
    readOnly: 'workflowRules.builder.readOnly',
    retiredNote: 'workflowRules.builder.retiredNote',
  },
  subject: {
    lead: 'workflowRules.subject.lead',
    payment: 'workflowRules.subject.payment',
    job: 'workflowRules.subject.job',
    ticket: 'workflowRules.subject.ticket',
    name: {
      lead: 'workflowRules.subject.name.lead',
      payment: 'workflowRules.subject.name.payment',
      job: 'workflowRules.subject.name.job',
      ticket: 'workflowRules.subject.name.ticket',
    },
    hint: {
      lead: 'workflowRules.subject.hint.lead',
      payment: 'workflowRules.subject.hint.payment',
      job: 'workflowRules.subject.hint.job',
      ticket: 'workflowRules.subject.hint.ticket',
    },
  },
  field: {
    lead: {
      daysUntouched: 'workflowRules.field.lead.daysUntouched',
      daysInStage: 'workflowRules.field.lead.daysInStage',
      stage: 'workflowRules.field.lead.stage',
      value: 'workflowRules.field.lead.value',
      city: 'workflowRules.field.lead.city',
      source: 'workflowRules.field.lead.source',
      score: 'workflowRules.field.lead.score',
      unassigned: 'workflowRules.field.lead.unassigned',
    },
    payment: {
      daysOverdue: 'workflowRules.field.payment.daysOverdue',
      remaining: 'workflowRules.field.payment.remaining',
      status: 'workflowRules.field.payment.status',
      stage: 'workflowRules.field.payment.stage',
    },
    job: {
      status: 'workflowRules.field.job.status',
      daysSinceStart: 'workflowRules.field.job.daysSinceStart',
      daysSinceBooked: 'workflowRules.field.job.daysSinceBooked',
    },
    ticket: {
      ageHours: 'workflowRules.field.ticket.ageHours',
      urgency: 'workflowRules.field.ticket.urgency',
      status: 'workflowRules.field.ticket.status',
      category: 'workflowRules.field.ticket.category',
    },
  },
  unit: {
    days: 'workflowRules.unit.days',
    hours: 'workflowRules.unit.hours',
    points: 'workflowRules.unit.points',
  },
  op: {
    gte: 'workflowRules.op.gte',
    lte: 'workflowRules.op.lte',
    eq: 'workflowRules.op.eq',
    is: 'workflowRules.op.is',
    isNot: 'workflowRules.op.isNot',
    contains: 'workflowRules.op.contains',
  },
  yes: 'workflowRules.yes',
  no: 'workflowRules.no',
  choice: {
    lead: {
      stage: {
        captured: 'workflowRules.choice.lead.stage.captured',
        contacted: 'workflowRules.choice.lead.stage.contacted',
        site_visit: 'workflowRules.choice.lead.stage.site_visit',
        quoted: 'workflowRules.choice.lead.stage.quoted',
        negotiation: 'workflowRules.choice.lead.stage.negotiation',
      },
      source: {
        field_survey: 'workflowRules.choice.lead.source.field_survey',
        referral_repeat: 'workflowRules.choice.lead.source.referral_repeat',
        inbound_website: 'workflowRules.choice.lead.source.inbound_website',
        inbound_whatsapp: 'workflowRules.choice.lead.source.inbound_whatsapp',
        bulk_import: 'workflowRules.choice.lead.source.bulk_import',
      },
    },
    payment: {
      status: {
        due: 'workflowRules.choice.payment.status.due',
        pending: 'workflowRules.choice.payment.status.pending',
        overdue: 'workflowRules.choice.payment.status.overdue',
        failed: 'workflowRules.choice.payment.status.failed',
      },
      stage: {
        advance: 'workflowRules.choice.payment.stage.advance',
        material: 'workflowRules.choice.payment.stage.material',
        installation: 'workflowRules.choice.payment.stage.installation',
        handover: 'workflowRules.choice.payment.stage.handover',
        retention: 'workflowRules.choice.payment.stage.retention',
      },
    },
    job: {
      status: {
        scheduled: 'workflowRules.choice.job.status.scheduled',
        materials_pending: 'workflowRules.choice.job.status.materials_pending',
        in_progress: 'workflowRules.choice.job.status.in_progress',
        qc_pending: 'workflowRules.choice.job.status.qc_pending',
        handover_pending: 'workflowRules.choice.job.status.handover_pending',
        on_hold: 'workflowRules.choice.job.status.on_hold',
      },
    },
    ticket: {
      urgency: {
        emergency: 'workflowRules.choice.ticket.urgency.emergency',
        high: 'workflowRules.choice.ticket.urgency.high',
        normal: 'workflowRules.choice.ticket.urgency.normal',
        low: 'workflowRules.choice.ticket.urgency.low',
      },
      status: {
        submitted: 'workflowRules.choice.ticket.status.submitted',
        assigned: 'workflowRules.choice.ticket.status.assigned',
        in_progress: 'workflowRules.choice.ticket.status.in_progress',
      },
      category: {
        emergency: 'workflowRules.choice.ticket.category.emergency',
        safety: 'workflowRules.choice.ticket.category.safety',
        fault: 'workflowRules.choice.ticket.category.fault',
        billing: 'workflowRules.choice.ticket.category.billing',
        general: 'workflowRules.choice.ticket.category.general',
        maintenance: 'workflowRules.choice.ticket.category.maintenance',
      },
    },
  },
  action: {
    alert: 'workflowRules.action.alert',
    alertHint: 'workflowRules.action.alertHint',
    task: 'workflowRules.action.task',
    taskHint: 'workflowRules.action.taskHint',
    message: 'workflowRules.action.message',
    messageHint: 'workflowRules.action.messageHint',
  },
  severity: {
    low: 'workflowRules.severity.low',
    medium: 'workflowRules.severity.medium',
    high: 'workflowRules.severity.high',
  },
  summary: {
    watch: 'workflowRules.summary.watch',
    when: 'workflowRules.summary.when',
    and: 'workflowRules.summary.and',
    or: 'workflowRules.summary.or',
    thenWord: 'workflowRules.summary.thenWord',
    condition: 'workflowRules.summary.condition',
    empty: 'workflowRules.summary.empty',
    then: {
      alert: 'workflowRules.summary.then.alert',
      task: 'workflowRules.summary.then.task',
      message: 'workflowRules.summary.then.message',
    },
    once: 'workflowRules.summary.once',
  },
  check: {
    name_required: 'workflowRules.check.name_required',
    conditions_required: 'workflowRules.check.conditions_required',
    too_many_conditions: 'workflowRules.check.too_many_conditions',
    condition_incomplete: 'workflowRules.check.condition_incomplete',
    value_invalid: 'workflowRules.check.value_invalid',
    duplicate_condition: 'workflowRules.check.duplicate_condition',
    never_matches: 'workflowRules.check.never_matches',
    task_days_invalid: 'workflowRules.check.task_days_invalid',
    template_required: 'workflowRules.check.template_required',
    note_long: 'workflowRules.check.note_long',
    severity_required: 'workflowRules.check.severity_required',
  },
  complexity: {
    busy: 'workflowRules.complexity.busy',
    complex: 'workflowRules.complexity.complex',
  },
  conflict: {
    specialised: {
      paymentReminders: 'workflowRules.conflict.specialised.paymentReminders',
      sequences: 'workflowRules.conflict.specialised.sequences',
      followUps: 'workflowRules.conflict.specialised.followUps',
      ticketNotices: 'workflowRules.conflict.specialised.ticketNotices',
    },
    duplicate: 'workflowRules.conflict.duplicate',
    open: 'workflowRules.conflict.open',
  },
  test: {
    title: 'workflowRules.test.title',
    intro: 'workflowRules.test.intro',
    real: 'workflowRules.test.real',
    sampleTab: 'workflowRules.test.sampleTab',
    run: 'workflowRules.test.run',
    result: 'workflowRules.test.result',
    noMatch: 'workflowRules.test.noMatch',
    sampleList: 'workflowRules.test.sampleList',
    sampleFill: 'workflowRules.test.sampleFill',
    sample: {
      yes: 'workflowRules.test.sample.yes',
      no: 'workflowRules.test.sample.no',
      missed: 'workflowRules.test.sample.missed',
    },
    current: 'workflowRules.test.current',
    stale: 'workflowRules.test.stale',
  },
  activate: {
    title: 'workflowRules.activate.title',
    body: 'workflowRules.activate.body',
    fromNow: 'workflowRules.activate.fromNow',
    fromNowHint: 'workflowRules.activate.fromNowHint',
    now: 'workflowRules.activate.now',
    nowHint: 'workflowRules.activate.nowHint',
    many: 'workflowRules.activate.many',
    ack: 'workflowRules.activate.ack',
    confirm: 'workflowRules.activate.confirm',
    cancel: 'workflowRules.activate.cancel',
    done: 'workflowRules.activate.done',
  },
  retire: {
    title: 'workflowRules.retire.title',
    body: 'workflowRules.retire.body',
    reason: 'workflowRules.retire.reason',
    confirm: 'workflowRules.retire.confirm',
  },
  history: {
    title: 'workflowRules.history.title',
    line: 'workflowRules.history.line',
    kind: {
      created: 'workflowRules.history.kind.created',
      edited: 'workflowRules.history.kind.edited',
      simulated: 'workflowRules.history.kind.simulated',
      activated: 'workflowRules.history.kind.activated',
      paused: 'workflowRules.history.kind.paused',
      resumed: 'workflowRules.history.kind.resumed',
      retired: 'workflowRules.history.kind.retired',
      copied: 'workflowRules.history.kind.copied',
      capped: 'workflowRules.history.kind.capped',
    },
  },
  firings: {
    title: 'workflowRules.firings.title',
    empty: 'workflowRules.firings.empty',
  },
  draft: {
    restored: 'workflowRules.draft.restored',
  },
  notice: {
    placeholders: 'workflowRules.notice.placeholders',
  },
  alert: {
    fired: 'workflowRules.alert.fired',
    capped: 'workflowRules.alert.capped',
  },
  problem: {
    forbidden: 'workflowRules.problem.forbidden',
    not_found: 'workflowRules.problem.not_found',
    rule_retired: 'workflowRules.problem.rule_retired',
    rule_active: 'workflowRules.problem.rule_active',
    already_active: 'workflowRules.problem.already_active',
    not_active: 'workflowRules.problem.not_active',
    not_simulated: 'workflowRules.problem.not_simulated',
    conflicts_unacknowledged: 'workflowRules.problem.conflicts_unacknowledged',
    many_unconfirmed: 'workflowRules.problem.many_unconfirmed',
    reason_short: 'workflowRules.problem.reason_short',
    generic: 'workflowRules.problem.generic',
  },
} as const;
