/** Screen 186 — System Health & Bot Monitoring. Types and keys only. */
export const POLL_MS = 20_000;
export const BOT_ROUTE = '/admin/comm/bot';

export const SYSTEM_HEALTH_KEYS = {
  title: 'systemHealth.title',
  subtitle: 'systemHealth.subtitle',
  loading: 'systemHealth.loading',
  offline: 'systemHealth.offline',
  refresh: 'systemHealth.refresh',
  close: 'systemHealth.close',
  error: {
    title: 'systemHealth.error.title',
    body: 'systemHealth.error.body',
    retry: 'systemHealth.error.retry',
    generic: 'systemHealth.error.generic',
    forbidden: 'systemHealth.error.forbidden',
    invalid_url: 'systemHealth.error.invalid_url',
    reason_required: 'systemHealth.error.reason_required',
    not_probed: 'systemHealth.error.not_probed',
    invalid_state: 'systemHealth.error.invalid_state',
    not_found: 'systemHealth.error.not_found',
  },
  summary: {
    operational: 'systemHealth.summary.operational',
    degraded: 'systemHealth.summary.degraded',
    down: 'systemHealth.summary.down',
    followUps: 'systemHealth.summary.followUps',
  },
  status: {
    operational: 'systemHealth.status.operational',
    degraded: 'systemHealth.status.degraded',
    down: 'systemHealth.status.down',
    unknown: 'systemHealth.status.unknown',
  },
  shared: {
    title: 'systemHealth.shared.title',
    ours: 'systemHealth.shared.ours',
    mixed: 'systemHealth.shared.mixed',
  },
  followUp: {
    title: 'systemHealth.followUp.title',
    messages: 'systemHealth.followUp.messages',
    payouts: 'systemHealth.followUp.payouts',
    statements: 'systemHealth.followUp.statements',
    open: 'systemHealth.followUp.open',
    done: 'systemHealth.followUp.done',
    note: 'systemHealth.followUp.note',
    noteHint: 'systemHealth.followUp.noteHint',
    closed: 'systemHealth.followUp.closed',
  },
  integrations: {
    title: 'systemHealth.integrations.title',
    hint: 'systemHealth.integrations.hint',
  },
  integration: {
    payment_gateway: 'systemHealth.integration.payment_gateway',
    whatsapp: 'systemHealth.integration.whatsapp',
    sms: 'systemHealth.integration.sms',
    maps: 'systemHealth.integration.maps',
    financing_partner: 'systemHealth.integration.financing_partner',
    bank_feed: 'systemHealth.integration.bank_feed',
    payout_rail: 'systemHealth.integration.payout_rail',
    id_verification: 'systemHealth.integration.id_verification',
    carrier_tracking: 'systemHealth.integration.carrier_tracking',
    engine: 'systemHealth.integration.engine',
  },
  card: {
    byOurs: 'systemHealth.card.byOurs',
    rate: 'systemHealth.card.rate',
    noCalls: 'systemHealth.card.noCalls',
    uptime: 'systemHealth.card.uptime',
    lastCheck: 'systemHealth.card.lastCheck',
    neverChecked: 'systemHealth.card.neverChecked',
    lastIncident: 'systemHealth.card.lastIncident',
    noIncident: 'systemHealth.card.noIncident',
    check: 'systemHealth.card.check',
    record: 'systemHealth.card.record',
    openScreen: 'systemHealth.card.openScreen',
    statusPage: 'systemHealth.card.statusPage',
    statusPageSet: 'systemHealth.card.statusPageSet',
    providerSays: 'systemHealth.card.providerSays',
    providerRecorded: 'systemHealth.card.providerRecorded',
    providerNone: 'systemHealth.card.providerNone',
  },
  agreement: {
    provider_better: 'systemHealth.agreement.provider_better',
    provider_worse: 'systemHealth.agreement.provider_worse',
  },
  cause: {
    third_party: 'systemHealth.cause.third_party',
    ours: 'systemHealth.cause.ours',
    unknown: 'systemHealth.cause.unknown',
  },
  demo: {
    title: 'systemHealth.demo.title',
    hint: 'systemHealth.demo.hint',
    working: 'systemHealth.demo.working',
    degraded: 'systemHealth.demo.degraded',
    failing: 'systemHealth.demo.failing',
  },
  record: {
    title: 'systemHealth.record.title',
    hint: 'systemHealth.record.hint',
    note: 'systemHealth.record.note',
    save: 'systemHealth.record.save',
    url: 'systemHealth.record.url',
    urlHint: 'systemHealth.record.urlHint',
    saveUrl: 'systemHealth.record.saveUrl',
  },
  engine: {
    title: 'systemHealth.engine.title',
    beat: 'systemHealth.engine.beat',
    gap: 'systemHealth.engine.gap',
    steps: 'systemHealth.engine.steps',
    failing: 'systemHealth.engine.failing',
    none: 'systemHealth.engine.none',
    note: 'systemHealth.engine.note',
  },
  bot: {
    title: 'systemHealth.bot.title',
    hint: 'systemHealth.bot.hint',
    replies: 'systemHealth.bot.replies',
    handoffs: 'systemHealth.bot.handoffs',
    rate: 'systemHealth.bot.rate',
    rateValue: 'systemHealth.bot.rateValue',
    rateNone: 'systemHealth.bot.rateNone',
    drift: 'systemHealth.bot.drift',
    failed: 'systemHealth.bot.failed',
    threshold: 'systemHealth.bot.threshold',
    open: 'systemHealth.bot.open',
  },
  incidents: {
    title: 'systemHealth.incidents.title',
    empty: 'systemHealth.incidents.empty',
    emptyBody: 'systemHealth.incidents.emptyBody',
    open: 'systemHealth.incidents.open',
    recovered: 'systemHealth.incidents.recovered',
    line: 'systemHealth.incidents.line',
    cause: {
      third_party: 'systemHealth.incidents.cause.third_party',
      ours: 'systemHealth.incidents.cause.ours',
      unknown: 'systemHealth.incidents.cause.unknown',
    },
    lineEnded: 'systemHealth.incidents.lineEnded',
    peak: 'systemHealth.incidents.peak',
    notSeen: 'systemHealth.incidents.notSeen',
    followUpOwed: 'systemHealth.incidents.followUpOwed',
    followUpDone: 'systemHealth.incidents.followUpDone',
  },
  note: {
    placeholders: 'systemHealth.note.placeholders',
  },
  alert: {
    down: 'systemHealth.alert.down',
    degraded: 'systemHealth.alert.degraded',
    shared: 'systemHealth.alert.shared',
  },
  link: {
    open: 'systemHealth.link.open',
  },
} as const;
