export const POLL_MS = 20_000;
export const TEMPLATES_ROUTE = '/admin/comm/templates';

export const INTERNAL_NOTIFICATIONS_KEYS = {
  title: 'internalNotifications.title',
  subtitle: 'internalNotifications.subtitle',
  loading: 'internalNotifications.loading',
  error: {
    title: 'internalNotifications.error.title',
    body: 'internalNotifications.error.body',
    reduction_unconfirmed: 'internalNotifications.error.reduction_unconfirmed',
    content_too_long: 'internalNotifications.error.content_too_long',
    invalid_channels: 'internalNotifications.error.invalid_channels',
    forbidden: 'internalNotifications.error.forbidden',
    generic: 'internalNotifications.error.generic',
  },
  refresh: 'internalNotifications.refresh',
  close: 'internalNotifications.close',
  link: {
    open: 'internalNotifications.link.open',
  },
  apart: {
    title: 'internalNotifications.apart.title',
    body: 'internalNotifications.apart.body',
    open: 'internalNotifications.apart.open',
  },
  demo: {
    note: 'internalNotifications.demo.note',
  },
  stat: {
    types: 'internalNotifications.stat.types',
    critical: 'internalNotifications.stat.critical',
    sent: 'internalNotifications.stat.sent',
    noisy: 'internalNotifications.stat.noisy',
  },
  urgency: {
    critical: 'internalNotifications.urgency.critical',
    high: 'internalNotifications.urgency.high',
    routine: 'internalNotifications.urgency.routine',
    hint: {
      critical: 'internalNotifications.urgency.hint.critical',
      high: 'internalNotifications.urgency.hint.high',
      routine: 'internalNotifications.urgency.hint.routine',
    },
    fromSeverity: 'internalNotifications.urgency.fromSeverity',
  },
  channel: {
    inApp: 'internalNotifications.channel.inApp',
    sms: 'internalNotifications.channel.sms',
    email: 'internalNotifications.channel.email',
    always: 'internalNotifications.channel.always',
  },
  defaults: {
    title: 'internalNotifications.defaults.title',
    body: 'internalNotifications.defaults.body',
    current: 'internalNotifications.defaults.current',
    save: 'internalNotifications.defaults.save',
    saved: 'internalNotifications.defaults.saved',
  },
  types: {
    title: 'internalNotifications.types.title',
    search: 'internalNotifications.types.search',
    empty: 'internalNotifications.types.empty',
    custom: 'internalNotifications.types.custom',
    noisy: 'internalNotifications.types.noisy',
    off: 'internalNotifications.types.off',
    frequency: 'internalNotifications.types.frequency',
    never: 'internalNotifications.types.never',
    goesTo: 'internalNotifications.types.goesTo',
    goesNowhere: 'internalNotifications.types.goesNowhere',
  },
  role: {
    admin: 'internalNotifications.role.admin',
    technician: 'internalNotifications.role.technician',
    surveyor: 'internalNotifications.role.surveyor',
    new: 'internalNotifications.role.new',
  },
  detail: {
    urgency: 'internalNotifications.detail.urgency',
    urgencyNow: 'internalNotifications.detail.urgencyNow',
    enabled: 'internalNotifications.detail.enabled',
    enabledHint: 'internalNotifications.detail.enabledHint',
    roles: 'internalNotifications.detail.roles',
    rolesHint: 'internalNotifications.detail.rolesHint',
    wording: 'internalNotifications.detail.wording',
    wordingHint: 'internalNotifications.detail.wordingHint',
    subject: 'internalNotifications.detail.subject',
    body: 'internalNotifications.detail.body',
    standard: 'internalNotifications.detail.standard',
    preview: 'internalNotifications.detail.preview',
    length: 'internalNotifications.detail.length',
    unicode: 'internalNotifications.detail.unicode',
    test: 'internalNotifications.detail.test',
    testHint: 'internalNotifications.detail.testHint',
    testSent: 'internalNotifications.detail.testSent',
    testRejected: 'internalNotifications.detail.testRejected',
    frequency: 'internalNotifications.detail.frequency',
    frequencyLine: 'internalNotifications.detail.frequencyLine',
    last: 'internalNotifications.detail.last',
    fatigue: 'internalNotifications.detail.fatigue',
    history: 'internalNotifications.detail.history',
    historyLine: 'internalNotifications.detail.historyLine',
    save: 'internalNotifications.detail.save',
    saved: 'internalNotifications.detail.saved',
    revert: 'internalNotifications.detail.revert',
  },
  confirm: {
    title: 'internalNotifications.confirm.title',
    body: 'internalNotifications.confirm.body',
    check: 'internalNotifications.confirm.check',
    yes: 'internalNotifications.confirm.yes',
    no: 'internalNotifications.confirm.no',
  },
  log: {
    title: 'internalNotifications.log.title',
    empty: 'internalNotifications.log.empty',
    line: 'internalNotifications.log.line',
    test: 'internalNotifications.log.test',
    sent: 'internalNotifications.log.sent',
    rejected: 'internalNotifications.log.rejected',
  },
  problem: {
    sms_too_long: 'internalNotifications.problem.sms_too_long',
    sms_multipart: 'internalNotifications.problem.sms_multipart',
    email_subject_long: 'internalNotifications.problem.email_subject_long',
    in_app_title_long: 'internalNotifications.problem.in_app_title_long',
    body_empty: 'internalNotifications.problem.body_empty',
  },
  notice: {
    placeholders: 'internalNotifications.notice.placeholders',
  },
} as const;
