/** Screen 134 — Compliance Certification. Types and translation keys only. */

import type { ComplianceStandardId } from '@/data/types';
import { STANDARD_IDS } from '@/features/qc/compliance';

export type ComplianceStatus = 'loading' | 'ready' | 'error' | 'not_found';
export const POLL_MS = 20_000;
export const TABS = ['certificate', 'package', 'next', 'history'] as const;
export type ComplianceTab = (typeof TABS)[number];

export const FINAL_ERRORS = [
  'standard_required', 'standard_label_required', 'override_reason_required', 'additional_reason_required', 'duplicate_standard', 'too_many_additional', 'unknown_standard',
  'reason_required', 'authority_required', 'steps_required', 'no_state', 'not_ready', 'already_issued', 'not_issued', 'no_spec', 'forbidden', 'not_found',
] as const;

const rec = <T extends string>(ns: string, keys: readonly T[]) => Object.fromEntries(keys.map((k) => [k, `${ns}.${k}`])) as Record<T, string>;
export const boardPath = '/qc-assignments';
export const assignmentPath = (id: string) => `/qc-assignments/${id}`;
export const STANDARDS: ComplianceStandardId[] = STANDARD_IDS;
export const ADDITIONAL_CHOICES: ComplianceStandardId[] = ['IS_14671', 'other'];

export const COMPLIANCE_KEYS = {
  title: 'compliance.title',
  loading: 'compliance.loading',
  back: 'compliance.back',
  more: 'compliance.more',
  offline: 'compliance.offline',
  error: { title: 'compliance.error.title', body: 'compliance.error.body' },
  noJob: { title: 'compliance.noJob.title', body: 'compliance.noJob.body', action: 'compliance.noJob.action' },
  notFound: { title: 'compliance.notFound.title', body: 'compliance.notFound.body', action: 'compliance.notFound.action' },
  problem: rec('compliance.problem', [...FINAL_ERRORS, 'offline', 'generic'] as const),
  status: rec('compliance.status', ['issued', 'issuedHistoric', 'ready', 'waiting', 'before'] as const),
  stat: { standard: 'compliance.stat.standard', standardNone: 'compliance.stat.standardNone', checks: 'compliance.stat.checks', checksValue: 'compliance.stat.checksValue', issued: 'compliance.stat.issued', notIssued: 'compliance.stat.notIssued', version: 'compliance.stat.version' },
  disclaimer: { title: 'compliance.disclaimer.title', body: 'compliance.disclaimer.body' },
  tab: rec('compliance.tab', TABS),
  standard: rec('compliance.standard', STANDARDS),
  standardDesc: rec('compliance.standardDesc', ['IS_14665', 'IS_15259', 'IS_14671'] as const),
  basis: { drive_type: 'compliance.basis.drive_type', selected: 'compliance.basis.selected' },
  ready: {
    heading: 'compliance.ready.heading',
    mechanical: 'compliance.ready.mechanical',
    electrical: 'compliance.ready.electrical',
    rework: 'compliance.ready.rework',
    reworkNone: 'compliance.ready.reworkNone',
    spec: 'compliance.ready.spec',
    before: 'compliance.ready.before',
    allGood: 'compliance.ready.allGood',
    open: 'compliance.ready.open',
    openQc: 'compliance.ready.openQc',
  },
  form: {
    heading: 'compliance.form.heading',
    auto: 'compliance.form.auto',
    none: 'compliance.form.none',
    change: 'compliance.form.change',
    useAuto: 'compliance.form.useAuto',
    primary: 'compliance.form.primary',
    otherLabel: 'compliance.form.otherLabel',
    otherHint: 'compliance.form.otherHint',
    overrideReason: 'compliance.form.overrideReason',
    overrideHint: 'compliance.form.overrideHint',
    additionalHeading: 'compliance.form.additionalHeading',
    additionalHint: 'compliance.form.additionalHint',
    add: 'compliance.form.add',
    remove: 'compliance.form.remove',
    reason: 'compliance.form.reason',
    reasonHint: 'compliance.form.reasonHint',
    ok: 'compliance.form.ok',
  },
  issue: { button: 'compliance.issue.button', title: 'compliance.issue.title', body: 'compliance.issue.body', go: 'compliance.issue.go', back: 'compliance.issue.back', toast: 'compliance.issue.toast', waiting: 'compliance.issue.waiting', adminOnly: 'compliance.issue.adminOnly' },
  cert: {
    heading: 'compliance.cert.heading',
    code: 'compliance.cert.code',
    job: 'compliance.cert.job',
    quotation: 'compliance.cert.quotation',
    drive: 'compliance.cert.drive',
    checkedAgainst: 'compliance.cert.checkedAgainst',
    primary: 'compliance.cert.primary',
    additional: 'compliance.cert.additional',
    because: 'compliance.cert.because',
    issuedBy: 'compliance.cert.issuedBy',
    locked: 'compliance.cert.locked',
    voided: 'compliance.cert.voided',
    voidedBody: 'compliance.cert.voidedBody',
    supersedes: 'compliance.cert.supersedes',
    historic: 'compliance.cert.historic',
    download: 'compliance.cert.download',
    fileTitle: 'compliance.cert.fileTitle',
    statement: 'compliance.cert.statement',
    state: 'compliance.cert.state',
    stateNone: 'compliance.cert.stateNone',
  },
  pkg: {
    heading: 'compliance.pkg.heading',
    live: 'compliance.pkg.live',
    frozen: 'compliance.pkg.frozen',
    historic: 'compliance.pkg.historic',
    installation: 'compliance.pkg.installation',
    installationValue: 'compliance.pkg.installationValue',
    team: 'compliance.pkg.team',
    mechanical: 'compliance.pkg.mechanical',
    electrical: 'compliance.pkg.electrical',
    trials: 'compliance.pkg.trials',
    safety: 'compliance.pkg.safety',
    parts: 'compliance.pkg.parts',
    signedOff: 'compliance.pkg.signedOff',
    notSigned: 'compliance.pkg.notSigned',
    attempts: 'compliance.pkg.attempts',
    trialLine: 'compliance.pkg.trialLine',
    trialLineNoLoad: 'compliance.pkg.trialLineNoLoad',
    trialNone: 'compliance.pkg.trialNone',
    noParts: 'compliance.pkg.noParts',
    partLine: 'compliance.pkg.partLine',
    substituted: 'compliance.pkg.substituted',
    partsConfirmed: 'compliance.pkg.partsConfirmed',
    safetyReady: 'compliance.pkg.safetyReady',
    safetyOpen: 'compliance.pkg.safetyOpen',
    overridden: 'compliance.pkg.overridden',
    safetyState: rec('compliance.pkg.safetyState', ['not_tested', 'passed', 'failed', 'retest_due', 'held', 'in_review', 'overridden'] as const),
    itemState: rec('compliance.pkg.itemState', ['not_checked', 'pass', 'fail', 'exception_pending', 'exception_accepted'] as const),
  },
  next: {
    heading: 'compliance.next.heading',
    intro: 'compliance.next.intro',
    baselineHeading: 'compliance.next.baselineHeading',
    b1: 'compliance.next.b1',
    b2: 'compliance.next.b2',
    b3: 'compliance.next.b3',
    stateHeading: 'compliance.next.stateHeading',
    authority: 'compliance.next.authority',
    steps: 'compliance.next.steps',
    noneForState: 'compliance.next.noneForState',
    noState: 'compliance.next.noState',
    changed: 'compliance.next.changed',
    updated: 'compliance.next.updated',
    edit: 'compliance.next.edit',
    editTitle: 'compliance.next.editTitle',
    authorityLabel: 'compliance.next.authorityLabel',
    stepsLabel: 'compliance.next.stepsLabel',
    stepsHint: 'compliance.next.stepsHint',
    noteLabel: 'compliance.next.noteLabel',
    save: 'compliance.next.save',
    saved: 'compliance.next.saved',
    example: 'compliance.next.example',
  },
  history: { heading: 'compliance.history.heading', none: 'compliance.history.none', current: 'compliance.history.current', voided: 'compliance.history.voided', voids: 'compliance.history.voids', view: 'compliance.history.view', viewTitle: 'compliance.history.viewTitle' },
  reissue: { open: 'compliance.reissue.open', title: 'compliance.reissue.title', intro: 'compliance.reissue.intro', reason: 'compliance.reissue.reason', reasonHint: 'compliance.reissue.reasonHint', go: 'compliance.reissue.go', toast: 'compliance.reissue.toast', keeps: 'compliance.reissue.keeps' },
  inspector: { readOnly: 'compliance.inspector.readOnly' },
  cancel: 'compliance.cancel',
} as const;
