import { ATTENTION_DUE, FAILURES, NOTE_MIN, PAGE, SETTLE_MS, UPI_LIMIT, csvCell, needsDetails } from '@/features/commission/disbursement';
import type { DisbursementKind, DisbursementMethod, DisbursementStatus, FailureReason } from '@/features/commission/disbursement';

export { ATTENTION_DUE, FAILURES, NOTE_MIN, PAGE, SETTLE_MS, UPI_LIMIT, csvCell, needsDetails };
export type { DisbursementKind, DisbursementMethod, DisbursementStatus, FailureReason };
export const PULL_DISTANCE = 70;
export const STATES = ['attention', 'processing', 'completed', 'failed', 'cancelled'] as const;
export type StateFilter = (typeof STATES)[number] | 'all';
export const CHANNELS = ['call', 'whatsapp', 'message'] as const;
export type Channel = (typeof CHANNELS)[number];
export const payoutDisbursementPath = (q: Record<string, string>) => { const p = new URLSearchParams(q).toString(); return p ? `/payout-disbursement?${p}` : '/payout-disbursement'; };

export const DISBURSEMENT_KEYS = {
  title: 'payoutDisbursement.title',
  subtitle: 'payoutDisbursement.subtitle',
  loading: 'payoutDisbursement.loading',
  error: {
    title: 'payoutDisbursement.error.title',
    body: 'payoutDisbursement.error.body',
  },
  refresh: {
    button: 'payoutDisbursement.refresh.button',
    pull: 'payoutDisbursement.refresh.pull',
    release: 'payoutDisbursement.refresh.release',
    busy: 'payoutDisbursement.refresh.busy',
  },
  close: 'payoutDisbursement.close',
  cancel: 'payoutDisbursement.cancel',
  back: 'payoutDisbursement.back',
  kpi: {
    ready: {
      label: 'payoutDisbursement.kpi.ready.label',
      caption: 'payoutDisbursement.kpi.ready.caption',
      none: 'payoutDisbursement.kpi.ready.none',
      urgent: 'payoutDisbursement.kpi.ready.urgent',
    },
    inFlight: {
      label: 'payoutDisbursement.kpi.inFlight.label',
      caption: 'payoutDisbursement.kpi.inFlight.caption',
      none: 'payoutDisbursement.kpi.inFlight.none',
    },
    failed: {
      label: 'payoutDisbursement.kpi.failed.label',
      caption: 'payoutDisbursement.kpi.failed.caption',
      none: 'payoutDisbursement.kpi.failed.none',
    },
    completed: {
      label: 'payoutDisbursement.kpi.completed.label',
      caption: 'payoutDisbursement.kpi.completed.caption',
      none: 'payoutDisbursement.kpi.completed.none',
    },
  },
  next: {
    heading: 'payoutDisbursement.next.heading',
    when: 'payoutDisbursement.next.when',
    off: 'payoutDisbursement.next.off',
    last: 'payoutDisbursement.next.last',
    consolidated: 'payoutDisbursement.next.consolidated',
    separate: 'payoutDisbursement.next.separate',
    runNow: 'payoutDisbursement.next.runNow',
    change: 'payoutDisbursement.next.change',
  },
  schedule: {
    title: 'payoutDisbursement.schedule.title',
    enabled: 'payoutDisbursement.schedule.enabled',
    enabledHint: 'payoutDisbursement.schedule.enabledHint',
    weekday: 'payoutDisbursement.schedule.weekday',
    hour: 'payoutDisbursement.schedule.hour',
    consolidate: 'payoutDisbursement.schedule.consolidate',
    consolidateHint: 'payoutDisbursement.schedule.consolidateHint',
    save: 'payoutDisbursement.schedule.save',
    saved: 'payoutDisbursement.schedule.saved',
  },
  run: {
    title: 'payoutDisbursement.run.title',
    body: 'payoutDisbursement.run.body',
    confirm: 'payoutDisbursement.run.confirm',
    started: 'payoutDisbursement.run.started',
    nothing: 'payoutDisbursement.run.nothing',
  },
  rail: {
    heading: 'payoutDisbursement.rail.heading',
    connected: 'payoutDisbursement.rail.connected',
    unavailable: 'payoutDisbursement.rail.unavailable',
    demo: 'payoutDisbursement.rail.demo',
    simulateOutage: 'payoutDisbursement.rail.simulateOutage',
    interrupt: 'payoutDisbursement.rail.interrupt',
    interruptHint: 'payoutDisbursement.rail.interruptHint',
    save: 'payoutDisbursement.rail.save',
    saved: 'payoutDisbursement.rail.saved',
  },
  ready: {
    heading: 'payoutDisbursement.ready.heading',
    body: 'payoutDisbursement.ready.body',
    empty: 'payoutDisbursement.ready.empty',
    entries: 'payoutDisbursement.ready.entries',
    urgent: 'payoutDisbursement.ready.urgent',
    sendNow: 'payoutDisbursement.ready.sendNow',
    blocked: {
      no_details: 'payoutDisbursement.ready.blocked.no_details',
      failed_open: 'payoutDisbursement.ready.blocked.failed_open',
    },
    addDetails: 'payoutDisbursement.ready.addDetails',
    openFailed: 'payoutDisbursement.ready.openFailed',
    sendTitle: 'payoutDisbursement.ready.sendTitle',
    sendBody: 'payoutDisbursement.ready.sendBody',
    sendConfirm: 'payoutDisbursement.ready.sendConfirm',
    sent: 'payoutDisbursement.ready.sent',
    openApproval: 'payoutDisbursement.ready.openApproval',
  },
  runs: {
    heading: 'payoutDisbursement.runs.heading',
    body: 'payoutDisbursement.runs.body',
    empty: 'payoutDisbursement.runs.empty',
    kind: {
      weekly: 'payoutDisbursement.runs.kind.weekly',
      manual: 'payoutDisbursement.runs.kind.manual',
    },
    status: {
      running: 'payoutDisbursement.runs.status.running',
      completed: 'payoutDisbursement.runs.status.completed',
      interrupted: 'payoutDisbursement.runs.status.interrupted',
    },
    breakdown: 'payoutDisbursement.runs.breakdown',
    amounts: 'payoutDisbursement.runs.amounts',
    skippedHeading: 'payoutDisbursement.runs.skippedHeading',
    skipReason: {
      no_details: 'payoutDisbursement.runs.skipReason.no_details',
      failed_open: 'payoutDisbursement.runs.skipReason.failed_open',
    },
    interrupted: {
      rail: 'payoutDisbursement.runs.interrupted.rail',
      bank_unavailable: 'payoutDisbursement.runs.interrupted.bank_unavailable',
    },
    retryAll: 'payoutDisbursement.runs.retryAll',
    retried: 'payoutDisbursement.runs.retried',
    retrySkipped: 'payoutDisbursement.runs.retrySkipped',
  },
  state: {
    attention: 'payoutDisbursement.state.attention',
    processing: 'payoutDisbursement.state.processing',
    completed: 'payoutDisbursement.state.completed',
    failed: 'payoutDisbursement.state.failed',
    cancelled: 'payoutDisbursement.state.cancelled',
    all: 'payoutDisbursement.state.all',
  },
  search: 'payoutDisbursement.search',
  list: {
    heading: 'payoutDisbursement.list.heading',
    count: 'payoutDisbursement.list.count',
    empty: {
      title: 'payoutDisbursement.list.empty.title',
      body: 'payoutDisbursement.list.empty.body',
    },
    noMatch: 'payoutDisbursement.list.noMatch',
    noMatchBody: 'payoutDisbursement.list.noMatchBody',
    clear: 'payoutDisbursement.list.clear',
    showMore: 'payoutDisbursement.list.showMore',
    export: 'payoutDisbursement.list.export',
    exported: 'payoutDisbursement.list.exported',
  },
  status: {
    initiated: 'payoutDisbursement.status.initiated',
    processing: 'payoutDisbursement.status.processing',
    completed: 'payoutDisbursement.status.completed',
    failed: 'payoutDisbursement.status.failed',
    cancelled: 'payoutDisbursement.status.cancelled',
  },
  method: {
    bank_transfer: 'payoutDisbursement.method.bank_transfer',
    upi: 'payoutDisbursement.method.upi',
  },
  kind: {
    scheduled: 'payoutDisbursement.kind.scheduled',
    urgent: 'payoutDisbursement.kind.urgent',
    retry: 'payoutDisbursement.kind.retry',
  },
  role: {
    surveyor: 'payoutDisbursement.role.surveyor',
    technician: 'payoutDisbursement.role.technician',
    supplier: 'payoutDisbursement.role.supplier',
    other: 'payoutDisbursement.role.other',
  },
  row: {
    entries: 'payoutDisbursement.row.entries',
    out: 'payoutDisbursement.row.out',
    retryOf: 'payoutDisbursement.row.retryOf',
    continued: 'payoutDisbursement.row.continued',
    needsDetails: 'payoutDisbursement.row.needsDetails',
  },
  failure: {
    invalid_account: 'payoutDisbursement.failure.invalid_account',
    account_closed: 'payoutDisbursement.failure.account_closed',
    bank_rejected: 'payoutDisbursement.failure.bank_rejected',
    upi_invalid: 'payoutDisbursement.failure.upi_invalid',
    limit_exceeded: 'payoutDisbursement.failure.limit_exceeded',
    bank_unavailable: 'payoutDisbursement.failure.bank_unavailable',
    interrupted: 'payoutDisbursement.failure.interrupted',
    hint: {
      invalid_account: 'payoutDisbursement.failure.hint.invalid_account',
      account_closed: 'payoutDisbursement.failure.hint.account_closed',
      bank_rejected: 'payoutDisbursement.failure.hint.bank_rejected',
      upi_invalid: 'payoutDisbursement.failure.hint.upi_invalid',
      limit_exceeded: 'payoutDisbursement.failure.hint.limit_exceeded',
      bank_unavailable: 'payoutDisbursement.failure.hint.bank_unavailable',
      interrupted: 'payoutDisbursement.failure.hint.interrupted',
    },
  },
  detail: {
    title: 'payoutDisbursement.detail.title',
    progress: {
      initiated: 'payoutDisbursement.detail.progress.initiated',
      processing: 'payoutDisbursement.detail.progress.processing',
      completed: 'payoutDisbursement.detail.progress.completed',
      failed: 'payoutDisbursement.detail.progress.failed',
      cancelled: 'payoutDisbursement.detail.progress.cancelled',
    },
    to: 'payoutDisbursement.detail.to',
    gross: 'payoutDisbursement.detail.gross',
    tds: 'payoutDisbursement.detail.tds',
    net: 'payoutDisbursement.detail.net',
    tdsNote: 'payoutDisbursement.detail.tdsNote',
    method: 'payoutDisbursement.detail.method',
    reference: 'payoutDisbursement.detail.reference',
    run: 'payoutDisbursement.detail.run',
    started: 'payoutDisbursement.detail.started',
    finished: 'payoutDisbursement.detail.finished',
    entries: 'payoutDisbursement.detail.entries',
    reconciled: 'payoutDisbursement.detail.reconciled',
    notReconciled: 'payoutDisbursement.detail.notReconciled',
    openReconciliation: 'payoutDisbursement.detail.openReconciliation',
    openPayout: 'payoutDisbursement.detail.openPayout',
    events: 'payoutDisbursement.detail.events',
    account: {
      heading: 'payoutDisbursement.detail.account.heading',
      none: 'payoutDisbursement.detail.account.none',
      holder: 'payoutDisbursement.detail.account.holder',
      upi: 'payoutDisbursement.detail.account.upi',
      bank: 'payoutDisbursement.detail.account.bank',
      checked: 'payoutDisbursement.detail.account.checked',
      changedSince: 'payoutDisbursement.detail.account.changedSince',
    },
    contact: {
      heading: 'payoutDisbursement.detail.contact.heading',
      call: 'payoutDisbursement.detail.contact.call',
      whatsapp: 'payoutDisbursement.detail.contact.whatsapp',
      log: 'payoutDisbursement.detail.contact.log',
      channel: {
        call: 'payoutDisbursement.detail.contact.channel.call',
        whatsapp: 'payoutDisbursement.detail.contact.channel.whatsapp',
        message: 'payoutDisbursement.detail.contact.channel.message',
      },
      how: 'payoutDisbursement.detail.contact.how',
      note: 'payoutDisbursement.detail.contact.note',
      noteHint: 'payoutDisbursement.detail.contact.noteHint',
      save: 'payoutDisbursement.detail.contact.save',
      saved: 'payoutDisbursement.detail.contact.saved',
    },
    update: {
      heading: 'payoutDisbursement.detail.update.heading',
      body: 'payoutDisbursement.detail.update.body',
      holder: 'payoutDisbursement.detail.update.holder',
      upi: 'payoutDisbursement.detail.update.upi',
      account: 'payoutDisbursement.detail.update.account',
      ifsc: 'payoutDisbursement.detail.update.ifsc',
      bank: 'payoutDisbursement.detail.update.bank',
      note: 'payoutDisbursement.detail.update.note',
      noteHint: 'payoutDisbursement.detail.update.noteHint',
      retry: 'payoutDisbursement.detail.update.retry',
      save: 'payoutDisbursement.detail.update.save',
      saved: 'payoutDisbursement.detail.update.saved',
      savedRetried: 'payoutDisbursement.detail.update.savedRetried',
    },
    retry: {
      button: 'payoutDisbursement.detail.retry.button',
      blocked: {
        details_unchanged: 'payoutDisbursement.detail.retry.blocked.details_unchanged',
        in_flight: 'payoutDisbursement.detail.retry.blocked.in_flight',
        not_failed: 'payoutDisbursement.detail.retry.blocked.not_failed',
      },
      done: 'payoutDisbursement.detail.retry.done',
    },
    cancel: {
      button: 'payoutDisbursement.detail.cancel.button',
      body: 'payoutDisbursement.detail.cancel.body',
      reason: 'payoutDisbursement.detail.cancel.reason',
      confirm: 'payoutDisbursement.detail.cancel.confirm',
      done: 'payoutDisbursement.detail.cancel.done',
    },
    partnerSees: 'payoutDisbursement.detail.partnerSees',
  },
  event: {
    created: 'payoutDisbursement.event.created',
    processing: 'payoutDisbursement.event.processing',
    completed: 'payoutDisbursement.event.completed',
    failed: 'payoutDisbursement.event.failed',
    retried: 'payoutDisbursement.event.retried',
    cancelled: 'payoutDisbursement.event.cancelled',
    contacted: 'payoutDisbursement.event.contacted',
    details_updated: 'payoutDisbursement.event.details_updated',
    note: 'payoutDisbursement.event.note',
  },
  partner: {
    sending: 'payoutDisbursement.partner.sending',
    needsDetails: 'payoutDisbursement.partner.needsDetails',
    retrying: 'payoutDisbursement.partner.retrying',
  },
  alert: {
    failed: 'payoutDisbursement.alert.failed',
    noDetails: 'payoutDisbursement.alert.noDetails',
  },
  link: {
    open: 'payoutDisbursement.link.open',
  },
  placeholder: 'payoutDisbursement.placeholder',
  note: {
    ledger: 'payoutDisbursement.note.ledger',
  },
  problem: {
    not_found: 'payoutDisbursement.problem.not_found',
    not_failed: 'payoutDisbursement.problem.not_failed',
    details_unchanged: 'payoutDisbursement.problem.details_unchanged',
    in_flight: 'payoutDisbursement.problem.in_flight',
    nothing_ready: 'payoutDisbursement.problem.nothing_ready',
    no_details: 'payoutDisbursement.problem.no_details',
    blocked: 'payoutDisbursement.problem.blocked',
    reason_required: 'payoutDisbursement.problem.reason_required',
    details_invalid: 'payoutDisbursement.problem.details_invalid',
    schedule_invalid: 'payoutDisbursement.problem.schedule_invalid',
    not_admin: 'payoutDisbursement.problem.not_admin',
    generic: 'payoutDisbursement.problem.generic',
  },
} as const;
