/** Screen 191 — Company Profile & Branding. Types and keys only. */
export const DRAFT_PREFIX = 'aiec.brandDraft';

export const COMPANY_PROFILE_KEYS = {
  title: 'companyProfile.title',
  subtitle: 'companyProfile.subtitle',
  loading: 'companyProfile.loading',
  offline: 'companyProfile.offline',
  refresh: 'companyProfile.refresh',
  close: 'companyProfile.close',
  error: {
    title: 'companyProfile.error.title',
    body: 'companyProfile.error.body',
    retry: 'companyProfile.error.retry',
    generic: 'companyProfile.error.generic',
    forbidden: 'companyProfile.error.forbidden',
    not_found: 'companyProfile.error.not_found',
    scheduled_pending: 'companyProfile.error.scheduled_pending',
    no_changes: 'companyProfile.error.no_changes',
    preview_stale: 'companyProfile.error.preview_stale',
    preview_unseen: 'companyProfile.error.preview_unseen',
    reason_short: 'companyProfile.error.reason_short',
    registration_unchecked: 'companyProfile.error.registration_unchecked',
    accountant_unconfirmed: 'companyProfile.error.accountant_unconfirmed',
    in_the_past: 'companyProfile.error.in_the_past',
    too_far: 'companyProfile.error.too_far',
    not_a_day: 'companyProfile.error.not_a_day',
    not_scheduled: 'companyProfile.error.not_scheduled',
    not_legal: 'companyProfile.error.not_legal',
    not_in_effect: 'companyProfile.error.not_in_effect',
    note_short: 'companyProfile.error.note_short',
    name_short: 'companyProfile.error.name_short',
    name_long: 'companyProfile.error.name_long',
    owner_short: 'companyProfile.error.owner_short',
    gstin_missing: 'companyProfile.error.gstin_missing',
    gstin_format: 'companyProfile.error.gstin_format',
    gstin_state: 'companyProfile.error.gstin_state',
    address_short: 'companyProfile.error.address_short',
    city_short: 'companyProfile.error.city_short',
    state_missing: 'companyProfile.error.state_missing',
    pincode_format: 'companyProfile.error.pincode_format',
    hex_primary: 'companyProfile.error.hex_primary',
    hex_secondary: 'companyProfile.error.hex_secondary',
    font_unknown: 'companyProfile.error.font_unknown',
    logo_type: 'companyProfile.error.logo_type',
    logo_size: 'companyProfile.error.logo_size',
    logo_unreadable: 'companyProfile.error.logo_unreadable',
    contrast_primary: 'companyProfile.error.contrast_primary',
    contrast_secondary: 'companyProfile.error.contrast_secondary',
  },
  warn: {
    accents_similar: 'companyProfile.warn.accents_similar',
    gstin_address_state: 'companyProfile.warn.gstin_address_state',
    names_same_as_english: 'companyProfile.warn.names_same_as_english',
  },
  now: {
    title: 'companyProfile.now.title',
    version: 'companyProfile.now.version',
    value: 'companyProfile.now.value',
    none: 'companyProfile.now.none',
  },
  group: {
    identity: {
      title: 'companyProfile.group.identity.title',
      hint: 'companyProfile.group.identity.hint',
    },
    legal: {
      title: 'companyProfile.group.legal.title',
      hint: 'companyProfile.group.legal.hint',
      warn: 'companyProfile.group.legal.warn',
    },
    look: {
      title: 'companyProfile.group.look.title',
      hint: 'companyProfile.group.look.hint',
    },
  },
  field: {
    companyName: 'companyProfile.field.companyName',
    nameHi: 'companyProfile.field.nameHi',
    nameMr: 'companyProfile.field.nameMr',
    ownerName: 'companyProfile.field.ownerName',
    logo: 'companyProfile.field.logo',
    gstin: 'companyProfile.field.gstin',
    line1: 'companyProfile.field.line1',
    city: 'companyProfile.field.city',
    state: 'companyProfile.field.state',
    pincode: 'companyProfile.field.pincode',
    accentPrimary: 'companyProfile.field.accentPrimary',
    accentSecondary: 'companyProfile.field.accentSecondary',
    headingFont: 'companyProfile.field.headingFont',
  },
  logo: {
    choose: 'companyProfile.logo.choose',
    replace: 'companyProfile.logo.replace',
    remove: 'companyProfile.logo.remove',
    hint: 'companyProfile.logo.hint',
    none: 'companyProfile.logo.none',
  },
  font: {
    fraunces: 'companyProfile.font.fraunces',
    martel: 'companyProfile.font.martel',
    jakarta: 'companyProfile.font.jakarta',
    sample: 'companyProfile.font.sample',
    devaNote: 'companyProfile.font.devaNote',
  },
  contrast: {
    title: 'companyProfile.contrast.title',
    primary: 'companyProfile.contrast.primary',
    secondary: 'companyProfile.contrast.secondary',
    distinct: 'companyProfile.contrast.distinct',
  },
  look: {
    reset: 'companyProfile.look.reset',
  },
  preview: {
    title: 'companyProfile.preview.title',
    hint: 'companyProfile.preview.hint',
    sample: 'companyProfile.preview.sample',
    now: 'companyProfile.preview.now',
    changes: 'companyProfile.preview.changes',
    empty: 'companyProfile.preview.empty',
    quote: {
      heading: 'companyProfile.preview.quote.heading',
      line: 'companyProfile.preview.quote.line',
      total: 'companyProfile.preview.quote.total',
      valid: 'companyProfile.preview.quote.valid',
    },
    invoice: {
      heading: 'companyProfile.preview.invoice.heading',
      billed: 'companyProfile.preview.invoice.billed',
      customer: 'companyProfile.preview.invoice.customer',
      taxable: 'companyProfile.preview.invoice.taxable',
      gst: 'companyProfile.preview.invoice.gst',
      total: 'companyProfile.preview.invoice.total',
    },
    portal: {
      heading: 'companyProfile.preview.portal.heading',
      stage: 'companyProfile.preview.portal.stage',
      next: 'companyProfile.preview.portal.next',
      pay: 'companyProfile.preview.portal.pay',
    },
  },
  publish: {
    title: 'companyProfile.publish.title',
    nothing: 'companyProfile.publish.nothing',
    review: 'companyProfile.publish.review',
    discard: 'companyProfile.publish.discard',
    changes: 'companyProfile.publish.changes',
    kind: {
      cosmetic: 'companyProfile.publish.kind.cosmetic',
      legal: 'companyProfile.publish.kind.legal',
      none: 'companyProfile.publish.kind.none',
    },
    kindHint: {
      cosmetic: 'companyProfile.publish.kindHint.cosmetic',
      legal: 'companyProfile.publish.kindHint.legal',
    },
    blocked: 'companyProfile.publish.blocked',
    warnings: 'companyProfile.publish.warnings',
    keeps: 'companyProfile.publish.keeps',
    impact: {
      title: 'companyProfile.publish.impact.title',
      moves: 'companyProfile.publish.impact.moves',
      same: 'companyProfile.publish.impact.same',
    },
    effective: {
      title: 'companyProfile.publish.effective.title',
      now: 'companyProfile.publish.effective.now',
      day: 'companyProfile.publish.effective.day',
      dayLabel: 'companyProfile.publish.effective.dayLabel',
      legalNote: 'companyProfile.publish.effective.legalNote',
    },
    reason: 'companyProfile.publish.reason',
    seen: 'companyProfile.publish.seen',
    registration: 'companyProfile.publish.registration',
    accountant: 'companyProfile.publish.accountant',
    go: 'companyProfile.publish.go',
    goLegal: 'companyProfile.publish.goLegal',
    done: 'companyProfile.publish.done',
    doneNow: 'companyProfile.publish.doneNow',
  },
  scheduled: {
    title: 'companyProfile.scheduled.title',
    body: 'companyProfile.scheduled.body',
    cancel: 'companyProfile.scheduled.cancel',
    cancelBody: 'companyProfile.scheduled.cancelBody',
    cancelReason: 'companyProfile.scheduled.cancelReason',
    cancelDo: 'companyProfile.scheduled.cancelDo',
    cancelled: 'companyProfile.scheduled.cancelled',
  },
  verify: {
    title: 'companyProfile.verify.title',
    body: 'companyProfile.verify.body',
    due: 'companyProfile.verify.due',
    note: 'companyProfile.verify.note',
    do: 'companyProfile.verify.do',
    done: 'companyProfile.verify.done',
  },
  history: {
    title: 'companyProfile.history.title',
    hint: 'companyProfile.history.hint',
    line: 'companyProfile.history.line',
    usage: 'companyProfile.history.usage',
    start: 'companyProfile.history.start',
    startDone: 'companyProfile.history.startDone',
    confirmed: 'companyProfile.history.confirmed',
    unconfirmed: 'companyProfile.history.unconfirmed',
    cancelledBy: 'companyProfile.history.cancelledBy',
    initial: 'companyProfile.history.initial',
  },
  status: {
    current: 'companyProfile.status.current',
    scheduled: 'companyProfile.status.scheduled',
    past: 'companyProfile.status.past',
    cancelled: 'companyProfile.status.cancelled',
  },
  kind: {
    initial: 'companyProfile.kind.initial',
    cosmetic: 'companyProfile.kind.cosmetic',
    legal: 'companyProfile.kind.legal',
  },
  change: {
    empty: 'companyProfile.change.empty',
    field: {
      companyName: 'companyProfile.change.field.companyName',
      nameHi: 'companyProfile.change.field.nameHi',
      nameMr: 'companyProfile.change.field.nameMr',
      ownerName: 'companyProfile.change.field.ownerName',
      logo: 'companyProfile.change.field.logo',
      gstin: 'companyProfile.change.field.gstin',
      address: 'companyProfile.change.field.address',
      accentPrimary: 'companyProfile.change.field.accentPrimary',
      accentSecondary: 'companyProfile.change.field.accentSecondary',
      headingFont: 'companyProfile.change.field.headingFont',
    },
    line: 'companyProfile.change.line',
  },
  draft: {
    note: 'companyProfile.draft.note',
    discarded: 'companyProfile.draft.discarded',
  },
  note: {
    placeholders: 'companyProfile.note.placeholders',
  },
  alert: {
    legalEffective: 'companyProfile.alert.legalEffective',
  },
  link: {
    open: 'companyProfile.link.open',
  },
} as const;
