/** Screen 154 — Quiz & Certification Test. Constants and translation keys only. */

import type { AssessmentError, AssessmentStateName } from '@/data/repository';

export const draftKey = (userId: string, attemptId: string) => `aiec.assessmentDraft.${userId}.${attemptId}`;
export const assessmentPath = (moduleId: string, step?: number) => `/assessment/${moduleId}${step ? `?step=${step}` : ''}`;
export const lessonsPath = (moduleId: string) => `/training/${moduleId}`;
export const libraryPath = '/training';
export const STATES: AssessmentStateName[] = ['locked', 'to_take', 'in_progress', 'cooldown', 'certified'];
export const TICK_MS = 30_000;

const rec = <T extends string>(ns: string, keys: readonly T[]) => Object.fromEntries(keys.map((k) => [k, `${ns}.${k}`])) as Record<T, string>;
const PROBLEMS: (AssessmentError | 'offline' | 'generic')[] = ['forbidden', 'not_found', 'locked', 'not_for_you', 'retired', 'invalid_state', 'not_ready', 'cooldown', 'already_certified', 'no_assessment', 'outdated', 'incomplete', 'attempt_not_found', 'already_submitted', 'not_admin', 'none_chosen', 'single_only', 'out_of_range', 'unknown_question', 'pass_range', 'cooldown_range', 'offline', 'generic'];

export const ASSESS_KEYS = {
  title: 'assessment.title',
  loading: 'assessment.loading',
  error: { title: 'assessment.error.title', body: 'assessment.error.body' },
  notFound: { title: 'assessment.notFound.title', body: 'assessment.notFound.body', action: 'assessment.notFound.action' },
  back: 'assessment.back',
  state: rec('assessment.state', STATES),
  stateBody: rec('assessment.stateBody', STATES),
  rules: {
    heading: 'assessment.rules.heading',
    questions: 'assessment.rules.questions',
    pass: 'assessment.rules.pass',
    attempt: 'assessment.rules.attempt',
    retake: 'assessment.rules.retake',
    retakeBody: 'assessment.rules.retakeBody',
    version: 'assessment.rules.version',
    gates: 'assessment.rules.gates',
    offline: 'assessment.rules.offline',
    cooldownEnds: 'assessment.rules.cooldownEnds',
    cooldownLeft: 'assessment.rules.cooldownLeft',
  },
  renewal: { dueSoon: 'assessment.renewal.dueSoon', expired: 'assessment.renewal.expired', validFor: 'assessment.renewal.validFor', renew: 'assessment.renewal.renew' },
  action: { start: 'assessment.action.start', resume: 'assessment.action.resume', lessons: 'assessment.action.lessons', library: 'assessment.action.library', studyAgain: 'assessment.action.studyAgain' },
  badge: { heading: 'assessment.badge.heading', body: 'assessment.badge.body', earned: 'assessment.badge.earned', score: 'assessment.badge.score', expires: 'assessment.badge.expires', noExpiry: 'assessment.badge.noExpiry', code: 'assessment.badge.code', mine: 'assessment.badge.mine' },
  history: { heading: 'assessment.history.heading', row: 'assessment.history.row', passed: 'assessment.history.passed', notPassed: 'assessment.history.notPassed', none: 'assessment.history.none' },
  wizard: {
    steps: 'assessment.wizard.steps',
    start: 'assessment.wizard.start',
    question: 'assessment.wizard.question',
    review: 'assessment.wizard.review',
    questionOf: 'assessment.wizard.questionOf',
    single: 'assessment.wizard.single',
    multi: 'assessment.wizard.multi',
    back: 'assessment.wizard.back',
    next: 'assessment.wizard.next',
    toReview: 'assessment.wizard.toReview',
    answerFirst: 'assessment.wizard.answerFirst',
    saved: 'assessment.wizard.saved',
    savedLocal: 'assessment.wizard.savedLocal',
    resumed: 'assessment.wizard.resumed',
  },
  review: {
    heading: 'assessment.review.heading',
    body: 'assessment.review.body',
    unanswered: 'assessment.review.unanswered',
    change: 'assessment.review.change',
    submit: 'assessment.review.submit',
    missing: 'assessment.review.missing',
    confirm: 'assessment.review.confirm',
    needSignal: 'assessment.review.needSignal',
    answered: 'assessment.review.answered',
  },
  result: {
    passed: 'assessment.result.passed',
    notPassed: 'assessment.result.notPassed',
    score: 'assessment.result.score',
    correctOf: 'assessment.result.correctOf',
    needed: 'assessment.result.needed',
    badge: 'assessment.result.badge',
    badgeBody: 'assessment.result.badgeBody',
    gateCleared: 'assessment.result.gateCleared',
    gateStillOpen: 'assessment.result.gateStillOpen',
    retryAt: 'assessment.result.retryAt',
    kind: 'assessment.result.kind',
    coaching: 'assessment.result.coaching',
    feedback: 'assessment.result.feedback',
    correct: 'assessment.result.correct',
    wrong: 'assessment.result.wrong',
    yourAnswer: 'assessment.result.yourAnswer',
    rightAnswer: 'assessment.result.rightAnswer',
    allRight: 'assessment.result.allRight',
    done: 'assessment.result.done',
  },
  admin: {
    heading: 'assessment.admin.heading',
    intro: 'assessment.admin.intro',
    attempts: 'assessment.admin.attempts',
    passes: 'assessment.admin.passes',
    certified: 'assessment.admin.certified',
    questionsOf: 'assessment.admin.questionsOf',
    pass: 'assessment.admin.pass',
    cooldowns: 'assessment.admin.cooldowns',
    struggling: 'assessment.admin.struggling',
    strugglingNone: 'assessment.admin.strugglingNone',
    strugglingRow: 'assessment.admin.strugglingRow',
    lapsed: 'assessment.admin.lapsed',
    lapsedNone: 'assessment.admin.lapsedNone',
    lapsedRow: 'assessment.admin.lapsedRow',
    lapsedNote: 'assessment.admin.lapsedNote',
    edit: 'assessment.admin.edit',
    editTitle: 'assessment.admin.editTitle',
    editBody: 'assessment.admin.editBody',
    passPercent: 'assessment.admin.passPercent',
    passHint: 'assessment.admin.passHint',
    cadenceNote: 'assessment.admin.cadenceNote',
    refreshers: 'assessment.admin.refreshers',
    skillMatrix: 'assessment.admin.skillMatrix',
    compliance: 'assessment.admin.compliance',
    validRow: 'assessment.admin.validRow',
    noExpiryRow: 'assessment.admin.noExpiryRow',
    cooldown1: 'assessment.admin.cooldown1',
    cooldown2: 'assessment.admin.cooldown2',
    cooldown3: 'assessment.admin.cooldown3',
    cooldownHint: 'assessment.admin.cooldownHint',
    placeholder: 'assessment.admin.placeholder',
    save: 'assessment.admin.save',
    cancel: 'assessment.admin.cancel',
    saved: 'assessment.admin.saved',
    empty: 'assessment.admin.empty',
    coachingNote: 'assessment.admin.coachingNote',
  },
  alert: { struggling: 'assessment.alert.struggling' },
  close: 'assessment.close',
  problem: rec('assessment.problem', PROBLEMS),
} as const;

/** The words of a question are translation keys under the module's code (the same place the lessons live), so a revised module adds keys, not a screen. */
export const qBase = (code: string, questionId: string) => `assessmentContent.${code.toLowerCase()}.${questionId}`;
