/** Screen 113 — Supplier Invoice Matching. Types and translation keys only. */

import type { InvoiceGate, InvoiceMatchStatus, LineVerdict, MatchIssue } from '@/features/suppliers/invoiceMatch';
import type { SupplierInvoiceEventKind } from '@/data/types';

export type InvoiceMatchingStatus = 'loading' | 'ready' | 'error';

/** How often the board re-reads while open: a delivery signed on site changes what matches. */
export const POLL_MS = 20_000;

/** `attention`: mismatched or billed ahead of delivery. `missing`: delivered, with nothing (or not enough) billed. */
export type InvoiceFilter = 'attention' | 'missing' | 'matched' | 'rejected';
export const INVOICE_FILTERS: InvoiceFilter[] = ['attention', 'missing', 'matched', 'rejected'];

export const MATCH_STATUSES: InvoiceMatchStatus[] = ['matched', 'awaiting_delivery', 'mismatch', 'rejected'];
export const VERDICTS: LineVerdict[] = ['matched', 'partial', 'adjusted', 'awaiting_delivery', 'mismatch'];
export const ISSUES: MatchIssue[] = ['price_differs', 'over_delivered', 'over_ordered', 'unknown_item'];
export const GATES: Exclude<InvoiceGate, 'ok'>[] = ['no_invoice', 'mismatch', 'incomplete', 'awaiting_delivery'];
export const EVENT_KINDS: SupplierInvoiceEventKind[] = ['submitted', 'adjustment_accepted', 'rejected', 'withdrawn', 'reinstated', 'mismatch_notified'];

const rec = <T extends string>(ns: string, keys: readonly T[]) => Object.fromEntries(keys.map((k) => [k, `${ns}.${k}`])) as Record<T, string>;

export const MATCHING_KEYS = {
  title: 'supplierInvoiceMatching.title',
  subtitle: 'supplierInvoiceMatching.subtitle',
  subtitleSupplier: 'supplierInvoiceMatching.subtitleSupplier',
  loading: 'supplierInvoiceMatching.loading',
  error: { title: 'supplierInvoiceMatching.error.title', body: 'supplierInvoiceMatching.error.body' },
  alert: { mismatch: 'supplierInvoiceMatching.alert.mismatch' },
  totals: {
    attention: 'supplierInvoiceMatching.totals.attention',
    missing: 'supplierInvoiceMatching.totals.missing',
    matched: 'supplierInvoiceMatching.totals.matched',
    count: 'supplierInvoiceMatching.totals.count',
  },
  filter: { label: 'supplierInvoiceMatching.filter.label', search: 'supplierInvoiceMatching.filter.search', ...rec('supplierInvoiceMatching.filter', INVOICE_FILTERS) },
  list: {
    emptyAttentionTitle: 'supplierInvoiceMatching.list.emptyAttentionTitle',
    emptyAttentionBody: 'supplierInvoiceMatching.list.emptyAttentionBody',
    emptyMissingTitle: 'supplierInvoiceMatching.list.emptyMissingTitle',
    emptyMissingBody: 'supplierInvoiceMatching.list.emptyMissingBody',
    emptyMatchedTitle: 'supplierInvoiceMatching.list.emptyMatchedTitle',
    emptyMatchedBody: 'supplierInvoiceMatching.list.emptyMatchedBody',
    emptyRejectedTitle: 'supplierInvoiceMatching.list.emptyRejectedTitle',
    emptyRejectedBody: 'supplierInvoiceMatching.list.emptyRejectedBody',
    emptySearchTitle: 'supplierInvoiceMatching.list.emptySearchTitle',
    emptySearchBody: 'supplierInvoiceMatching.list.emptySearchBody',
    clear: 'supplierInvoiceMatching.list.clear',
    onlyOrder: 'supplierInvoiceMatching.list.onlyOrder',
    showAll: 'supplierInvoiceMatching.list.showAll',
    submittedOn: 'supplierInvoiceMatching.list.submittedOn',
    deliveredOn: 'supplierInvoiceMatching.list.deliveredOn',
    itemCount: 'supplierInvoiceMatching.list.itemCount',
    notFound: 'supplierInvoiceMatching.list.notFound',
    notFoundBody: 'supplierInvoiceMatching.list.notFoundBody',
    enter: 'supplierInvoiceMatching.list.enter',
    send: 'supplierInvoiceMatching.list.send',
  },
  status: rec('supplierInvoiceMatching.status', MATCH_STATUSES),
  verdict: rec('supplierInvoiceMatching.verdict', VERDICTS),
  issue: rec('supplierInvoiceMatching.issue', ISSUES),
  gate: rec('supplierInvoiceMatching.gate', GATES),
  gateBody: rec('supplierInvoiceMatching.gateBody', GATES),
  event: rec('supplierInvoiceMatching.event', EVENT_KINDS),
  detail: {
    back: 'supplierInvoiceMatching.detail.back',
    order: 'supplierInvoiceMatching.detail.order',
    supplier: 'supplierInvoiceMatching.detail.supplier',
    site: 'supplierInvoiceMatching.detail.site',
    date: 'supplierInvoiceMatching.detail.date',
    document: 'supplierInvoiceMatching.detail.document',
    noDocument: 'supplierInvoiceMatching.detail.noDocument',
    submittedBy: 'supplierInvoiceMatching.detail.submittedBy',
    onBehalf: 'supplierInvoiceMatching.detail.onBehalf',
    matchHeading: 'supplierInvoiceMatching.detail.matchHeading',
    matchHint: 'supplierInvoiceMatching.detail.matchHint',
    threeWay: 'supplierInvoiceMatching.detail.threeWay',
    ordered: 'supplierInvoiceMatching.detail.ordered',
    invoiced: 'supplierInvoiceMatching.detail.invoiced',
    delivered: 'supplierInvoiceMatching.detail.delivered',
    notOnOrder: 'supplierInvoiceMatching.detail.notOnOrder',
    qtyOnly: 'supplierInvoiceMatching.detail.qtyOnly',
    billedElsewhere: 'supplierInvoiceMatching.detail.billedElsewhere',
    quantityCheck: 'supplierInvoiceMatching.detail.quantityCheck',
    priceCheck: 'supplierInvoiceMatching.detail.priceCheck',
    qtyOk: 'supplierInvoiceMatching.detail.qtyOk',
    qtyAwaiting: 'supplierInvoiceMatching.detail.qtyAwaiting',
    qtyFail: 'supplierInvoiceMatching.detail.qtyFail',
    priceOk: 'supplierInvoiceMatching.detail.priceOk',
    priceExplained: 'supplierInvoiceMatching.detail.priceExplained',
    priceFail: 'supplierInvoiceMatching.detail.priceFail',
    priceGap: 'supplierInvoiceMatching.detail.priceGap',
    unlocked: 'supplierInvoiceMatching.detail.unlocked',
    locked: 'supplierInvoiceMatching.detail.locked',
    adjustmentBasis: 'supplierInvoiceMatching.detail.adjustmentBasis',
    adjustmentNote: 'supplierInvoiceMatching.detail.adjustmentNote',
    approvedChange: 'supplierInvoiceMatching.detail.approvedChange',
    adjustmentAccepted: 'supplierInvoiceMatching.detail.adjustmentAccepted',
    adjustmentDispute: 'supplierInvoiceMatching.detail.adjustmentDispute',
    noApprovedChange: 'supplierInvoiceMatching.detail.noApprovedChange',
    useChange: 'supplierInvoiceMatching.detail.useChange',
    partialNote: 'supplierInvoiceMatching.detail.partialNote',
    gateHeading: 'supplierInvoiceMatching.detail.gateHeading',
    paymentOk: 'supplierInvoiceMatching.detail.paymentOk',
    seePayments: 'supplierInvoiceMatching.detail.seePayments',
    rejectedBy: 'supplierInvoiceMatching.detail.rejectedBy',
    withdrawnBy: 'supplierInvoiceMatching.detail.withdrawnBy',
    historyHeading: 'supplierInvoiceMatching.detail.historyHeading',
    by: 'supplierInvoiceMatching.detail.by',
    supplierNote: 'supplierInvoiceMatching.detail.supplierNote',
  },
  action: {
    submit: 'supplierInvoiceMatching.action.submit',
    submitFor: 'supplierInvoiceMatching.action.submitFor',
    reject: 'supplierInvoiceMatching.action.reject',
    withdraw: 'supplierInvoiceMatching.action.withdraw',
    close: 'supplierInvoiceMatching.action.close',
    resubmit: 'supplierInvoiceMatching.action.resubmit',
  },
  form: {
    title: 'supplierInvoiceMatching.form.title',
    titleFor: 'supplierInvoiceMatching.form.titleFor',
    intro: 'supplierInvoiceMatching.form.intro',
    introAdmin: 'supplierInvoiceMatching.form.introAdmin',
    order: 'supplierInvoiceMatching.form.order',
    number: 'supplierInvoiceMatching.form.number',
    numberHint: 'supplierInvoiceMatching.form.numberHint',
    date: 'supplierInvoiceMatching.form.date',
    document: 'supplierInvoiceMatching.form.document',
    documentHint: 'supplierInvoiceMatching.form.documentHint',
    linesHeading: 'supplierInvoiceMatching.form.linesHeading',
    quantity: 'supplierInvoiceMatching.form.quantity',
    unitPrice: 'supplierInvoiceMatching.form.unitPrice',
    remaining: 'supplierInvoiceMatching.form.remaining',
    orderPrice: 'supplierInvoiceMatching.form.orderPrice',
    deliveredSoFar: 'supplierInvoiceMatching.form.deliveredSoFar',
    fullyBilled: 'supplierInvoiceMatching.form.fullyBilled',
    addExtra: 'supplierInvoiceMatching.form.addExtra',
    extraDescription: 'supplierInvoiceMatching.form.extraDescription',
    removeExtra: 'supplierInvoiceMatching.form.removeExtra',
    previewHeading: 'supplierInvoiceMatching.form.previewHeading',
    previewClean: 'supplierInvoiceMatching.form.previewClean',
    previewWarn: 'supplierInvoiceMatching.form.previewWarn',
    total: 'supplierInvoiceMatching.form.total',
    confirm: 'supplierInvoiceMatching.form.confirm',
    noOrders: 'supplierInvoiceMatching.form.noOrders',
  },
  adjust: {
    title: 'supplierInvoiceMatching.adjust.title',
    intro: 'supplierInvoiceMatching.adjust.intro',
    note: 'supplierInvoiceMatching.adjust.note',
    noteHint: 'supplierInvoiceMatching.adjust.noteHint',
    confirm: 'supplierInvoiceMatching.adjust.confirm',
  },
  rejectSheet: {
    title: 'supplierInvoiceMatching.rejectSheet.title',
    titleOwn: 'supplierInvoiceMatching.rejectSheet.titleOwn',
    introOwn: 'supplierInvoiceMatching.rejectSheet.introOwn',
    confirmOwn: 'supplierInvoiceMatching.rejectSheet.confirmOwn',
    introSupplier: 'supplierInvoiceMatching.rejectSheet.introSupplier',
    reason: 'supplierInvoiceMatching.rejectSheet.reason',
    reasonHint: 'supplierInvoiceMatching.rejectSheet.reasonHint',
    confirm: 'supplierInvoiceMatching.rejectSheet.confirm',
  },
  toast: {
    submitted: 'supplierInvoiceMatching.toast.submitted',
    submittedClean: 'supplierInvoiceMatching.toast.submittedClean',
    submittedMismatch: 'supplierInvoiceMatching.toast.submittedMismatch',
    adjusted: 'supplierInvoiceMatching.toast.adjusted',
    rejected: 'supplierInvoiceMatching.toast.rejected',
    withdrawn: 'supplierInvoiceMatching.toast.withdrawn',
  },
  problem: {
    forbidden: 'supplierInvoiceMatching.problem.forbidden',
    not_found: 'supplierInvoiceMatching.problem.not_found',
    number_required: 'supplierInvoiceMatching.problem.number_required',
    invalid_date: 'supplierInvoiceMatching.problem.invalid_date',
    invalid_lines: 'supplierInvoiceMatching.problem.invalid_lines',
    duplicate_invoice: 'supplierInvoiceMatching.problem.duplicate_invoice',
    adjustment_invalid: 'supplierInvoiceMatching.problem.adjustment_invalid',
    invalid_state: 'supplierInvoiceMatching.problem.invalid_state',
    note_required: 'supplierInvoiceMatching.problem.note_required',
    generic: 'supplierInvoiceMatching.problem.generic',
  },
} as const;
