/** Screen 198 — Legal & Contract Templates. Types and keys only. */
export const POLL_MS = 30_000;
export type LegalTab = 'library' | 'states' | 'reviews';
export const TABS: LegalTab[] = ['library', 'states', 'reviews'];

export const LEGAL_TEMPLATES_KEYS = {
  title: 'legal.title',
  subtitle: 'legal.subtitle',
  loading: 'legal.loading',
  offline: 'legal.offline',
  refresh: 'legal.refresh',
  close: 'legal.close',
  cancel: 'legal.cancel',
  error: {
    title: 'legal.error.title',
    body: 'legal.error.body',
    retry: 'legal.error.retry',
    generic: 'legal.error.generic',
    forbidden: 'legal.error.forbidden',
    not_found: 'legal.error.not_found',
    state_unknown: 'legal.error.state_unknown',
    state_required: 'legal.error.state_required',
    scheduled_pending: 'legal.error.scheduled_pending',
    text_short: 'legal.error.text_short',
    text_long: 'legal.error.text_long',
    no_change: 'legal.error.no_change',
    reason_unknown: 'legal.error.reason_unknown',
    reference_short: 'legal.error.reference_short',
    note_short: 'legal.error.note_short',
    date_invalid: 'legal.error.date_invalid',
    date_past: 'legal.error.date_past',
    date_far: 'legal.error.date_far',
    preview_stale: 'legal.error.preview_stale',
    confirm_required: 'legal.error.confirm_required',
    not_scheduled: 'legal.error.not_scheduled',
    reason_short: 'legal.error.reason_short',
    reviewed_on_invalid: 'legal.error.reviewed_on_invalid',
    reviewed_in_future: 'legal.error.reviewed_in_future',
    reviewer_short: 'legal.error.reviewer_short',
    outcome_unknown: 'legal.error.outcome_unknown',
    next_due_invalid: 'legal.error.next_due_invalid',
    next_due_before: 'legal.error.next_due_before',
    next_due_far: 'legal.error.next_due_far',
    doc_unknown: 'legal.error.doc_unknown',
    not_open: 'legal.error.not_open',
    close_note_short: 'legal.error.close_note_short',
    cities_needed: 'legal.error.cities_needed',
    city_invalid: 'legal.error.city_invalid',
    authority_short: 'legal.error.authority_short',
    city_taken: 'legal.error.city_taken',
    nothing_new: 'legal.error.nothing_new',
  },
  note: {
    advice: 'legal.note.advice',
    placeholders: 'legal.note.placeholders',
  },
  tab: {
    label: 'legal.tab.label',
    library: 'legal.tab.library',
    states: 'legal.tab.states',
    reviews: 'legal.tab.reviews',
  },
  summary: {
    docs: 'legal.summary.docs',
    needReview: 'legal.summary.needReview',
    issues: 'legal.summary.issues',
    scheduled: 'legal.summary.scheduled',
  },
  issues: {
    title: 'legal.issues.title',
    body: 'legal.issues.body',
    fixBy: 'legal.issues.fixBy',
    late: 'legal.issues.late',
    open: 'legal.issues.open',
  },
  prop: {
    title: 'legal.prop.title',
    hint: 'legal.prop.hint',
    clear: 'legal.prop.clear',
    behind: 'legal.prop.behind',
    signedOlder: 'legal.prop.signedOlder',
    fallback: 'legal.prop.fallback',
    open: 'legal.prop.open',
    sample: 'legal.prop.sample',
    signature: {
      unsigned: 'legal.prop.signature.unsigned',
      customer_signed: 'legal.prop.signature.customer_signed',
      fully_signed: 'legal.prop.signature.fully_signed',
    },
  },
  library: {
    search: 'legal.library.search',
    all: 'legal.library.all',
    empty: 'legal.library.empty',
    emptyHint: 'legal.library.emptyHint',
    noMatch: 'legal.library.noMatch',
    noMatchHint: 'legal.library.noMatchHint',
    clear: 'legal.library.clear',
  },
  category: {
    contract: 'legal.category.contract',
    state: 'legal.category.state',
    partner: 'legal.category.partner',
    supplier: 'legal.category.supplier',
    privacy: 'legal.category.privacy',
    guidance: 'legal.category.guidance',
  },
  doc: {
    contract: 'legal.doc.contract',
    state: 'legal.doc.state',
    partner: 'legal.doc.partner',
    supplier: 'legal.doc.supplier',
    privacy: 'legal.doc.privacy',
    guidance: 'legal.doc.guidance',
  },
  role: {
    surveyor: 'legal.role.surveyor',
    technician: 'legal.role.technician',
    supplier: 'legal.role.supplier',
  },
  used: {
    contract: 'legal.used.contract',
    partner: 'legal.used.partner',
    supplier: 'legal.used.supplier',
    privacy: 'legal.used.privacy',
    inspection: 'legal.used.inspection',
  },
  row: {
    version: 'legal.row.version',
    since: 'legal.row.since',
    reviewedOn: 'legal.row.reviewedOn',
    neverReviewed: 'legal.row.neverReviewed',
    scheduled: 'legal.row.scheduled',
    gaps: 'legal.row.gaps',
    gapTemplates: 'legal.row.gapTemplates',
    written: 'legal.row.written',
    elsewhere: 'legal.row.elsewhere',
  },
  review: {
    never: 'legal.review.never',
    current: 'legal.review.current',
    due: 'legal.review.due',
    outdated: 'legal.review.outdated',
    issue_open: 'legal.review.issue_open',
    dueIn: 'legal.review.dueIn',
    overdue: 'legal.review.overdue',
    by: 'legal.review.by',
    form: {
      title: 'legal.review.form.title',
      doc: 'legal.review.form.doc',
      on: 'legal.review.form.on',
      who: 'legal.review.form.who',
      firm: 'legal.review.form.firm',
      outcome: 'legal.review.form.outcome',
      clear: 'legal.review.form.clear',
      issues: 'legal.review.form.issues',
      note: 'legal.review.form.note',
      next: 'legal.review.form.next',
      versionNote: 'legal.review.form.versionNote',
      issueNote: 'legal.review.form.issueNote',
      save: 'legal.review.form.save',
      saved: 'legal.review.form.saved',
      issueSaved: 'legal.review.form.issueSaved',
    },
  },
  sheet: {
    where: 'legal.sheet.where',
    usedBy: 'legal.sheet.usedBy',
    maintained: 'legal.sheet.maintained',
    openWhere: 'legal.sheet.openWhere',
    current: 'legal.sheet.current',
    change: 'legal.sheet.change',
    clauses: 'legal.sheet.clauses',
    clausesHint: 'legal.sheet.clausesHint',
    clauseMissing: 'legal.sheet.clauseMissing',
    addClause: 'legal.sheet.addClause',
    editClause: 'legal.sheet.editClause',
    history: 'legal.sheet.history',
    noHistory: 'legal.sheet.noHistory',
    reviews: 'legal.sheet.reviews',
    noReviews: 'legal.sheet.noReviews',
    recordReview: 'legal.sheet.recordReview',
    propagation: 'legal.sheet.propagation',
    statesLink: 'legal.sheet.statesLink',
  },
  hist: {
    applied: 'legal.hist.applied',
    scheduled: 'legal.hist.scheduled',
    cancelled: 'legal.hist.cancelled',
    reason: {
      law_change: 'legal.hist.reason.law_change',
      standard_change: 'legal.hist.reason.standard_change',
      legal_review: 'legal.hist.reason.legal_review',
      correction: 'legal.hist.reason.correction',
      new_state: 'legal.hist.reason.new_state',
      edited_elsewhere: 'legal.hist.reason.edited_elsewhere',
    },
    nationalKind: 'legal.hist.nationalKind',
    stateKind: 'legal.hist.stateKind',
    reference: 'legal.hist.reference',
    showBefore: 'legal.hist.showBefore',
    hideBefore: 'legal.hist.hideBefore',
    before: 'legal.hist.before',
    after: 'legal.hist.after',
    cancel: 'legal.hist.cancel',
    cancelReason: 'legal.hist.cancelReason',
    cancelDo: 'legal.hist.cancelDo',
    cancelled2: 'legal.hist.cancelled2',
  },
  edit: {
    title: 'legal.edit.title',
    target: 'legal.edit.target',
    targetTemplate: 'legal.edit.targetTemplate',
    text: 'legal.edit.text',
    note: 'legal.edit.note',
    reason: 'legal.edit.reason',
    reference: 'legal.edit.reference',
    referenceHint: 'legal.edit.referenceHint',
    when: 'legal.edit.when',
    now: 'legal.edit.now',
    onDate: 'legal.edit.onDate',
    date: 'legal.edit.date',
    check: 'legal.edit.check',
    impact: 'legal.edit.impact',
    newDocs: 'legal.edit.newDocs',
    impactNone: 'legal.edit.impactNone',
    impactBehind: 'legal.edit.impactBehind',
    impactSigned: 'legal.edit.impactSigned',
    confirm: 'legal.edit.confirm',
    publish: 'legal.edit.publish',
    schedule: 'legal.edit.schedule',
    published: 'legal.edit.published',
    scheduledDone: 'legal.edit.scheduledDone',
    letters: 'legal.edit.letters',
    wasEmpty: 'legal.edit.wasEmpty',
  },
  reviews: {
    title: 'legal.reviews.title',
    hint: 'legal.reviews.hint',
    empty: 'legal.reviews.empty',
    emptyHint: 'legal.reviews.emptyHint',
    add: 'legal.reviews.add',
    status: {
      clear: 'legal.reviews.status.clear',
      issue_open: 'legal.reviews.status.issue_open',
      issue_corrected: 'legal.reviews.status.issue_corrected',
      issue_closed: 'legal.reviews.status.issue_closed',
    },
    version: 'legal.reviews.version',
    next: 'legal.reviews.next',
    recordedBy: 'legal.reviews.recordedBy',
    close: {
      open: 'legal.reviews.close.open',
      hint: 'legal.reviews.close.hint',
      note: 'legal.reviews.close.note',
      save: 'legal.reviews.close.save',
      saved: 'legal.reviews.close.saved',
    },
    correct: 'legal.reviews.correct',
    correctElsewhere: 'legal.reviews.correctElsewhere',
  },
  states: {
    title: 'legal.states.title',
    hint: 'legal.states.hint',
    add: 'legal.states.add',
    empty: 'legal.states.empty',
    emptyHint: 'legal.states.emptyHint',
    cities: 'legal.states.cities',
    authority: 'legal.states.authority',
    contracts: 'legal.states.contracts',
    coverage: 'legal.states.coverage',
    has: 'legal.states.has',
    missing: 'legal.states.missing',
    pending: 'legal.states.pending',
    addClause: 'legal.states.addClause',
    editClause: 'legal.states.editClause',
    addCities: 'legal.states.addCities',
    fallback: 'legal.states.fallback',
    history: 'legal.states.history',
    event: {
      added: 'legal.states.event.added',
      cities_added: 'legal.states.event.cities_added',
      authority_changed: 'legal.states.event.authority_changed',
    },
    form: {
      title: 'legal.states.form.title',
      titleExisting: 'legal.states.form.titleExisting',
      state: 'legal.states.form.state',
      cities: 'legal.states.form.cities',
      citiesHint: 'legal.states.form.citiesHint',
      authority: 'legal.states.form.authority',
      note: 'legal.states.form.note',
      next: 'legal.states.form.next',
      save: 'legal.states.form.save',
      saved: 'legal.states.form.saved',
    },
  },
  alert: {
    reviewIssue: 'legal.alert.reviewIssue',
    stateGap: 'legal.alert.stateGap',
    contractsBehind: 'legal.alert.contractsBehind',
  },
  link: {
    open: 'legal.link.open',
  },
} as const;
