import { DESCRIPTION_MAX, END_REASON_MIN, LABEL_MAX, MAX_CASH, MAX_DAYS, MAX_PLACES, MAX_TENURE_DAYS, MIN_DAYS, NAME_MAX, PREVIEW_SHOWN, contestProblem, csvCell, durationDays, rewardsProblem, totalCash } from '@/features/rewards/contestConfig';
import type { ContestInput, ContestProblem, PreviewCheck, RewardInput } from '@/features/rewards/contestConfig';
import { METRICS_OF } from '@/features/rewards/standings';
import type { ContestMetric, ContestPhase } from '@/features/rewards/standings';

export { DESCRIPTION_MAX, END_REASON_MIN, LABEL_MAX, MAX_CASH, MAX_DAYS, MAX_PLACES, MAX_TENURE_DAYS, METRICS_OF, MIN_DAYS, NAME_MAX, PREVIEW_SHOWN, contestProblem, csvCell, durationDays, rewardsProblem, totalCash };
export type { ContestInput, ContestMetric, ContestPhase, ContestProblem, PreviewCheck, RewardInput };
export const PULL_DISTANCE = 70;
export const STATE_FILTERS = ['live', 'scheduled', 'finished', 'all'] as const;
export type StateFilter = (typeof STATE_FILTERS)[number];
export const contestSetupPath = (q: Record<string, string>) => { const p = new URLSearchParams(q).toString(); return p ? `/contest-setup?${p}` : '/contest-setup'; };

export const SETUP_KEYS = {
  title: 'contestSetup.title',
  subtitle: 'contestSetup.subtitle',
  loading: 'contestSetup.loading',
  error: {
    title: 'contestSetup.error.title',
    body: 'contestSetup.error.body',
  },
  refresh: {
    button: 'contestSetup.refresh.button',
    pull: 'contestSetup.refresh.pull',
    release: 'contestSetup.refresh.release',
    busy: 'contestSetup.refresh.busy',
  },
  close: 'contestSetup.close',
  cancelButton: 'contestSetup.cancelButton',
  back: 'contestSetup.back',
  new: 'contestSetup.new',
  summary: {
    live: 'contestSetup.summary.live',
    scheduled: 'contestSetup.summary.scheduled',
    finished: 'contestSetup.summary.finished',
    captionLive: 'contestSetup.summary.captionLive',
    none: 'contestSetup.summary.none',
  },
  filter: {
    live: 'contestSetup.filter.live',
    scheduled: 'contestSetup.filter.scheduled',
    finished: 'contestSetup.filter.finished',
    all: 'contestSetup.filter.all',
  },
  list: {
    empty: {
      title: 'contestSetup.list.empty.title',
      body: 'contestSetup.list.empty.body',
    },
    noneIn: 'contestSetup.list.noneIn',
    count: 'contestSetup.list.count',
  },
  card: {
    window: 'contestSetup.card.window',
    participants: 'contestSetup.card.participants',
    prizes: 'contestSetup.card.prizes',
    winners: 'contestSetup.card.winners',
    noWinners: 'contestSetup.card.noWinners',
    paid: 'contestSetup.card.paid',
    legacy: 'contestSetup.card.legacy',
    notPaid: 'contestSetup.card.notPaid',
    open: 'contestSetup.card.open',
    edit: 'contestSetup.card.edit',
    locked: 'contestSetup.card.locked',
  },
  reward: {
    cash: 'contestSetup.reward.cash',
    place: 'contestSetup.reward.place',
    line: 'contestSetup.reward.line',
  },
  editor: {
    titleNew: 'contestSetup.editor.titleNew',
    titleEdit: 'contestSetup.editor.titleEdit',
    name: 'contestSetup.editor.name',
    nameHint: 'contestSetup.editor.nameHint',
    description: 'contestSetup.editor.description',
    cohort: 'contestSetup.editor.cohort',
    metric: 'contestSetup.editor.metric',
    metricHelp: {
      leadsCaptured: 'contestSetup.editor.metricHelp.leadsCaptured',
      leadsConverted: 'contestSetup.editor.metricHelp.leadsConverted',
      revenue: 'contestSetup.editor.metricHelp.revenue',
      jobsCompleted: 'contestSetup.editor.metricHelp.jobsCompleted',
    },
    starts: 'contestSetup.editor.starts',
    ends: 'contestSetup.editor.ends',
    duration: 'contestSetup.editor.duration',
    startsNow: 'contestSetup.editor.startsNow',
    eligibility: 'contestSetup.editor.eligibility',
    minTenure: 'contestSetup.editor.minTenure',
    minTenureHint: 'contestSetup.editor.minTenureHint',
    lateJoin: 'contestSetup.editor.lateJoin',
    lateJoinHint: 'contestSetup.editor.lateJoinHint',
    rewards: {
      heading: 'contestSetup.editor.rewards.heading',
      place: 'contestSetup.editor.rewards.place',
      kind: 'contestSetup.editor.rewards.kind',
      cash: 'contestSetup.editor.rewards.cash',
      recognition: 'contestSetup.editor.rewards.recognition',
      amount: 'contestSetup.editor.rewards.amount',
      label: 'contestSetup.editor.rewards.label',
      add: 'contestSetup.editor.rewards.add',
      remove: 'contestSetup.editor.rewards.remove',
      total: 'contestSetup.editor.rewards.total',
      note: 'contestSetup.editor.rewards.note',
    },
    rulesLocked: 'contestSetup.editor.rulesLocked',
    save: 'contestSetup.editor.save',
    saveNew: 'contestSetup.editor.saveNew',
    saveNow: 'contestSetup.editor.saveNow',
    saved: 'contestSetup.editor.saved',
    savedLive: 'contestSetup.editor.savedLive',
    draftKept: 'contestSetup.editor.draftKept',
  },
  preview: {
    heading: 'contestSetup.preview.heading',
    body: 'contestSetup.preview.body',
    run: 'contestSetup.preview.run',
    windowLive: 'contestSetup.preview.windowLive',
    windowTrailing: 'contestSetup.preview.windowTrailing',
    participants: 'contestSetup.preview.participants',
    empty: 'contestSetup.preview.empty',
    nothing: 'contestSetup.preview.nothing',
    check: {
      everyone_level: 'contestSetup.preview.check.everyone_level',
      one_dominates: 'contestSetup.preview.check.one_dominates',
      few_active: 'contestSetup.preview.check.few_active',
      overlaps: 'contestSetup.preview.check.overlaps',
      counts_quantity: 'contestSetup.preview.check.counts_quantity',
    },
  },
  problem: {
    name_short: 'contestSetup.problem.name_short',
    name_long: 'contestSetup.problem.name_long',
    description_long: 'contestSetup.problem.description_long',
    metric_invalid: 'contestSetup.problem.metric_invalid',
    dates_invalid: 'contestSetup.problem.dates_invalid',
    start_past: 'contestSetup.problem.start_past',
    too_short: 'contestSetup.problem.too_short',
    too_long: 'contestSetup.problem.too_long',
    no_rewards: 'contestSetup.problem.no_rewards',
    too_many_places: 'contestSetup.problem.too_many_places',
    ranks_invalid: 'contestSetup.problem.ranks_invalid',
    cash_invalid: 'contestSetup.problem.cash_invalid',
    cash_too_high: 'contestSetup.problem.cash_too_high',
    label_short: 'contestSetup.problem.label_short',
    label_long: 'contestSetup.problem.label_long',
    tenure_invalid: 'contestSetup.problem.tenure_invalid',
    locked: 'contestSetup.problem.locked',
    not_found: 'contestSetup.problem.not_found',
    not_live: 'contestSetup.problem.not_live',
    reason_short: 'contestSetup.problem.reason_short',
    policy_invalid: 'contestSetup.problem.policy_invalid',
    not_admin: 'contestSetup.problem.not_admin',
    generic: 'contestSetup.problem.generic',
  },
  detail: {
    title: 'contestSetup.detail.title',
    rules: 'contestSetup.detail.rules',
    counted: 'contestSetup.detail.counted',
    eligible: 'contestSetup.detail.eligible',
    minTenure: 'contestSetup.detail.minTenure',
    lateYes: 'contestSetup.detail.lateYes',
    lateNo: 'contestSetup.detail.lateNo',
    standings: 'contestSetup.detail.standings',
    standingsNote: 'contestSetup.detail.standingsNote',
    noStandings: 'contestSetup.detail.noStandings',
    partnerView: 'contestSetup.detail.partnerView',
    outcome: {
      heading: 'contestSetup.detail.outcome.heading',
      during: 'contestSetup.detail.outcome.during',
      before: 'contestSetup.detail.outcome.before',
      quality: 'contestSetup.detail.outcome.quality',
      small: 'contestSetup.detail.outcome.small',
      note: 'contestSetup.detail.outcome.note',
    },
    prizes: {
      heading: 'contestSetup.detail.prizes.heading',
    },
    prize: {
      state: {
        pending: 'contestSetup.detail.prize.state.pending',
        held: 'contestSetup.detail.prize.state.held',
        cleared: 'contestSetup.detail.prize.state.cleared',
        paid: 'contestSetup.detail.prize.state.paid',
        projected: 'contestSetup.detail.prize.state.projected',
        forfeited: 'contestSetup.detail.prize.state.forfeited',
      },
      openQueue: 'contestSetup.detail.prize.openQueue',
      openTracker: 'contestSetup.detail.prize.openTracker',
    },
    recognitions: 'contestSetup.detail.recognitions',
    skipped: {
      not_paid: 'contestSetup.detail.skipped.not_paid',
      no_winner: 'contestSetup.detail.skipped.no_winner',
      nothing_earned: 'contestSetup.detail.skipped.nothing_earned',
    },
    events: 'contestSetup.detail.events',
  },
  event: {
    created: 'contestSetup.event.created',
    edited: 'contestSetup.event.edited',
    launched: 'contestSetup.event.launched',
    ended_early: 'contestSetup.event.ended_early',
    closed: 'contestSetup.event.closed',
    rewarded: 'contestSetup.event.rewarded',
    cancelled: 'contestSetup.event.cancelled',
  },
  end: {
    heading: 'contestSetup.end.heading',
    body: 'contestSetup.end.body',
    reason: 'contestSetup.end.reason',
    reasonHint: 'contestSetup.end.reasonHint',
    rewards: 'contestSetup.end.rewards',
    pay: 'contestSetup.end.pay',
    none: 'contestSetup.end.none',
    confirm: 'contestSetup.end.confirm',
    done: 'contestSetup.end.done',
  },
  cancel: {
    heading: 'contestSetup.cancel.heading',
    body: 'contestSetup.cancel.body',
    confirm: 'contestSetup.cancel.confirm',
    done: 'contestSetup.cancel.done',
  },
  note: {
    how: 'contestSetup.note.how',
  },
  placeholder: 'contestSetup.placeholder',
  link: {
    open: 'contestSetup.link.open',
  },
} as const;
