/** Screen 109 — Delivery Partner Management. Types and translation keys only. */

import type { Responsibility, TrackingMode } from '@/features/logistics/partnerPerformance';

export type PartnerMgmtStatus = 'loading' | 'ready' | 'error';

/** How often the board re-reads while open. */
export const POLL_MS = 30_000;

export type PartnerTab = 'partners' | 'book' | 'delays';
export const PARTNER_TABS: PartnerTab[] = ['partners', 'book', 'delays'];

export type PartnerFilter = 'all' | 'live' | 'milestone' | 'attention' | 'new' | 'paused';
export const PARTNER_FILTERS: PartnerFilter[] = ['all', 'live', 'milestone', 'attention', 'new', 'paused'];

export type CauseFilter = 'all' | Responsibility;
export const CAUSE_FILTERS: CauseFilter[] = ['all', 'partner', 'supplier', 'shared', 'external'];
export const RESPONSIBILITIES: Responsibility[] = ['partner', 'supplier', 'shared', 'external'];

export const TRACKING_MODES: TrackingMode[] = ['live', 'manual', 'fallback'];
export const EVENT_KINDS = ['onboarded', 'details', 'lane_added', 'paused', 'resumed', 'feed_outage', 'feed_restored', 'booked'] as const;

const rec = <T extends string>(ns: string, keys: readonly T[]) => Object.fromEntries(keys.map((k) => [k, `${ns}.${k}`])) as Record<T, string>;

export const PARTNER_KEYS = {
  title: 'deliveryPartners.title',
  subtitle: 'deliveryPartners.subtitle',
  loading: 'deliveryPartners.loading',
  error: { title: 'deliveryPartners.error.title', body: 'deliveryPartners.error.body' },
  alert: { feedDown: 'deliveryPartners.alert.feedDown' },
  tab: { label: 'deliveryPartners.tab.label', ...rec('deliveryPartners.tab', PARTNER_TABS) },
  add: 'deliveryPartners.add',
  filter: { label: 'deliveryPartners.filter.label', search: 'deliveryPartners.filter.search', ...rec('deliveryPartners.filter', PARTNER_FILTERS) },
  tracking: rec('deliveryPartners.tracking', TRACKING_MODES),
  trackingBody: rec('deliveryPartners.trackingBody', TRACKING_MODES),
  status: { active: 'deliveryPartners.status.active', paused: 'deliveryPartners.status.paused' },
  list: {
    emptyTitle: 'deliveryPartners.list.emptyTitle',
    emptyBody: 'deliveryPartners.list.emptyBody',
    emptyFilteredTitle: 'deliveryPartners.list.emptyFilteredTitle',
    emptyFilteredBody: 'deliveryPartners.list.emptyFilteredBody',
    clear: 'deliveryPartners.list.clear',
    areas: 'deliveryPartners.list.areas',
    deliveries: 'deliveryPartners.list.deliveries',
    onTime: 'deliveryPartners.list.onTime',
    notRated: 'deliveryPartners.list.notRated',
    buildingHistory: 'deliveryPartners.list.buildingHistory',
    notFound: 'deliveryPartners.list.notFound',
    back: 'deliveryPartners.list.back',
    feedDown: 'deliveryPartners.list.feedDown',
    call: 'deliveryPartners.list.call',
  },
  detail: {
    contact: 'deliveryPartners.detail.contact',
    edit: 'deliveryPartners.detail.edit',
    areas: 'deliveryPartners.detail.areas',
    performance: 'deliveryPartners.detail.performance',
    performanceHint: 'deliveryPartners.detail.performanceHint',
    onTimeRate: 'deliveryPartners.detail.onTimeRate',
    avgLate: 'deliveryPartners.detail.avgLate',
    lateLoads: 'deliveryPartners.detail.lateLoads',
    newTitle: 'deliveryPartners.detail.newTitle',
    newBody: 'deliveryPartners.detail.newBody',
    recentTrips: 'deliveryPartners.detail.recentTrips',
    noTrips: 'deliveryPartners.detail.noTrips',
    onTimeTrip: 'deliveryPartners.detail.onTimeTrip',
    lateTrip: 'deliveryPartners.detail.lateTrip',
    causeHeading: 'deliveryPartners.detail.causeHeading',
    causeHint: 'deliveryPartners.detail.causeHint',
    causeNone: 'deliveryPartners.detail.causeNone',
    rateCard: 'deliveryPartners.detail.rateCard',
    rateRef: 'deliveryPartners.detail.rateRef',
    rateFrom: 'deliveryPartners.detail.rateFrom',
    noLanes: 'deliveryPartners.detail.noLanes',
    lane: 'deliveryPartners.detail.lane',
    perKm: 'deliveryPartners.detail.perKm',
    days: 'deliveryPartners.detail.days',
    addLane: 'deliveryPartners.detail.addLane',
    integration: 'deliveryPartners.detail.integration',
    feedSince: 'deliveryPartners.detail.feedSince',
    reportFeed: 'deliveryPartners.detail.reportFeed',
    feedBack: 'deliveryPartners.detail.feedBack',
    inFlight: 'deliveryPartners.detail.inFlight',
    noInFlight: 'deliveryPartners.detail.noInFlight',
    inFlightFeed: { live: 'deliveryPartners.detail.inFlightFeed.live', lost: 'deliveryPartners.detail.inFlightFeed.lost', manual: 'deliveryPartners.detail.inFlightFeed.manual' },
    openShipment: 'deliveryPartners.detail.openShipment',
    activity: 'deliveryPartners.detail.activity',
    pause: 'deliveryPartners.detail.pause',
    resume: 'deliveryPartners.detail.resume',
    book: 'deliveryPartners.detail.book',
    pausedBanner: 'deliveryPartners.detail.pausedBanner',
    by: 'deliveryPartners.detail.by',
  },
  event: rec('deliveryPartners.event', EVENT_KINDS),
  responsibility: rec('deliveryPartners.responsibility', RESPONSIBILITIES),
  form: {
    createTitle: 'deliveryPartners.form.createTitle',
    editTitle: 'deliveryPartners.form.editTitle',
    intro: 'deliveryPartners.form.intro',
    name: 'deliveryPartners.form.name',
    contact: 'deliveryPartners.form.contact',
    phone: 'deliveryPartners.form.phone',
    email: 'deliveryPartners.form.email',
    areas: 'deliveryPartners.form.areas',
    areasHint: 'deliveryPartners.form.areasHint',
    otherCity: 'deliveryPartners.form.otherCity',
    addCity: 'deliveryPartners.form.addCity',
    live: 'deliveryPartners.form.live',
    liveHint: 'deliveryPartners.form.liveHint',
    rateRef: 'deliveryPartners.form.rateRef',
    rateRefHint: 'deliveryPartners.form.rateRefHint',
    save: 'deliveryPartners.form.save',
    create: 'deliveryPartners.form.create',
  },
  lane: {
    title: 'deliveryPartners.lane.title',
    intro: 'deliveryPartners.lane.intro',
    origin: 'deliveryPartners.lane.origin',
    destination: 'deliveryPartners.lane.destination',
    km: 'deliveryPartners.lane.km',
    rate: 'deliveryPartners.lane.rate',
    days: 'deliveryPartners.lane.days',
    replaces: 'deliveryPartners.lane.replaces',
    save: 'deliveryPartners.lane.save',
  },
  reason: {
    pauseTitle: 'deliveryPartners.reason.pauseTitle',
    pauseIntro: 'deliveryPartners.reason.pauseIntro',
    resumeTitle: 'deliveryPartners.reason.resumeTitle',
    resumeIntro: 'deliveryPartners.reason.resumeIntro',
    feedTitle: 'deliveryPartners.reason.feedTitle',
    feedIntro: 'deliveryPartners.reason.feedIntro',
    backTitle: 'deliveryPartners.reason.backTitle',
    backIntro: 'deliveryPartners.reason.backIntro',
    note: 'deliveryPartners.reason.note',
    noteHint: 'deliveryPartners.reason.noteHint',
    confirm: 'deliveryPartners.reason.confirm',
  },
  book: {
    intro: 'deliveryPartners.book.intro',
    emptyTitle: 'deliveryPartners.book.emptyTitle',
    emptyBody: 'deliveryPartners.book.emptyBody',
    forSite: 'deliveryPartners.book.forSite',
    parts: 'deliveryPartners.book.parts',
    choose: 'deliveryPartners.book.choose',
    title: 'deliveryPartners.book.title',
    lines: 'deliveryPartners.book.lines',
    linesNone: 'deliveryPartners.book.linesNone',
    carriers: 'deliveryPartners.book.carriers',
    carriersHint: 'deliveryPartners.book.carriersHint',
    noneEligibleTitle: 'deliveryPartners.book.noneEligibleTitle',
    noneEligibleBody: 'deliveryPartners.book.noneEligibleBody',
    unavailable: 'deliveryPartners.book.unavailable',
    unavailable_area: 'deliveryPartners.book.unavailable_area',
    unavailable_paused: 'deliveryPartners.book.unavailable_paused',
    rate: 'deliveryPartners.book.rate',
    noRate: 'deliveryPartners.book.noRate',
    transit: 'deliveryPartners.book.transit',
    newBadge: 'deliveryPartners.book.newBadge',
    historyLine: 'deliveryPartners.book.historyLine',
    vehicle: 'deliveryPartners.book.vehicle',
    vehicleHint: 'deliveryPartners.book.vehicleHint',
    driver: 'deliveryPartners.book.driver',
    driverPhone: 'deliveryPartners.book.driverPhone',
    fallbackWarn: 'deliveryPartners.book.fallbackWarn',
    manualNote: 'deliveryPartners.book.manualNote',
    liveNote: 'deliveryPartners.book.liveNote',
    submit: 'deliveryPartners.book.submit',
    done: 'deliveryPartners.book.done',
    doneLive: 'deliveryPartners.book.doneLive',
    doneMilestones: 'deliveryPartners.book.doneMilestones',
    track: 'deliveryPartners.book.track',
    another: 'deliveryPartners.book.another',
    best: 'deliveryPartners.book.best',
  },
  delays: {
    intro: 'deliveryPartners.delays.intro',
    summary: 'deliveryPartners.delays.summary',
    noneTitle: 'deliveryPartners.delays.noneTitle',
    noneBody: 'deliveryPartners.delays.noneBody',
    legend: 'deliveryPartners.delays.legend',
    supplierPart: 'deliveryPartners.delays.supplierPart',
    partnerPart: 'deliveryPartners.delays.partnerPart',
    lateBy: 'deliveryPartners.delays.lateBy',
    split: 'deliveryPartners.delays.split',
    filter: { label: 'deliveryPartners.delays.filter.label', ...rec('deliveryPartners.delays.filter', CAUSE_FILTERS) },
    emptyFiltered: 'deliveryPartners.delays.emptyFiltered',
    fixHeading: 'deliveryPartners.delays.fixHeading',
    fix: rec('deliveryPartners.delays.fix', RESPONSIBILITIES),
  },
  duration: { minutes: 'deliveryPartners.duration.minutes', hours: 'deliveryPartners.duration.hours' },
  toast: {
    created: 'deliveryPartners.toast.created',
    saved: 'deliveryPartners.toast.saved',
    laneSaved: 'deliveryPartners.toast.laneSaved',
    paused: 'deliveryPartners.toast.paused',
    resumed: 'deliveryPartners.toast.resumed',
    feedDown: 'deliveryPartners.toast.feedDown',
    feedBack: 'deliveryPartners.toast.feedBack',
  },
  problem: {
    forbidden: 'deliveryPartners.problem.forbidden',
    not_found: 'deliveryPartners.problem.not_found',
    invalid_state: 'deliveryPartners.problem.invalid_state',
    invalid_input: 'deliveryPartners.problem.invalid_input',
    invalid_phone: 'deliveryPartners.problem.invalid_phone',
    area_required: 'deliveryPartners.problem.area_required',
    rate_card_required: 'deliveryPartners.problem.rate_card_required',
    duplicate: 'deliveryPartners.problem.duplicate',
    note_required: 'deliveryPartners.problem.note_required',
    no_live_feed: 'deliveryPartners.problem.no_live_feed',
    live_in_flight: 'deliveryPartners.problem.live_in_flight',
    area_not_served: 'deliveryPartners.problem.area_not_served',
    partner_paused: 'deliveryPartners.problem.partner_paused',
    no_destination: 'deliveryPartners.problem.no_destination',
    generic: 'deliveryPartners.problem.generic',
  },
} as const;
