/** Screen 096 — Manufacturer Production Status. Types and translation keys only. */

export type ProductionStatusState = 'loading' | 'ready' | 'error' | 'unavailable';

export const PRODUCTION_STATUS_KEYS = {
  title: 'productionStatus.title',
  loading: 'productionStatus.loading',
  error: { title: 'productionStatus.error.title', body: 'productionStatus.error.body' },
  unavailable: {
    not_found: { title: 'productionStatus.unavailable.not_found.title', body: 'productionStatus.unavailable.not_found.body' },
    not_manufacturer: { title: 'productionStatus.unavailable.not_manufacturer.title', body: 'productionStatus.unavailable.not_manufacturer.body' },
    not_in_production: { title: 'productionStatus.unavailable.not_in_production.title', body: 'productionStatus.unavailable.not_in_production.body' },
    action: 'productionStatus.unavailable.action',
  },

  stage: {
    raw_material: 'production.stage.raw_material',
    fabrication: 'production.stage.fabrication',
    quality_testing: 'production.stage.quality_testing',
    packaging: 'production.stage.packaging',
    complete: 'production.stage.complete',
  },

  hero: {
    meta: 'productionStatus.hero.meta',
    complete: 'productionStatus.hero.complete',
    stalled: 'productionStatus.hero.stalled',
    onPace: 'productionStatus.hero.onPace',
    percent: 'productionStatus.hero.percent',
    inStage: 'productionStatus.hero.inStage',
    usually: 'productionStatus.hero.usually',
    usuallyDefault: 'productionStatus.hero.usuallyDefault',
    stalledNote: 'productionStatus.hero.stalledNote',
  },
  batch: {
    heading: 'productionStatus.batch.heading',
    body: 'productionStatus.batch.body',
    sibling: 'productionStatus.batch.sibling',
    applyToBatch: 'productionStatus.batch.applyToBatch',
  },
  stages: {
    heading: 'productionStatus.stages.heading',
    evidenceCount: 'productionStatus.stages.evidenceCount',
    shortened: 'productionStatus.stages.shortened',
  },
  evidence: {
    heading: 'productionStatus.evidence.heading',
    intro: 'productionStatus.evidence.intro',
    slot: 'productionStatus.evidence.slot',
    slotHint: 'productionStatus.evidence.slotHint',
    note: 'productionStatus.evidence.note',
    add: 'productionStatus.evidence.add',
    none: 'productionStatus.evidence.none',
    required: 'productionStatus.evidence.required',
    by: 'productionStatus.evidence.by',
  },
  history: {
    heading: 'productionStatus.history.heading',
    none: 'productionStatus.history.none',
    started: 'productionStatus.history.started',
    advanced: 'productionStatus.history.advanced',
    regressed: 'productionStatus.history.regressed',
    skipped: 'productionStatus.history.skipped',
    viaBatch: 'productionStatus.history.viaBatch',
    meta: 'productionStatus.history.meta',
  },
  action: {
    advance: 'productionStatus.action.advance',
    finish: 'productionStatus.action.finish',
    more: 'productionStatus.action.more',
    adminNote: 'productionStatus.action.adminNote',
    adminNoteHint: 'productionStatus.action.adminNoteHint',
    readOnly: 'productionStatus.action.readOnly',
    openOrder: 'productionStatus.action.openOrder',
  },
  more: {
    title: 'productionStatus.more.title',
    defect: 'productionStatus.more.defect',
    defectHint: 'productionStatus.more.defectHint',
    backTo: 'productionStatus.more.backTo',
    defectReason: 'productionStatus.more.defectReason',
    sendBack: 'productionStatus.more.sendBack',
    skip: 'productionStatus.more.skip',
    skipHint: 'productionStatus.more.skipHint',
    skipStage: 'productionStatus.more.skipStage',
    skipReason: 'productionStatus.more.skipReason',
    doSkip: 'productionStatus.more.doSkip',
    nothingToSkip: 'productionStatus.more.nothingToSkip',
  },
  toast: {
    advanced: 'productionStatus.toast.advanced',
    finished: 'productionStatus.toast.finished',
    regressed: 'productionStatus.toast.regressed',
    skipped: 'productionStatus.toast.skipped',
    evidenceAdded: 'productionStatus.toast.evidenceAdded',
    batchEvidenceMissing: 'productionStatus.toast.batchEvidenceMissing',
    error: 'productionStatus.toast.error',
  },
} as const;
