/** Screen 188 — Manual Override Console. Types and keys only. */
export const POLL_MS = 30_000;
export const AUDIT_ROUTE = '/audit-log?cat=overrides';

export const MANUAL_OVERRIDE_KEYS = {
  title: 'manualOverride.title',
  subtitle: 'manualOverride.subtitle',
  loading: 'manualOverride.loading',
  offline: 'manualOverride.offline',
  close: 'manualOverride.close',
  error: {
    title: 'manualOverride.error.title',
    body: 'manualOverride.error.body',
    retry: 'manualOverride.error.retry',
    generic: 'manualOverride.error.generic',
    forbidden: 'manualOverride.error.forbidden',
    not_found: 'manualOverride.error.not_found',
    reason_short: 'manualOverride.error.reason_short',
    confirm_required: 'manualOverride.error.confirm_required',
    same_stage: 'manualOverride.error.same_stage',
    won_needs_deal: 'manualOverride.error.won_needs_deal',
    lost_needs_reason: 'manualOverride.error.lost_needs_reason',
    not_overridable_state: 'manualOverride.error.not_overridable_state',
    until_required: 'manualOverride.error.until_required',
    until_past: 'manualOverride.error.until_past',
    until_too_far: 'manualOverride.error.until_too_far',
    safety_critical_open: 'manualOverride.error.safety_critical_open',
    no_override_path: 'manualOverride.error.no_override_path',
  },
  intro: {
    title: 'manualOverride.intro.title',
    body: 'manualOverride.intro.body',
  },
  pattern: {
    title: 'manualOverride.pattern.title',
    body: 'manualOverride.pattern.body',
    fix: 'manualOverride.pattern.fix',
  },
  step: {
    what: 'manualOverride.step.what',
    which: 'manualOverride.step.which',
    how: 'manualOverride.step.how',
    why: 'manualOverride.step.why',
  },
  kind: {
    lead_stage: {
      name: 'manualOverride.kind.lead_stage.name',
      body: 'manualOverride.kind.lead_stage.body',
    },
    payout_clear: {
      name: 'manualOverride.kind.payout_clear.name',
      body: 'manualOverride.kind.payout_clear.body',
    },
    stop_reminders: {
      name: 'manualOverride.kind.stop_reminders.name',
      body: 'manualOverride.kind.stop_reminders.body',
    },
    commitment_waive: {
      name: 'manualOverride.kind.commitment_waive.name',
      body: 'manualOverride.kind.commitment_waive.body',
    },
  },
  which: {
    search: 'manualOverride.which.search',
    none: 'manualOverride.which.none',
    stuck: 'manualOverride.which.stuck',
    held: 'manualOverride.which.held',
    blocked: 'manualOverride.which.blocked',
    days: 'manualOverride.which.days',
    overdue: 'manualOverride.which.overdue',
  },
  how: {
    stage: 'manualOverride.how.stage',
    until: 'manualOverride.how.until',
    untilHint: 'manualOverride.how.untilHint',
    valid: 'manualOverride.how.valid',
    stageNote: 'manualOverride.how.stageNote',
  },
  why: {
    label: 'manualOverride.why.label',
    hint: 'manualOverride.why.hint',
    valid: 'manualOverride.why.valid',
    draft: 'manualOverride.why.draft',
  },
  preview: {
    title: 'manualOverride.preview.title',
    pick: 'manualOverride.preview.pick',
    blocked: 'manualOverride.preview.blocked',
    change: 'manualOverride.preview.change',
  },
  effect: {
    stage: 'manualOverride.effect.stage',
    skipped: 'manualOverride.effect.skipped',
    backwards: 'manualOverride.effect.backwards',
    followUps: 'manualOverride.effect.followUps',
    quotes: 'manualOverride.effect.quotes',
    rescored: 'manualOverride.effect.rescored',
    payout: 'manualOverride.effect.payout',
    flagsSeen: 'manualOverride.effect.flagsSeen',
    releasesHold: 'manualOverride.effect.releasesHold',
    nextRun: 'manualOverride.effect.nextRun',
    tds: 'manualOverride.effect.tds',
    reminders: 'manualOverride.effect.reminders',
    owing: 'manualOverride.effect.owing',
    queue: 'manualOverride.effect.queue',
    resumes: 'manualOverride.effect.resumes',
    waive: 'manualOverride.effect.waive',
    stopsChasing: 'manualOverride.effect.stopsChasing',
    sourceUnchanged: 'manualOverride.effect.sourceUnchanged',
  },
  value: {
    captured: 'manualOverride.value.captured',
    contacted: 'manualOverride.value.contacted',
    site_visit: 'manualOverride.value.site_visit',
    quoted: 'manualOverride.value.quoted',
    negotiation: 'manualOverride.value.negotiation',
    held: 'manualOverride.value.held',
    pending: 'manualOverride.value.pending',
    cleared: 'manualOverride.value.cleared',
    active: 'manualOverride.value.active',
    open: 'manualOverride.value.open',
    waived: 'manualOverride.value.waived',
    pausedUntil: 'manualOverride.value.pausedUntil',
  },
  review: {
    button: 'manualOverride.review.button',
    title: 'manualOverride.review.title',
    warning: 'manualOverride.review.warning',
    target: 'manualOverride.review.target',
    reason: 'manualOverride.review.reason',
    understand: 'manualOverride.review.understand',
    apply: 'manualOverride.review.apply',
    back: 'manualOverride.review.back',
    done: 'manualOverride.review.done',
  },
  absolute: {
    title: 'manualOverride.absolute.title',
    body: 'manualOverride.absolute.body',
    qc_failure: 'manualOverride.absolute.qc_failure',
    safety_check: 'manualOverride.absolute.safety_check',
    handover_gate: 'manualOverride.absolute.handover_gate',
    compliance_certificate: 'manualOverride.absolute.compliance_certificate',
    training_gate: 'manualOverride.absolute.training_gate',
    attempts: 'manualOverride.absolute.attempts',
    fix: 'manualOverride.absolute.fix',
    try: 'manualOverride.absolute.try',
    tryHint: 'manualOverride.absolute.tryHint',
    which: 'manualOverride.absolute.which',
    target: 'manualOverride.absolute.target',
    ask: 'manualOverride.absolute.ask',
    refused: 'manualOverride.absolute.refused',
  },
  recent: {
    title: 'manualOverride.recent.title',
    empty: 'manualOverride.recent.empty',
    emptyBody: 'manualOverride.recent.emptyBody',
    applied: 'manualOverride.recent.applied',
    refused: 'manualOverride.recent.refused',
    by: 'manualOverride.recent.by',
    audit: 'manualOverride.recent.audit',
  },
  note: {
    placeholders: 'manualOverride.note.placeholders',
  },
  alert: {
    pattern: 'manualOverride.alert.pattern',
  },
  link: {
    open: 'manualOverride.link.open',
  },
} as const;
